<style> #profile-side-info{
        background-color: unset !important;
    }</style>
<li>
    <span><i class="ion-edit"></i> <?php echo lang('post') ?>:</span> <?php echo social_count_page_posts($page)." ".lang('posts') ?>
</li>
<li>
    <span><i class="ion-link"></i> <?php echo lang('link') ?>:</span> <?php echo $page['website'] ?>
</li>
<li>
    <span><i class="ion-ios-briefcase"></i> <?php echo lang('page::company-name') ?>:</span> <?php echo $page['company'] ?>
</li>
<li>
    <span><i class="ion-ios-location"></i> <?php echo lang('page::location') ?>:</span> <?php echo $page['location'] ?>
</li>
<li>
    <span><i class="ion-android-share-alt"></i> <?php echo lang('social-connections') ?>:</span>
    <div style="margin-left: 25px;font-size: 25px;">
        <?php if ($social = get_social_more('facebook','','pages',$page['page_id'])): ?>
        <a target="_blank" style="font-size: 25px;" href="<?php echo $social ?>" title="Facebook Link"> <i style="color: #4B77BE !important" class="ion-social-facebook"></i></a>
        <?php endif ?>

        <?php if ($social = get_social_more('twitter','','pages',$page['page_id'])): ?>
        <a target="_blank" style="font-size: 25px;" href="<?php echo $social ?>" title="Twitter Link"> <i style="color:#19B5FE !important" class="ion-social-twitter"></i></a>
        <?php endif ?>

        <?php if ($social = get_social_more('google','','pages',$page['page_id'])): ?>
            <a target="_blank" style="font-size: 25px;" href="<?php echo $social ?>" title="Google+ Link"> <i style="color: #ff1107 !important" class="fa fa-google"></i></a>
        <?php endif ?>

        <?php if ($social = get_social_more('linkedin','','pages',$page['page_id'])): ?>
            <a target="_blank" style="font-size: 25px;" href="<?php echo $social ?>" title="LinkedIn Link"> <i style="color: #4B77BE !important" class="ion-social-linkedin"></i></a>
        <?php endif ?>

        <?php if ($social = get_social_more('youtube','','pages',$page['page_id'])): ?>
            <a target="_blank" style="font-size: 25px;" href="<?php echo $social ?>" title="YouTube Link"> <i style="color: #ff1107 !important" class="ion-social-youtube"></i></a>
        <?php endif ?>

        <?php if ($social = get_social_more('vkontakte','','pages',$page['page_id'])): ?>
            <a target="_blank" style="font-size: 25px;" href="<?php echo $social ?>" title="VKontakte Link"> <i style="color: #19B5FE !important" class="ion-social-vimeo"></i></a>
        <?php endif ?>
    </div>
</li>
