<ul id="profile-side-info">
    <?php foreach (get_custom_fields('page', $id) as $field): ?>
        <?php if (get_page_details($field['title'], $app->profilePage)): ?>
            <?php $value = output_text(get_page_details($field['title'], $app->profilePage)) ?>
            <?php $value = $field['field_type'] == 'boolean' ? ($value == 1 ? 'Yes' : ($value == 0 ? 'No' : $value)) : $value ?>
            <li>
                <span><i class="ion-ios-information-outline"></i> <?php echo lang($field['title']) ?>: </span> <?php echo $value ?>
            </li>
        <?php endif ?>
    <?php endforeach ?>
</ul>