<?php $show_button = isset($show_button) ? $show_button : true; $list_items = 1; $max_items = 2 ?>
<div class="media <?php echo (isset($type)) ? $type : 'media-lg' ?> user">
	<div class="media-left">
		<a ajax="true" href="<?php echo profile_url(null, $user) ?>" class="media-object"><img class="responsive-img" src="<?php echo get_avatar(75, $user) ?>"/>
		</a>
	</div>
	<div class="media-body">

		<a class="media-heading" style="font-weight:bold" ajax="true" href="<?php echo profile_url(null, $user) ?>"><?php echo get_user_name($user) ?> <?php echo verify_badge($user) ?></a>
		<ul class="info">
			<li>
				<i class="ion-android-people"></i> <?php echo count(get_friends($user['id'])) ?> <?php echo lang('friends') ?>
			</li>
			<?php if(is_loggedIn() and $user['id'] != get_userid()): ?>
				<?php $count = count(get_mutual_friends($user['id'])) ?>
				<?php if($count > 0 && $list_items < $max_items) : $list_items++?>
					<li>
						<i class="ion-android-person-add"></i> <?php echo $count ?> <?php echo lang('mutual-friends') ?>
					</li>
				<?php endif ?>

			<?php endif ?>
			<?php if(count(get_followers($user['id'])) && $list_items < $max_items): $list_items++?>
				<li>
					<i class="ion-social-rss"></i> <?php echo count(get_followers($user['id'])) ?> <?php echo lang('followers') ?>
				</li>
			<?php endif; ?>
			<?php if($user['country'] && $list_items < $max_items): $list_items++?>
				<li>
					<i class="ion-ios-location"></i> <?php echo ucwords($user['country']) ?>
				</li>
			<?php endif ?>
		</ul>
		<div class="action">
			<?php if(plugin_loaded('relationship') && $show_button): ?>
				<?php echo view('relationship::button', array('userid' => $user['id'])) ?>
			<?php endif ?>
		</div>
	</div>
</div>
