<?php load_functions('country');
$countries = get_countries(); ?>
<div class="box people people-content">
    <div class="people-list">
        <div class="head">
            <div class="cover" style="background-image: url(<?php echo url_img(config('user-list-cover', 'themes/default/images/user/list-cover.jpg'), 920); ?>)">
                <div class="title"><?php echo lang('people') ?></div>
            </div>
            <div class="filters filter-pane global-filter-container" data-url="<?php echo url_to_pager('users') ?>">
                <div class="top">
                    <form id="people-list-search" method="post" onsubmit="return run_global_filter()" action="" class="search form-inline list-search">
                        <?php CSRFProtection::embed() ?>
                        <input id="people-keywords-input" value="<?php echo isset($filter['keywords']) ? $filter['keywords'] : '' ?>" type="search" class="form-control search-box filter-input" data-name="term" placeholder="<?php echo lang('search') ?>" />
                        <button type="submit">
                            <i class="search-icon icon ion-ios-search"></i>
                        </button>
                    </form>
                </div>
                <div class="bottom">
                    <i class="icon ion-android-options"></i>
                    <?php if (config('enable-feature-filter')) : ?>
                        <!--<select name="val[feature]" id="people-feature-select" data-name="feature" onchange="return people.submitSearch()" class="c-select filter-input">
                            <option value="both" <?php if (isset($filter['feature']) && $filter['feature'] == 'both') : ?>selected<?php endif ?>><?php echo lang('feature') ?></option>
                            <option value="featured" <?php if (isset($filter['feature']) && $filter['feature'] == 'featured') : ?>selected<?php endif ?>><?php echo lang('featured') ?></option>
                            <option value="not-featured" <?php if (isset($filter['feature']) && $filter['feature'] == 'not-featured') : ?>selected<?php endif ?>><?php echo lang('not-featured') ?></option>
                        </select>-->
                    <?php endif ?>
                    <?php if (config('enable-gender-filter') && config('enable-gender', true)) : ?>
                        <select name="val[gender]" id="people-gender-select" data-name="gender" onchange="return people.submitSearch()" class="c-select filter-input">
                            <option value="both" <?php if (isset($filter['gender']) && $filter['gender'] == 'both') : ?>selected<?php endif ?>><?php echo lang('gender') ?></option>
                            <?php $genders = get_genders(); ?>
                            <?php foreach ($genders as $gender) : ?>
                                <option <?php echo isset($filter['gender']) && $filter['gender'] == $gender ? 'selected' : '' ?> value="<?php echo $gender ?>"><?php echo lang($gender) ?></option>
                            <?php endforeach; ?>
                            <?php fire_hook('people.gender', $filter, array($filter)); ?>
                        </select>
                    <?php endif ?>
                    <?php if (config('enable-online-filter')) : ?>
                        <select name="val[online_status]" id="people-online-select" data-name="online_status" onchange="return people.submitSearch()" class="c-select filter-input">
                            <option value="both" <?php if (isset($filter['online_status']) && $filter['online_status'] == 'both') : ?>selected<?php endif ?>><?php echo lang('status') ?></option>
                            <option value="online" <?php if (isset($filter['online_status']) && $filter['online_status'] == 'online') : ?>selected<?php endif ?>><?php echo lang('online') ?></option>
                            <option value="offline" <?php if (isset($filter['online_status']) && $filter['online_status'] == 'offline') : ?>selected<?php endif ?>><?php echo lang('offline') ?></option>
                        </select>

                    <?php endif ?>
                    <select name="val[location]" id="people-location-select" data-name="location" onchange="return people.submitSearch()" class="c-select filter-input">
                        <option value="any" <?php if (isset($filter['location']) && $filter['location'] == 'any') : ?>selected<?php endif ?>><?php echo lang('location') ?></option>
                        <option value="nearby" <?php if (isset($filter['location']) && $filter['location'] == 'nearby') : ?>selected<?php endif ?>><?php echo lang('nearby') ?></option>
                    </select>
                    <?php if (config('enable-country-filter')) : ?>
                        <!--<select name="val[country]" id="people-country-select" data-name="country" onchange="return people.submitSearch()" class="c-select filter-input">
                        <option value="any" <?php if (isset($filter['country']) && $filter['country'] == 'any') : ?>selected<?php endif ?>><?php echo lang('country') ?></option>
                        <?php foreach ($countries as $country => $name) : ?>
                            <option value="<?php echo $name ?>" <?php if (isset($filter['country']) && $filter['country'] == $name) : ?>selected<?php endif ?>><?php echo ucwords($name) ?></option>
                        <?php endforeach ?>
                    </select>-->
                    <?php endif ?>
                    <?php if (config('enable-age-filter')) : ?>
                        <!--<select name="val[from_age]" id="people-min-age-select" data-name="from_age" onchange="return people.submitSearch()" class="c-select filter-input">
                        <option value="any" <?php if (isset($filter['from_age']) && $filter['from_age'] == 'any') : ?>selected<?php endif ?>><?php echo lang('min-age') ?></option>
                        <?php for ($i = 13; $i <= 99; $i++) : ?>
                            <option value="<?php echo $i ?>" <?php if (isset($filter['from_age']) && $filter['from_age'] == $i) : ?>checked<?php endif ?>><?php echo $i ?></option>
                        <?php endfor ?>
                    </select>-->
                        <!--<select name="val[to_age]" id="people-max-age-select" data-name="to_age" onchange="return people.submitSearch()" class="c-select filter-input">
                        <option value="any" <?php if (isset($filter['to_age']) && $filter['to_age'] == 'any') : ?>selected<?php endif ?>><?php echo lang('max-age') ?></option>
                        <?php for ($i = 13; $i <= 99; $i++) : ?>
                            <option value="<?php echo $i ?>" <?php if (isset($filter['to_age']) && $filter['to_age'] == $i) : ?>selected<?php endif ?>><?php echo $i ?></option>
                        <?php endfor ?>
                    </select>-->
                    <?php endif ?>
                    <?php fire_hook('people.filter.pane', $filter) ?>
                </div>
            </div>
        </div>
        <div class="body">
            <div class="listings">
                <div class="listing row">
                    <?php foreach ($people->results() as $user) : ?>
                        <?php $gender = (isset($user['gender']) and $user['gender']) ? $user['gender'] : null ?>
                        <?php $gender_image = ($gender) ? img("images/avatar/{$gender}.png") : img("images/avatar.png") ?>
                        <?php $user_image = $user['avatar'] ? url_img($user['avatar'], 200) : $gender_image ?>
                        <?php $user_name = trim($user['first_name'] . $user['last_name']) == '' ? $user['username'] : $user['first_name'] . ' ' . $user['last_name'] ?>
                        <?php $online_status = $user['online_time'] > (time() - 50) ? 'online' : 'offline' ?>
                        <?php $info = array() ?>
                        <?php if (!empty($user['gender'])) $info[] = lang($user['gender']); ?>
                        <?php if (!empty($user['country'])) $info[] = ucwords($user['country']); ?>
                        <div class="item col-lg-3">
                            <a ajax="true" href="<?php echo url($user['username']) ?>" class="thumb">
                                <img class="image" src="<?php echo $user_image ?>" alt="<?php echo $user_name ?> " />
                                <?php if (isset($user['featured']) && $user['featured']) : ?>
                                    <div class="featured">
                                        <i class="ion-ios-star-outline"></i>
                                    </div>
                                <?php endif ?>
                            </a>
                            <div class="details">
                                <a ajax="true" href="<?php echo url($user['username']) ?>" class="title"><?php echo $user_name ?> <?php fire_hook('users.membership.icon', $user); ?></a>
                                <div class="stat">
                                    <div class="status <?php echo $online_status ?>"></div>
                                    <div><?php echo implode(', ', $info) ?></div>
                                    <?php if (isset($filter['location']) && $filter['location'] == 'nearby') : ?>
                                        <div>
                                            <?php if ($user['distance'] !== -1) : ?>
                                                <?= round($user['distance'], 2); ?> miles away
                                            <?php else : ?>
                                                Location not found
                                            <?php endif; ?>
                                        </div>
                                    <?php endif ?>
                                    <div class="counts">
                                        <?php if (in_array(config('relationship-method', 3), array(2, 3))) : ?>
                                            <div>
                                                <div class="value"><?php echo socialCountDisplay(count(get_friends($user['id']))) ?></div>
                                                <div class="title"><?php echo lang('friends') ?></div>
                                            </div>
                                        <?php endif; ?>
                                        <div>
                                            <div class="value"><?php echo socialCountDisplay(count_user_posts($user['id'])) ?></div>
                                            <div class="title"><?php echo lang('posts') ?></div>
                                        </div>
                                    </div>
                                </div>
                                <div class="action">
                                    <?php if (plugin_loaded('relationship')) : ?>
                                        <?php echo view('relationship::button', array('userid' => $user['id'])) ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>
        </div>
    </div>
    <div class="box-content">
        <?php if ($people->total) : ?>
            <?php if ($people->total > config('max-page-result', 20)) : ?>
                <?php echo $people->links(true) ?>
            <?php endif ?>
        <?php else : ?>
            <div class="alert alert-info"><?php echo lang('no-member-found') ?></div>
        <?php endif ?>
    </div>
</div>