<div class="box">
	<?php if(!is_loggedIn()): ?>
		<span class="error"><?php echo lang('marketplace::marketplace-create-login-error') ?></span>
	<?php else: ?>
		<?php if($message): ?>
			<div class="alert alert-danger"><?php echo $message ?></div>
		<?php endif ?>
		<?php if(config('max-num-listing-photos', 5) > $num_listing_images): ?>
			<form action="" method="post" enctype="multipart/form-data">
				<?php CSRFProtection::embed() ?>
				<div class="form-group row">
					<div class="col-sm-4">
						<h6>
							<label class="control-label" for="image"><?php echo lang('marketplace::add-image') ?>: </label>
						</h6>
						<p class="form-description"><?php echo lang('marketplace::add-image-image-desc') ?></p>
					</div>
					<div class="col-sm-8">
						<div class="magic-input-image-preview" data-name="image">
							<span class="dimension"></span>
						</div>
					</div>
				</div>
				<div class="form-group row">
					<div class="col-sm-5">
					</div>
					<div class="col-sm-4">
						<div class="input-field col s12">
							<input type="submit" value="<?php echo lang('marketplace::add') ?>" class="btn btn-info"/>
						</div>
					</div>
				</div>
				<input type="hidden" name="val[listing_id]" value="<?php echo $listing_id ?>"/>
				<input type="hidden" name="val[type]" value="add_image"/>
			</form>
		<?php else: ?>
			<div class="alert alert-danger"><?php echo lang('marketplace::max-image-error') ?></div>
		<?php endif ?>
	<?php endif ?>
</div>