<div class="portable-login">
	<form action="<?php echo url_to_pager('login') ?>" method="post">
		<?php CSRFProtection::embed() ?>
		<div class="form-group">
			<input class="form-control" value="<?php echo input('val.username') ?>" type="text" name="val[username]" placeholder="<?php echo lang('username') ?>" autocomplete="off"/>
		</div>
		<div class="form-group">
			<input class="form-control" value="<?php echo input('val.password') ?>" type="password" name="val[password]" placeholder="<?php echo lang('password') ?>" autocomplete="off"/>
		</div>
		<?php echo fire_hook('login.form.extend', null, array('is_portable' => true)) ?>
		<div class="form-group">
			<div class="row">
				<div class="col-md-6">
					<label class="c-input c-checkbox">
						<input name="val[remember]" checked type="checkbox">
						<span class="c-indicator"></span>
						<?php echo lang('remember-me') ?>
					</label>
					<button class="btn btn-info"><?php echo lang('login') ?></button>
				</div>
				<div class="col-md-6">
					<a href="<?php echo url_to_pager('forgot-password') ?>" class="float-right" style="font-size: 15px"><?php echo lang('forgot-password') ?></a>
				</div>
			</div>
		</div>
	</form>

	<?php if(config('enable-facebook', false) || config('enable-twitter', false) || config('enable-googleplus', false) || config('enable-vk', false)): ?>
		<div id="social-links-container">
			<div class="sign-with-container">
				<ul id="home-social-links">
                    <li> <div class="text" style="font-size: 14px;"><?php echo lang('login-with') ?></div> </li>
					<?php if(config('enable-facebook', false)): ?>
						<li>
							<a class="facebook" href="<?php echo url_to_pager('facebook-auth') ?>">
								<i class="icon ion-social-facebook"></i>
							</a>
						</li>
					<?php endif ?>
					<?php if(config('enable-twitter', false)): ?>
						<li>
							<a class="twitter" href="<?php echo url_to_pager('twitter-auth') ?>">
								<i class="icon ion-social-twitter"></i>
							</a>
						</li>
					<?php endif ?>
					<?php if(config('enable-googleplus', false)): ?>
						<li>
							<a class="googleplus" href="<?php echo url_to_pager('googleplus-auth') ?>">
								<i class="fa fa-google"></i>
							</a>
						</li>
					<?php endif ?>
					<?php if(config('enable-vk', false)): ?>
						<li>
							<a class="vk" href="<?php echo url_to_pager('vk-auth') ?>">
								<i class="fa fa-vk"></i>
							</a>
						</li>
					<?php endif ?>
					<?php echo fire_hook('extend.third.party.auth', null, array()); ?>
				</ul>
			</div>
		</div>
	<?php endif ?>
</div>