<?php echo view("affliate::tm"); ?>

<div class="box">
    <div class="title"><?php echo lang("affliate::affliate-signup"); ?></div>
    <div class="box-content row">
        <?php if($message): ?>
            <div class="alert alert-info"><?php echo $message; ?></div>
        <?php endif; ?>
        <div class="container" id="affliate-signup">
            <form class="form" action="" method="post">
                <?php CSRFProtection::embed(); ?>
                <div class="col-sm-12">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label><?php echo lang("affliate::contact-name") ?></label>
                            <input class="form-control" value="<?php echo input('val.name'); ?>" name="val[name]" type="text" />
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label><?php echo lang("affliate::contact-email"); ?></label>
                            <input class="form-control" value="<?php echo input('val.email'); ?>" name="val[email]" type="text" />
                        </div>
                    </div>
                </div><br/>
                <div class="col-sm-12">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label><?php echo lang("affliate::contact-address"); ?></label>
                            <input class="form-control" value="<?php echo input('val.address'); ?>" name="val[address]" type="text" />
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label><?php echo lang("affliate::contact-phone"); ?></label>
                            <input class="form-control" value="<?php echo input('val.phone'); ?>" name="val[phone]" type="text" />
                        </div>
                    </div>
                </div>
                <br/>
                <div class="col-sm-12">
                    <p><input type="checkbox" name="val[terms]" />  <?php echo lang("affliate::i-have-read") ?> <b><a id="show-aff-tc" href=""><?php  echo lang("affliate::terms-condition")?></a></b></p>
                    <button class="btn btn-info"><?php echo lang("affliate::register") ?></button>
                </div>
            </form>
        </div>
    </div>
</div>

<div id="tc-modal" class="modal fade " tabindex="-1" role="dialog" aria-labelledby="mytc-modal" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only"><?php _lang('close')?></span>
                </button>
                <h5 class="modal-title"><?php _lang('affliate::terms-condition'); ?></h5>
            </div>
            <div class="modal-body">
                <?php echo get_affliate_tc(); ?>
            </div>
        </div>
    </div>
</div>