<?php $call_types = array(
    '1' => 'Read more',
    '2' => 'Shop now',
    '3' => 'View now',
    '4' => 'Visit now',
    '5' => 'Book now',
    '6' => 'Learn more',
    '7' => 'Play now',
    '8' => 'Bet now',
    '9' => 'Donate',
    '10' => 'Apply now',
    '11' => 'Quote here',
    '12' => 'Order now',
    '13' => 'Book Tickets',
    '14' => 'Enroll mow',
    '15' => 'Find a card',
    '16' => 'Get a quote',
    '17' => 'Get tickets',
    '18' => 'Locate a dealer',
    '19' => 'Order online',
    '20' => 'Pre-order now',
    '21' => 'Schedule now',
    '22' => 'Sign up now',
    '23' => 'Subscribe',
    '24' => 'Register now'
) ?>

<?php echo view('layouts/menu') ?>
<div class="container pr-profile-container">
	<div data-width="950" class="profile-container" id="page-profile-container" data-id="<?php echo get_page_details('page_id') ?>">
		<?php if(config('design-profile', true) and is_page_admin($app->profilePage)): ?>
			<?php echo view('design/pane', array('default' => get_user_design_details($app->profilePage), 'type' => 'page', 'typeId' => $app->profilePage['page_id'])) ?>
		<?php endif ?>
		<div id="profile-cover" class="box">
			<?php if(config('design-profile', true) and is_page_admin($app->profilePage)): ?>
				<a onclick="return open_designer()" href="" data-toggle="tooltip" title="<?php echo lang('design-your-page') ?>" class="btn btn-secondary btn-sm design-button"><i class="ion-paintbucket"></i></a>
			<?php endif ?>
			<div class="profile-cover-indicator">
				<img src="<?php echo img('images/loading.gif') ?>"/>
			</div>
			<a href="javascript::void(0)" id="profile-cover-viewer" data-id="<?php echo ($app->profilePage['page_cover']) ? get_media_id($app->profilePage['page_cover']) : null ?>" data-image="<?php echo get_page_cover(app()->profilePage) ?>" class="<?php echo ($app->profilePage['page_cover']) ? 'photo-viewer' : null ?>">
				<div class="profile-cover-wrapper">
					<img src="<?php echo get_page_cover(app()->profilePage, false) ?>"/>
				</div>
			</a>

			<?php if(is_page_admin($app->profilePage) or is_page_editor($app->profilePage) or is_page_moderator($app->profilePage)): ?>

				<div class="profile-resize-cover-wrapper">
					<div class="drag-info"><?php echo lang('drag-to-position-cover') ?></div>
					<img src="<?php echo get_page_cover(app()->profilePage) ?>"/>
				</div>
				<form id="profile-cover-change-form" enctype="multipart/form-data" method="post">
					<?php CSRFProtection::embed() ?>
					<span class="file-input"><input accept="image/*" multiple onchange="return upload_page_profile_cover()" type="file" id="user-profile-cover-input" name="image"/> </span>
					<div class="dropdown">
						<button class="btn btn-sm btn-info dropdown-toggle" data-toggle="dropdown">
							<i class="ion-camera"></i> <?php echo lang('change-cover') ?>
						</button>
						<ul style="width: 240px" class="dropdown-menu dropdown-menu-right" id="profile-cover-dropdown-menu">
							<li>
								<a class="dropdown-item" onclick="return file_chooser('#user-profile-cover-input')" href=""><?php echo lang('upload-photo') ?>...</a>
							</li>
							<li class="hide-in-mobile">
								<a class="dropdown-item" onclick="return reposition_user_profile_cover()" href=""><?php echo lang('reposition') ?>...</a>
							</li>
							<li>
								<a class="dropdown-item" onclick="return remove_page_profile_cover('<?php echo img("images/cover.jpg") ?>')" href=""><?php echo lang('remove') ?>...</a>
							</li>
						</ul>
					</div>
				</form>
				<div class="profile-cover-reposition-button">
					<input type="hidden" id="profile-cover-resized-top" value="0"/>
					<a onclick="return cancel_profile_cover_position()" class="btn-danger-outline btn btn-sm" href="#!"><?php echo lang('cancel') ?></a>
					<a onclick="return save_page_profile_cover()" class="btn btn-success btn-upper btn-sm" href=""><?php echo lang('save') ?></a>
				</div>
			<?php endif ?>
			<div class="user-avatar box">
				<?php if(is_page_admin($app->profilePage) || is_page_moderator($app->profilePage)): ?>
					<form data-id="<?php echo $app->profilePage['page_id'] ?>" id="page-profile-image-form" action="" method="post" enctype="multipart/form-data">
						<?php CSRFProtection::embed() ?>
						<span class="file-input"><input accept="image/*" multiple onchange="upload_page_logo()" type="file" id="page-avatar-input" name="logo"/> </span>
						<a class="profile-image-selector" id="profile-image-selector" href="" <?php echo config('profile-avatar-crop', true) ? 'onclick="return false"' : 'onclick="return file_chooser(\'#page-avatar-input\')"' ?>><i class="ion-ios-camera"></i>
							<span></span>
						</a>
					</form>
				<?php endif ?>
				<div class="profile-image-indicator">
					<img src="<?php echo img("images/loading.gif") ?>"/>
					<span class="percent-indicator">0%</span>
				</div>

				<a id="profile-image-viewer" style="display: block" href="javascript::void(0)" data-id="<?php echo ($app->profilePage['page_logo']) ? get_media_id($app->profilePage['page_logo']) : null ?>" data-image="<?php echo get_page_logo(920, app()->profilePage) ?>" class="<?php echo ($app->profilePage['page_logo']) ? 'photo-viewer' : null ?>">
					<img id="profile-image" class="profile-image" src="<?php echo get_page_logo(200, app()->profilePage) ?>"/>
				</a>

			</div>
			<div class="user-info">
				<h4 class="user-name left"><?php echo get_page_details('page_title') ?> <?php echo verify_badge($app->profilePage) ?></h4>
			</div>

			<nav id="profile-menu" class="">
				<div class="navbar navbar-light">
					<ul id="menu" class="nav navbar-nav">
						<?php foreach(get_menus("page-profile") as $menu): ?>
							<li class="<?php echo ($menu->isActive() == 1) ? 'active' : null ?>">
								<a ajax="true" href="<?php echo $menu->link ?>"><?php echo $menu->title ?></a>
							</li>
						<?php endforeach ?>
						<?php $page_profile_more = get_menus("page-profile-more") ?>
						<?php if(!empty($page_profile_more)): ?>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									<i class="ion-ios-more"></i></a>
								<ul style="width: 200px;" id="profile-more-menu" class="dropdown-menu dropdown-menu-right">
									<?php foreach($page_profile_more as $menu): ?>
										<li>
											<a class="dropdown-item" href="<?php echo $menu->link ?>"><?php echo $menu->title ?></a>
										</li>
									<?php endforeach ?>
									<?php $page_profile_more = get_menus("page-profile-more") ?>
									<?php if(!empty($page_profile_more)): ?>
										<li class="dropdown">
											<a href="#" class="dropdown-toggle" data-toggle="dropdown">
												<i class="ion-ios-more"></i></a>
											<ul style="width: 250px;" id="profile-more-menu" class="dropdown-menu">
												<?php foreach($page_profile_more as $menu): ?>
													<li>
														<a ajax="true" class="dropdown-item" href="<?php echo $menu->link ?>"><?php echo $menu->title ?></a>
													</li>
												<?php endforeach ?>

											</ul>
										</li>
									<?php endif ?>
								</ul>
							</li>
						<?php endif ?>
					</ul>

				</div>
			</nav>
		</div>

		<div class="profile-actions">
            <?php if ($app->profilePage['target_type'] && $app->profilePage['target_call']): ?>
                <a href="<?php echo $app->profilePage['target_call'] ?>" target="_blank" class="btn btn-secondary"><?php echo $call_types[$app->profilePage['target_type']] ?></a>
            <?php endif; ?>
			<?php if(is_loggedIn()): ?>
                <?php if(plugin_loaded('chat') &&(!is_page_admin($app->profilePage) or !is_page_editor($app->profilePage) or !is_page_moderator($app->profilePage))): ?>
                    <a onclick="return Chat.open(null, '<?php echo get_userid() ?>', '<?php echo $app->profilePage['page_title'] ?>', '<?php echo get_page_logo(200, app()->profilePage) ?>', null, null, this, 'page', '<?php echo $app->profilePage['page_id'] ?>')" class="btn btn-secondary "><i class="ion-ios-chatboxes-outline"></i> <?php echo lang('chat::message') ?>
                        <?php fire_hook("page.more.button",$app->profilePage,array('page'))?>
                    </a>
                <?php endif ?>
				<?php if(plugin_loaded('like')): ?>
					<?php load_functions('like::like'); ?>
					<a onclick="return like_item('page', '<?php echo $app->profilePage['page_id'] ?>')" data-status="<?php echo (has_liked('page', $app->profilePage['page_id'])) ? '1' : 0 ?>" class="btn btn-secondary like-button-page-<?php echo $app->profilePage['page_id'] ?> like-button <?php echo (has_liked('page', $app->profilePage['page_id'])) ? 'liked' : null ?>" href="">
						<i class="fa fa-thumbs-o-up"></i> <?php echo lang('like::like') ?>
					</a>
				<?php endif ?>
				<?php if(is_page_admin($app->profilePage) or is_page_editor($app->profilePage) or is_page_moderator($app->profilePage)): ?>
					<a ajax="true" href="<?php echo url_to_pager('page-manage', array('id' => get_page_details('page_id'))) ?>" class="btn btn-secondary "><i class="ion-edit"></i> <?php echo lang('edit') ?>
                        <?php fire_hook("page.more.button",$app->profilePage,array('page'))?>
					</a>
				<?php endif ?>
			<?php endif ?>
            <span class="page-social-share"><?php if(plugin_loaded('sharer')) echo view('sharer::share_link', array('link' => url($app->profilePage['page_url']))) ?></span>
			<?php if(is_loggedIn() and plugin_loaded('report')): ?>
				<a data-type="page" data-link="<?php echo page_url(null, $app->profilePage) ?>" class="report-btn btn btn-secondary " href=""><i class="ion-flag"></i></a>
			<?php endif ?>

			<?php if(is_loggedIn()): ?>
				<span class="dropdown">
                        <a href="" class="dropdown-toggle btn btn-secondary" data-toggle="dropdown"><i class="ion-android-more-vertical"></i></a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li>
                                <a onclick="return process_user_save(this, 'page', '<?php echo $app->profilePage['page_id'] ?>')" href="" class="dropdown-item user-save" data-status="<?php echo (user_saved('page', $app->profilePage['page_id'])) ? 1 : 0 ?>">
                                    <i class="ion-android-bookmark"></i>
                                    <span><?php echo (user_saved('page', $app->profilePage['page_id'])) ? lang('unsave-post') : lang('save-post') ?></span>
                                </a>
                            </li>
	                        <?php fire_hook('profile.actions.page', null, array()); ?>
                        </ul>
                    </span>

			<?php endif ?>
		</div>
	</div>

</div>
<div id="user-profile-content-container">
		<?php echo $content ?>
</div>
<div class="container" id="crop-avatar">

	<!-- Cropping modal -->
	<div class="modal fade" id="avatar-modal" aria-hidden="true" aria-labelledby="avatar-modal-label" role="dialog" tabindex="-1">
		<div class="modal-dialog modal-lg">
			<div class="modal-content">
				<form id="avatar-crop-form" class="avatar-form" action="<?php echo $url = url('page/change/logo').'?id='.$app->profilePage['page_id'] ?>" enctype="multipart/form-data" method="post">
					<?php CSRFProtection::embed() ?>
					<div class="modal-header">
						<h4 class="modal-title" id="avatar-modal-label">Change Avatar</h4>
						<button type="button" class="close" data-dismiss="modal">&times;</button>
					</div>
					<div class="modal-body">
						<div class="avatar-body">

							<!-- Upload image and data -->
							<div class="avatar-upload">
								<input type="hidden" class="avatar-src" name="avatar_src">
								<input type="hidden" class="avatar-data" name="avatar_data">
								<label for="avatarInput">Local upload</label>
								<input type="file" class="avatar-input" id="avatarInput" name="avatar_file">
							</div>

							<!-- Crop and preview -->
							<div class="row">
								<div class="col-md-9">
									<div class="avatar-wrapper"></div>
								</div>
								<div class="col-md-3">
									<div class="avatar-preview preview-lg"></div>
									<div class="avatar-preview preview-md"></div>
									<div class="avatar-preview preview-sm"></div>
								</div>
							</div>

							<div class="row avatar-btns">
								<div class="col-md-11">
									<div class="btn-group">
										<button type="button" class="btn btn-outline-info flip-horizontal ion-refresh" data-method="rotate" data-option="-15" title="<?php echo lang('rotate-left') ?>"></button>
										<button type="button" class="btn btn-outline-info ion-refresh" data-method="rotate" data-option="15" title="<?php echo lang('rotate-right') ?>"></button>
									</div>
									<div class="btn-group">
										<button type="button" class="btn btn-outline-info fa fa-search-plus" data-method="zoom" data-option="0.1" title="<?php echo lang('zoom-in') ?>"></button>
										<button type="button" class="btn btn-outline-info fa fa-search-minus" data-method="zoom" data-option="-0.1" title="<?php echo lang('zoom-out') ?>"></button>
									</div>
									<div class="btn-group">
										<button type="button" class="btn btn-outline-info fa fa-arrows-h" data-method="scaleX" data-option="-1" title="<?php echo lang('flip-horizontal') ?>"></button>
										<button type="button" class="btn btn-outline-info fa fa-arrows-v" data-method="scaleY" data-option="-1" title="<?php echo lang('flip-vertical') ?>"></button>
									</div>
									<!--									<div class="btn-group">-->
									<!--										<button type="button" class="btn btn-outline-info ion-ios-arrow-back" data-method="move" data-option="-10" data-second-option="0" title="--><?php //echo lang('move-left') ?><!--"></button>-->
									<!--										<button type="button" class="btn btn-outline-info ion-ios-arrow-up" data-method="move" data-option="0" data-second-option="-10" title="--><?php //echo lang('move-up') ?><!--"></button>-->
									<!--										<button type="button" class="btn btn-outline-info ion-ios-arrow-forward" data-method="move" data-option="10" data-second-option="0" title="--><?php //echo lang('move-right') ?><!--"></button>-->
									<!--										<button type="button" class="btn btn-outline-info ion-ios-arrow-down" data-method="move" data-option="0" data-second-option="10" title="--><?php //echo lang('move-down') ?><!--"></button>-->
									<!--									</div>-->
									<button type="button" class="btn btn-outline-info ion-android-sync" data-method="reset" title="<?php echo lang('reset') ?>"></button>
								</div>
								<div class="col-md-1">
									<button type="submit" class="btn btn-outline-info avatar-save ion-android-send" title="<?php echo lang('done') ?>"></button>
								</div>
							</div>
						</div>
					</div>
					<!-- <div class="modal-footer">
					  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
					</div> -->
				</form>
			</div>
			<!-- Loading state -->
			<div class="loading" aria-label="Loading" role="img" tabindex="-1"></div>
		</div>
	</div><!-- /.modal -->
</div>
