<?php if(is_page_admin($app->profilePage) || is_page_editor($app->profilePage) || is_page_moderator($app->profilePage) || $app->profilePage['visitor_editor']): ?>
    <?php echo view('feed::editor', array(
		'offPrivacy' => true,
		'avatar' => get_page_logo(75, $app->profilePage),
		'privacy' => 1,
		'type' => 'page',
		'type_id' => $app->profilePage['page_id'],
		'entity_type' => 'page',
		'entity_id' => $app->profilePage['page_id'],
		'offTagging' => true)) ?>
<?php endif ?>
<div id="feed-lists" data-type="page" data-type-id="<?php echo $app->profilePage['page_id'] ?>" data-offset="0">
	<?php $feed = get_pinned_feed('page', $app->profilePage['page_id']);
	if($feed) echo view('feed::feed', array('feed' => $feed)) ?>
	<?php $i = 0;
	foreach($feeds as $feed):fire_hook('feed.lists.inline', null, array($i)); $i++ ?>
		<?php echo view('feed::feed', array('feed' => $feed)) ?>
	<?php endforeach ?>
</div>
<?php if(!count($feeds)): ?>
	<div class="feed-empty text-center">
		<i class="ion-android-bicycle"></i>
		<h3><?php echo lang('no-post-show') ?></h3>
	</div>
<?php endif ?>
<?php if(count($feeds)): ?>
	<div class="feed-load-more">
		<div class="col-sm-2 no-padding"></div>
		<div class="col-sm-10 no-padding">
			<div class="feed-loading">
				<div class="feed_loading_post">
					<div class="feed_loading_post_child2">

					</div>
				</div>
			</div>
		</div>
	</div>
<?php endif ?>