<div class="wrapper business">
	<div class="wrapper-title">
		<p><?php echo lang('business::businesses-manager-active') ?></p>
		<span><?php echo lang('business::businesses-manager-active-desc') ?></span>
	</div>
	<div class="wrapper-content">
        <?php $filter = 'all'; ?>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a href="<?php echo url_to_pager('admin-business-active') ?>" class="nav-link <?php echo ($filter == 'all') ? 'active' : null ?>"><?php echo lang('business::active') ?></a>
            </li>
            <li class="nav-item">
                <a href="<?php echo url_to_pager('admin-business-claimable') ?>" class="nav-link"><?php echo lang('business::claimable') ?></a>
            </li>
            <li class="nav-item">
                <a href="<?php echo url_to_pager('admin-business-claimed') ?>" class="nav-link "><?php echo lang('business::claim-log') ?></a>
            </li>
            <li class="nav-item">
                <a href="<?php echo url_to_pager('admin-business-pending') ?>" class="nav-link"><?php echo lang('business::pending-approval') ?></a>
            </li>
        </ul>
		<table class="table table-bordered wrapper-form">
			<thead>
			<tr>
				<th>ID</th>
				<th><?php echo lang('business::title') ?></th>
				<th><?php echo lang('business::category') ?></th>
				<th><?php echo lang('business::price') ?></th>
				<th><?php echo lang('business::views') ?></th>
				<th><?php echo lang('business::featured') ?></th>
				<th><?php echo lang('business::approved') ?></th>
				<th><?php echo lang('business::actions') ?></th>
			</tr>
			</thead>
			<tbody>
			<?php foreach($businesses->results() as $business): ?>
				<tr>
					<td><?php echo $business['id'] ?></td>
					<td><?php echo $business['business_name'] ?></td>
					<td><?php echo lang($business['category_title']) ?></td>
					<td><?php echo $business['price'] <= 0 ? lang('business::free') : $business['price'].' '.config('default-currency') ?></td>
					<td><?php echo $business['views'] <= 1 ? viewCounts($business['id']).' '.lang('business::view') : viewCounts($business['id']).' '.lang('business::views') ?></td>
					<td><?php echo $business['featured'] ? lang('business::yes') : lang('business::no') ?></td>
					<td><?php echo $business['approved'] ? lang('business::yes') : lang('business::no') ?></td>
					<td>
						<?php if($business['approved'] == 0): ?>
							<a href="<?php echo url_to_pager('admin-business-approve').'?id='.$business['id'] ?>" class="btn btn-success btn-sm admin-confirm"><?php echo lang('business::approve') ?></a> <?php endif; ?>
						<?php if($business['approved'] == 1): ?>
							<a href="<?php echo url_to_pager('admin-business-disapprove').'?id='.$business['id'] ?>" class="btn alert-info btn-sm admin-confirm"><?php echo lang('business::disapprove') ?></a> <?php endif; ?>
						<a href="<?php echo url_to_pager('admin-business-edit').'?id='.$business['id'] ?>" class="btn btn-primary btn-sm"><?php echo lang('business::edit') ?></a>
						<a href="<?php echo url_to_pager('admin-business-delete').'?id='.$business['id'] ?>" class="btn btn-danger btn-sm admin-confirm"><?php echo lang('business::delete') ?></a>
					</td>
				</tr>
			<?php endforeach ?>
			</tbody>
		</table>
		<?php if($businesses->total): ?>
			<?php if($businesses->total > config('pagination-limit-businesses', 20)): ?>
				<?php echo $businesses->links() ?>
			<?php endif ?>
		<?php else: ?>
			<div class="alert alert-info"><?php echo lang('business::no-business-found') ?></div>
		<?php endif ?>
	</div>
</div>