<?php
$countries = business_get_country();
$types = business_get_type();
?>
<div class="wrapper business">
	<div class="wrapper-title">
		<p><?php echo lang('business::edit-business') ?></p>
		<span><?php ?></span>
	</div>
	<div class="wrapper-title">
		<a href="<?php echo url_to_pager('admin-business-add') ?>" class="btn btn-primary"><?php echo lang('business::add-new') ?></a>
		<a href="<?php echo url_to_pager('admin-business-pending') ?>" class="btn btn-danger"><?php echo lang('business::pending-approval') ?></a>
		<a href="<?php echo url_to_pager('admin-business-active') ?>" class="btn btn-success "><?php echo lang('business::active') ?></a>
		<a href="<?php echo url_to_pager('admin-business-claimable') ?>" class="btn btn-info "><?php echo lang('business::claimable') ?></a>
		<a href="<?php echo url_to_pager('admin-business-claimed') ?>" class="btn btn-primary "><?php echo lang('business::claim-log') ?></a>
	</div>
</div>
<div class="wrapper-content">
	<div id="edit-business" class="business business-content box">
		<div id="business-page-title" class="business-title"><?php echo lang('business::edit-business') ?></div>
		<?php if($message): ?>
			<div class="alert alert-danger"><?php echo $message ?></div>
		<?php endif ?>
		<form action="" method="post" enctype="multipart/form-data">
			<?php CSRFProtection::embed() ?>
			<div class="form-group row">
				<div class="col-sm-4">
					<h6>
						<label class="control-label" for="val[type]"><?php echo lang('business::type') ?>:</label>
					</h6>
					<p class="business-form-description"><?php echo lang('business::create-business-type-desc') ?></p>
				</div>
				<div class="col-sm-8">
					<div class="input-field col s10">
						<select name="val[type_id]" class="form-control c-select">
							<option <?php echo ($business['business_type_id'] == 1) ? 'selected' : null ?> value="1"><?php echo lang('business::personal-business') ?></option>
							<option <?php echo ($business['business_type_id'] == 2) ? 'selected' : null ?> value="2"><?php echo lang('business::claim-business') ?></option>
						</select>
					</div>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-4">
					<h6>
						<label class="control-label" for="val[category]"><?php echo lang('business::category') ?>:</label>
					</h6>
					<p class="business-form-description"><?php echo lang('business::create-business-category-desc') ?></p>
				</div>
				<div class="col-sm-8">
					<div class="input-field col s10">
						<select name="val[category_id]" class="form-control c-select">
							<option value="<?php echo $business['category_id'] ?>"><?php echo lang(find_cat_name($business['category_id'])) ?></option>
							<?php foreach($categories as $category): ?>
								<option value="<?php echo $category['id'] ?>"><?php echo lang($category['category']) ?></option>
							<?php endforeach ?>
						</select>
					</div>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-4">
					<h6>
						<label class="control-label" for="val[busniess_name]"><?php echo lang('business::name') ?>: </label>
					</h6>
					<p class="business-form-description"><?php echo lang('business::create-business-title-desc') ?></p>
				</div>
				<div class="col-sm-8">
					<div class="input-field col s10">
						<input name="val[business_name]" value="<?php echo $business['business_name'] ?>" type="text" class="form-control" required placeholder="Business Name"/>
					</div>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-4">
					<h6>
						<label class="control-label" for="val[description]"><?php echo lang('business::description') ?>: </label>
					</h6>
					<p class="business-form-description"><?php echo lang('business::create-business-description-desc') ?></p>
				</div>
				<div class="col-sm-8">
					<div class="input-field col s10">
						<textarea id="business-edit-description-textarea" name="val[description]" class="form-control ckeditor"> <?php echo $business['description']; ?> </textarea>
					</div>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-4">
					<h6>
						<label class="control-label" for="val[address]"><?php echo lang('business::address') ?>: </label>
					</h6>
					<p class="business-form-description"><?php echo lang('business::create-business-address-desc') ?></p>
				</div>
				<div class="col-sm-8">
					<div class="input-field col s10">
						<input onfocus="geolocate()" id="autocomplete" name="val[address]" value="<?php echo $business['company_address'] ?>" type="text" class="form-control" required placeholder="Enter Business Address"/>
					</div>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-4">
					<h6>
						<label class="control-label" for="val[country]"><?php echo lang('business::country') ?>:</label>
					</h6>
					<p class="business-form-description"><?php echo lang('business::create-business-country-desc') ?></p>
				</div>
				<div class="col-sm-8">
					<div class="input-field col s10">
						<select name="val[country]" class="form-control c-select">
							<option value="<?php echo $business['country'] ?>"><?php echo lang(find_country_name($business['country'])) ?></option>
							<?php foreach($countries as $country): ?>
								<option value="<?php echo $country['id'] ?>"><?php echo lang($country['country_name']) ?></option>
							<?php endforeach ?>
						</select>
					</div>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-4">
					<h6>
						<label class="control-label" for="val[timezone]"><?php echo lang('business::timezone') ?>:</label>
					</h6>
					<p class="business-form-description"><?php echo lang('business::create-business-timezone-desc') ?></p>
				</div>
				<div class="col-sm-8">
					<div class="input-field col s10">
						<select name="val[timezone]" id="timezone" class="form-control">
							<option value="<?php echo $business['timezone']; ?>" selected="selected"> <?php echo $business['timezone']; ?> </option>
							<option value="Pacific/Kwajalein">(GMT-12:00) Kwajalein</option>
							<option value="Pacific/Midway">(GMT-11:00) Midway Island</option>
							<option value="Pacific/Samoa">(GMT-11:00) Samoa</option>
							<option value="Pacific/Honolulu">(GMT-10:00) Hawaii</option>
							<option value="America/Anchorage">(GMT-09:00) Alaska</option>
							<option value="America/Los_Angeles">(GMT-08:00) Pacific Time</option>
							<option value="America/Tijuana">(GMT-08:00) Tijuana, Baja California</option>
							<option value="America/Denver">(GMT-07:00) Mountain Time</option>
							<option value="America/Chihuahua">(GMT-07:00) Chihuahua</option>
							<option value="America/Mazatlan">(GMT-07:00) Mazatlan</option>
							<option value="America/Phoenix">(GMT-07:00) Arizona</option>
							<option value="America/Regina">(GMT-06:00) Saskatchewan</option>
							<option value="America/Tegucigalpa">(GMT-06:00) Central America</option>
							<option value="America/Chicago">(GMT-06:00) Central Time</option>
							<option value="America/Mexico_City">(GMT-06:00) Mexico City</option>
							<option value="America/Monterrey">(GMT-06:00) Monterrey</option>
							<option value="America/New_York">(GMT-05:00) Eastern Time</option>
							<option value="America/Bogota">(GMT-05:00) Bogota</option>
							<option value="America/Lima">(GMT-05:00) Lima</option>
							<option value="America/Rio_Branco">(GMT-05:00) Rio Branco</option>
							<option value="America/Indiana/Indianapolis">(GMT-05:00) Indiana (East)</option>
							<option value="America/Caracas">(GMT-04:30) Caracas</option>
							<option value="America/Halifax">(GMT-04:00) Atlantic Time</option>
							<option value="America/Manaus">(GMT-04:00) Manaus</option>
							<option value="America/Santiago">(GMT-04:00) Santiago</option>
							<option value="America/La_Paz">(GMT-04:00) La Paz</option>
							<option value="America/St_Johns">(GMT-03:30) Newfoundland</option>
							<option value="America/Argentina/Buenos_Aires">(GMT-03:00) Georgetown</option>
							<option value="America/Sao_Paulo">(GMT-03:00) Brasilia</option>
							<option value="America/Godthab">(GMT-03:00) Greenland</option>
							<option value="America/Montevideo">(GMT-03:00) Montevideo</option>
							<option value="Atlantic/South_Georgia">(GMT-02:00) Mid-Atlantic</option>
							<option value="Atlantic/Azores">(GMT-01:00) Azores</option>
							<option value="Atlantic/Cape_Verde">(GMT-01:00) Cape Verde Is.</option>
							<option value="Europe/Dublin">(GMT) Dublin</option>
							<option value="Europe/Lisbon">(GMT) Lisbon</option>
							<option value="Europe/London">(GMT) London</option>
							<option value="Africa/Monrovia">(GMT) Monrovia</option>
							<option value="Atlantic/Reykjavik">(GMT) Reykjavik</option>
							<option value="Africa/Casablanca">(GMT) Casablanca</option>
							<option value="Europe/Belgrade">(GMT+01:00) Belgrade</option>
							<option value="Europe/Bratislava">(GMT+01:00) Bratislava</option>
							<option value="Europe/Budapest">(GMT+01:00) Budapest</option>
							<option value="Europe/Ljubljana">(GMT+01:00) Ljubljana</option>
							<option value="Europe/Prague">(GMT+01:00) Prague</option>
							<option value="Europe/Sarajevo">(GMT+01:00) Sarajevo</option>
							<option value="Europe/Skopje">(GMT+01:00) Skopje</option>
							<option value="Europe/Warsaw">(GMT+01:00) Warsaw</option>
							<option value="Europe/Zagreb">(GMT+01:00) Zagreb</option>
							<option value="Europe/Brussels">(GMT+01:00) Brussels</option>
							<option value="Europe/Copenhagen">(GMT+01:00) Copenhagen</option>
							<option value="Europe/Madrid">(GMT+01:00) Madrid</option>
							<option value="Europe/Paris">(GMT+01:00) Paris</option>
							<option value="Africa/Algiers">(GMT+01:00) West Central Africa</option>
							<option value="Europe/Amsterdam">(GMT+01:00) Amsterdam</option>
							<option value="Europe/Berlin">(GMT+01:00) Berlin</option>
							<option value="Europe/Rome">(GMT+01:00) Rome</option>
							<option value="Europe/Stockholm">(GMT+01:00) Stockholm</option>
							<option value="Europe/Vienna">(GMT+01:00) Vienna</option>
							<option value="Europe/Minsk">(GMT+02:00) Minsk</option>
							<option value="Africa/Cairo">(GMT+02:00) Cairo</option>
							<option value="Europe/Helsinki">(GMT+02:00) Helsinki</option>
							<option value="Europe/Riga">(GMT+02:00) Riga</option>
							<option value="Europe/Sofia">(GMT+02:00) Sofia</option>
							<option value="Europe/Tallinn">(GMT+02:00) Tallinn</option>
							<option value="Europe/Vilnius">(GMT+02:00) Vilnius</option>
							<option value="Europe/Athens">(GMT+02:00) Athens</option>
							<option value="Europe/Bucharest">(GMT+02:00) Bucharest</option>
							<option value="Europe/Istanbul">(GMT+02:00) Istanbul</option>
							<option value="Asia/Jerusalem">(GMT+02:00) Jerusalem</option>
							<option value="Asia/Amman">(GMT+02:00) Amman</option>
							<option value="Asia/Beirut">(GMT+02:00) Beirut</option>
							<option value="Africa/Windhoek">(GMT+02:00) Windhoek</option>
							<option value="Africa/Harare">(GMT+02:00) Harare</option>
							<option value="Asia/Kuwait">(GMT+03:00) Kuwait</option>
							<option value="Asia/Riyadh">(GMT+03:00) Riyadh</option>
							<option value="Asia/Baghdad">(GMT+03:00) Baghdad</option>
							<option value="Africa/Nairobi">(GMT+03:00) Nairobi</option>
							<option value="Asia/Tbilisi">(GMT+03:00) Tbilisi</option>
							<option value="Europe/Moscow">(GMT+03:00) Moscow</option>
							<option value="Europe/Volgograd">(GMT+03:00) Volgograd</option>
							<option value="Asia/Tehran">(GMT+03:30) Tehran</option>
							<option value="Asia/Muscat">(GMT+04:00) Muscat</option>
							<option value="Asia/Baku">(GMT+04:00) Baku</option>
							<option value="Asia/Yerevan">(GMT+04:00) Yerevan</option>
							<option value="Asia/Yekaterinburg">(GMT+05:00) Ekaterinburg</option>
							<option value="Asia/Karachi">(GMT+05:00) Karachi</option>
							<option value="Asia/Tashkent">(GMT+05:00) Tashkent</option>
							<option value="Asia/Kolkata">(GMT+05:30) Calcutta</option>
							<option value="Asia/Colombo">(GMT+05:30) Sri Jayawardenepura</option>
							<option value="Asia/Katmandu">(GMT+05:45) Kathmandu</option>
							<option value="Asia/Dhaka">(GMT+06:00) Dhaka</option>
							<option value="Asia/Almaty">(GMT+06:00) Almaty</option>
							<option value="Asia/Novosibirsk">(GMT+06:00) Novosibirsk</option>
							<option value="Asia/Rangoon">(GMT+06:30) Yangon (Rangoon)</option>
							<option value="Asia/Krasnoyarsk">(GMT+07:00) Krasnoyarsk</option>
							<option value="Asia/Bangkok">(GMT+07:00) Bangkok</option>
							<option value="Asia/Jakarta">(GMT+07:00) Jakarta</option>
							<option value="Asia/Brunei">(GMT+08:00) Beijing</option>
							<option value="Asia/Chongqing">(GMT+08:00) Chongqing</option>
							<option value="Asia/Hong_Kong">(GMT+08:00) Hong Kong</option>
							<option value="Asia/Urumqi">(GMT+08:00) Urumqi</option>
							<option value="Asia/Irkutsk">(GMT+08:00) Irkutsk</option>
							<option value="Asia/Ulaanbaatar">(GMT+08:00) Ulaan Bataar</option>
							<option value="Asia/Kuala_Lumpur">(GMT+08:00) Kuala Lumpur</option>
							<option value="Asia/Singapore">(GMT+08:00) Singapore</option>
							<option value="Asia/Taipei">(GMT+08:00) Taipei</option>
							<option value="Australia/Perth">(GMT+08:00) Perth</option>
							<option value="Asia/Seoul">(GMT+09:00) Seoul</option>
							<option value="Asia/Tokyo">(GMT+09:00) Tokyo</option>
							<option value="Asia/Yakutsk">(GMT+09:00) Yakutsk</option>
							<option value="Australia/Darwin">(GMT+09:30) Darwin</option>
							<option value="Australia/Adelaide">(GMT+09:30) Adelaide</option>
							<option value="Australia/Canberra">(GMT+10:00) Canberra</option>
							<option value="Australia/Melbourne">(GMT+10:00) Melbourne</option>
							<option value="Australia/Sydney">(GMT+10:00) Sydney</option>
							<option value="Australia/Brisbane">(GMT+10:00) Brisbane</option>
							<option value="Australia/Hobart">(GMT+10:00) Hobart</option>
							<option value="Asia/Vladivostok">(GMT+10:00) Vladivostok</option>
							<option value="Pacific/Guam">(GMT+10:00) Guam</option>
							<option value="Pacific/Port_Moresby">(GMT+10:00) Port Moresby</option>
							<option value="Asia/Magadan">(GMT+11:00) Magadan</option>
							<option value="Pacific/Fiji">(GMT+12:00) Fiji</option>
							<option value="Asia/Kamchatka">(GMT+12:00) Kamchatka</option>
							<option value="Pacific/Auckland">(GMT+12:00) Auckland</option>
							<option value="Pacific/Tongatapu">(GMT+13:00) Nukualofa</option>
						</select>
					</div>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-4">
					<h6>
						<label class="control-label" for="val[address]"><?php echo lang('business::company-phone') ?>: </label>
					</h6>
					<p class="business-form-description"><?php echo lang('business::create-business-phone-desc') ?></p>
				</div>
				<div class="col-sm-8">
					<div class="input-field col s10">
						<input name="val[phone]" type="tel" value="<?php echo $business['business_number'] ?>" class="form-control" required placeholder="Enter Business Phone Number"/>
					</div>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-4">
					<h6>
						<label class="control-label" for="val[fax]"><?php echo lang('business::fax') ?>: </label>
					</h6>
					<p class="business-form-description"><?php echo lang('business::create-business-fax-desc') ?></p>
				</div>
				<div class="col-sm-8">
					<div class="input-field col s10">
						<input name="val[fax]" type="tel" value="<?php echo $business['fax']; ?>" class="form-control" required placeholder="Enter Business Fax Number"/>
					</div>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-4">
					<h6>
						<label class="control-label" for="val[email]"><?php echo lang('business::company-email') ?>: </label>
					</h6>
					<p class="business-form-description"><?php echo lang('business::create-business-email-desc') ?></p>
				</div>
				<div class="col-sm-8">
					<div class="input-field col s10">
						<input name="val[email]" type="email" value="<?php echo $business['company_email'] ?>" class="form-control" required placeholder="Enter Business Email"/>
					</div>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-4">
					<h6>
						<label class="control-label" for="val[link]"><?php echo lang('business::link') ?>: </label>
					</h6>
					<p class="business-form-description"><?php echo lang('business::create-business-link-desc') ?>.</p>
				</div>
				<div class="col-sm-8">
					<div class="input-field col s10">
						<input type="url" name="val[link]" value="<?php echo $business['website'] ?>" class="form-control" placeholder="http://domain.com"/>
					</div>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-4">
					<h6>
						<label class="control-label" for="val[price]"><?php echo lang('business::price') ?>: </label>
					</h6>
					<p class="business-form-description"><?php echo lang('business::create-business-price-desc') ?></p>
				</div>
				<div class="col-sm-8">
					<div class="input-field col s10">
						<input class="form-control" type="text" name="val[price]" value="<?php echo lang($business['price']); ?>" size="30" placeholder="Enter business price">
					</div>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-4">
					<h6>
						<label class="control-label" for="val[size]"><?php echo lang('business::create-size') ?>:</label>
					</h6>
					<p class="business-form-description"><?php echo lang('business::create-business-size-desc') ?></p>
				</div>
				<div class="col-sm-8">
					<div class="input-field col s10">
						<select class="form-control" id="" name="val[size]">
							<option value="1 - 50">1 - 50</option>
							<option value="51 - 250">51 - 250</option>
							<option value="251 - 1000">251 - 1000</option>
							<option value="> 1000">&gt; 1000</option>
						</select>
					</div>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-4">
					<h6>
						<label class="control-label" for="val[tag_list]"><?php echo lang('business::tag') ?>: </label>
					</h6>
					<p class="business-form-description"><?php echo lang('business::create-business-tags-desc') ?></p>
				</div>
				<div class="col-sm-8">
					<div class="input-field col s10">
						<input class="form-control" type="text" name="val[tag_list]" value="<?php echo $business['tags'] ?>" size="30" placeholder="keywords associated with your business separated by commas">
					</div>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-4">
					<h6>
						<label class="control-label" for="val[always_open]"><?php echo lang('business::always-opened') ?>:</label>
					</h6>
					<p class="business-form-description"><?php echo lang('business::create-business-always-opened-desc') ?></p>
				</div>
				<div class="col-sm-8">
					<div id="errorcontainer" class="errorcontainer"></div>
					<div class="input-field col s10" data-id="business_hr">
						<input type="checkbox" name="val[always_open]" id="business_checkbox" class="" onfocus="return removeBusinessHours(this)">
						<?php $hours = get_business_hour($business['id']); ?>
						<input type="hidden" name="val[counter]" data-id="counter" value="<?php echo count($hours->results()); ?>" id="addbutton">
						<i class="ion-android-add-circle" id="add_hr" style="color:green" onclick="return addBusinessHours(this)"> </i>
						<div class="addmorebusiness" id="addmorebusiness" data-id="addmorebusiness">
							<?php
							$div = rand(1, 1000);
							foreach($hours->results() as $hour):
								?>
								<div id="<?php echo $div ?>">
									<select class="form-control valid" name="val[visiting_hours_dayofweek_id][]">
										<option value="<?php echo $hour['day']; ?>" selected><?php echo lang($hour['day']); ?></option>
										<option value="Monday">Monday</option>
										<option value="Tuesday">Tuesday</option>
										<option value="Wednesday">Wednesday</option>
										<option value="Thursday">Thursday</option>
										<option value="5">Friday</option>
										<option value="Saturday">Saturday</option>
										<option value="Sunday">Sunday</option>
									</select>
									<select class="form-control valid" name="val[visiting_hours_hour_starttime][]">
										<option selected value="<?php echo $hour['open_time']; ?>"> <?php echo lang($hour['open_time']); ?></option>
										<option value="Closed">Closed</option>
										<option value
										"00:00">12:00 AM </option>
										<option value="00:30">12:30 AM</option>
										<option value="01:00">01:00 AM</option>
										<option value="01:30">01:30 AM</option>
										<option value="02:00">02:00 AM</option>
										<option value="02:30">02:30 AM</option>
										<option value="03:00">03:00 AM</option>
										<option value="03:30">03:30 AM</option>
										<option value="04:00">04:00 AM</option>
										<option value="04:30">04:30 AM</option>
										<option value="05:00">05:00 AM</option>
										<option value="05:30">05:30 AM</option>
										<option value="06:00">06:00 AM</option>
										<option value="06:30">06:30 AM</option>
										<option value="07:00">07:00 AM</option>
										<option value="07:30">07:30 AM</option>
										<option value="08:00">08:00 AM</option>
										<option value="08:30">08:30 AM</option>
										<option value="09:00">09:00 AM</option>
										<option value="09:30">09:30 AM</option>
										<option value="10:00">10:00 AM</option>
										<option value="10:30">10:30 AM</option>
										<option value="11:00">11:00 AM</option>
										<option value="11:30">11:30 AM</option>
										<option value="12:00">12:00 PM</option>
										<option value="12:30">12:30 PM</option>
										<option value="13:00">01:00 PM</option>
										<option value="13:30">01:30 PM</option>
										<option value="14:00">02:00 PM</option>
										<option value="14:30">02:30 PM</option>
										<option value="15:00">03:00 PM</option>
										<option value="15:30">03:30 PM</option>
										<option value="16:00">04:00 PM</option>
										<option value="16:30">04:30 PM</option>
										<option value="17:00">05:00 PM</option>
										<option value="17:30">05:30 PM</option>
										<option value="18:00">06:00PM</option>
										<option value="18:30">06:30 PM</option>
										<option value="19:00">07:00 PM</option>
										<option value="19:30">07:30 PM</option>
										<option value="20:00">08:00 PM</option>
										<option value="20:30">08:30 PM</option>
										<option value="21:00">09:00 PM</option>
										<option value="21:30">09:30 PM</option>
										<option value="22:00">10:00 PM</option>
										<option value="22:30">10:30 PM</option>
										<option value="23:00">11:00 PM</option>
										<option value="23:30">11:30 PM</option>
									</select>
									<select class="form-control valid" name="val[visiting_hours_hour_endtime][]">
										<option selected value="<?php echo $hour['close_time']; ?>"> <?php echo lang($hour['close_time']); ?></option>
										<option value="Closed">Closed</option>
										<option value
										"00:00">12:00 AM </option>
										<option value="00:30">12:30 AM</option>
										<option value="01:00">01:00 AM</option>
										<option value="01:30">01:30 AM</option>
										<option value="02:00">02:00 AM</option>
										<option value="02:30">02:30 AM</option>
										<option value="03:00">03:00 AM</option>
										<option value="03:30">03:30 AM</option>
										<option value="04:00">04:00 AM</option>
										<option value="04:30">04:30 AM</option>
										<option value="05:00">05:00 AM</option>
										<option value="05:30">05:30 AM</option>
										<option value="06:00">06:00 AM</option>
										<option value="06:30">06:30 AM</option>
										<option value="07:00">07:00 AM</option>
										<option value="07:30">07:30 AM</option>
										<option value="08:00">08:00 AM</option>
										<option value="08:30">08:30 AM</option>
										<option value="09:00">09:00 AM</option>
										<option value="09:30">09:30 AM</option>
										<option value="10:00">10:00 AM</option>
										<option value="10:30">10:30 AM</option>
										<option value="11:00">11:00 AM</option>
										<option value="11:30">11:30 AM</option>
										<option value="12:00">12:00 PM</option>
										<option value="12:30">12:30 PM</option>
										<option value="13:00">01:00 PM</option>
										<option value="13:30">01:30 PM</option>
										<option value="14:00">02:00 PM</option>
										<option value="14:30">02:30 PM</option>
										<option value="15:00">03:00 PM</option>
										<option value="15:30">03:30 PM</option>
										<option value="16:00">04:00 PM</option>
										<option value="16:30">04:30 PM</option>
										<option value="17:00">05:00 PM</option>
										<option value="17:30">05:30 PM</option>
										<option value="18:00">06:00PM</option>
										<option value="18:30">06:30 PM</option>
										<option value="19:00">07:00 PM</option>
										<option value="19:30">07:30 PM</option>
										<option value="20:00">08:00 PM</option>
										<option value="20:30">08:30 PM</option>
										<option value="21:00">09:00 PM</option>
										<option value="21:30">09:30 PM</option>
										<option value="22:00">10:00 PM</option>
										<option value="22:30">10:30 PM</option>
										<option value="23:00">11:00 PM</option>
										<option value="23:30">11:30 PM</option>
									</select>
									<i style="color:#ff0000;" class="ion-android-remove-circle" id="remove_hr" onclick="return RemoveThisBusinessHours(this)" data-id='<?php echo $div; ?>'> </i>
								</div>
							<?php endforeach; ?>
						</div>
					</div>
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-4 form-control-label"><?php echo lang('business::featured') ?></label>
				<div class="col-sm-8">
					<select class="c-select" name="val[featured]">
						<option <?php echo ($business['featured'] == 0) ? 'selected' : null ?> value="0"><?php echo lang('business::no') ?></option>
						<option <?php echo ($business['featured'] == 1) ? 'selected' : null ?> value="1"><?php echo lang('business::yes') ?></option>
					</select>
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-4 form-control-label"><?php echo lang('business::can-create') ?></label>
				<div class="col-sm-8">
					<select class="c-select" name="val[can_create]">
						<option <?php echo ($business['can_create'] == 0) ? 'selected' : null ?> value="0"><?php echo lang('business::no') ?></option>
						<option <?php echo ($business['can_create'] == 1) ? 'selected' : null ?> value="1"><?php echo lang('business::yes') ?></option>
					</select>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-4">
					<h6>
						<label class="control-label" for="image"><?php echo lang('business::image') ?>: </label>
					</h6>
					<p class="business-form-description"><?php echo lang('business::create-business-image-desc') ?></p>
				</div>
				<div class="col-sm-8">
					<div class="business-form-file-selector">
						<input type="file" name="image" id="business-image-file"/>
					</div>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-5">
				</div>
				<div class="col-sm-4">
					<div class="input-field col s12">
						<input type="submit" value="<?php echo lang('business::save') ?>" class="btn btn-primary"/>
					</div>
				</div>
			</div>
			<input type="hidden" name="val[image_path]" value="<?php echo $business['company_logo'] ?>"/>
			<input type="hidden" name="val[business_id]" value="<?php echo $business['id'] ?>"/>
			<input type="hidden" name="val[type]" value="edit_business_admin"/>
		</form>
	</div>
</div>