<div class="wrapper business">
	<div class="wrapper-title">
		<p><?php echo lang('business::businesses-manager') ?></p>
		<span><?php echo lang('business::businesses-manager-desc') ?></span>
	</div>
	<div class="wrapper-content">
        <?php $filter = 'all'; ?>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a href="<?php echo url_to_pager('admin-business-active') ?>" class="nav-link <?php echo ($filter == 'all') ? 'active' : null ?>"><?php echo lang('business::active') ?></a>
            </li>
            <li class="nav-item">
                <a href="<?php echo url_to_pager('admin-business-active') ?>" class="nav-link <?php echo ($filter == 'all') ? 'active' : null ?>"><?php echo lang('business::active') ?></a>
            </li>
            <li class="nav-item">
                <a href="<?php echo url_to_pager('admin-business-claimable') ?>" class="nav-link"><?php echo lang('business::claimable') ?></a>
            </li>
            <li class="nav-item">
                <a href="<?php echo url_to_pager('admin-business-claimed') ?>" class="nav-link "><?php echo lang('business::claim-log') ?></a>
            </li>
            <li class="nav-item">
                <a href="<?php echo url_to_pager('admin-business-pending') ?>" class="nav-link"><?php echo lang('business::pending-approval') ?></a>
            </li>
        </ul>
        <div class="wrapper-form">
            <?php echo $message ?>
            <div class="list-table-container">
                <div class="row list-table-select-actions hide" data-group="users">
                    <div class="col-sm-12">
                        <a href="<?php echo url_to_pager('admin-business-batch-action') ?>?action=approve"
                           class="action-link list-table-select-action"
                           data-group="users"><?php echo lang('activate') ?></a>
                        <a href="<?php echo url_to_pager('admin-business-batch-action') ?>?action=disapprove"
                           class="action-link list-table-select-action"
                           data-group="users"><?php echo lang('deactivate') ?></a>

                        <a href="<?php echo url_to_pager('admin-business-batch-action') ?>?action=delete"
                           class="action-link list-table-select-action" data-group="users"><?php echo lang('delete') ?></a>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped list-table">
                        <thead>
                        <tr>
                            <th>
                                <div class="list-table-select" data-group="users" data-id="0"></div>
                            </th>
                            <th>ID</th>
                            <th><?php echo lang('business::title') ?></th>
                            <th><?php echo lang('business::category') ?></th>
                            <th><?php echo lang('business::price') ?></th>
                            <th><?php echo lang('business::views') ?></th>
                            <th><?php echo lang('business::featured') ?></th>
                            <th><?php echo lang('business::approved') ?></th>
                            <th><?php echo lang('business::actions') ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach($businesses->results() as $business): ?>
                            <tr>
                                <td>
                                    <div class="list-table-select" data-group="users"
                                         data-id="<?php echo $business['id'] ?>"></div>
                                </td>
                                <td><?php echo $business['id'] ?></td>
                                <td><?php echo $business['business_name'] ?></td>
                                <td><?php echo lang($business['category_title']) ?></td>
                                <td><?php echo $business['price'] <= 0 ? lang('business::free') : $business['price'].' '.config('default-currency') ?></td>
                                <td><?php echo $business['views'] <= 1 ? viewCounts($business['id']).' '.lang('business::view') : viewCounts($business['id']).' '.lang('business::views') ?></td>
                                <td><?php echo $business['featured'] ? lang('business::yes') : lang('business::no') ?></td>
                                <td><?php echo $business['approved'] ? lang('business::yes') : lang('business::no') ?></td>

                                <td>
                                    <div class="dropdown actions">
                                        <a href="#" data-toggle="dropdown">
                                            <i class="ion-android-settings"></i>
                                        </a>
                                        <div class="dropdown-menu dropdown-menu-right">
                                            <?php if($business['approved'] == 0): ?>
                                                <a class="ion-checkmark-round" href='<?php echo url_to_pager('admin-business-approve').'?id='.$business['id'] ?>' ></a><?php endif; ?>
                                            <?php if($business['approved'] == 1): ?>
                                                <a class="ion-close-round" href='<?php echo url_to_pager('admin-business-disapprove').'?id='.$business['id'] ?>' ></a><?php endif; ?>
                                            <a class="ion-edit" href='<?php echo url_to_pager('admin-business-edit').'?id='.$business['id'] ?>'></a>
                                            <a class="admin-confirm ion-android-delete" href="<?php echo url_to_pager('admin-business-delete').'?id='.$business['id'] ?>"></a>
                                        </div>
                                    </div>
                                </td>


                            </tr>
                        <?php endforeach ?>
                        </tbody>
                    </table>
                </div>
                <?php if($businesses->total): ?>
                    <?php if($businesses->total > config('pagination-limit-businesses', 20)): ?>
                        <?php echo $businesses->links() ?>
                    <?php endif ?>
                <?php else: ?>
                    <div class="alert alert-info"><?php echo lang('business::no-business-found') ?></div>
                <?php endif ?>
            </div>
        </div>
	</div>