<?php $week = array('SUN', 'MON', 'TUE', 'WED', 'THUR', 'FRI', 'SAT') ?>
<div style=" margin-top: 17px">
	<div class="upcoming-dashboard">
		<div>
			<div class="upcoming-event">
				<div class="upcoming-event-heading">
                    <span itemcomponent="span" class="upcoming-event-heading-1">
                        <?php echo lang("event::events") ?>
	                    <span></span>
                    </span>
					<div style="clear: both"></div>
				</div>
				<div style="border-top: 1px solid #e5e5e5;">
					<ul style="padding:12px;margin: 0px;list-style-type: none; padding-left: 12px !important;">
						<?php if(!$events->total): ?>
							<div class="alert alert-info"><?php echo lang('event::no-event-display') ?></div>
						<?php else: ?>
							<?php $i = 1 ?>
							<?php foreach($events->results() as $event):$event = arrange_event($event); ?>
								<?php //if ($i <= 4):?>
								<li style="list-style: none; margin-bottom: 16px;">
									<div class="upcoming-event-body">
										<div style="zoom: 1" direction="left">
											<div style="float: left; width: 200px; height: 120px; border-radius: 4px; background: rgba(0,0,0,0.06) url(<?php echo get_event_logo($event) ?>); background-size: cover;">
												<div class="upcoming-event-dt">
													<div style="font-weight: bold;"> <?php echo get_event_date($event)." ".get_event_date($event, 'day', 'd') ?> </div>
													<div style="padding: 4px 0px;"> <?php echo $week[get_event_date($event, 'day', 'w')]; ?></div>
												</div>
											</div>
											<div>
												<div style="zoom: 1; overflow: hidden;display: block" direction="right">
													<div>
														<div style="padding-left: 12px;">
															<header style="position: relative">
																<a href="#">
																	<h3 style="font-size: 18px;line-height: 18px;">  <?php echo ucwords($event['event_title']) ?> </h3>
																</a>
															</header>
															<div style="font-size: 12px;line-height: 16px;">
																<span><?php echo date('h A', $event['start_time']) ?></span>
																<span role="presentation" aria-hidden="true"> · </span>
																<span class="event-addr"><?php echo $event['address'].", ".$event['location'] ?>.</span>
															</div>
															<div style="height: 20px;zoom:1">
																<div style="float: left; padding: 3px 0px;">
																	<div class="event-icon event-icon-1">
																		<div style="display: flex">
                                                                                <span style="display: inline-block">
                                                                                    <div style="z-index: 1;  border: 2px solid #fff; border-radius: 50%;overflow: hidden;height: 16px; width: 16px; background-color: #4267b2;position: relative;">
                                                                                        <i class="upcoming-event-icon" height="8" width="8" alt="" style="margin: 4px; background-image: url("<?php echo img('event::images/static.png') ?>")"></i>
                                                                                    </div>
                                                                                </span>
																		</div>
																	</div>
																</div>
																<div style="display: block">
																	<div style="overflow: hidden">
                                                                <span style="    color: #90949c;display: block; font-size: 12px; line-height: 22px;">
                                                                    <span class="event-interested-button"> <?php echo manage_interested(count_event_going($event['event_id'])) ?></span>
                                                                </span>
																	</div>
																</div>
															</div>
															<div style="margin: 4px 0;">
																<div style=" display: inline-block; margin: 0 4px 0 0;">
																	<div>
																		<div style="vertical-align: middle; display: inline-block">
																			<a style="border: 0; padding: 2px; 4px" class="event-link-dt">
                                                                                    <span style="display: inline-block;">
                                                                                        <i alt="" class="event-feed-interested-dt"></i>
	                                                                                    <?php if(is_loggedIn() && $event['user_id'] != get_userid()): ?>
		                                                                                    <div class="box-content clearfix" style="display: inline-block; padding: 0px 4px;">
                                                                                                <span style="padding: 4px 4px 0px 0px; display: inline-block; vertical-align: middle;"><?php echo lang('event::rsvp') ?>:</span>
                                                                                                <select onchange="event_rsvp(this, '<?php echo $event['event_id'] ?>')" data-id="" class="c-select pull-right" style="display: inline-block; vertical-align: middle;">
                                                                                                    <?php $value = get_event_my_rsvp($event['event_id']) ?>
	                                                                                                <option <?php echo ($value == 0) ? 'selected' : null ?> value="0"><?php echo lang('event::not-going') ?></option>
                                                                                                    <option <?php echo ($value == 1) ? 'selected' : null ?> value="1"><?php echo lang('event::going') ?></option>
                                                                                                    <option <?php echo ($value == 2) ? 'selected' : null ?> value="2"><?php echo lang('event::maybe') ?></option>
                                                                                                </select>
                                                                                            </div>
	                                                                                    <?php endif; ?>
                                                                                    </span>
																			</a>
																		</div>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
										<div class="event-clear"></div>
									</div>
								</li>
								<?php $i++ ?>
								<?php //endif;?>
							<?php endforeach; ?>
						<?php endif; ?>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>