<?php if(!(isset($feed['empty']) && $feed['empty'])): ?>
    <?php $feed_filter = fire_hook('feed.filter', array(true), array('feed' => $feed))[0] ?>
    <?php if($feed_filter): ?>
        <?php $avatar = $feed['editor']['avatar']; $entityId = $feed['editor']['id']; $entityType = $feed['editor']['type']; ?>
        <div data-error="<?php echo lang('something-went-wrong-error') ?>" class="feed-hide-container" id="feed-hide-container-<?php echo $feed['feed_id'] ?>">
            <div class="col-sm-12" style="padding: 0">
                <div class="box">
                    <div class="box-content">
                        <?php echo lang('feed::feed-no-longer-show') ?>
                        <a href="" onclick="return unhide_feed('<?php echo $feed['feed_id'] ?>')"><?php echo lang('undo') ?></a>
                    </div>
                </div>
            </div>
        </div>
        <div id="feed-wrapper-<?php echo $feed['feed_id'] ?>" class="feed-wrapper clearfix">
            <div class="col-sm-12  right no-padding">
                <div class="box">
                    <div class="feed-header clearfix">
                        <div class="left">
                            <a ajax="true" href="<?php echo $feed['publisher']['url'] ?>" class="avatar"><img src="<?php echo $feed['publisher']['avatar'] ?>"/>
                                <?php if(isset($feed['publisher']['id'])): ?>
                                    <?php $userDetails = find_user($feed['publisher']['id']); ?>
                                    <?php $getOnlineStatus = user_is_online($userDetails); ?>
                                    <?php if(($getOnlineStatus) && ($feed['publisher']['id'] != get_userid())): ?>
                                        <i class="online-status feed-online online-icon"></i>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </a>
                        </div>
                        <div class="right">
                            <div class="feed-title">
			                   <span class=" preview-card" data-type="<?php echo $feed['entity_type'] ?>" data-id="<?php echo $feed['entity_id'] ?>">
			                        <a ajax="true" href="<?php echo $feed['publisher']['url'] ?>" class="">
			                             <?php echo $feed['publisher']['name'] ?>
                                         <?php echo verify_badge($feed['publisher']) ?>
			                       </a>
			                   </span>
                                <?php if(isset($feed['targetUser'])): ?>
                                    <i class="ion-ios-arrow-thin-right"></i>
                                    <span class=" preview-card" data-type="user" data-id="<?php echo $feed['targetUser']['id'] ?>">
                                        <a href="<?php echo profile_url(null, $feed['targetUser']) ?>" ajax="true"><?php echo get_user_name($feed['targetUser']) ?></a>
			                        </span>
                                <?php endif ?>
                                <?php if($feed['shared']): ?>
                                    <?php echo $feed['shared_title'] ?>
                                <?php endif ?>
                                <?php if(isset($feed['tags-users'])): ?>
                                    <i class="fa fa-share-square-o"></i> <?php echo lang('with'); ?>
                                    <?php if($feed['tagsCount'] > 2): ?>
                                        <?php $firstUser = $feed['tags-users'][0] ?>
                                        <span data-type="user" data-id="<?php echo $firstUser['id'] ?>" class="preview-card">
                                            <a ajax="true" href="<?php echo profile_url(null, $firstUser) ?>"><?php echo get_user_name($firstUser) ?></a>
                                        </span>
                                        <?php echo lang('and') ?>
                                        <a data-toggle="tooltip" data-placement="top"
                                           title="<?php $i = 1;
                                           foreach($feed['tags-users'] as $user): ?>
                                    <?php if($i > 1): ?>
                                        <?php echo get_user_name($user) ?>,
                                    <?php endif ?>
                                <?php $i++;endforeach ?>"
                                           href=""><?php echo(count($feed['tags-users']) - 1) ?><?php echo lang('other-people') ?></a>
                                    <?php else: ?>
                                        <?php $i = 1;
                                        foreach($feed['tags-users'] as $user): ?>
                                            <?php echo ($i == 2) ? ' '.lang('and').' ' : null ?>
                                            <span data-type="user" data-id="<?php echo $user['id'] ?>" class="preview-card">
                                    <a ajax="true" href="<?php echo profile_url(null, $user) ?>"><?php echo get_user_name($user) ?></a>
                                </span>
                                            <?php $i++; endforeach ?>
                                    <?php endif ?>
                                <?php endif ?>
                                <?php theme_extend('feed-title', null, array($feed)) ?>
                            </div>
                            <span class="feed-time"> <span class="timeago " title="<?php echo date('c', $feed['time']) ?>"><?php echo date('c', $feed['time']) ?></span></span>
                            <?php if($feed['location']): ?>
                                · <i class="ion-ios-location"></i>
                                <span style="color:grey;font-size:12px"><?php echo $feed['location'] ?></span>
                            <?php endif ?>
                            ·
                            <span class="feed-privacy-icon-container dropdown">
				            <?php if(in_array($feed['privacy'], range(1, 3))): ?>
                                <a id="feed-privacy-icon-<?php echo $feed['feed_id'] ?>" data-toggle="dropdown" class="dropdown-button" href="#">
                                    <?php if($feed['privacy'] == 1): ?>
                                        <i class="ion-android-globe"></i>
                                    <?php elseif($feed['privacy'] == 2): ?>
                                        <i class="ion-ios-people"></i>
                                    <?php else: ?>
                                        <i class="ion-android-lock"></i>
                                    <?php endif ?>
                                </a>
                            <?php endif ?>
                                <?php if(can_edit_feed_privacy($feed)): ?>
                                    <ul id="feed-privacy-dropdown-<?php echo $feed['feed_id'] ?>" class="dropdown-menu">
				                    <li><a data-icon="ion-android-globe" data-id="1" data-feed="<?php echo $feed['feed_id'] ?>" class="dropdown-item feed-privacy-toggle" href="javascript:void(0)"><i class="ion-android-globe"></i> <?php echo lang('public') ?></a></li>
				                    <li>
					                    <a data-icon="ion-ios-people" data-id="2" data-feed="<?php echo $feed['feed_id'] ?>" class="dropdown-item feed-privacy-toggle" href="javascript:void(0)">
				                            <i class="ion-ios-people"></i>
						                    <?php echo (config('relationship-method', 3) == 1) ? lang('feed::followers-only') : lang('feed::friends-only') ?>
				                        </a>
				                    </li>
				                    <li><a data-icon="ion-android-lock" data-feed="<?php echo $feed['feed_id'] ?>" data-id="3" class="dropdown-item feed-privacy-toggle" href="javascript:void(0)"><i class="ion-android-lock"></i> <?php echo lang('feed::only-me') ?></a> </li>
				                </ul>
                                <?php endif ?>
                            </span>
                            <?php if($feed['edited']): ?>
                                · <?php echo lang('feed::edited') ?>
                            <?php endif ?>
                            <?php if(plugin_exists('counts') && plugin_loaded('counts') && isset($feed['views'])): ?>
                                <?php fire_hook('show.feed.counts', null, array($feed['views'])); ?>
                            <?php endif; ?>
                            <div class="feed-menu dropdown">
                                <?php if(is_feed_pinned($feed['feed_id'])): ?>
                                    <i data-toggle="tooltip" title="<?php echo lang('feed::pinned-post') ?>" class="ion-bookmark feed-pinned"></i>
                                <?php endif ?>
                                <a href="" class="dropdown-toggle" data-toggle="dropdown" style="font-size: 30px;margin-right: 5px"><i class="ion-android-more-vertical"></i></a>
                                <ul style="width: 220px;float: right; z-index: 99999" id="<?php echo $feed['feed_id'] ?>-feed-menu" class="dropdown-menu dropdown-menu-right left">
                                    <?php if(is_loggedIn()): ?>
                                        <li>
                                            <a onclick="return hide_feed('<?php echo $feed['feed_id'] ?>')" href="" class="dropdown-item">
                                                <i class="ion-eye-disabled"></i> <?php echo lang('feed::dont-like-post') ?>
                                                <p class="help-block"><?php echo lang('feed::see-less-post-like-this') ?></p>
                                            </a>
                                        </li>
                                    <?php endif ?>
                                    <?php if(is_loggedIn()): ?>
                                        <li>
                                            <a class="dropdown-item" data-on="<?php echo lang('feed::get-notifications') ?>" data-off="<?php echo lang('feed::stop-notifications') ?>" id="feed-notifications-<?php echo $feed['feed_id'] ?>" data-turned="<?php echo (has_subscribed('feed', $feed['feed_id'])) ? 1 : 0 ?>" onclick="return toggle_feed_notification('<?php echo $feed['feed_id'] ?>')" href="">
                                                <i class="ion-android-notifications-none"></i>
                                                <?php if(has_subscribed('feed', $feed['feed_id'])): ?>
                                                    <?php echo lang('feed::stop-notifications') ?>
                                                <?php else: ?>
                                                    <?php echo lang('feed::get-notifications') ?>
                                                <?php endif ?>
                                            </a>
                                        </li>
                                        <?php if(can_pin_post($feed)): ?>
                                            <li>
                                                <a onclick="return pin_feed(this)" href="<?php echo url('feed/pin/'.$feed['feed_id']) ?>" class="dropdown-item">
                                                    <i class="ion-pin"></i>
                                                    <?php echo (is_feed_pinned($feed['feed_id'])) ? lang('feed::unpin-from-top') : lang('feed::pin-to-top') ?>
                                                </a>
                                            </li>
                                        <?php endif ?>
                                        <li>
                                            <a onclick="return process_user_save(this, 'feed', '<?php echo $feed['feed_id'] ?>')" href="" class="dropdown-item user-save" data-status="<?php echo (user_saved('feed', $feed['feed_id'])) ? 1 : 0 ?>">
                                                <i class="ion-android-bookmark"></i>
                                                <span><?php echo (user_saved('feed', $feed['feed_id'])) ? lang('unsave-post') : lang('save-post') ?></span>
                                            </a>
                                        </li>
                                        <li class="divider"></li>
                                        <?php if(can_delete_feed($feed)): ?>
                                            <li>
                                                <a class="dropdown-item" onclick="return delete_feed('<?php echo $feed['feed_id'] ?>')" href=""><i class="ion-android-delete"></i> <?php echo lang('feed::delete-post') ?></a>
                                            </li>
                                        <?php endif ?>
                                        <?php if(can_edit_feed($feed)): ?>
                                            <?php if(config('allow-feed-editing', true)): ?>
                                                <li>
                                                    <a class="dropdown-item" onclick="return show_feed_edit_form('<?php echo $feed['feed_id'] ?>')" href="#!"><i class="ion-edit"></i> <?php echo lang('feed::edit-post') ?></a>
                                                </li>
                                                <li>
                                                    <a id="feed-hide-comment-<?php echo $feed['feed_id'] ?>" data-type="<?php echo ($feed && isset($feed['hide_comment']) && $feed['hide_comment']=='1')?'enable':'disable' ?>" data-id="<?php echo $feed['feed_id']?>" class="dropdown-item feed-hide-comment"  href="#!"><i class="ion-eye-disabled"></i> <?php echo lang(($feed && isset($feed['hide_comment']) && $feed['hide_comment']=='1')?'feed::enable-comment':'feed::disable-comment') ?></a>
                                                </li>
                                            <?php endif ?>
                                        <?php endif ?>
                                    <?php endif ?>
                                    <?php theme_extend('feed.menu', null, array($feed)) ?>
                                    <li>
                                        <a class="dropdown-item" href="<?php echo url_to_pager('view-post', array('id' => $feed['feed_id'])) ?>" ajax="true"><i class="ion-eye"></i> <?php echo lang('feed::view-post') ?></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <form onsubmit="return save_feed('<?php echo $feed['feed_id'] ?>')" id="feed-edit-form-<?php echo $feed['feed_id'] ?>" class="feed-edit-form" action="post">
                        <?php CSRFProtection::embed() ?>
                        <textarea name="text" class="auto-grow-input <?php echo (config('enable-feed-text-limit', false)) ? 'textarea-limit' : null ?>" data-height="50px" data-text-limit="<?php echo config('maximum-feed-text-limit', 150) ?>" data-text-limit-count-target=".feed-edit-text-limit-count-<?php echo $feed['feed_id'] ?>"><?php echo $feed['feed_content'] ?></textarea>
                        <?php if(config('enable-feed-text-limit', false)): ?>
                            <span class="feed-edit-text-limit-count feed-edit-text-limit-count-<?php echo $feed['feed_id'] ?>"><?php echo config('maximum-feed-text-limit', 150) ?></span>
                        <?php endif ?>
                        <button class="btn btn-info btn-sm"><?php echo lang('save') ?></button>
                        <a onclick="return show_feed_edit_form('<?php echo $feed['feed_id'] ?>')" href="" class="btn btn-secondary btn-sm"><?php echo lang('cancel') ?></a>
                        <img src="<?php echo img('images/loading.gif') ?>" class="feed-edit-form-indicator"/>
                    </form>
                    <?php echo view('feed::feed-content', array('feed' => $feed)) ?>
                    <?php if($feed['shared']): ?>
                        <div class="feed-shared-container">
                            <div class="media media-md">
                                <div class="media-left">
                                    <div class="media-object">
                                        <a ajax="true" href="<?php echo $feed['shared-feed']['publisher']['url'] ?>">
                                            <img src="<?php echo $feed['shared-feed']['publisher']['avatar'] ?>"/>
                                        </a>
                                    </div>
                                </div>
                                <div class="media-body">
                                    <div class="feed-title">
		                                <span data-type='<?php echo $feed['shared-feed']['entity_type'] ?>' data-id='<?php echo $feed['shared-feed']['entity_id'] ?>' class='preview-card'>
		                                    <a ajax="true" href="<?php echo $feed['shared-feed']['publisher']['url'] ?>">
		                                        <?php echo $feed['shared-feed']['publisher']['name'] ?>
                                                <?php echo verify_badge($feed['shared-feed']['publisher']) ?>
		                                    </a>
		                                </span>
                                        <?php theme_extend('feed-title', null, array($feed['shared-feed'])) ?>
                                    </div>
                                    <span class="feed-time"> <span class="timeago " title="<?php echo date('c', $feed['shared-feed']['time']) ?>"><?php echo date('c', $feed['shared-feed']['time']) ?></span></span>
                                    <?php if($feed['shared-feed']['edited']): ?>
                                        · <?php echo lang('feed::edited') ?>
                                    <?php endif ?>
                                    <?php if($feed['shared-feed']['location']): ?>
                                        <i class="ion-ios-location"></i> <?php echo $feed['location'] ?>
                                    <?php endif ?>
                                </div>
                            </div>
                            <?php echo view('feed::feed-content', array('feed' => $feed['shared-feed'])) ?>
                        </div>
                    <?php endif ?>
                    <?php if(plugin_loaded('like') and config('feed-like-type', 'regular') != 'regular'): ?>
                        <div class="reactors reactors-feed-<?php echo $feed['feed_id'] ?>">
                            <?php echo view('like::reacts', array('type' => 'feed', 'type_id' => $feed['feed_id'])) ?>
                        </div>
                    <?php endif ?>
                    <div id="feed-footer-<?php echo $feed['feed_id'] ?>" class="feed-footer">
                        <div class="">
                            <ul class="feed-footer-menu">
                                <?php if(plugin_loaded('like')): ?>
                                    <?php load_functions('like::like'); ?>
                                    <?php echo view('like::like-footer', array('type' => 'feed', 'typeId' => $feed['feed_id'], 'hide_counts' => true)); ?>
                                <?php endif ?>
                                <?php if(config('allow-feed-sharing', true) and can_share_feed($feed)): ?>
                                    <li class="dropdown feed-share-dropdown">
                                        <a href="#" class="dropdown-toggle" type="button" id="feed-share-dropdown-toggle-<?php echo $feed['feed_id'] ?>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="font-awesome-i fa fa-share-square-o"></i> <?php echo lang('feed::share') ?>
                                        </a>
                                        <div class="dropdown-menu" aria-labelledby="feed-share-dropdown-toggle-<?php echo $feed['feed_id'] ?>">
                                            <ul>
                                                <li><a href="#!" class="font-awesome-i fa fa-share-square-o" onclick="return share_feed('<?php echo $feed['feed_id'] ?>', '<?php echo lang('feed::share-warning-message') ?>')"><?php echo lang('feed::share') ?></a></li>
                                                <li><a href="#!" class="ion-android-mail" data-container="#feed-send-message-modal" data-id="<?php echo $feed['feed_id']?>" onclick="return shareFeedAsMessage(this)"><?php echo lang("feed::send-as-message")?></a></li>
                                                <li><a href="#!" class="ion-ios-list" data-container="#feed-send-share-to-timeline-modal" data-id="<?php echo $feed['feed_id']?>" onclick="return shareFeedToTimeline(this)"><?php echo lang("feed::share-on-friend-timeline")?></a></li>
                                                <li><a href="#!" class="ion-flag" data-container="#feed-send-share-to-page-modal" data-id="<?php echo $feed['feed_id']?>" onclick="return shareFeedToPage(this)"><?php echo lang("feed::share-to-a-page")?></a></li>
                                                <?php if(config('enable-feed-social-share', true) && $feed['privacy'] == 1 && plugin_loaded('sharer')): ?>
                                                    <li class="dropdown-divider"></li>
                                                    <li id="feed-share-menu-more-items-<?php echo $feed['feed_id'] ?>" class="feed-share-menu-more-items menu-more-items">
                                                        <div class="feed-social-share">
                                                            <?php echo view('sharer::share_link_list', array('link' => url_to_pager('view-post', array('id' => $feed['feed_id'])))) ?>
                                                        </div>
                                                    </li>
                                                    <li class="feed-share-more menu-more">
                                                        <a morelabel=" <?php echo lang('see-more') ?>..." lesslabel=" <?php echo lang('see-less') ?>" class="feed-share-menu-more-button ion-arrow-down-b" href="#!" data-feed-id="<?php echo $feed['feed_id'] ?>"> <?php echo lang('show-more') ?></a>
                                                    </li>
                                                <?php endif ?>
                                            </ul>
                                        </div>
                                    </li>
                                <?php endif ?>
                                <?php fire_hook('more-feed-footer', null, array('feed', $feed['feed_id'])); ?>
                                <li class="right" style="margin: 0">
                                    <ul class="feed-statistics">
                                        <?php if(plugin_loaded('like') and config('feed-like-type', 'regular') == 'regular'): ?>
                                            <li>
                                                <a data-toggle="tooltip"data-original-title="<?php echo lang('feed::like') ?>" onclick="return show_likes('feed', '<?php echo $feed['feed_id'] ?>')" href="">
                                                    <i class="fa fa-thumbs-o-up font-awesome-ismall"></i>
                                                    <span class="like-count-feed-<?php echo $feed['feed_id'] ?>"><?php echo count_likes('feed', $feed['feed_id']) ?></span>
                                                </a>
                                            </li>
                                            <?php if(config('enable-dislike', false)): ?>
                                                <li>
                                                    <a onclick="return show_dislikes('feed', '<?php echo $feed['feed_id'] ?>')" href="">
                                                        <i class="fa fa-thumbs-o-down font-awesome-ismall"></i>
                                                        <span class="dislike-count-feed-<?php echo $feed['feed_id'] ?>"><?php echo count_dislikes('feed', $feed['feed_id']) ?></span>
                                                    </a>
                                                </li>
                                            <?php endif ?>
                                        <?php endif ?>
                                        <?php if(plugin_loaded('comment')): ?>
                                            <?php load_functions('comment::comment') ?>
                                            <?php $countComments = count_comments('feed', $feed['feed_id']); ?>
                                            <li class="feed-comment-count-<?php echo $feed['feed_id']?>" style="display: <?php echo ($feed['hide_comment'] =='1')?'none':'inline' ?>">
                                                <a href="javascript::void(0)">
                                                    <i class="font-awesome-ismall fa fa-comments-o"></i>
                                                    <span class="comment-count-feed-<?php echo $feed['feed_id'] ?>"><?php echo ($countComments) ? $countComments : '' ?></span>
                                                </a>
                                            </li>
                                        <?php endif ?>
                                        <?php if(config('allow-feed-sharing', true)): ?>
                                            <li>
                                                <a href="javascript::void(0)">
                                                    <i class="font-awesome-ismall fa fa-share-square-o"></i>
                                                    <span id="feed-share-count-<?php echo $feed['feed_id'] ?>"><?php echo ($feed['shared_count']) ? $feed['shared_count'] : '' ?></span>
                                                </a>
                                            </li>
                                        <?php endif ?>
                                        <?php fire_hook('more-feed-footer-count', null, array('feed', $feed['feed_id'])); ?>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <?php if(plugin_loaded('comment') && $feed['hide_comment'] != '1'): ?>
                            <?php echo view('comment::pre_display',
                                array(
                                    'type' => 'feed',
                                    'typeId' => $feed['feed_id'],
                                    'countComments' => $countComments,
                                    'owner' => $feed,
                                    'entityId' => $entityId,
                                    'entityType' => $entityType,
                                    'avatar' => $avatar,
                                    'limit' => config('feed-comment-limit', 3),
                                    'textLimit' => (config('enable-feed-text-limit', false)) ? config('maximum-feed-text-limit', 150) : false,
                                )
                            )?>
                        <?php endif ?>
                    </div>
                </div>
            </div>
        </div>
    <?php endif ?>
<?php else: ?>
    <?php remove_feed($feed['feed_id']) ?>
<?php endif ?>