<div class="feed-wrapper clearfix">
    <div class="col-sm-12 clearfix">
        <div class="col-sm-6">
            <img class="img img-responsive" src="<?php echo url_img($donation['image'], 700) ?>"/>
        </div>
        <div class="col-sm-6">
            <p><b><?php echo $donation['title']; ?></b></p>
            <p><?php echo $donation['description']; ?></p>
        </div>
    </div>
</div>