<div class="md-container">
	<div class="box">
		<div class="title">
			<?php echo lang('quiz::new-quiz') ?>
		</div>
		<div>
			<?php if($message): ?>
			<div class="alert alert-danger">
				<?php echo $message ?>
			</div>
			<?php endif ?>
			<form action="" method="post" enctype="multipart/form-data" class="ajax-form">
				<?php CSRFProtection::embed() ?>
				<?php if($message): ?>
				<div class="alert alert-danger">
					<?php echo $message ?>
				</div>
				<?php endif ?>
				<div class="field">
					<div class="top">
						<label class="control-label">
							<?php echo lang('quiz::quiz-title') ?>
						</label>
					</div>
					<div class="bottom">
						<input value="<?php echo input('val.title') ?>" type="text" class="form-control" name="val[title]" placeholder="<?php echo lang('quiz::quiz-title') ?>"/>
					</div>
				</div>
				<div class="field">
					<div class="top">
						<label class="control-label">
							<?php echo lang('quiz::category') ?>
						</label>
					</div>
					<div class="bottom">
						<div class="magic-select" data-name="val[category]" data-width="200px">
							<?php $categories = get_quiz_categories(); ?>
							<div class="magic-select-toggle">
								<?php echo lang('select-category') ?>
							</div>
							<div class="magic-select-content">
								<?php foreach($categories as $category): ?>
								<?php $sub_categories = get_quiz_parent_categories($category['id']) ?>
								<?php if($sub_categories): ?>
								<div class="magic-select-label">
									<?php echo lang($category['title']) ?>
								</div>
								<?php foreach($sub_categories as $cat): ?>
								<div class="magic-select-option" data-value="<?php echo $cat['id'] ?>">
									<?php echo lang($cat['title']) ?>
								</div>
								<?php endforeach ?>
								<?php else: ?>
								<div class="magic-select-option" data-value="<?php echo $category['id'] ?>">
									<?php echo lang($category['title']) ?>
								</div>
								<?php endif ?>
								<?php endforeach ?>
							</div>
						</div>
					</div>
				</div>
				<div class="field">
					<div class="top">
						<label class="control-label">
							<?php echo lang('quiz::quiz-desc') ?>
						</label>
					</div>
					<div class="bottom quiz-desc-c">
						<textarea name="val[content]" class="" placeholder="<?php echo lang('quiz::quiz-desc') ?>"><?php echo input('val.content') ?>
						</textarea>
					</div>
				</div>
				<div class="field">
					<div class="top">
						<label class="control-label">
							<?php echo lang('quiz::pass-mark') ?>
						</label>
					</div>
					<div class="bottom">
						<input value="<?php echo input('val.pass_mark') ?>" type="number" class="form-control" name="val[pass_mark]" placeholder="<?php echo lang('quiz::pass-mark') ?>"/>
					</div>
				</div>
				<div class="field">
					<div class="top">
						<label class="control-label">
							<?php echo lang('quiz::preview-image') ?>
						</label>
					</div>
					<div class="bottom">
						<div class="magic-input-image-preview" data-name="image">
							<span class="dimension"/>
						</div>
					</div>
				</div>
				<div class="field">
						<div class="top">
						<label class="control-label"><?php echo lang('quiz::tags') ?></label>
					</div>
					<div class="bottom">
						<input type="text" name="val[tags]" class="form-control" value="<?php echo input('val.tags') ?>" placeholder="<?php echo lang('quiz::tags') ?>">
					</div>
				</div>
				<div class="field">
					<div class="top">
						<label class="control-label">
							<?php echo lang('status') ?>
						</label>
					</div>
					<div class="bottom">
						<div class="magic-select" data-name="val[status]" data-width="200px">
							<div class="magic-select-toggle">
								<?php echo lang('quiz::draft') ?>
							</div>
							<div class="magic-select-content">
								<div class="magic-select-content">
									<div class="magic-select-option" data-value="0"><?php echo lang('quiz::draft') ?></div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="field">
					<div class="top">
						<label class="control-label">
							<?php echo lang('publisher') ?>
						</label>
					</div>
					<div class="bottom">
						<div class="magic-select" data-name="val[entity]" data-width="300px">
							<div class="magic-select-toggle">
								<img src="<?php echo get_avatar(75) ?>" class="thumb"/>
								<?php echo get_user_name(); ?>
							</div>
							<div class="magic-select-content slimscroll" data-height="200px">
								<div class="magic-select-option" data-value="user-<?php echo get_userid() ?>">
									<img src="<?php echo get_avatar(75) ?>" class="thumb"/>
									<?php echo get_user_name(); ?>
								</div>
								<?php fire_hook('entity.select.list') ?>
							</div>
						</div>
					</div>
				</div>
				<?php fire_hook('more.quiz.field') ?>
				<div class="field">
					<div class="top">
						<label class="control-label">
							<?php echo lang('privacy') ?>
						</label>
					</div>
					<div class="bottom">
						<?php fire_hook('privacy.select'); ?>
					</div>
				</div>
				<div class="submit">
					<button class="btn btn-info">
						<?php echo lang("quiz::create") ?>
					</button>
				</div>
			</form>
		</div>
	</div>
</div>