<div class="box">
    <div class="quiz-list">
        <div class="head">
            <div class="cover" style="background-image: url(<?php echo url_img(config('quiz-list-cover', 'plugins/quiz/images/cover.png'), 920); ?>)">
                <div class="title"><?php echo lang('quiz::quiz') ?></div>
            </div>
            <div class="filters global-filter-container filter-pane" data-url="<?php echo url('quizes') ?>">
                <div class="left">
                    <i class="icon ion-android-options"></i>
                    <select id="quiz-category-list" onchange="return run_global_filter()" data-name="category" class="c-select filter-input">
                        <option <?php echo (input('category', 'all') == 'all') ? 'selected' : null ?> value="all"><?php echo lang('quiz::all-categories') ?></option>
                        <?php foreach(get_quiz_categories() as $category): ?>
                            <?php $subCategories = get_quiz_parent_categories($category['id']) ?>
                            <?php if($subCategories): ?>
                                <optgroup label="<?php echo lang($category['title']) ?>">
                                    <?php foreach($subCategories as $cat): ?>
                                        <option <?php echo (input('category', 'all') == $cat['id']) ? 'selected' : null ?> value="<?php echo $cat['id'] ?>"><?php echo lang($cat['title']) ?></option>
                                    <?php endforeach ?>
                                </optgroup>
                            <?php else: ?>
                                <option <?php echo (input('category', 'all') == $category['id']) ? 'selected' : null ?> value="<?php echo $category['id'] ?>"><?php echo lang($category['title']) ?></option>
                            <?php endif ?>
                        <?php endforeach ?>
                    </select>
                    <select id="quiz-filter-select" onchange="return run_global_filter()" data-name="filter" class="c-select filter-input">
                        <option value="all"><?php echo lang('all') ?></option>
                        <option <?php echo (input('filter') == 'top') ? 'selected' : null ?> value="top"><?php echo lang('quiz::top') ?></option>
                        <option <?php echo (input('filter') == 'featured') ? 'selected' : null ?> value="featured"><?php echo lang('quiz::featured') ?></option>
                    </select>
                </div>
                <div class="right">
                    <form id="quiz-list-search" method="post" onsubmit="return run_global_filter()" action="" class="search form-inline list-search">
                        <?php CSRFProtection::embed() ?>
                        <input type="search" value="<?php echo input('term') ?>" class="form-control search-box filter-input" data-name="term" placeholder="<?php echo lang('search') ?>" />
                        <button type="submit">
                            <i class="search-icon icon ion-ios-search"></i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
        <div class="body">
            <div class="listings">
                <div class="listing">
                    <?php foreach($quizes->results() as $quiz): ?>

                        <?php $quiz = arrange_quiz($quiz); ?>
                        <?php $user = find_user($quiz['user_id']) ?>
                        <?php $refId = $quiz['id']; $refName = 'quiz'; ?>
                        <div class="item">
                            <div class="top">
                                <small class="time muted"><?php echo date('M j , y  h:i A', $quiz['time']) ?></small>
                            </div>
                            <a ajax="true" href="<?php echo url('quiz/'.$quiz['slug']) ?>" class="thumb">
                                <img class="image" src="<?php echo $quiz['image'] ? url_img($quiz['image'], 700) : url_img('plugins/quiz/images/quiz.jpeg', 700) ?>" alt="<?php echo $quiz['title'] ?> "/>
                                <?php if($quiz['featured']): ?>
                                    <div class="featured">
                                        <i class="ion-ios-star-outline"></i>
                                    </div>
                                <?php endif ?>
                            </a>
                            <div class="details">
                                <a ajax="true" href="<?php echo url('quiz/'.$quiz['slug']) ?>" class="title"><?php echo $quiz['title'] ?></a>
                                <p class="description"><?php echo str_limit(strip_tags($quiz['content']), 100) ?></p>
                                <div class="stat">
                                    <div class="left">
                                        <div class="user">
                                            <div class="avatar">
                                                <img src="<?php echo get_avatar(200, $user) ?>" alt="<?php echo $quiz['publisher']['name'] ?>"/>
                                            </div>
                                            <a ajax="true" href="<?php echo url($quiz['publisher']['id']) ?>" class="name"><?php echo $quiz['publisher']['name'] ?></a>
                                        </div>
                                        <div class="count view"><?php echo $quiz['views']; ?> <?php echo lang('quiz::views'); ?></div>
                                        <div class="count like">
                                            <?php $likes = count_likes($refName, $refId); ?>
                                            <?php echo $likes; ?>
                                            <?php echo $likes > 1 ? lang('quiz::likes') : lang('quiz::like'); ?>
                                        </div>
										<div class="count-participants">
											<?php echo count_quiz_participants($quiz['id']); ?>
											<?php echo lang('quiz::participants'); ?>
										</div>
                                    </div>
                               
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
    <div class="box-content">
        <?php if($quizes->total): ?>
            <?php echo $quizes->append(array('category' => input('category'), 'type' => input('type', 'browse'), 'term' => input('term'), 'filter' => input('filter', 'all')))->links() ?>
        <?php else: ?>
            <div class="alert alert-info"><?php echo lang('quiz::quizes-list-empty') ?></div>
        <?php endif ?>
    </div>
</div>
