<?php $refId = $quiz['id'];
$refName = 'quiz';
$user = find_user($quiz['user_id']); ?>
<div class="box quiz">
	<div class="title">
		<div style="width:80%">
			<?php echo $quiz['title'] ?>
			<div class="action">
				<?php if(!has_taken_quiz($quiz['id']) && is_published($quiz['id']) && !is_quiz_owner($quiz)): ?>
					<a href="" class="btn btn-secondary btn-sm action-button" data-toggle="modal" data-target="#start-quiz-modal"><?php echo lang('quiz::start-now') ?></a>
					<!---------------start quiz starts--------------------->
					<?php fire_hook('start.quiz.load', null, array('quiz' => $quiz)); ?>
					<!---------------start quiz ends--------------------->
				<?php endif ?>
				<?php if(has_taken_quiz($quiz['id']) or is_quiz_owner($quiz)): ?>
					<a href="<?php echo url_to_pager('quiz-participants',array('slug' => $quiz['id'])) ?>" class="btn btn-secondary btn-sm action-button" ajax="true"><?php echo lang('quiz::quiz-participants') ?></a>
				<?php endif ?>
				<?php if(is_quiz_owner($quiz)): ?>
					<a href="<?php echo url_to_pager('quiz-question',array('slug' => $quiz['id'])) ?>" class="btn btn-secondary btn-sm action-button" ajax="true"><?php if(is_published($quiz['id'])): ?><?php echo lang('quiz::questions') ?><?php else: ?><?php echo lang('quiz::add-questions') ?><?php endif ?></a>
					<?php if(!is_published($quiz['id'])): ?>
					<a href="<?php echo url('quiz/manage?type=edit&id='.$quiz['id']) ?>" class="btn btn-secondary btn-sm action-button" ajax="true"><?php echo lang('quiz::edit-quiz') ?></a>
					<?php endif ?>
				<?php elseif(is_loggedIn() and plugin_loaded('report')): ?>
					<a data-type="quiz" data-link="<?php echo url_to_pager('quiz-page', array('slugs' => $quiz['slug'])) ?>" class="report-btn btn btn-secondary" href=""><i class="ion-flag"></i></a>
				<?php endif ?>
			</div>
		</div>
	</div>
	<div class="clearfix">
		<div style="float: left; padding: 0px 8px">
				<img style="border-radius: 50%; float: left;" src="<?php echo get_avatar(75, $user) ?>" width="45" height="45"/>
		</div>
		<div>
			<div>
				<?php echo lang('quiz::publisher') ?>:
					<a ajax="true" href="<?php echo url($quiz['publisher']['id']) ?>"><?php echo $quiz['publisher']['name'] ?></a>
			</div>
			<div>
				<?php echo lang('quiz::date'); ?>:
				<span class="timeago" title="<?php echo date('c', $quiz['time']) ?>"><?php echo date('c', $quiz['time']) ?></span>
			</div>
		</div>
	</div>
	<div class="box-content post">
		<div style=" padding:2% 0 2% 0; border-top:1px solid #F1F1F1; border-bottom: 1px solid #F1F1F1;">
			<span><?php if(plugin_loaded('sharer')) echo view('sharer::share_link', array('link' => url("quiz/".$quiz['slug']))) ?></span>
			<span class="participant-count"><strong><?php echo count_quiz_participants($quiz['id']); ?></strong><?php echo lang('quiz::participants'); ?></span>
			<span class="pull-right"><strong><?php echo $quiz['views']; ?></strong> <?php echo lang('quiz::views'); ?></span>
		</div>
		<br/>
		<?php if($quiz['image']): ?>
			<div class="blog-large-image">
				<img src="<?php echo url_img($quiz['image'], 700) ?>"/>
			</div>
		<?php else: ?>
			<div class="blog-large-image">
				<img src="<?php echo url_img('plugins/quiz/images/quiz.jpeg', 700) ?>"/>
			</div>
		<?php endif ?>
        <?php fire_hook("more.quiz.details", $quiz) ?>
		<?php echo $quiz['content'] ?>
		<?php if(plugin_loaded('like') and config('feed-like-type', 'regular') != 'regular'): ?>
			<div class="reactors reactors-<?php echo $refName ?>-<?php echo $refId ?>">
				<?php echo view('like::reacts', array('type' => $refName, 'type_id' => $refId)) ?>
			</div>
		<?php endif ?>
	</div>
	<div class="feed-footer">
		<ul class=" feed-footer-menu clearfix">
			<?php if(plugin_loaded('like')): ?>
				<?php load_functions('like::like'); ?>
				<?php echo view('like::like-footer', array('type' => $refName, 'typeId' => $refId)); ?>
			<?php endif ?>
			<li class="blog-social-share"><?php echo plugin_loaded('sharer') ? view('sharer::share_link', array('link' => url("quiz/".$quiz['slug']))) : '' ?></li>
			<?php fire_hook('more-feed-footer', null, array($refName, $refId)); ?>
			<li class="pull-right">
				<ul class="feed-statistics">
					<?php if(plugin_loaded('like')): ?>
						<li>
							<a onclick="return show_likes('<?php echo $refName ?>', '<?php echo $refId ?>')" href="">
								<i class="fa fa-thumbs-o-up"></i>
								<span class="like-count-<?php echo $refName ?>-<?php echo $refId ?>"><?php echo count_likes($refName, $refId) ?></span>
							</a>
						</li>
						<?php if(config('enable-dislike', false)): ?>
							<li>
								<a onclick="return show_dislikes('<?php echo $refName ?>', '<?php echo $refId ?>')" href="">
									<i class="ion-thumbsdown"></i>
									<span class="dislike-count-<?php echo $refName ?>-<?php echo $refId ?>"><?php echo count_dislikes($refName, $refId) ?></span>
								</a>
							</li>
						<?php endif ?>
					<?php endif ?>
					<?php if(plugin_loaded('comment')): ?>
						<?php load_functions('comment::comment') ?>
						<?php $countComments = count_comments($refName, $refId); ?>
						<li>
							<i class="ion-chatbubbles"></i>
							<span class="comment-count-<?php echo $refName ?>-<?php echo $refId ?>"><?php echo ($countComments) ? $countComments : null ?></span>
						</li>
					<?php endif ?>
					<?php fire_hook('more-feed-footer-count', null, array($refName, $refId)); ?>
				</ul>
			</li>
		</ul>
	</div>
</div>
<div class="box">
	<div class="box-content feed-footer">
		<?php if(plugin_loaded('comment')): ?>
			<div class="feed-comment-container">
				<?php if($countComments > config('feed-comment-limit', 3)): ?>
					<a id="comment-view-more-button-<?php echo $refName ?>-<?php echo $refId ?>" class="comment-view-more-button comment-view-more-button-<?php echo $refName ?>-<?php echo $refId ?>" onclick="return show_more_comment('<?php echo $refName ?>', '<?php echo $refId ?>', 'comment-view-more-indicator-<?php echo $refId ?>')" href=""><?php echo lang('view-previous-comments') ?></a>
					<img class="comment-view-more-indicator" id="comment-view-more-indicator-<?php echo $refId ?>" src="<?php echo img('images/loading.gif') ?>"/>
				<?php endif ?>
				<div data-offset="<?php echo config('feed-comment-limit', 3) ?>" data-limit="<?php echo config('feed-comment-limit', 3) ?>" class="comment-lists comment-lists-<?php echo $refName ?>-<?php echo $refId ?>" id="">
					<?php foreach(get_comments($refName, $refId, config('feed-comment-limit', 3), 0) as $comment): ?>
						<?php echo view('comment::display', array('comment' => $comment)) ?>
					<?php endforeach; ?>
				</div>
				<?php echo view('comment::editor', array('typeId' => $quiz['id'], 'type' => 'quiz', 'textLimit' => (config('enable-feed-text-limit', false)) ? config('maximum-feed-text-limit', 150) : false)) ?>
			</div>
		<?php endif ?>
	</div>
</div>