<?php $contests = get_contests(null, null, null, null, $limit); ?>
<?php if($contests->total): ?>
	<div class="box">
		<div class="title">
			<?php echo lang('contest::latest-contests') ?>
			<a ajax="true" href="<?php echo url('contests') ?>"><i class="ion-ios-arrow-forward pull-right"></i></a>
		</div>
		<div class="box-content slider-side-widget">
			<?php foreach($contests->results() as $contest): ?>
				<?php $contest = arrange_contest($contest); ?>
                <?php echo view("contest::widget-view",array('contest'=>$contest)); ?>
			<?php endforeach ?>
		</div>
	</div>
<?php endif ?>