<div id="notification-<?php echo $notification['notification_id'] ?>" class="notification media media-md  <?php echo ($notification['mark_read'] == 0) ? 'notification-unread' : null ?>">
	<div class="media-left">
		<div class="media-object">
			<img src="<?php echo get_avatar(75, $notification) ?>"/>
		</div>
	</div>
	<div class="media-body">
		<a ajax="true" href="<?php echo url($notification['username']) ?>">
			<h6 class="media-heading"><?php echo lang(($transaction['amount'] <= 1 ? 'creditgift::sent-credit-notification-message' : 'creditgift::sent-credits-notification-message'), array('name' => get_user_name($notification), 'price' => $transaction['amount'])) ?></h6>
		</a>
		<span class="help-block"></span>
		<span style="display: block" class="timeago" title="<?php echo date('c', $notification['time']) ?>"><?php echo date('c', $notification['time']) ?></span>
		<div class="actions">
			<a class="mark-button" data-status="<?php echo $notification['mark_read'] ?>" data-read="<?php echo lang('notification::read') ?>" data-mark="<?php echo lang('notification::mark-as-read') ?>" title="<?php echo ($notification['mark_read'] == 1) ? lang('notification::read') : lang('notification::mark-as-read') ?> " onclick="return notification.markRead('<?php echo $notification['notification_id'] ?>')" href="#!"><i class="ion-checkmark-circled"></i></a><a onclick="return notification.delete('<?php echo $notification['notification_id'] ?>')" href="#!"><i class="ion-close"></i></a>
		</div>
	</div>
</div>