<?php $videos = get_videos('browse', 'all', null, null, $limit, 'featured'); ?>
<?php if($videos->total): ?>
	<div class="box">
		<div class="title"><?php echo lang('video::latest-video') ?></div>
		<div class="box-content" id="video-widget">
			<?php foreach($videos->results() as $video): ?>
				<div class="media media-lg user">
					<div class="media-left">
						<a ajax="true" href="<?php echo get_video_url($video) ?>">
							<div class="media-object" style="background: url(<?php echo $video['photo_path'] ? url_img($video['photo_path'], 75) : img('video::images/preview.png', 75) ?>) center; background-size: cover;"></div>
							<div class="media-object video-thumb-hover<?php echo $video['thumbnail'] ? '' : ' static'?>" <?php echo $video['thumbnail'] ? 'data-image="'.url_img($video['thumbnail'], 75).'"' : 'style="background-image: url('.img('video::images/play.png').')"'?>></div>
						</a>
					</div>
					<div class="media-body">
						<?php $title = $video['title'] ? $video['title'] : lang('video::untitled-video') ?>
						<a ajax="true" href="<?php echo get_video_url($video) ?>">
							<h6 class="media-heading" style="font-weight: normal"><?php echo str_limit(($video['title']) ? $video['title'] : lang('video::untitled-video'), 32) ?></h6>
						</a>
						<p class="help-block"><?php echo str_limit($video['description'], 40) ?></p>
					</div>
				</div>
			<?php endforeach ?>
		</div>
	</div>
<?php endif ?>