<?php if(is_loggedIn()): ?>
	<?php echo view('feed::editor', array(
			'offPrivacy' => true,
			'privacy' => 6,
			'type' => 'event',
			'type_id' => $event['event_id'],
			'offTagging' => true
		)
	) ?>
<?php endif ?>
	<div id="feed-lists" data-type="group" data-type-id="<?php echo $event['event_id'] ?>" data-offset="0">
		<?php $feed = get_pinned_feed('event', $event['event_id']);
		if($feed) echo view('feed::feed', array('feed' => $feed)) ?>
		<?php $i = 0;
		foreach($feeds as $feed):fire_hook('feed.lists.inline', null, array($i));
			$i++ ?>
			<?php echo view('feed::feed', array('feed' => $feed)) ?>
		<?php endforeach ?>
	</div>
<?php if(!count($feeds)): ?>
	<div class="feed-empty text-center">
		<i class="ion-android-bicycle"></i>
		<h3><?php echo lang('no-post-show') ?></h3>
	</div>
<?php endif ?>
<?php if(count($feeds)): ?>
	<div class="feed-load-more">
		<div class="col-sm-2 no-padding"></div>
		<div class="col-sm-10 no-padding">
			<div class="feed-loading">
				<div class="feed_loading_post">
					<div class="feed_loading_post_child2">

					</div>
				</div>
			</div>
		</div>
	</div>
<?php endif ?>