<?php $week = array('SUN', 'MON', 'TUE', 'WED', 'THUR', 'FRI', 'SAT') ?>
<div>
	<div data-width="470" class="profile-container" id="event-profile-container" data-id="<?php echo get_event_details('event_id') ?>">
		<div id="profile-cover" class="box">
			<div class="profile-cover-indicator">
				<img src="<?php echo img('images/loading.gif') ?>"/>
			</div>
			<div class="profile-cover-wrapper" style="height:100%">
				<img src="<?php echo get_event_cover(app()->profileEvent, false) ?>"/>
			</div>
			<?php if(is_event_admin($app->profileEvent)): ?>
				<!--<div class="profile-resize-cover-wrapper">-->
				<!--<div class="drag-info">--><?php //_lang('drag-to-position-cover') ?><!--</div>-->
				<!--<img src="--><?php //echo get_event_cover(app()->profileEvent) ?><!--" />-->
				<!--</div>-->
				<form id="profile-cover-change-form" enctype="multipart/form-data" method="post">
					<?php CSRFProtection::embed() ?>
					<span class="file-input"><input accept="image/*" multiple onchange="return upload_event_profile_cover(false)" type="file" id="user-profile-cover-input" name="image"/> </span>
					<div class="dropdown">
						<span data-toggle="dropdown"><i class="ion-camera"></i></span>
						<ul style="width: 240px" class="dropdown-menu dropdown-menu-right" id="profile-cover-dropdown-menu">
							<li>
								<a class="dropdown-item" onclick="return file_chooser('#user-profile-cover-input')" href=""><?php echo lang('upload-photo') ?>...</a>
							</li>
							<!--                        <li class="hide-in-mobile"><a class="dropdown-item" onclick="return reposition_user_profile_cover()" href="">--><?php //_lang('reposition') ?><!--...</a> </li>-->
							<li>
								<a class="dropdown-item" onclick="return remove_event_profile_cover('<?php echo img("images/cover.jpg") ?>')" href=""><?php echo lang('remove') ?>...</a>
							</li>
						</ul>
					</div>
				</form>
				<!--<div class="profile-cover-reposition-button">-->
				<!--<input type="hidden" id="profile-cover-resized-top" value="0" />-->
				<!--<a onclick="return cancel_profile_cover_position()" class="btn-danger-outline btn btn-sm" href="#!">--><?php //_lang('cancel') ?><!--</a>-->
				<!--<a onclick="return save_event_profile_cover()" class="btn btn-success btn-upper btn-sm" href="">--><?php //_lang('save') ?><!--</a>-->
				<!--</div>-->
			<?php endif ?>
			<div class="event-title">
				<h4 class="user-name left"><?php echo get_event_details('event_title') ?></h4>
			</div>
		</div>
	</div>
	<div class="event-dashboard">
		<div class="event-dashboard-title-wrapper">
			<i class="event-dashboard-icon" style="background-image: url(<?php echo img('event::images/event-icon.png') ?>)"></i>
			<div class="event-dashboard-title-c">
				<div class="event-dashboard-title-i">
					<h1> <?php echo ucwords(lang($app->profileEvent['event_title'])) ?></h1>
					<div class="event-dashboard-privacy">
						<div class="event-hosted-b">
							<ul id="menu" class="nav navbar-nav">
								<li style="border: none !important">
									<?php echo lang('event::hosted-by') ?>:
									<a ajax="true" href="<?php echo url($app->profileEvent['host']['id']) ?>"> <?php echo $app->profileEvent['host']['name'] ?></a>
									<br/><i class="ion-android-calendar"></i> <?php echo ($app->profileEvent['privacy'] == 1) ? lang('public') : lang('private') ?>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="profile-actions">
			<div class="event-going-button">
				<?php if(is_loggedIn()): ?>
					<span><?php echo lang('event::rsvp') ?>:&nbsp;</span>
					<select onchange="event_rsvp(this, '<?php echo $app->profileEvent['event_id'] ?>')" data-id="" class="c-select">
						<?php $value = get_event_my_rsvp($app->profileEvent['event_id']) ?>
						<option <?php echo $value == 0 ? 'selected' : null ?> value="0"><?php echo lang('event::not-going') ?></option>
						<option <?php echo $value == 1 ? 'selected' : null ?> value="1"><?php echo lang('event::going') ?></option>
						<option <?php echo $value == 2 ? 'selected' : null ?> value="2"><?php echo lang('event::maybe') ?></option>
					</select>
				<?php endif; ?>
			</div>
<!--			<div class="event-interested-button-wrapper">-->
<!--				<div class="event-interested-inner-button">-->
<!--					<a onclick="event_rsvp(this, '--><?php //echo $app->profileEvent['event_id'] ?><!--')" data-id="3" --><?php //$inte = user_interests($app->profileEvent['event_id']); echo $inte > 0 ? 'data-current="1"' : 'data-current="0"' ?><!-- href="#" class="event-action-button-a">-->
<!--						--><?php //echo lang('event::interested') ?>
<!--						<span class="event-interested-stats">--><?php //echo count_event_interested($app->profileEvent['event_id']) ?><!--</span>-->
<!--					</a>-->
<!--				</div>-->
<!--			</div>-->
			<span class="event-social-share"><?php if(plugin_loaded('sharer')) echo view('sharer::share_link', array('link' => url('event/'.$app->profileEvent['event_id']))) ?></span>
			<?php if(is_loggedIn()): ?>
				<?php if(is_event_admin($app->profileEvent)): ?>
					<a ajax="true" href="<?php echo event_url('edit', $app->profileEvent) ?>" class="btn btn-secondary "><i class="ion-edit"></i> <?php echo lang('edit') ?>
					</a>
				<?php endif ?>
			<?php endif ?>
			<?php if(is_loggedIn() and plugin_loaded('report')): ?>
				<a data-type="game" data-link="<?php echo event_url(null, $app->profileEvent) ?>" class="report-btn btn btn-secondary " href=""><i class="ion-flag"></i></a>
			<?php endif ?>
			<?php if(is_loggedIn()): ?>
				<span class="dropdown">
            <a href="" class="btn btn-secondary" data-toggle="dropdown"><i class="ion-android-more-vertical"></i></a>
            <ul class="dropdown-menu dropdown-menu-right">
                <li>
                    <a onclick="return process_user_save(this, 'event', '<?php echo $app->profileEvent['event_id'] ?>')" href="" class="dropdown-item user-save" data-status="<?php echo (user_saved('event', $app->profileEvent['event_id'])) ? 1 : 0 ?>">
                        <i class="ion-android-bookmark"></i>
                        <span><?php echo user_saved('event', $app->profileEvent['event_id']) ? lang('unsave-post') : lang('save-post') ?></span>
                    </a>
                </li>
            </ul>
        </span>
			<?php endif ?>
		</div>
		<div class="event-profile-summary">
			<div class="event-profile-summary-i">
				<ul class="event-profile-summary-ul">
					<li class="event-profile-summary-ul-i">
						<div class="event-summary-dates">
							<table cellpadding="0" cellspacing="0" class="event-summary-dates-table">
								<tbody>
								<tr class="summary-dates-tr">
									<td class="date-td date-event">
										<div class="event-summary-icon" aria-hidden="true">
											<div>
												<i class="event-summary-icon-i event-summary-icon-img" style="background-image: url(<?php echo img('event::images/clock.png') ?>)"></i>
											</div>
										</div>
									</td>
									<td class="date-td date-event td-d td-s">
										<div class="date-event">
											<div> <?php echo event_days_duration($app->profileEvent['start_time'], $app->profileEvent['end_time']) ?> <?php echo lang('days') ?> · <?php echo get_event_date($app->profileEvent, 'month', 'M', 'start')." ".get_event_date($app->profileEvent, 'day', 'd', 'start') ?> - <?php echo get_event_date($app->profileEvent, 'month', 'M', 'end')." ".get_event_date($app->profileEvent, 'day', 'd', 'end') ?></div>
											<div class="date-event-summary"></div>
										</div>
									</td>
								</tr>
								</tbody>
							</table>
						</div>
					</li>
					<li class="event-profile-summary-ul-i">
						<div class="event-summary-dates">
							<table cellpadding="0" cellspacing="0" class="event-summary-dates-table">
								<tbody>
								<tr class="summary-dates-tr">
									<td class="date-td date-event"></td>
									<td class="date-td date-event td-d td-s">
										<div class="date-event">
											<div>
												<div>
													<div class="event-summary-range event-summary-range-1">
														<a>
															<div class="event-summary-range-time range-time">
																<div class="range-time-box">
                                                                <span class="range-time-box-span">
                                                                    <span class="month-range-event"> <?php echo get_event_date($app->profileEvent, 'month', 'M', 'start') ?>  </span>
                                                                    <span class="date-range-event"> <?php echo get_event_date($app->profileEvent, 'day', 'd', 'start') ?> </span>
                                                                </span>
																</div>
																<div class="event-weekday-time">
																	<?php echo $week[get_event_date($app->profileEvent, 'day', 'w', 'start')]; ?>
																	<span class="pir"><?php echo date('h A', $app->profileEvent['start_time']) ?></span>
																</div>
															</div>
														</a>
														<span> <?php echo lang('to') ?> </span>
														<a>
															<div class="event-summary-range-time range-time">
																<div class="range-time-box">
                                                                <span class="range-time-box-span">
                                                                    <span class="month-range-event"> <?php echo get_event_date($app->profileEvent, 'month', 'M', 'end') ?>  </span>
                                                                    <span class="date-range-event"> <?php echo get_event_date($app->profileEvent, 'day', 'd', 'end') ?> </span>
                                                                </span>
																</div>
																<div class="event-weekday-time">
																	<?php echo $week[get_event_date($app->profileEvent, 'day', 'w', 'end')]; ?>
																	<span class="pir"><?php echo date('h A', $app->profileEvent['end_time']) ?></span>
																</div>
															</div>
														</a>
													</div>
													<div class="date-event-summary-bottom"></div>
												</div>
											</div>
										</div>
									</td>
								</tr>
								</tbody>
							</table>
						</div>
					</li>
					<li class="event-location-li">
						<div>
							<table cellpadding="0" cellspacing="0" class="event-summary-dates-table">
								<tbody>
								<tr class="summary-dates-tr">
									<td class="date-td date-event">
										<div aria-hidden="true">
											<i style="background-image: url(<?php echo img("event::images/location.png") ?>)" class="event-location-icon"></i>
										</div>
									</td>
									<td class="date-td date-event td-d td-s">
										<div class="event-location-div-wrapper">
											<div class="event-location-title-wrapper">
												<a class="event-location-a">
													<?php echo $app->profileEvent['address'].", ".$app->profileEvent['location'] ?>.
												</a>
											</div>
										</div>
									</td>
								</tr>
								</tbody>
							</table>
						</div>
					</li>
				</ul>
				<div class="event-about-discussion-border">
					<div>
						<div class="event-about-discussion-wrapper">
							<ul role="tablist" class="event-about-discussion-ul">
								<li role="presentation" class="active event-about-title">
									<a onclick="return event_feed_toggle(this)" data-current="0" data-action="about" data-id="<?php echo $app->profileEvent['event_id'] ?>" href="#" aria-selected="true" role="tab" tabindex="0">
										<div class="event-about-title-div-i">
											<div class="event-about-title-div-ii">
												<span><?php echo lang('about') ?></span>
											</div>
											<div class="event-about-button" aria-hidden="true">About</div>
										</div>
										<span class="event-about-title-bottom"></span>
									</a>
								</li>
								<li role="presentation" class="event-discussion-title">
									<a onclick="return event_feed_toggle(this)" data-current="0" data-action="feed" data-id="<?php echo $app->profileEvent['event_id'] ?>" href="#" tabindex="-1" role="tab" class="event-discussion-link event-discussion-a event-about-link">
										<div class="event-about-title-div-i">
											<div class="event-about-title-div-ii">
												<span><?php echo lang('discussion') ?></span>
											</div>
											<div class="event-about-button" aria-hidden="true">Discussion</div>
										</div>
										<span class="event-about-title-bottom"></span>
									</a>
								</li>
							</ul>
							<div class="event-loading-img" style="display:none;">
								<!--<img src="--><?php //echo img('images/loading.gif') ?><!--" class="" />-->
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="event-about-discussion-container">
		<?php echo view('event::profile/event-details', array('event' => $app->profileEvent)) ?>
	</div>
</div>