<?php //echo view('feed::editormodal')?>
	<div class="container">
		<div data-width="750" class="profile-container" id="group-profile-container" data-id="<?php echo get_event_details('event_id') ?>">
			<div id="profile-cover" class="box">
				<div class="profile-cover-indicator">
					<img src="<?php echo img('images/loading.gif') ?>"/>
				</div>
				<div class="profile-cover-wrapper">
					<img src="<?php echo get_event_cover(app()->profileEvent, true, 600) ?>"/>
				</div>
				<?php if(is_event_admin($app->profileEvent)): ?>
					<div class="profile-resize-cover-wrapper">
						<div class="drag-info"><?php echo lang('drag-to-position-cover') ?></div>
						<img src="<?php echo get_event_cover(app()->profileEvent) ?>"/>
					</div>
					<form id="profile-cover-change-form" enctype="multipart/form-data" method="post">
						<?php CSRFProtection::embed() ?>
						<div class="dropdown">
							<span class="file-input"><input accept="image/*" multiple onchange="return upload_event_profile_cover()" type="file" id="user-profile-cover-input" name="image"/> </span>
							<button class="btn btn-sm btn-secondary dropdown-toggle" data-toggle="dropdown">
								<i class="ion-camera"></i> <?php echo lang('change-cover') ?>
							</button>
						</div>
						<ul style="width: 240px" class="dropdown-menu dropdown-menu-right" id="profile-cover-dropdown-menu">
							<li>
								<a class="dropdown-item" onclick="return file_chooser('#user-profile-cover-input')" href=""><?php echo lang('upload-photo') ?>...</a>
							</li>
							<li class="hide-in-mobile">
								<a class="dropdown-item" onclick="return reposition_user_profile_cover()" href=""><?php echo lang('reposition') ?>...</a>
							</li>
							<li>
								<a class="dropdown-item" onclick="return remove_event_profile_cover('<?php echo img("images/cover.jpg") ?>')" href=""><?php echo lang('remove') ?>...</a>
							</li>
						</ul>
					</form>
					<div class="profile-cover-reposition-button">
						<input type="hidden" id="profile-cover-resized-top" value="0"/>
						<a onclick="return cancel_profile_cover_position()" class="btn-danger-outline btn btn-sm" href="#!"><?php echo lang('cancel') ?></a>
						<a onclick="return save_event_profile_cover()" class="btn btn-success btn-upper btn-sm" href=""><?php echo lang('save') ?></a>
					</div>
				<?php endif ?>
			</div>
			<div class="profile-actions">
				<span class="event-social-share"><?php if(plugin_loaded('sharer')) echo view('sharer::share_link', array('link' => url('event/'.$app->profileEvent['event_id']))) ?></span>
				<?php if(is_loggedIn()): ?>
					<?php if(is_event_admin($app->profileEvent)): ?>
						<a ajax="true" href="<?php echo event_url('edit', $app->profileEvent) ?>" class="btn btn-secondary "><i class="ion-edit"></i> <?php echo lang('edit') ?>
						</a>
					<?php endif ?>
				<?php endif ?>
				<?php if(is_loggedIn() and plugin_loaded('report')): ?>
					<a data-type="game" data-link="<?php echo event_url(null, $app->profileEvent) ?>" class="report-btn btn btn-secondary " href=""><i class="ion-flag"></i></a>
				<?php endif ?>
				<?php if(is_loggedIn()): ?>
					<span class="dropdown">
                        <a href="" class="dropdown-toggle btn btn-secondary" data-toggle="dropdown"><i class="ion-android-more-vertical"></i></a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li>
                                <a onclick="return process_user_save(this, 'event', '<?php echo $app->profileEvent['event_id'] ?>')" href="" class="dropdown-item user-save" data-status="<?php echo (user_saved('event', $app->profileEvent['event_id'])) ? 1 : 0 ?>">
                                    <i class="ion-android-bookmark"></i>
                                    <span><?php echo (user_saved('event', $app->profileEvent['event_id'])) ? lang('unsave-post') : lang('save-post') ?></span>
                                </a>
                            </li>
                        </ul>
                    </span>
				<?php endif ?>
			</div>
		</div>
	</div>
	<div class="box event-info">
		<ul>
			<li>
				<i class="ion-ios-calendar-outline"></i>
				<?php $s = config('event-date-separator', ' ') ?>
				<?php $y = get_event_date($app->profileEvent, 'year', 'Y') != date('Y') ? $s.get_event_date($app->profileEvent, 'year', 'Y') : '' ?>
				<?php $t = config('event-time-format', '12') == '12' ? get_event_date($app->profileEvent, 'time', 'h:i A') : get_event_date($app->profileEvent, 'time', 'H:i'); ?>
				<?php $d = get_event_date($app->profileEvent, 'day', 'd') ?>
				<?php $m = get_event_date($app->profileEvent) ?>
				<?php $x = config('event-date-order', 'day') == 'day' ? $d.$s.$m : $m.$s.$d ?>

				<?php $ey = get_event_date($app->profileEvent, 'year', 'Y', 'end') != date('Y') ? $s.get_event_date($app->profileEvent, 'year', 'Y', 'end') : '' ?>
				<?php $et = config('event-time-format', '12') == '12' ? get_event_date($app->profileEvent, 'time', 'h:i A', 'end') : get_event_date($app->profileEvent, 'time', 'H:i', 'end'); ?>
				<?php $ed = get_event_date($app->profileEvent, 'day', 'd', 'end') ?>
				<?php $ex = config('event-date-order', 'day') == 'day' ? $ed.$s.$m : $m.$s.$ed ?>

				<font class="bold"><?php echo lang('event::from'); ?> </font>
				<?php echo $x.$y.' '.lang('event::at').' '.$t ?>
				<font class="bold"><?php echo lang('event::to'); ?> </font>
				<?php echo $ex.$ey.' '.lang('event::at').' '.$et ?>
			</li>
			<li>
				<i class="ion-android-time"></i> <?php echo time_duration(get_event_details('start_time'), get_event_details('end_time')); ?>
			</li>
			<li>
				<i class="ion-location"></i> <?php echo output_text($app->profileEvent['location']) ?>
			</li>
			<?php if($app->profileEvent['address']): ?>
				<li>
					<i class="ion-location"></i> <?php echo output_text($app->profileEvent['address']) ?>
				</li>
			<?php endif ?>
		</ul>
	</div>
<?php if($app->profileEvent['event_desc']): ?>
	<div class="box">
		<div class="box-content"><?php echo output_text($app->profileEvent['event_desc']) ?></div>
	</div>
<?php endif ?>
<?php if(is_loggedIn()): ?>
	<?php echo view('feed::editor', array(
			'offPrivacy' => true,
			'privacy' => 6,
			'type' => 'event',
			'type_id' => $app->profileEvent['event_id'],
			'offTagging' => true
		)
	) ?>
<?php endif ?>
	<div id="feed-lists" data-type="group" data-type-id="<?php echo $app->profileEvent['event_id'] ?>" data-offset="0">
		<?php $feed = get_pinned_feed('event', $app->profileEvent['event_id']);
		if($feed) echo view('feed::feed', array('feed' => $feed)) ?>
		<?php $i = 0;
		foreach($feeds as $feed):fire_hook('feed.lists.inline', null, array($i));
			$i++ ?>
			<?php echo view('feed::feed', array('feed' => $feed)) ?>
		<?php endforeach ?>
	</div>
<?php if(!count($feeds)): ?>
	<div class="feed-empty text-center">
		<i class="ion-android-bicycle"></i>
		<h3><?php echo lang('no-post-show') ?></h3>
	</div>
<?php endif ?>
<?php if(count($feeds)): ?>
	<div class="feed-load-more">
		<div class="col-sm-2 no-padding"></div>
		<div class="col-sm-10 no-padding">
			<div class="feed-loading">
				<div class="feed_loading_post">
					<div class="feed_loading_post_child2">

					</div>
				</div>
			</div>
		</div>
	</div>
<?php endif ?>