<div class="box">
	<div class="title"><?php echo lang("event::events") ?><?php fire_hook("profile.event.title") ?></div>
	<div id="events-list-container" class="box-content clearfix list-listing-container">
		<?php if(!$events->total): ?>
			<div class="alert alert-info"><?php echo lang('event::no-event-display') ?></div>
		<?php else: ?>
			<?php foreach($events->results() as $event): $event = arrange_event($event); ?>
				<div class="media media-lg event">
					<div class="media-left">
						<a href="<?php echo event_url(null, $event) ?>" ajax="true">
							<div class="media-object" style="background-image: url(<?php echo get_event_logo($event) ?>)">
								<div class="info">
									<span><?php echo get_event_date($event) ?></span>
									<span><?php echo get_event_date($event, 'day', 'd') ?></span>
								</div>
							</div>
						</a>
					</div>
					<div class="media-body">
						<h6 class="media-heading">
							<a class="bold" href="<?php echo event_url(null, $event) ?>" ajax="true"><?php echo $event['event_title'] ?></a>
						</h6>
						<p class="help-block">
							<i class="ion-ios-calendar-outline"></i>
							<?php $s = config('event-date-separator', ' ') ? config('event-date-separator', ' ') : ' ' ?>
							<?php $y = get_event_date($event, 'year', 'Y') != date('Y') ? $s.get_event_date($event, 'year', 'Y') : '' ?>
							<?php $t = config('event-time-format', '12') == '12' ? get_event_date($event, 'time', 'h:i A') : get_event_date($event, 'time', 'H:i'); ?>
							<?php $d = get_event_date($event, 'day', 'd') ?>
							<?php $m = get_event_date($event) ?>
							<?php $x = config('event-date-order', 'day') == 'day' ? $d.$s.$m : $m.$s.$d ?>
							<?php $ey = get_event_date($event, 'year', 'Y', 'end') != date('Y') ? $s.get_event_date($event, 'year', 'Y', 'end') : '' ?>
							<?php $et = config('event-time-format', '12') == '12' ? get_event_date($event, 'time', 'h:i A', 'end') : get_event_date($event, 'time', 'H:i', 'end'); ?>
							<?php $ed = get_event_date($event, 'day', 'd', 'end') ?>
							<?php $ex = config('event-date-order', 'day') == 'day' ? $ed.$s.$m : $m.$s.$ed ?>
							<?php echo $x.$y.' '.lang('event::at').' '.$t ?>
							<font class="bold"><?php echo lang('event::to'); ?> </font>
							<?php echo $ex.$ey.' '.lang('event::at').' '.$et ?>
						</p>
						<p>
							<i class="ion-android-time"></i> <?php echo time_duration($event['start_time'], $event['end_time']); ?>
						</p>
						<p><?php echo output_text(str_limit($event['event_desc'], 50)) ?></p>
					</div>
				</div>
			<?php endforeach ?>
			<?php echo $events->append(array('term' => input('term'), 'type' => input('type', 'upcoming'), 'category' => input('category')))->links(true) ?>
		<?php endif ?>
	</div>
</div>