<?php $livestreams = Livestream::getLivestreams(array('user_id' => 1), $limit); ?>
<?php if($livestreams->total): ?>
	<div class="box">
		<div class="title"><?php echo lang('livestream::recent-livestreams') ?></div>
		<div class="box-content livestream-widget">
			<?php foreach($livestreams->results() as $livestream): ?>
				<div class="media media-lg user">
					<div class="media-left">
						<a ajax="true" href="<?php echo url_to_pager('livestream-view', array('slug' => $livestream['slug'])) ?>">
							<div class="media-object" style="background: url(<?php echo $livestream['image'] ? url_img($livestream['image'], 75) : img('livestream::images/no_image.png', 75) ?>) center; background-size: cover;"></div>
						</a>
					</div>
					<div class="media-body">
						<?php $title = $livestream['title'] ? $livestream['title'] : lang('livestream::untitled-livestream') ?>
						<a ajax="true" href="<?php echo url_to_pager('livestream-view', array('slug' => $livestream['slug'])) ?>">
							<h6 class="media-heading" style="font-weight: normal"><?php echo str_limit(($livestream['title']) ? $livestream['title'] : lang('livestream::untitled-livestream'), 32) ?></h6>
						</a>
						<p class="help-block"><?php echo str_limit($livestream['description'], 120) ?></p>
					</div>
				</div>
			<?php endforeach ?>
		</div>
	</div>
<?php endif ?>