<div class="wrapper">
	<div class="wrapper-title">
		<?php echo lang('edit') ?>

	</div>
	<div class="wrapper-content">
		<?php if(isset($message)): ?>
			<div class="alert alert-danger"><?php echo $message ?></div>
		<?php endif ?>
		<form method="post" action="" class="wrapper-form">
			<?php CSRFProtection::embed() ?>
			<div class="form-group row">
				<label class="col-sm-3 form-control-label"><?php echo lang('title') ?></label>
				<div class="col-sm-9">
					<input class="form-control" value="<?php echo lang($relationship['relationship'] )?>" type="text" name="val[title][english]" placeholder="<?php echo lang('title') ?>"/><br>
					<p class="help-block"><?php echo lang('English')?></p>
                    <a href="" class="other-languages-link" onclick="return show_other_languages('#other-languages-content')"><?php echo lang('edit-other-languages') ?></a>
                    <div class="other-languages" id="other-languages-content">
                        <?php foreach(get_all_languages() as $language): ?>
                            <?php if ($language['language_id'] !="english"): ?>
                                <input value="<?php echo get_phrase($language['language_id'], $relationship['relationship']) ?>" class="form-control" type="text" name="val[title][<?php echo $language['language_id'] ?>]" placeholder="<?php echo lang('forum::category-title') ?>"/>
                                <br>
                                <p class="help-block"><?php echo $language['language_title'] ?></p>
                            <?php endif; ?>
                        <?php endforeach ?>
                    </div>
				</div>
			</div>
            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php echo lang('gender') ?></label>
                <div class="col-sm-9">
                    <select class="form-control c-select" name="val[gender]">
                        <?php $value = input('val.gender'); $genders = get_genders(); ?>
                        <?php foreach ($genders as $gender): ?>
                            <option <?php echo $relationship == $gender ? 'selected' : '' ?> value="<?php echo $gender ?>"><?php echo lang($gender) ?></option>
                        <?php endforeach; ?>
                        <option <?php echo ($relationship['type'] == 'status') ? 'selected' : null ?> value="status"><?php echo lang('status') ?></option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php echo lang('status') ?></label>
                <div class="col-sm-9">
                    <select class="form-control c-select" name="val[type]">
                        <option <?php echo ($relationship['type'] == 'relation') ? 'selected' : null ?> value="relation"><?php echo lang('Relation') ?></option>
                        <option <?php echo ($relationship['type'] == 'status') ? 'selected' : null ?> value="status"><?php echo lang('Personal Status') ?></option>
                    </select>
                </div>
            </div>
			<div class="form-group row">
				<label class="col-sm-3 form-control-label"><?php echo lang('status') ?></label>
				<div class="col-sm-9">
					<select class="form-control c-select" name="val[status]">
						<option <?php echo ($relationship['status'] == 0) ? 'selected' : null ?> value="0"><?php echo lang('no') ?></option>
						<option <?php echo ($relationship['status'] == 1) ? 'selected' : null ?> value="1"><?php echo lang('yes') ?></option>
					</select>
				</div>
			</div>
            <div class="form-group row">
                <label class="col-sm-3 form-control-label"></label>
                <div class="col-sm-9">
                    <button class="btn btn-info"><?php echo lang('save') ?></button>
                </div>
            </div>
		</form>
	</div>
</div>