<div class="box blog">
	<div class="global-filter-container" data-url="<?php echo url('blogs') ?>">
		<form id="blog-list-search" method="post" onsubmit="return run_global_filter()" action="" class="form-inline list-search">
			<?php CSRFProtection::embed() ?>
			<input type="hidden" class="filter-input form-control" data-name="type" value="<?php echo input('type', 'browse') ?>"/>
			<i class="search-icon ion-ios-search"></i>
			<input value="<?php echo input('term') ?>" type="text" class="form-control search-box filter-input" data-name="term" placeholder="<?php echo lang('search') ?>"/>
		</form>
		<div class="list-head">
			<h3 class="heading"><?php echo lang('blog::blogs') ?></h3>
		</div>
		<div class="filter-pane">
			<select id="video-category-list" onchange="return run_global_filter()" data-name="category" class="c-select filter-input">
                <option <?php echo (input('category', 'all') == 'all') ? 'selected' : null ?> value="all"><?php echo lang('music::all-categories') ?></option>
                <?php foreach(get_blog_categories() as $category): ?>
                    <?php $subCategories = get_blog_parent_categories($category['id']) ?>
                    <?php if($subCategories): ?>
                        <optgroup label="<?php echo lang($category['title']) ?>">
                            <?php foreach($subCategories as $cat): ?>
                                <option <?php echo (input('category', 'all') == $cat['id']) ? 'selected' : null ?> value="<?php echo $cat['id'] ?>"><?php echo lang($cat['title']) ?></option>
                            <?php endforeach ?>
                        </optgroup>
                    <?php else: ?>
                        <option <?php echo (input('category', 'all') == $category['id']) ? 'selected' : null ?> value="<?php echo $category['id'] ?>"><?php echo lang($category['title']) ?></option>
                    <?php endif ?>
                <?php endforeach ?>
			</select>
			<select id="video-filter-select" onchange="return run_global_filter()" data-name="filter" class="c-select filter-input">
				<option value="all"><?php echo lang('all') ?></option>
				<option <?php echo (input('filter') == 'top') ? 'selected' : null ?> value="top"><?php echo lang('video::top') ?></option>
				<option <?php echo (input('filter') == 'featured') ? 'selected' : null ?> value="featured"><?php echo lang('video::featured') ?></option>
			</select>
            <div class="list-layout-type">
                <a href="" onclick="return change_listing_layout('#blogs-list-container', 'list', 'blog')"><i class="ion-ios-list-outline"></i></a>
                <a href="" onclick="return change_listing_layout('#blogs-list-container', 'grid', 'blog')"><i class="ion-android-apps"></i></a>
            </div>
		</div>
	</div>
	<div id="blogs-list-container" class="box-content clearfix <?php echo ($list_type == 'list') ? 'list-listing-container' : 'grid-listing-container' ?>">
		<?php foreach($blogs->results() as $blog): ?>
			<?php $blog = arrange_blog($blog); ?>
			<?php $user = find_user($blog['user_id']) ?>
			<?php $refId = $blog['id'];
			$refName = 'blog'; ?>
			<div class="each-item blog-each-item clearfix blog-list">
				<?php if($blog['image']): ?>
					<div class="left">
						<?php if($blog['featured']): ?>
							<span class="featured-tag"><?php echo lang('featured') ?></span>
						<?php endif ?>
						<a ajax="true" href="<?php echo url('blog/'.$blog['slug']) ?>" style="background-image:url(<?php echo ($blog['image']) ? url_img($blog['image'], 700) : get_avatar(200, $user) ?>)"></a>
					</div>
					<div class="right">
						<span class="item-title"><a ajax="true" href="<?php echo url('blog/'.$blog['slug']) ?>"><?php echo $blog['title'] ?></a></span>
						<div class="item-info">
							<span class="help-block" style="display: block">
                                <span class="publisher">
                                    <span class="label"><?php echo lang('blog::publisher') ?>: </span>
                                    <a href="<?php echo url($blog['publisher']['id']) ?>"><?php echo $blog['publisher']['name'] ?></a>
                                </span>
                                <span class="time">
                                    <span class="label"><?php echo lang('blog::on') ?></span><?php echo date('M j , y  h:i A', $blog['time']) ?>
                                </span>
							</span>
						</div>
						<p class="item-desc"><?php echo str_limit(strip_tags($blog['content']), 100) ?></p>
						<p>
							<strong><?php echo $blog['views']; ?></strong> <?php echo lang('blog::views'); ?>
							<strong><?php $likes = count_likes($refName, $refId);
								echo $likes; ?></strong> <?php if($likes > 1) {
								echo lang('blog::likes');
							} else {
								echo lang('blog::like');
							} ?>
						</p>
					</div>
				<?php else: ?>
					<div class="right" style="width: 97% !important;">
                    <span class="item-title">
					<a ajax="true" href="<?php echo url('blog/'.$blog['slug']) ?>"><strong><?php echo $blog['title'] ?></strong></a> </span>
						<div class="item-info">
							<span class="help-block" style="display: block">
								<?php echo lang('blog::publisher') ?>: <a href="<?php echo url($blog['publisher']['id']) ?>"><?php echo $blog['publisher']['name'] ?></a>
								<?php echo lang('blog::on') ?> <?php echo date('M j , y  h:i A', $blog['time']) ?>
							</span>
						</div>
						<p class="item-desc"><?php echo str_limit(strip_tags($blog['content']), 250) ?></p>
						<p>
							<strong><?php echo $blog['views']; ?></strong> <?php echo lang('blog::views'); ?>
							<strong><?php $likes = count_likes($refName, $refId);
								echo $likes; ?></strong> <?php if($likes > 1) {
								echo lang('blog::likes');
							} else {
								echo lang('blog::like');
							} ?>
						</p>
					</div>
				<?php endif; ?>
			</div>
		<?php endforeach ?>
	</div>
	<div class="box-content">
		<?php if($blogs->total): ?>
			<?php echo $blogs->append(array('category' => input('category'), 'type' => input('type', 'browse'), 'term' => input('term'), 'filter' => input('filter', 'all')))->links() ?>
		<?php else: ?>
			<div class="alert alert-info"><?php echo lang('blog::blogs-list-empty') ?></div>
		<?php endif ?>
	</div>
</div>
