<div class="each-item clearfix">
	<div class="left">
		<?php if($page['featured']): ?>
			<span class="featured-tag"><?php echo lang('featured') ?></span>
		<?php endif ?>
		<a href="#" style="background-image:url(<?php echo get_page_logo(200, $page) ?>)" ajax="true">

		</a>
	</div>
	<div class="right">
        <span class="item-title">
            <a data-type="page" data-id="<?php echo $page['page_id'] ?>" class="previw-card" href="#" ajax="true"><h6 class="media-heading"><?php echo $page['page_title'] ?> <?php echo verify_badge($page) ?></h6> </a>
             </span>
		<div class="item-info page-item-info">
			<p class="help-block"><?php echo str_limit($page['page_desc'], 50) ?></p>
		</div>
	</div>
</div>
