<div class="navigate nav-left">
	<?php if($photo['imageBefore']): ?>
		<a data-image="<?php echo url_img($photo['imageBefore']['path'], 920) ?>" data-id="<?php echo $photo['imageBefore']['id'] ?>" class=" photo-viewer" href=""><i class="ion-ios-arrow-back"></i></a>
	<?php endif ?>

</div>

<div id="photo-viewer-wrapper">
	<img id="photo-viewer-image" src="<?php echo url_img($photo['path'], 920) ?>"/>
</div>

<div class="navigate nav-right">
	<?php if($photo['imageAfter']): ?>
		<a data-image="<?php echo url_img($photo['imageAfter']['path'], 920) ?>" data-id="<?php echo $photo['imageAfter']['id'] ?>" class=" photo-viewer" href=""><i class="ion-ios-arrow-forward"></i></a>
	<?php else: ?>
		<?php if(isset($photo['firstImage']) && $photo['firstImage']): ?>
				<a data-image="<?php echo url_img($photo['firstImage']['path'], 920) ?>" data-id="<?php echo $photo['firstImage']['id'] ?>" class=" photo-viewer" href=""><i class="ion-ios-arrow-forward"></i></a>
		<?php endif; ?>
	<?php endif ?>
</div>