<p><b><?php echo lang("donation::personal-informtion"); ?></b></p>
<form class="form" action="" method="post" enctype="multipart/form-data">
    <?php CSRFProtection::embed() ?>
    <?php if($message): ?>
        <?php echo view("donation::alert",array('message'=>$message)); ?>
    <?php endif; ?>
    <div class="form-group row">
        <div class="col-sm-12">
            <label><?php echo lang("donation::full-name") ?></label>
            <input  type="text" name="val[fl]" value="<?php echo $donation['full_name'] ?>"
                    class="form-control"/>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-12">
            <label><?php echo lang("donation::phone_number") ?></label>
            <input  type="text" name="val[ph]" value="<?php echo $donation['phone_number'] ?>"
                    class="form-control"/>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-12">
            <label><?php echo lang("donation::email-address") ?></label>
            <input  type="text" name="val[em]" value="<?php echo $donation['email_address'] ?>"
                    class="form-control"/>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-12">
            <label><?php echo lang("donation::country") ?></label>
            <?php load_function('country'); ?>
            <select class="c-select" name="val[country]">
                <option value=""><?php echo lang('select-country')?></option>
                <?php foreach(get_countries() as $country => $name):?>
                    <option <?php echo (input("val.country") == $name) ? "selected" : null?> value="<?php echo $name?>"><?php echo ucwords($name)?></option>
                <?php endforeach?>
            </select>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-12">
            <label><?php echo lang("donation::state") ?></label>
            <input  type="text" name="val[state]" value="<?php echo $donation['state'] ?>"
                    class="form-control"/>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-12">
            <label><?php echo lang("donation::city") ?></label>
            <input  type="text" name="val[city]" value="<?php echo $donation['city'] ?>"
                    class="form-control"/>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-12">
            <label><?php echo lang("donation::street") ?></label>
            <input  type="text" name="val[street]" value="<?php echo $donation['street'] ?>"
                    class="form-control"/>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-12">
            <label><?php echo lang("donation::street") ?></label>
            <input  type="text" name="val[street]" value="<?php echo $donation['street'] ?>"
                    class="form-control"/>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-12">
            <button type="submit" class="btn btn-info"><?php echo lang("save"); ?></button>
        </div>
    </div>
</form>