<p><b><?php echo lang("donation::thanks-donor"); ?></b></p>
<form class="form" action="" method="post" enctype="multipart/form-data">

    <?php CSRFProtection::embed() ?>
    <?php if($message): ?>
        <?php echo view("donation::alert",array('message'=>$message)); ?>
    <?php endif; ?>

    <div class="form-group row">
        <div class="col-sm-12">
            <label><?php echo lang("donation::subject"); ?></label>
            <input  type="text" name="val[subject]" value="<?php echo $donation['t_subject']; ?>"  class="form-control"/>

        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-12">
            <label><?php echo lang("donation::message"); ?></label>
            <textarea name="val[message]" class="form-control"><?php echo nl2br($donation['t_message']); ?></textarea>
        </div>
    </div>
    <p><?php echo lang("donation::title-break-down-note") ?></p>
    <p>[title] : <?php echo lang("donation::campaign-title");  ?></p>
    <p>[donor_name] : <?php echo lang("donation::donor-name");  ?></p>
    <p>[website_title] : <?php echo lang("donation::website-title");  ?></p>
    <p>[donation_url] : <?php echo lang("donation::donation_url");  ?></p>

    <div class="form-group row">
        <div class="col-sm-12">
            <label><b><?php echo lang("donation::terms-and-condition") ?></b></label>
            <textarea class="form-control" name="val[terms]"><?php echo $donation['terms'] ?></textarea>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-12">
            <button type="submit" class="btn btn-info"><?php _lang("save"); ?></button>
        </div>
    </div>

</form>