<p><b><?php echo lang("donation::gallery"); ?></b></p>
<form class="form" action="" method="post" enctype="multipart/form-data">
    <?php CSRFProtection::embed() ?>
    <?php if($message): ?>
        <?php echo view("donation::alert",array('message'=>$message)); ?>
    <?php endif; ?>

    <div class="form-group row">
        <div class="col-sm-12">
            <label><?php echo lang("donation::additional-images") ?></label>
            <input accept="image/*" multiple="" type="file" name="photo[]" class="form-control" />
        </div>
    </div>
    <?php if($donation['gallery']): ?>
        <p><?php echo lang("donation::choosing-new-images-will-replace"); ?></p>
        <div class="edit-gallery-images">
        <?php $images = perfectUnserialize($donation['gallery']);
        //echo '<pre>', print_r($images), '</pre>';
        ?>
        <?php foreach($images as $im): ?>
            <img src="<?php echo url_img($im,600) ?>" />
        <?php endforeach; ?>
        </div>

    <?php endif; ?>
    <br/>
    <div class="form-group row">
        <div class="col-sm-12">
            <label><?php echo lang("donation::youtube-url") ?></label>
            <input  type="text" name="val[ytube]" value="<?php echo $donation['ytube'] ?>"
                    class="form-control"/>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-12">
            <button type="submit" class="btn btn-info"><?php echo lang("donation::save-photos-and-video"); ?></button>
        </div>
    </div>

</form>