<p><b><?php echo lang("donation::invite-friends"); ?></b></p>
<form class="form" action="" method="post" enctype="multipart/form-data">
    <?php CSRFProtection::embed() ?>
    <?php if($message): ?>
        <?php echo view("donation::alert",array('message'=>$message)); ?>
    <?php endif; ?>
<?php if(is_loggedIn()): ?>
    <div class="form-group row">
        <div class="col-sm-12">
            <input style="font-size:12px !important" type="text" id="friend-name" name="val[friends]" placeholder="<?php echo lang("donation::search-by-email-firstname-lastname")  ?>"  class="form-control"/>
            <div class="friend-bring-result-donation">
                <div class="indicator"><img src="<?php echo img('images/loading.gif')?>"/></div>
                <div class="r"></div>
            </div>
        </div>
    </div>
    <p>
    <button id="import-all-friends" class="btn btn-secondary btn-sm"><?php echo lang("donation::import-all-my-friends"); ?></button>
    </p>
    <div class="friends-list box-content">
        <div class="slimscroll" data-height="150px">

        </div>
    </div>
    <div class="button-donation-holder">
        <button onclick="return checkAllDonation()" class="btn"><?php echo lang("donation::select-all") ?></button>
        <button onclick="return unCheckAllDonation()" class="btn"><?php echo lang("donation::un-select-all") ?></button>
    </div>
 <?php endif; ?>
    <br/>
    <div class="form-group row">
        <div class="col-sm-12">
            <label><?php echo lang("donation::invite-people-via-email"); ?></label>
            <textarea name="val[emails]" class="form-control"></textarea>
            <span><?php echo lang("donation::separate-each-email-with-comma") ?></span>
        </div>
    </div>
    <p><b><?php echo lang("donation::add-personal-mesage") ?></b></p>
    <div class="form-group row">
        <div class="col-sm-12">
            <label><?php echo lang("donation::subject"); ?></label>
            <input  type="text" name="val[subject]" value="<?php echo $email['subject']; ?>"  class="form-control"/>

        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-12">
            <label><?php echo lang("donation::message"); ?></label>
            <textarea name="val[message]" class="form-control"><?php echo nl2br($email['message']); ?></textarea>
        </div>
    </div>
    <p><?php echo lang("donation::title-break-down-note") ?></p>
    <p>[title] : <?php echo lang("donation::campaign-title");  ?></p>
    <p>[owner_name] : <?php echo lang("donation::creator-first-name-and-lastname");  ?></p>
    <p>[website_title] : <?php echo lang("donation::website-title");  ?></p>
    <p>[donation_url] : <?php echo lang("donation::donation_url");  ?></p>
    <div class="form-group row">
        <div class="col-sm-12">
            <button type="submit" class="btn btn-info send-ivm"><?php echo lang("donation::send-invitations"); ?></button>
        </div>
    </div>
</form>