<p><b><?php echo lang("donation::payment-details") ?></b></p>
<form class="form" action="" method="post" enctype="multipart/form-data">
    <?php CSRFProtection::embed() ?>
    <?php if($message): ?>
        <?php echo view("donation::alert",array('message'=>$message)); ?>
    <?php endif; ?>
    <div class="form-group row">
        <div class="col-sm-12">
            <label for="title"><?php echo lang("donation::paypal-email") ?></label>
            <input  type="text" name="val[pe]" value="<?php echo $donation['paypal_email'] ?>"
                    class="form-control"/>
        </div>
    </div>
    <?php if(!dCommissionEnabled()): ?>
    <div class="form-group row">
        <div class="col-sm-12">
            <label ><?php echo lang("donation::stripe-publishable-key") ?></label>
            <input  type="text" name="val[pk]" value="<?php echo $donation['publishable_key'] ?>"
                    class="form-control"/>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-12">
            <label ><?php echo lang("donation::stripe-secret-key") ?></label>
            <input  type="text" name="val[sk]" value="<?php echo $donation['secret_key']; ?>"
                    class="form-control"/>
        </div>
    </div>
    <?php endif; ?>
    <div class="form-group row">
        <div class="col-sm-12">
            <button type="submit" class="btn btn-info"><?php echo lang("save"); ?></button>
        </div>
    </div>
</form>
