<div class="row">
	<div class="col-md-4 left-column">
		<?php echo view('page::manage/menu') ?>
	</div>
	<div class="col-md-8 right-column">
		<div class="box">
			<div class="title"><?php echo lang('page::general-settings') ?></div>
			<div class="box-content">
				<?php if($message): ?>
					<div class="alert alert-success"><?php echo $message ?></div>
				<?php endif ?>
				<form action="" method="post">
					<?php CSRFProtection::embed() ?>
					<div class="form-group row">
						<label class="control-label col-sm-4"><?php echo lang('page::select-category') ?></label>
						<div class="col-sm-8">
							<select name="val[category]" class="form-control c-select">
								<?php foreach(get_page_categories() as $category): ?>
									<option <?php echo ($app->profilePage['page_category_id'] == $category['category_id']) ? 'selected' : null ?> value="<?php echo $category['category_id'] ?>"><?php echo lang($category['category_title']) ?></option>
								<?php endforeach ?>
							</select>
						</div>
					</div>

					<div class="form-group row">
						<label class="control-label col-sm-4"><?php echo lang('page-title') ?></label>
						<div class="col-sm-8">
							<input value="<?php echo $app->profilePage['page_title'] ?>" type="text" name="val[name]" class="form-control"/>
						</div>
					</div>

					<?php if(config('request-verification', true)): ?>
						<div style="margin: 20px 0">
							<?php if($app->profilePage['verified']): ?>
								<button type="button" class="btn btn-success btn-block disabled">
									<i class="ion-checkmark-circled"></i> <?php echo lang('verified') ?>
								</button>
							<?php else: ?>
								<?php if(verify_requested('page', $app->profilePage['page_id'])): ?>
									<button type="button" class="btn btn-danger btn-block disabled">
										<i class="ion-checkmark-circled"></i> <?php echo lang('verify-requested') ?>
									</button>
								<?php else: ?>
									<a href="#" data-toggle="modal" data-target="#myModal40" class="btn btn-secondary btn-block">
										<i class="ion-checkmark-circled"></i> <?php echo lang('request-verification') ?>
									</a>
								<?php endif ?>
							<?php endif ?>
						</div>
					<?php endif ?>
                    <?php fire_hook('page.manage.middle', $app->profilePage) ?>
					<div class="form-group row">
						<label class="control-label col-sm-4"><?php echo lang('page::page-description') ?></label>
						<div class="col-sm-8">
							<textarea name="val[description]" class="form-control auto-grow"><?php echo $app->profilePage['page_desc'] ?></textarea>
						</div>
					</div>
					<button class="btn btn-info"><?php echo lang('save') ?></button>
				</form>
			</div>
		</div>
	</div>
</div>
<!----Ouestion popup---->
<div class="modal fade" id="myModal40" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content modal-info">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">

				<!----Ouestion & Answers---->

				<div class="info widget-shadow info-box">
					<div class="info-title">
						<h4><?php echo lang('account-verification') ?></h4>
					</div>
					<div class="info-body">

						<form action="<?php echo url('user/verify/request') ?>" class="adm" method="post" enctype="multipart/form-data">
							<?php echo CSRFProtection::embed() ?>
							<input type="hidden" name="val[type]" value="page"/>
							<input type="hidden" name="val[type_id]" value="<?php echo $app->profilePage['page_id'] ?>"/>
							<table width="90%" style="min-height:100px; margin:auto; text-align:left">
								<?php $verification_question = get_verification_questions('page'); ?>
								<?php foreach($verification_question as $vquestion): ?>

									<?php if($vquestion['entity'] == 'page'): ?>
										<?php if(($vquestion ['input_type']) == 'text'): ?>
											<tr>
												<td class="bold"><?php echo $vquestion ['question']; ?>?</td>
												<td class="italic">
													<input type="text" name="val[<?php echo $vquestion['id'] ?>]">
												</td>
											</tr>
										<?php elseif(($vquestion ['input_type']) == 'boolean'): ?>
											<tr>
												<td class="bold"><?php echo $vquestion ['question']; ?>?</td>
												<td class="italic">
													<select class="c-select" name="val[<?php echo $vquestion['id'] ?>]">
														<option value="Yes">Yes</option>
														<option value="No">No</option>
													</select>
												</td>
											</tr>

										<?php elseif(($vquestion ['input_type']) == 'file'): ?>
											<tr>
												<td class="bold"><?php echo $vquestion ['question']; ?>?</td>
												<td class="italic">
													<input type="file" name="file<?php echo $vquestion['id'] ?>">
												</td>
											</tr>
										<?php endif ?>
									<?php endif ?>
								<?php endforeach ?>

							</table>


							<div class="clear"></div>
							<table class="button_table">
								<tr>

									<td align="center">
										<a href="">
											<button type="submit" name="submit" class="btn btn-sm btn-success"><?php echo lang('submit') ?></button>
										</a>
									</td>
								</tr>
							</table>
						</form>
						<div class="clear"></div>
					</div>
				</div>


				<!---//Ouestion & Answers--->

			</div>
		</div>
	</div>
</div>
<!----//Ouestion popup---->