<?php if((isset($mark) and $mark) or !isset($mark)) mark_message_read($message['message_id']); $user_id = isset($user_id) ? $user_id : get_userid() ?>
<div class="chat-message media chat-message-<?php echo $message['message_id'] ?>">
	<?php if($message['sender'] != $user_id): ?>
		<div class="media-left">
			<a ajax="true" href="<?php echo profile_url(null, $message) ?>">
				<div class="media-object">
					<img src="<?php echo get_avatar(75, $message) ?>"/>
				</div>
			</a>
		</div>
	<?php endif ?>
	<div class="media-body <?php echo ($message['sender'] == $user_id) ? 'message-owned' : 'message-not-owned' ?>">
		<?php if($message['sender'] != $user_id): ?>
			<span class="arrow-left"></span>
		<?php endif ?>
		<div class="message-content">
            <?php $chatMessage = removeUrlLinks($message['message']) ?>
			<?php echo output_text($chatMessage) ?>
            <?php echo get_chat_url_contents($message) ?>
			<?php if($message['image']): ?>
				<a data-image="<?php echo url_img($message['image'], 920) ?>" data-id="0" class="photo-viewer image" href="" style="background-image:url(<?php echo url_img($message['image'], 600) ?>)">

				</a>
			<?php endif ?>
            <?php if($message['gif']): ?>
            <?php $gifPath = perfectUnserialize($message['gif'])?>
                <a data-image="<?php echo url_img($gifPath) ?>" data-id="0" class="photo-viewer image" href="" style="background-image:url(<?php echo url_img($gifPath, 920) ?>)"></a>
            <?php endif ?>

			<?php if($message['voice']): ?>
				<div class="chat-voice">
					<div class="audio-player">
						<audio preload="true">
							<source src="<?php echo url($message['voice']) ?>" />
						</audio>
						<button class="playback-button ion-play" type="button"></button>
						<div class="timeline">
							<div class="play-head"></div>
						</div>
					</div>
				</div>
			<?php endif ?>
			<?php if($message['files']): ?>
				<?php $file = perfectUnserialize($message['files']) ?>
				<div class="media">
					<div class="media-left">
						<div>
							<img style="width: 40px" src="<?php echo img('images/file-icons/'.$file['extension'].'.png') ?>"/>
						</div>
					</div>
					<div class="media-body">
						<h6 class="media-heading" style="font-size: 13px"><?php echo sanitizeText($file['name']) ?></h6>
						<a data-toggle="tooltip" title="<?php echo lang('download-file') ?>" href="<?php echo url_to_pager('chat-download') ?>?message_id=<?php echo $message['message_id'] ?>&path=<?php echo $file['path'] ?>&name=<?php echo sanitizeText($file['name']) ?>" class="btn btn-secondary-outline btn-sm" download><i class="ion-android-download"></i></a>
					</div>
				</div>
			<?php endif ?>
		</div>
		<?php if($message['sender'] == $user_id): ?>
			<span class="arrow-right"></span>
		<?php endif ?>
		<span class="message-time"> <span class="timeago" title="<?php echo date('c', $message['time']) ?>"><?php echo date('c', $message['time']) ?></span></span>
		<a class="delete-button <?php echo ($message['sender'] == $user_id) ? 'delete-left' : 'delete-right' ?>" href="" onclick="return delete_chat_message('<?php echo $message['message_id'] ?>')"><i class="ion-android-delete"></i></a>

		<span class="seen"><i class="ion-android-done-all"></i> <span> <?php echo lang('chat::seen') ?></span></span>
	</div>
	<?php if($message['sender'] == $user_id): ?>
		<div class="media-right">
			<div class="media-object">
				<img src="<?php echo get_avatar(75, $message) ?>"/>
			</div>
		</div>
	<?php endif ?>

</div>