<?php $categories = marketplace_get_categories(); $category_id = input('c'); ?>
<div class="box">
	<ul class="menu">
		<li class="<?php if(!$category_id): ?> active<?php endif ?>">
			<a href="<?php echo url_to_pager('marketplace') ?>" ajax="true"><?php echo lang('marketplace::all-categories') ?></a>
		</li>
		<?php foreach($categories as $category): ?>
			<li class="<?php if($category_id == $category['id']): ?> active<?php endif ?>">
				<a href="<?php echo url_to_pager('marketplace') ?>?c=<?php echo $category['id'] ?>" ajax="true"><?php echo lang($category['title']) ?></a>
			</li>
		<?php endforeach ?>
	</ul>
</div>