<div class="box group">
	<div class="global-filter-container" data-url="<?php echo url('groups') ?>">
		<form id="page-list-search" method="post" onsubmit="return run_global_filter()" action="" class="form-inline list-search">
			<?php CSRFProtection::embed() ?>
			<input type="hidden" class="filter-input form-control" data-name="type" value="<?php echo input('type', 'recommend') ?>"/>
			<i class="search-icon ion-ios-search"></i>
			<input value="<?php echo input('term') ?>" type="text" class="form-control search-box filter-input" data-name="term" placeholder="<?php echo lang('search') ?>"/>
		</form>
		<div class="list-head">
			<h3 class="heading"><?php echo lang('group::groups') ?></h3>
		</div>
		<div class="filter-pane">
			<select id="video-category-list" onchange="return run_global_filter()" data-name="category" class="c-select filter-input">
				<option <?php echo (input('category', 'all') == 'all') ? 'selected' : null ?> value="all"><?php echo lang('video::all-categories') ?></option>
				<?php foreach(get_group_categories() as $category): ?>
					<option <?php echo (input('category', 'all') == $category['id']) ? 'selected' : null ?> value="<?php echo $category['id'] ?>"><?php echo lang($category['title']) ?></option>
				<?php endforeach ?>
			</select>

			<select id="video-filter-select" onchange="return run_global_filter()" data-name="filter" class="c-select filter-input">
				<option value="all"><?php echo lang('all') ?></option>
				<option <?php echo (input('filter') == 'top') ? 'selected' : null ?> value="top"><?php echo lang('top') ?></option>
				<option <?php echo (input('filter') == 'featured') ? 'selected' : null ?> value="featured"><?php echo lang('featured') ?></option>
			</select>
            <div class="list-layout-type">
                <a href="" onclick="return change_listing_layout('#group-list-container', 'list', 'group')"><i class="ion-ios-list-outline"></i></a>
                <a href="" onclick="return change_listing_layout('#group-list-container', 'grid', 'group')"><i class="ion-android-apps"></i></a>
            </div>
		</div>
	</div>
	<div id="group-list-container" class="box-content clearfix <?php echo ($list_type == 'list') ? 'list-listing-container' : 'grid-listing-container' ?>">
		<?php foreach($groups->results() as $group): ?>
			<?php echo view('group::display', array('group' => $group)) ?>
		<?php endforeach ?>
	</div>
	<div class="box-content">
		<?php if(!$groups->total): ?>
			<?php echo lang('group::no-grouo-found') ?>
		<?php else: ?>
			<?php echo $groups->append(array('term' => input('term'), 'type' => input('type', 'recommend'), 'filter' => input('filter')))->links(true) ?>
		<?php endif ?>
	</div>
</div>