<div class="box music">
	<div>
		<?php if($message): ?>
			<div class="alert alert-danger"><?php echo $message ?></div>
		<?php endif ?>
		<form action="" method="post" class="ajax-form">
			<?php CSRFProtection::embed() ?>
			<div class="field">
				<div class="left">
					<label for="val[title]" class="control-label"><?php echo lang('music::title') ?></label>
				</div>
				<div class="right">
					<input value="<?php echo input('val.title') ?>" type="text" name="val[title]" class="form-control" placeholder="<?php echo lang('music::title') ?>"/>
				</div>
			</div>
			<div class="field">
				<div class="left">
					<label for="val[description]" class="control-label"><?php echo lang('music::description') ?></label>
				</div>
				<div class="right">
					<input value="<?php echo input('val.description') ?>" type="text" name="val[description]" class="form-control" placeholder="<?php echo lang('music::description') ?>"/>
				</div>
			</div>
			<div class="field">
				<div class="left">
					<label for="val[music_search]" class="control-label"><?php echo lang('music::add-music') ?></label>
				</div>
				<div class="right">
					<input autocomplete="off" value="<?php echo input('val.music_search') ?>" type="text" name="val[music_search]" class="form-control" onblur="$('#music-playlist-editor-search-result-1').fadeOut('fast');" onfocus="music.playlist.editor.searchMusic(this, 'music-items-1', 'music-playlist-editor-search-result-1')" onkeyup="music.playlist.editor.searchMusic(this, 'music-items-1', 'music-playlist-editor-search-result-1')" placeholder="<?php echo lang('music::search-musics') ?>"/>
					<div style="height: 0px; overflow: visible; z-index: 9999; position: relative;">
						<div id="music-playlist-editor-search-result-1" class="box">

						</div>
					</div>
				</div>
			</div>
			<div class="field">
				<div class="left">
					<label for="val[musics]" class="control-label"></label>
				</div>
				<div class="right">
					<div id="music-items-1">
					</div>
				</div>
			</div>
			<div class="field">
				<div class="left">
					<label class="control-label"><?php echo lang('privacy') ?></label>
				</div>
				<div class="right">
					<?php fire_hook('privacy.select', 'relationship', config('default-playlist-privacy', 1)); ?>
				</div>
			</div>
			<div class="submit">
				<button class="btn btn-info"><?php echo lang('music::add-playlist') ?></button>
			</div>
		</form>
	</div>
</div>