<?php if (plugin_loaded('like') and config('feed-like-type', 'regular') != 'regular') : ?>
	<div class="reactors reactors-<?php echo $refName ?>-<?php echo $refId ?>">
		<?php echo view('like::reacts', array('type' => $refName, 'type_id' => $refId)) ?>
	</div>
<?php endif ?>
<?php $url = url_to_pager('music-player-page', array('id' => $music['slug'])); ?>
<div class="feed-footer">
	<ul class="feed-footer-menu clearfix">
		<?php if (plugin_loaded('like')) : ?>
			<?php load_functions('like::like'); ?>
			<?php echo view('like::like-footer', array('type' => $refName, 'typeId' => $refId)); ?>
		<?php endif ?>
		<li>
			<a href="#"><i class="ion-play"></i> <?php echo $music['play_count'] ?> <?php echo $music['play_count'] > 1 ? lang('music::plays') : lang('music::play') ?>
			</a>
		</li>
		<li class="music-social-share-link"><?php if (($music['privacy'] == 1 && plugin_loaded('sharer'))) echo view('sharer::share_link', array('link' => url_to_pager('music-page', array('id' => $music['slug'])))) ?></li>
		<?php if (config('enable-music-download')) : ?>
			<li>
				<a href="<?php echo url_to_pager('music-download', array('id' => $refId)) ?>" class="music-download-button ion-android-download" title="<?php echo lang('music::download-mp3'); ?>" style="font-size: 24px; position: relative; top: 2px; vertical-align: middle;" download></a>
			</li>
		<?php endif ?>
		<?php fire_hook('more-feed-footer', null, array($refName, $refId)); ?>
		<li class="pull-right">
			<ul class="feed-statistics">
				<?php if (plugin_loaded('like') and config('feed-like-type', 'regular') == 'regular') : ?>
					<?php if (plugin_loaded('like')) : ?>
						<li>
							<a onclick="return show_likes('<?php echo $refName ?>', '<?php echo $refId ?>')" href="">
								<i class="fa fa-thumbs-o-up"></i>
								<span class="like-count-<?php echo $refName ?>-<?php echo $refId ?>"><?php echo count_likes($refName, $refId) ?></span></a>
						</li>
						<?php if (config('enable-dislike', false)) : ?>
							<li>
								<a onclick="return show_dislikes('<?php echo $refName ?>', '<?php echo $refId ?>')" href="">
									<i class="ion-thumbsdown"></i>
									<span class="dislike-count-<?php echo $refName ?>-<?php echo $refId ?>"><?php echo count_dislikes($refName, $refId) ?></span></a>
							</li>
						<?php endif ?>
					<?php endif ?>
				<?php endif ?>
				<?php if (plugin_loaded('comment')) : ?>
					<?php load_functions('comment::comment') ?>
					<?php $countComments = count_comments($refName, $refId); ?>
					<li>
						<i class="ion-chatbubbles"></i>
						<span class="comment-count-<?php echo $refName ?>-<?php echo $refId ?>"><?php echo $countComments ?></span>
					</li>
				<?php endif ?>
				<?php fire_hook('more-feed-footer-count', null, array($refName, $refId)); ?>
			</ul>
		</li>
	</ul>
	<div class="d-block px-4 pb-2">
		<div class="field">
			<div class="top">
				<label for="" class="control-label"><?php echo lang('music::embed-code'); ?></label>
			</div>
			<div class="bottom">
				<textarea class="form-control" readonly id="" rows="3"><iframe width="100%" height="200" src="<?php echo $url; ?>" scrolling="no" frameborder="no"></iframe></textarea>
			</div>
		</div>
	</div>
	<?php fire_hook("music.footer", $music) ?>
</div>