<div class="box">
	<div class="title"><?php echo lang("blog::blogs") ?><?php fire_hook("profile.blog.title")?></div>
	<div id="blogs-list-container" class="box-content clearfix list-listing-container">
		<?php if($blogs->total): ?>
			<?php foreach($blogs->results() as $blog): ?>
				<?php $blog = arrange_blog($blog); ?>
				<?php $user = find_user($blog['user_id']) ?>
				<div class="media media-lg">
					<div class="media-left">
						<div class="media-object">
							<img src="<?php echo ($blog['image']) ? url_img($blog['image'], 700) : get_avatar(200, $user) ?>"/>
						</div>
					</div>
					<div class="media-body">
						<h4 class="media-heading">
							<a ajax="true" href="<?php echo url('blog/'.$blog['slug']) ?>"><?php echo $blog['title'] ?></a>
						</h4>
						<span class="help-block" style="display: block">
                            <?php echo lang('blog::publisher') ?>: <a ajax="true" href="<?php echo url($blog['publisher']['id']) ?>"><?php echo $blog['publisher']['name'] ?></a>
							<?php echo lang('blog::on') ?> <?php echo date('M j , y  h:i A', $blog['time']) ?>
						</span>
						<div><?php echo str_limit(strip_tags($blog['content']), 100) ?></div>
					</div>
				</div>
			<?php endforeach ?>
			<?php echo $blogs->links() ?>
		<?php else: ?>
			<div class="alert alert-info"><?php echo lang('blog::blogs-list-empty') ?></div>
		<?php endif ?>
	</div>
</div>