<?php $event_type = isset($app->eventType) ? $app->eventType : null; ?>
<div class="box ">
	<div class="box-content">
		<?php if(is_loggedIn() && can_create_event()): ?>
			<a class="btn btn-info btn-block btn-sm action-button" href="<?php echo url_to_pager('event-create') ?>" data-toggle="modal" data-target="#event-create-modal"><i class="ion-ios-plus-empty"></i> <?php echo lang('event::create-event') ?></a>
			<div id="event-create-modal" class="modal fade" role="dialog">
				<div class="modal-dialog modal-lg1">
					<div class="modal-content">
						<div class="modal-form-header">
							<button type="button" class="close" data-dismiss="modal">&times;</button>
							<p class="modal-title pull-left"><?php echo lang('event::add-event') ?></p>
						</div>
						<div class="modal-body">
							<form action="<?php echo url_to_pager('event-create') ?>" method="post" enctype="multipart/form-data" class="ajax-form">
								<?php CSRFProtection::embed() ?>
								<div class="field">
									<div class="top">
										<label class="control-label"><?php echo lang('event::event-category') ?></label><br/>
									</div>
									<div class="bottom">
										<div class="magic-select event-category" data-name="val[category]" data-width="200px">
											<?php $categories = get_event_categories(); ?>
											<div class="magic-select-toggle">
												<?php echo lang('select-category') ?>
											</div>
											<div class="magic-select-content">
												<?php foreach($categories as $category): ?>
													<div class="magic-select-option" data-value="<?php echo $category['id'] ?>">
														<?php echo lang($category['title']) ?>
													</div>
												<?php endforeach ?>
											</div>
										</div>
									</div>
								</div>
								<div class="field">
									<div class="top">
										<label class="control-label"><?php echo lang('event::event-title') ?></label>
									</div>
									<div class="bottom">
										<input value="<?php echo input('val.title') ?>" type="text" name="val[title]" class="form-control" placeholder="<?php echo lang('event::event-title') ?>"/>
									</div>
								</div>
								<div class="field">
									<div class="top">
										<label class="control-label"><?php echo lang('event::description') ?></label>
									</div>
									<div class="bottom">
										<textarea name="val[description]" class="form-control auto-grow-input<?php fire_hook('event.form.description.class') ?>" data-height="55px" placeholder="<?php echo lang('event::event-title') ?>"><?php echo input('val.description') ?></textarea>
									</div>
								</div>
								<div class="field">
									<div class="top">
										<label class="control-label"><?php echo lang('profile-cover') ?></label>
									</div>
									<div class="bottom">
										<div style="width:100% !important; height:200px; background-position: 0px 0px" class="magic-input-image-preview" data-name="cover_art">
											<span class="dimension"></span>
										</div>
									</div>
								</div>
								<div class="field">
									<div class="top">
										<label class="control-label"><?php echo lang('privacy') ?></label><br/>
									</div>
									<div class="bottom">
										<?php fire_hook('privacy.select', 'event'); ?>
									</div>
								</div>
								<?php echo fire_hook("event.host.html",view("event::host")) ?>
								<div class="field">
									<div class="top">
										<label class="control-label"><?php echo lang('event::location') ?></label>
									</div>
									<div class="bottom">
										<input id="feed-editor-geocomplete" value="<?php echo input('val.location') ?>" type="text" name="val[location]" placeholder="<?php echo lang('event::location') ?>" class="form-control"/>
									</div>
								</div>
								<div class="field">
									<div class="top">
										<label class="control-label"><?php echo lang('event::address') ?></label>
									</div>
									<div class="bottom">
										<textarea name="val[address]" class="form-control auto-grow-input" data-height="55px" placeholder="<?php echo lang('event::address') ?>"><?php echo input('val.address') ?></textarea>
									</div>
								</div>
								<div class="field">
									<div class="top">
										<label class="control-label"><?php echo lang('event::event-time') ?></label>
									</div>
									<div class="bottom">
										<input type="text" name="val[start_time]" class="<?php echo fire_hook('event.date.picker','datetimepicker') ?> form-control" placeholder="<?php echo lang('event::start-time') ?>"/>
										<?php echo lang('to') ?>
										<input type="text" name="val[end_time]" class="<?php echo fire_hook('event.date.picker','datetimepicker') ?> form-control" placeholder="<?php echo lang('event::end-time') ?>"/>
									</div>
								</div>
								<?php fire_hook('more.event.fields', null, array()); ?>
								<div class="modal-footer">
									<div class="submit">
										<button class="btn btn-info"><?php echo lang('event::create-event') ?></button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		<?php endif ?>
	</div>
	<ul class="menu">
		<li class="<?php echo ($event_type == 'upcoming') ? 'active' : null ?>">
			<a ajax="true" href="<?php echo url_to_pager('events') ?>"><?php echo lang('event::all-events') ?></a>
		</li>
		<!-- <li class="<?php echo (segment(1) == 'calender') ? 'active' : null ?>"><a ajax="true" href="<?php echo url_to_pager('events-calender', array('slug' => 'upcoming')) ?>"><?php echo lang('event::calender') ?></a> </li> -->
		<li class="<?php echo ($event_type == 'invite') ? 'active' : null ?>">
			<a ajax="true" href="<?php echo url_to_pager('events') ?>?type=invite"><?php echo lang('event::invites') ?></a>
		</li>
		<li class="<?php echo ($event_type == 'me') ? 'active' : null ?>">
			<a ajax="true" href="<?php echo url_to_pager('events') ?>?type=me"><?php echo lang('event::yours') ?></a>
		</li>
		<li class="<?php echo ($event_type == 'birthdays') ? 'active' : null ?>">
			<a ajax="true" href="<?php echo url_to_pager('events') ?>?type=birthdays"><?php echo lang('event::birthdays') ?></a>
		</li>
		<li class="<?php echo ($event_type == 'past') ? 'active' : null ?>">
			<a ajax="true" href="<?php echo url_to_pager('events') ?>?type=past"><?php echo lang('event::past-events') ?></a>
		</li>
	</ul>
</div>