<div class="wrapper">
	<div class="wrapper-title">
		<?php echo lang('page::manage-pages') ?>
		<a href="<?php echo url_to_pager('admin-page-category-add') ?>"><?php echo lang('page::add-category') ?></a>
	</div>
	<div class="wrapper-content">
		<form class="wrapper-form" action="" method="post" style="margin: 20px 0">
			<?php CSRFProtection::embed() ?>
			<div class="form-group">
				<label><?php echo lang('page::page-title') ?></label>
				<input type="text" class="form-control" value="<?php echo $page['page_title'] ?>" name="val[page_title]"/>
			</div>

			<div class="form-group">
				<label><?php echo lang('page::page-description') ?></label>
				<textarea class="form-control" name="val[page_desc]"><?php echo $page['page_desc'] ?></textarea>
			</div>

			<div class="form-group">
				<label><?php echo lang('verified') ?></label>
				<div class="c-inputs-stacked">
					<label class="c-input c-radio">
						<input value="1" <?php echo ($page['verified']) ? 'checked' : null ?> id="radioStacked1" name="val[verified]" type="radio">
						<span class="c-indicator"></span>
						<?php echo lang('yes') ?>
					</label>
					<label class="c-input c-radio">
						<input value="0" <?php echo (!$page['verified']) ? 'checked' : null ?> id="radioStacked2" name="val[verified]" type="radio">
						<span class="c-indicator"></span>
						<?php echo lang('no') ?>
					</label>
				</div>
			</div>
			<?php fire_hook("more.admincp.page.edit", $page, array()); ?>
			<button class="btn btn-info"><?php echo lang('save') ?></button>
		</form>

	</div>
</div>