<div class="wrapper">
	<div class="wrapper-title">
		<?php echo lang('page::manage-pages') ?>
		<a href="<?php echo url_to_pager('admin-page-category-add') ?>"><?php echo lang('page::add-category') ?></a>
	</div>
	<div class="wrapper-content">
		<form action="" method="get" style="margin: 20px 0">
			<?php CSRFProtection::embed() ?>
			<input type="text" class="form-control" name="term" placeholder="<?php echo lang('search') ?>"/>
			<button class="btn btn-sm btn-secondary" style="margin-top: 10px"><?php echo lang('search') ?></button>
		</form>
		<div class="list-table-container">
			<div class="row list-table-select-actions hide" data-group="users">
				<div class="col-sm-12">
					<a href="<?php echo url_to_pager('admin-page-batch-action') ?>?action=delete"
					   class="action-link list-table-select-action" data-group="users"><?php echo lang('delete') ?></a>
				</div>
			</div>
			<div class="table-responsive">
				<table class="table table-striped list-table">
					<thead>
					<tr>
						<th>
							<div class="list-table-select" data-group="users"
							     data-id="0"></div>
						</th>
						<th style="width: 10%">ID</th>
						<th style="width: 25%"><?php echo lang('page::page-title') ?></th>
						<th style="width: 25%"><?php echo lang('page::page-description') ?></th>
						<th style="width: 25%"><?php echo lang('page::page-owner') ?></th>
						<th style="width: 10%"><?php echo lang('verified') ?></th>
						<th style="width: 10%"><?php echo lang('page::likes') ?></th>
						<?php fire_hook("more.pages.head.arg", null, array()); ?>
						<th style="width: 20%"><?php echo lang('actions') ?></th>
					</tr>
					</thead>
					<tbody>
					<?php foreach($pages->results() as $page): ?>
						<tr>
							<th>
								<div class="list-table-select" data-group="users"
								     data-id="<?php echo $page['page_id'] ?>"></div>
							</th>
							<td><?php echo $page['page_id'] ?></td>
							<td>
								<a href="<?php echo page_url(null, $page) ?>"><?php echo $page['page_title'] ?></a>
							</td>
							<td><?php echo str_limit($page['page_desc'], 100); ?></td>
							<td><?php echo get_user_name(find_user($page['page_user_id'])) ?></td>
							<td><?php echo ($page['verified']) ? lang('yes') : lang('no') ?></td>
							<td><?php echo count_likes('page', $page['page_id']) ?></td>
							<?php fire_hook("more.pages.body.arg", $page, array()); ?>
							<td>
								<div class="dropdown actions">
									<a href="#" data-toggle="dropdown">
										<i class="ion-android-settings"></i>
									</a>
									<div class="dropdown-menu dropdown-menu-right">
										<a ajax="true" class="ion-edit"
										   href='<?php echo url_to_pager('admin-page-edit') ?>?id=<?php echo $page['page_id'] ?>'></a>
										|
										<a ajax="true" class="admin-confirm ion-android-delete"
										   href="<?php echo url('page/delete') ?>?id=<?php echo $page['page_id'] ?>&admin=true"></a>
									</div>
								</div>
							</td>
						</tr>
					<?php endforeach ?>
					</tbody>

				</table>
			</div>
		</div>
		<?php if($pages->total): ?><?php echo $pages->links() ?><?php endif ?>
	</div>
</div>