<div id="commissionModal" class="modal fade " tabindex="-1" role="dialog" aria-labelledby="commissionModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only"><?php _lang('close')?></span>
                </button>
                <h5 class="modal-title"><?php _lang('affliate::manage-commision-rules')?></h5>
            </div>
            <div class="modal-body">
                <div class="container row">
                    <form class="form" action="" method="post">
                        <input type="hidden" name="val[payment_type]" id="pt" />
                        <div class="form-group">
                            <label><?php echo lang("affliate::user-group");  ?></label>
                            <select id="ug" class="form-control" name="val[user_group]" onchange="return user_group_commision(this,'admincp');">
                                <?php $userRole = 2;?>
                                <?php foreach(list_user_roles() as $role):?>
                                    <option <?php echo ($role['role_id'] == $userRole) ? 'selected' : null?> value="<?php echo $role['role_id']?>"><?php echo $role['role_title']?></option>
                                <?php endforeach?>
                            </select>
                        </div>
                        <div class="wrapper-result-com">
                            <div class="indicator"><img src="<?php echo img('affliate::images/loading.gif')?>"/></div>
                            <div class="content">
                                <?php $limit = config('number-of-commision-levels',5); ?>
                                <?php for($i = 1;$i <= $limit; $i++): ?>
                                    <div class="form-group">
                                        <label> <?php echo lang("affliate::level").' '.$i;; ?></label>
                                        <input id="level_<?php echo $i; ?>" type="text" value="" name="val[level_<?php echo $i; ?>]" class="form-control" />
                                    </div>
                                <?php endfor; ?>
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary"><?php _lang('save'); ?></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>