<div class="wrapper">
    <div class="wrapper-title">
        <?php echo lang("affliate::manage-affliates-earnings"); ?>
    </div>
    <div class="wrapper-content">
        <div class="ajax-response"></div>
        <div class="container row">
            <div class="app-header-wrapper">
                <form class="form" action="" method="post">
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label><?php echo lang("affliate::client-name"); ?></label>
                            <input autocomplete="off"  id="name" class="form-control" name="val[name]" />
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <?php $from =  (input('val.from_date')) ? input('val.from_date') : date('m/d/Y',(strtotime('-6 days')));?>
                        <?php $end =  (input('val.end_date')) ? input('val.end_date') : date('m/d/Y',time());?>
                        <div class="form-group">
                            <label><?php echo lang("affliate::purchase-date"); ?></label>
                            <input autocomplete="off"  class="form-control" id="startDate" name="val[from_date]" value="<?php echo $from ?>" />
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label>.</label>
                            <input autocomplete="off" class="form-control" id="endDate" name="val[end_date]" value="<?php echo $end; ?>" />
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label><?php echo lang("affliate::payment-type"); ?></label>
                            <select id="ptype" name="val[ptype]" class="form-control">
                                <option value="any"><?php echo lang("affliate::any"); ?></option>
                                <?php foreach(get_commissions_list() as $k=>$v): ?>
                                    <option value="<?php echo toAscii($v) ?>"><?php echo $v; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label><?php echo lang("affliate::status"); ?></label>
                            <select id="status" name="val[status]" class="form-control">
                                <option value="any"><?php echo lang("affliate::any"); ?></option>
                                <?php foreach(get_aff_commission_status() as $k=>$v): ?>
                                    <option value="<?php echo $k ?>"><?php echo $v; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="col-sm-2">
                                <button class="btn btn-block btn-info submit-filter-com-track"><?php echo lang("affliate::search"); ?></button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>

            <div class="table-wrapper" id="comissonTrack">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th style=""><?php echo lang("affliate::purchased-date"); ?></th>
                        <th style=""><?php echo lang("affliate::client-name"); ?></th>
                        <th style=""><?php echo lang("affliate::payment-type"); ?></th>
                        <th style=""><?php echo lang("affliate::total-amount"); ?></th>
                        <th style=""><?php echo lang("affliate::comission-rate"); ?></th>
                        <th style=""><?php echo lang("affliate::comission-amount"); ?></th>
                        <th style=""><?php echo lang("affliate::comission-points"); ?></th>
                        <th style=""><?php echo lang("affliate::reason"); ?></th>
                        <th style=""><?php echo lang("affliate::status"); ?></th>
                        <th style=""><?php echo lang("affliate::action"); ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php echo view("affliate::commission-tracking-row",array('from'=>$from,'end'=>$end,'admin'=>'yes')); ?>
                    </tbody>
                </table>
                <div class="indicator" ><img src="<?php echo img('images/loading.gif')?>"/></div>
            </div>
        </div>
    </div>
</div>
<input type="hidden" id="ad" value="y" />
<div id="replyModal" class="modal fade " tabindex="-1" role="dialog" aria-labelledby="commissionModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only"><?php _lang('close')?></span>
                </button>
                <h5 class="modal-title"><?php _lang('affliate::response')?></h5>
            </div>
            <div class="modal-body">
                <div class="container row">
                    <div class="form-group">
                        <label><?php echo lang("affliate::message-op"); ?></label>
                        <textarea class="form-control" id="msg"></textarea>
                    </div>
                    <input type="hidden" id="eid" vaule="0" />
                    <div class="form-group">
                        <label><?php echo lang("affliate::action"); ?></label>
                        <select id="sumit-value" class="form-control">
                            <option value="3"><?php echo lang("affliate::approve") ?></option>
                            <option value="2"><?php echo lang("affliate::deny") ?></option>
                        </select>
                    </div>
                    <div class="form-group">
                        <button id="reply-earnings" data-type="earnings" class="btn btn-primary"><?php echo lang("affliate::submit"); ?></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>