<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<h4 class="modal-title"><?php echo lang('creditgift::send-credit') ?></h4>
			<button type="button" class="close" data-dismiss="modal">&times;</button>
		</div>
		<div class="modal-body">
			<div id="creditgift-modal-friends-list" class="box-content">
				<?php if($friends->results()): ?>
					<?php foreach($friends->results() as $friend): ?>
						<div class="row">
							<div class="col-sm-2">
								<a ajax="true" href="<?php echo profile_url(null, $friend) ?>"><img src="<?php echo get_avatar(75, $friend) ?>"/></a>
							</div>
							<div class="col-sm-10">
								<a href="<?php echo profile_url(null, $friend) ?>"><?php echo get_user_name($friend) ?></a>
								<ul class="info">
									<?php if($friend['country']): ?>
										<li>
											<i class="ion-ios-location"></i> <?php echo ucwords($friend['country']) ?>
										</li>
									<?php endif ?>
								</ul>
								<div class="action">
									<span><a id="creditgift-send-<?php echo $friend['id'] ?>" href="#" class="btn btn-secondary btn-sm" onclick="creditgift_send(<?php echo $id.', '.$friend['id'] ?>)"><?php echo lang('giftshop::send') ?></a></span>
								</div>
							</div>
						</div>
					<?php endforeach ?>
				<?php else: ?>
					<div class="alert alert-info"><?php echo lang('creditgift::no-friends') ?></div>
				<?php endif; ?>
			</div>
		</div>
		<div class="modal-footer">
			<?php if($total_pages > 1 && $id): ?>
				<div class="pagination">
					<?php if($page > 1): ?>
						<a href="#" onclick="return creditgift_paginate_friends(<?php echo $id ?>, 1);"><i class="ion-ios-skipbackward"></i></a>
						<a href="#" onclick="return creditgift_paginate_friends(<?php echo $id ?>, <?php echo($page - 1) ?>);"><i class="ion-arrow-left-b"></i></a>
					<?php endif ?>
					<?php if(($page < 6) && ($total_pages > 11)): ?>
						<?php for($i = 1; $i <= 11; $i++): ?>
							<?php echo preg_replace('/ '.$page.' /', ' <strong>'.$page.'</strong>', '<a href="#" onclick="return creditgift_paginate_friends('.$id.', '.$i.')"> '.$i.' </a>'); ?>
						<?php endfor ?>
					<?php elseif($page < 6): ?>
						<?php for($i = 1; $i <= $total_pages; $i++): ?>
							<?php echo preg_replace('/ '.$page.' /', ' <strong>'.$page.'</strong>', '<a href="#" onclick="return creditgift_paginate_friends('.$id.', '.$i.')"> '.$i.' </a>'); ?>
						<?php endfor ?>
					<?php elseif(($page >= 6) && ($page <= $total_pages - 5)): ?>
						<?php for($i = ($page - 5); $i <= ($page + 5); $i++): ?>
							<?php echo preg_replace('/ '.$page.' /', ' <strong>'.$page.'</strong>', '<a href="#" onclick="return creditgift_paginate_friends('.$id.', '.$i.')"> '.$i.' </a>'); ?>
						<?php endfor ?>
					<?php else: ?>
						<?php for($i = ($page - 5); $i <= $total_pages; $i++): ?>
							<?php echo preg_replace('/ '.$page.' /', ' <strong>'.$page.'</strong>', '<a href="#" onclick="return creditgift_paginate_friends('.$id.', '.$i.')"> '.$i.' </a>'); ?>
						<?php endfor ?>
					<?php endif ?>
					<?php if($page < $total_pages): ?>
						<a href="#" onclick="return creditgift_paginate_friends(<?php echo $id ?>, <?php echo($page + 1) ?>);"><i class="ion-arrow-right-b"></i></a>
						<a href="#" onclick="return creditgift_paginate_friends(<?php echo $id ?>, <?php echo $total_pages ?>);"><i class="ion-ios-skipforward"></i></a>
					<?php endif ?>
				</div>
			<?php endif ?>
		</div>
	</div>
	<div class="foreground">
		<div class="indicator">
			<img src="<?php echo img('images/loading.gif') ?>"/>
		</div>
		<div class="message">
			<div class="alert alert-success"><?php echo lang('creditgift::credit-sent') ?></div>
			<div class="alert alert-danger"><?php echo lang('creditgift::credit-not-sent') ?></div>
		</div>
	</div>
</div>
