<div class="box">
	<div class="box-content" style="margin: 5% 15%">
		<h6><?php echo lang('creditgift::transaction-details') ?></h6>
		<?php $plan = get_creditgift_planId($planId); ?>
        <div class="list-table-container">
            <div class="table-responsive">
	        	<table class="table list-table">
			<tbody>
                <tr>
                    <td><?php echo lang('creditgift::transaction-name') ?></td>
                    <td><?php echo lang('creditgift::purchase-of-credit') ?></td>
                </tr>
                <tr>
                    <td><?php echo lang('creditgift::purchased-by') ?></td>
                    <td><?php echo get_user_name(get_userid()); ?></td>
                </tr>
                <tr>
                    <td><?php echo lang('creditgift::unit') ?></td>
                    <td><?php echo $plan['unit']; ?></td>
                </tr>
                <tr>
                    <td><?php echo lang('creditgift::amount') ?></td>
                    <td><?php echo $plan['cost']; ?> (<?php echo config('default-currency') ?>)</td>
                </tr>
			</tbody>
		</table>
            </div>
        </div>
		<h6><?php echo lang('creditgift::select-payment-method') ?></h6>
		<img src="<?php echo img('images/payment-options.png') ?>"/>
		<div class="payment-methods">
			<?php fire_hook('payment.buttons.extend', null, array('creditgift', $plan['id'], lang($plan['description']), lang($plan['description']), $plan['cost'], url_to_pager('creditgift-payment-success').'?id='.$plan['id'].'&csrf_token='.CSRFProtection::getToken(), url_to_pager('creditgift-payment-cancel').'?id='.$plan['id'])) ?>
		</div>
	</div>
</div>