<div class="wrapper">
	<div class="wrapper-title"><?php echo lang('ranker::add-new-rank') ?>  </div>
	<div class="wrapper-content">
		<form method="post" action="" enctype="multipart/form-data" class="wrapper-form">
			<?php CSRFProtection::embed() ?>
			<?php if($message): ?>
				<div class="alert alert-danger"><?php echo $message ?></div>
			<?php endif ?>
			
            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php echo lang('ranker::title') ?></label>
                <div class="col-sm-9">
				   <select class="form-control" name="val[title]">
                    <option value="posts"><?php echo lang('Posts') ?></option>
                    <option value="likes"><?php echo lang('Likes') ?></option>
                </select>

                </div>
            </div>
			<div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php echo lang('ranker::point') ?></label>
                <div class="col-sm-9">
                   <input class="form-control" type="number" name="val[point]" placeholder="<?php echo lang('ranker::point') ?>"/>

                </div>
            </div>

			<button class="btn btn-info"><?php echo lang('ranker::add-rank') ?></button>
		</form>
	</div>
</div>