<div class="wrapper">
	<div class="wrapper-title">
		<?php echo lang('ranker::add-rank') ?>
		-
		<a class="btn btn-success" href="<?php echo url_to_pager('admincp-add-rank') ?>"><?php echo lang('ranker::add-rank') ?></a>
		<!--<a class="btn btn-success" href="<?php //echo url_to_pager('admincp-add-rank-title') ?>"><?php //echo lang('ranker::add-rank-title') ?></a>-->
	</div>
	<div class="wrapper-content">
		<div class="list-table-container">
			<div class="table-responsive">
				<table class="table table-striped list-table">
					<thead>
					<tr>
						<th>
							<div class="list-table-select" data-group="users" data-id="0"></div>
						</th>
						<th>ID</th>
						<th><?php echo lang('title') ?></th>
						<th><?php echo lang('point') ?></th>
						<th><?php echo lang('actions') ?></th>
					</tr>
					</thead>
					<tbody data-url="<?php echo url_to_pager('admincp-blog-manage-category').'?action=order' ?>" class="admincp-sortable" style="position: relative">
					<?php foreach($ranks as $rank): ?>
						<tr class="item" id="<?php echo $rank['id'] ?>">
							<td>
								<div class="list-table-select" data-group="users" data-id="<?php echo $rank['id'] ?>"></div>
							</td>

							<td style="width: 10%"><?php echo $rank['id'] ?></td>
							<td style="width: 30%"><?php echo lang($rank['title']) ?></td>
							<td style="width: 30%"><?php echo lang($rank['point']) ?></td>
							<td>
								<div class="dropdown actions">
									<a href="#" data-toggle="dropdown">
										<i class="ion-android-settings"></i>
									</a>
									<div class="dropdown-menu dropdown-menu-right">
										<a class="ion-edit" href='<?php echo url_to_pager('admincp-rank-manage-point').'?action=edit&id='.$rank['id'] ?>'></a>
										<a class="admin-confirm ion-android-delete" href="<?php echo url_to_pager('admincp-rank-manage-point').'?action=delete&id='.$rank['id'] ?>"></a>
									</div>
								</div>
							</td>


						</tr>
					<?php endforeach ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>