<?php if($id): ?>
<div class="wrapper auction">
	<div class="wrapper-title">Edit Auction Category
		<a class="btn btn-secondary" href="<?php echo url_to_pager('admincp-category-list'); ?>"> Categories</a>
	</div>
	<div class="wrapper-content" style="padding: 50px">
		<form action="" enctype="multipart/form-data" method="post">
			<?php CSRFProtection::embed(); ?>
			<?php $category = get_auction_category($id) ?>
			<div class="form-group row">
				<div class="col-sm-4">
					<label>Title</label>
				</div>
				<div class="col-sm-8">
					<input type="text" name="val[title]" class="form-control" value="<?php echo $category["title"]; ?>"/>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-4">
					<label>Description</label>
				</div>
				<div class="col-sm-8">
					<textarea rows="12" name="val[description]" class="form-control"><?php echo $category['description']; ?></textarea>
				</div>
			</div>
			<div class="form-group row">
				<button class="btn btn-success" name="create-cat">Save</button>
				<!--   <button class="btn btn-danger" name="cancel">Cancel</button>-->
				<a href="<?php echo url_to_pager('admincp-category-list') ?>" class="btn btn-danger" name="cancel">Cancel</a>
			</div>
			<?php endif ?>
		</form>
	</div>
</div>