<div class="wrapper auction">
	<div class="wrapper-title">Manage Auction Category
		<a class="btn btn-secondary" href="<?php echo url_to_pager('admincp-category-add'); ?>"> Add Category</a>
	</div>
	<div class="wrapper-content">
		<div class="wrapper-content">
			<div class="row list-table-select-actions hide" data-group="users">
				<div class="col-sm-12">
					<a href="<?php echo url_to_pager('admin-auction-batch-action') ?>?action=delete_cat"
					   class="action-link list-table-select-action" data-group="users"><?php echo lang('delete') ?></a>
					<?php fire_hook('admin.user.list.actions'); ?>
				</div>
			</div>
			<div class="table-responsive">
				<table class="table table-striped list-table">
					<thead>
					<tr>
						<th>
							<div class="list-table-select" data-group="users" data-id="0"></div>
						</th>
						<th width="39">ID</th>
						<th width="208">Title</th>
						<th width="491">Description</th>
						<th width="162">Operation</th>
					</tr>
					</thead>
					<tbody>
					<?php $cat_title = null;
					foreach(get_auction_categories() as $category): ?><?php $cat_title = $category['title']; ?>
						<tr>
							<td>
								<div class="list-table-select" data-group="users" data-id="<?php echo $category['id'] ?>"></div>
							</td>
							<td><?php echo $category['id']; ?></td>
							<td><?php echo $category['title']; ?></td>
							<td><?php echo $category['description']; ?></td>

							<td>
								<div class="dropdown actions">
									<a href="#" data-toggle="dropdown">
										<i class="ion-android-settings"></i>
									</a>
									<div class="dropdown-menu dropdown-menu-right">
										<a class="ion-edit" href='<?php echo url_to_pager('admincp-category-edit').'?id='.$category['id'] ?>'></a>
										<a class="ion-android-delete" href="" data-toggle="modal" data-target="#cat-delete"></a>
									</div>
								</div>
							</td>


						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div><!-- Modal -->
<div class="modal fade" id="cat-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="myModalLabel">Delete Confirmation</h4>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				Are you sure you want to delete <?php //echo $cat_title;  ?>... category
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-danger" data-miss="modal">Cancel</button>
				<a href="" class="btn btn-info">Delete</a> <!--<button type="button" class="btn btn-info">Delete</button>-->
			</div>
		</div>
	</div>
</div>