<div class="box">
    <div class="title"><?php echo lang('payment-status') ?></div>
    <div class="box-content">
        <div class="alert alert-danger">
            <?php echo lang('membership-payment-cancel') ?>
        </div>
        <a href="<?php echo url_to_pager('membership-choose-plan') ?>" ajax="true" class="btn btn-info btn-block action-button"><?php echo lang('choose-plan') ?></a>
    </div>
</div>
<script>
    <?php $url = url('membership/choose-plan'); ?>
    setTimeout(function(){
        window.location.href = '<?php echo $url?>'
    }, 500);
</script>