<div class="box">
    <div class="title"><?php echo lang('payment-status') ?></div>
    <div class="box-content">
        <div class="alert alert-success">
            <?php echo lang('membership-payment-success') ?>
        </div>
        <a href="<?php echo url_to_pager('feed') ?>" ajax="true" class="btn btn-info btn-block action-button"><?php echo lang('membership-home') ?></a>
    </div>
</div>
<script>
    <?php
    $url = url('feed'); if (user_need_welcome_page()) {
        $url = url('user/welcome');
    } ?>
    setTimeout(function(){
        window.location.href = '<?php echo $url?>'
    }, 500);
</script>