<?php $quiz_menus = get_menus("quizes-menu") ?>
<?php if($quiz_menus || (is_loggedIn() && user_has_permission('can-create-quiz') and config('allow-members-create-quiz', true))): ?>
	<div class="box">
		<div class="box-content">
			<a href="<?php echo url('quiz/add') ?>" class="btn btn-info btn-block" type="button" data-toggle="modal" data-target="#create-quiz-modal"><?php echo lang('quiz::add-quiz') ?></a>
			<div class="modal fade" id="create-quiz-modal" role="dialog">
				<div class="modal-dialog">
					<div class="modal-content">
						<form action="<?php echo url_to_pager('quiz-add'); ?>" method="post" enctype="multipart/form-data" class="ajax-form">
							<div class="modal-form-header">
								<button type="button" class="close" data-dismiss="modal">&times;</button>
								<p class="modal-title"><?php echo lang('quiz::new-quiz') ?></p>
							</div>
							<div class="modal-body">
								<?php CSRFProtection::embed() ?>
								
								<div class="field">
									<div class="top">
										<label class="control-label"><?php echo lang('quiz::quiz-title') ?></label>
									</div>
									<div class="bottom">
										<input value="<?php echo input('val.title') ?>" type="text" class="form-control" name="val[title]" placeholder="<?php echo lang('quiz::quiz-title') ?>"/>
									</div>
								</div>
								<div class="field">
									<div class="top">
										<label class="control-label"><?php echo lang('quiz::category') ?></label>
									</div>
									<div class="bottom">
                                        <div class="magic-select" data-name="val[category]" data-width="200px">
                                            <?php $categories = get_quiz_categories(); ?>
                                            <div class="magic-select-toggle">
                                                <?php echo lang('select-category') ?>
                                            </div>
                                            <div class="magic-select-content">
                                                <?php foreach($categories as $category): ?>
                                                    <?php $sub_categories = get_quiz_parent_categories($category['id']) ?>
                                                    <?php if($sub_categories): ?>
                                                        <div class="magic-select-label"><?php echo lang($category['title']) ?></div>
                                                        <?php foreach($sub_categories as $cat): ?>
                                                            <div class="magic-select-option" data-value="<?php echo $cat['id'] ?>">
                                                                <?php echo lang($cat['title']) ?>
                                                            </div>
                                                        <?php endforeach ?>
                                                    <?php else: ?>
                                                        <div class="magic-select-option" data-value="<?php echo $category['id'] ?>">
                                                            <?php echo lang($category['title']) ?>
                                                        </div>
                                                    <?php endif ?>
                                                <?php endforeach ?>
                                            </div>
                                        </div>
									</div>
								</div>
								<div class="field">
									<div class="top">
										<label class="control-label"><?php echo lang('quiz::quiz-desc') ?></label>
									</div>
									<div class="bottom quiz-desc-c">
										<textarea name="val[content]" class="" placeholder="<?php echo lang('quiz::quiz-desc') ?>"><?php echo input('val.content') ?></textarea>
									</div>
								</div>
								<div class="field">
									<div class="top">
										<label class="control-label"><?php echo lang('quiz::pass-mark') ?></label>
									</div>
									<div class="bottom">
										<input value="<?php echo input('val.pass_mark') ?>" type="number" class="form-control" name="val[pass_mark]" placeholder="<?php echo lang('quiz::pass-mark') ?>"/>
									</div>
								</div>
								<div class="field">
									<div class="top">
										<label class="control-label"><?php echo lang('quiz::preview-image') ?></label>
									</div>
									<div class="bottom">
										<div class="magic-input-image-preview" data-name="image">
											<span class="dimension"></span>
										</div>
									</div>
								</div>
								<div class="field">
									<div class="top">
										<label class="control-label"><?php echo lang('quiz::tags') ?></label>
									</div>
									<div class="bottom">
										<input type="text" name="val[tags]" class="form-control" value="<?php echo input('val.tags') ?>" placeholder="<?php echo lang('quiz::tags') ?>">
									</div>
								</div>
								<div class="field">
									<div class="top">
										<label class="control-label"><?php echo lang('status') ?></label>
									</div>
									<div class="bottom">
										<div class="magic-select" data-name="val[status]" data-width="200px">
											<div class="magic-select-toggle">
												<?php echo lang('quiz::draft') ?>
											</div>
											<div class="magic-select-content">
												<div class="magic-select-option" data-value="0"><?php echo lang('quiz::draft') ?></div>
											</div>
										</div>
									</div>
								</div>
								<div class="field">
									<div class="top">
										<label class="control-label"><?php echo lang('publisher') ?></label>
									</div>
									<div class="bottom">
										<div class="magic-select" data-name="val[entity]" data-width="300px">
											<div class="magic-select-toggle">
												<img src="<?php echo get_avatar(75) ?>" class="thumb"/>
												<?php echo get_user_name(); ?>
											</div>
											<div class="magic-select-content slimscroll" data-height="200px">
												<div class="magic-select-option" data-value="user-<?php echo get_userid() ?>">
													<img src="<?php echo get_avatar(75) ?>" class="thumb"/>
													<?php echo get_user_name(); ?>
												</div>
												<?php fire_hook('entity.select.list') ?>
											</div>
										</div>
									</div>
								</div>
                                <?php fire_hook('more.quiz.field') ?>
								<div class="field">
									<div class="top">
										<label class="control-label"><?php echo lang('privacy') ?></label>
									</div>
									<div class="bottom">
										<?php fire_hook('privacy.select'); ?>
									</div>
								</div>
							</div>
							<div class="modal-footer">
								<div class="submit">
									<input type="submit" class="btn btn-default" value="<?php echo lang("quiz::create") ?>"/>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
		<ul class="menu">
			<?php foreach($quiz_menus as $menu): ?>
				<li>
					<a <?php echo $menu->ajax ? 'ajax="true"' : null ?> <?php echo ($menu->tab) ? 'onclick="return window.open(\''.$menu->link.'\')"' : null ?> href="<?php echo ($menu->tab) ? 'javascript:void(0)' : $menu->link ?>"><?php echo lang($menu->title) ?></a>
				</li>
			<?php endforeach ?>
			<?php if(is_loggedIn()): ?>
				<li>
					<a href="<?php echo url('quizes?type=mine') ?>" ajax="true"><?php echo lang('quiz::my-quizes') ?></a>
				</li>
			<?php endif ?>
		</ul>
	</div>
<?php endif ?>
