<div class="wrapper">
	<div class="wrapper-title"><?php echo lang('report::manage-reports') ?></div>
	<div class="wrapper-content">
		<div class="list-table-container">
			<div class="table-responsive">
				<table class="table table-striped list-table">
					<thead>
					<tr>
						<th>
							<div class="list-table-select" data-group="users" data-id="0"></div>
						</th>
						<th>ID</th>
						<th><?php echo lang('type') ?></th>
						<th><?php echo lang('message') ?></th>
						<th><?php echo lang('report::reported-by-who') ?></th>
						<th><?php echo lang('actions') ?></th>
					</tr>
					</thead>
					<tbody>
					<?php foreach($reports->results() as $report): ?>
						<?php $user = find_user($report['user_id']) ?>
						<tr>
							<td>
								<div class="list-table-select" data-group="users" data-id="<?php echo $user['id'] ?>"></div>
							</td>
							<td><?php echo $report['report_id'] ?></td>
							<td><?php echo ucwords($report['type']) ?></td>
							<td><?php echo $report['message'] ?></td>
							<td>
								<a href="<?php echo url($user['username']) ?>" class="view-profile" ajax="true">
									<i class="ion-android-person"> </i> <?php echo $user['first_name']." ".$user['last_name']; ?>
								</a>
							</td>

							<td>
								<div class="dropdown actions">
									<a href="#" data-toggle="dropdown">
										<i class="ion-android-settings"></i>
									</a>
									<div class="dropdown-menu dropdown-menu-right">
										<a class="ion-edit" onclick="return window.open('<?php echo $report['link'] ?>')" nofollow='nofollow' href='javascript::void(0)'></a>
										<a class="admin-confirm ion-android-delete" href="<?php echo url_to_pager('admincp-reports-delete') ?>?id=<?php echo $report['report_id'] ?>"></a>
									</div>
								</div>
							</td>

						</tr>
					<?php endforeach ?>
					</tbody>
				</table>
			</div>
		</div>
		<?php echo $reports->links() ?>
	</div>
</div>