<div class="wrapper">
	<div class="wrapper-title"><?php echo lang('giftshop::gift-category') ?> |
		<button type="button" class="btn btn-info" data-toggle="modal"
		        data-target="#addCategory"><?php echo lang('add-new') ?></button>
	</div>
	<div class="wrapper-content">
		<div class="list-table-container">
			<div class="row list-table-select-actions hide" data-group="users">
				<div class="col-sm-12">
					<a href="<?php echo url_to_pager('admin-giftshop-batch-action') ?>?action=delete_cat"
					   class="action-link list-table-select-action" data-group="users"><?php echo lang('delete') ?></a>
					<?php fire_hook('admin.user.list.actions'); ?>
				</div>
			</div>
			<div class="table-responsive">
				<table class="table table-striped list-table">
					<thead>
					<tr>
						<th>
							<div class="list-table-select" data-group="users"
							     data-id="0"></div>
						</th>
						<th><?php echo lang('giftshop::id') ?></th>
						<th><?php echo lang('giftshop::category') ?></th>
						<th><?php echo lang('giftshop::option') ?></th>
					</tr>
					<?php foreach($cats as $cat): ?>
						<tr>
							<td>
								<div class="list-table-select" data-group="users"
								     data-id="<?php echo $cat['id']; ?>"></div>
							</td>
							<td><?php echo $cat['id']; ?></td>
							<td><?php echo $cat['category']; ?></td>
							<td>
								<div class="dropdown actions">
									<a href="#" data-toggle="dropdown">
										<i class="ion-android-settings"></i>
									</a>
									<div class="dropdown-menu dropdown-menu-right">
										<a ajax="true" class="ion-edit" href='<?php echo url_to_pager('admincp-giftshop-category-edit') ?>?action=edit&id=<?php echo $cat['id'] ?>'></a>
										<a ajax="true" class="admin-confirm ion-android-delete" href="<?php echo url_to_pager('admincp-giftshop-category-edit') ?>?action=delete&id=<?php echo $cat['id'] ?>"></a>
									</div>
								</div>
							</td>
						</tr>
					<?php endforeach; ?>
				</table>
			</div>
		</div>
	</div>
</div>
<!-- Modal -->
<div id="addCategory" class="modal fade" role="dialog">
	<div class="modal-dialog">
		<!-- Modal content-->
		<div class="modal-content">
			<form action="" method="post" class="form-control"
			">
			<div class="modal-header">
				<h4 class="modal-title"><?php echo lang('giftshop::add-new-category') ?></h4>
				<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>
			<div class="modal-body">
				<div>
					<label><?php echo lang('category') ?>:</label>
					<input id="inputsm" class="form-control input-sm" type="text" name="val[category]" required="">
				</div>
				<br/>
			</div>
			<div class="modal-footer">
				<button type="submit" class="btn btn-success"><?php echo lang('add') ?></button>
				<button type="button" class="btn btn-default" data-dismiss="modal"><?php echo lang('close') ?></button>
			</div>
			</form>
		</div>
	</div>
</div>