<div class="wrapper">
	<div class="wrapper-title">
		<a ajax="true" href="<?php echo url_to_pager('admincp-creditgift-rank') ?>">
			<h4><?php echo lang('contest::manage-rank') ?></h4>
		</a>
	</div>
	<div class="wrapper-content">
		<form enctype="multipart/form-data" class="wrapper-form" action="" method="post">
			<?php CSRFProtection::embed() ?>
			<?php foreach($edits as $edit): ?>
				<div>
					<label><?php echo lang('giftshop::category') ?>:</label>
					<input id="inputsm" class="form-control" type="text" name="val[category]" value="<?php echo $edit['category']; ?>" required="">
				</div>
				<br/>
			<?php endforeach; ?>
			<button class="btn btn-info" style="margin-top: 20px"><?php echo lang("edit") ?></button>
		</form>
	</div>
</div>