<?php /** @var array $servers */ ?>
<div class="list-table-container">
    <div class="row list-table-select-actions hide" data-group="users">
        <div class="col-sm-12">
            <a href="<?php echo url_to_pager('admin-livestream-batch-action') ?>?action=activate-server" class="action-link list-table-select-action" data-group="users"><?php echo lang('activate') ?></a>
            <a href="<?php echo url_to_pager('admin-livestream-batch-action') ?>?action=deactivate-server" class="action-link list-table-select-action" data-group="users"><?php echo lang('deactivate') ?></a>
            <a href="<?php echo url_to_pager('admin-livestream-batch-action') ?>?action=delete-server" class="action-link list-table-select-action" data-group="users"><?php echo lang('delete') ?></a>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-striped list-table">
            <thead>
                <tr>
                    <th><div class="list-table-select" data-group="users" data-id="0"></div></th>
                    <th style="width: 5%">ID</th>
                    <th><?php echo lang('livestream::url') ?></th>
                    <th><?php echo lang('username') ?></th>
                    <th><?php echo lang('type') ?></th>
                    <th><?php echo lang('status') ?></th>
                    <th><?php echo lang('actions') ?></th>
                </tr>
            </thead>
            <tbody>
            <?php foreach($servers as $server): ?>
                <?php echo view('livestream::admincp/server/get', array('server' => $server)) ?>
            <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>