<div id="mediachat-receive-container" class="mediachat">
	<div id="mediachat-receive" class="mediachat">
		<h1 id="mediachat-receiver-instruction" class="instruction"><?php echo lang('mediachat::incoming-call', array('type' => '')) ?></h1>
		<div id="mediachat-caller-info">
			<span></span>
			<img id="mediachat-caller-avatar" class="avatar" src="<?php get_avatar(200) ?>" />
		</div>
		<div id="mediachat-caller-name"></div>
		<div id="mediachat-receive-actions">
			<a href="#" id="mediachat-receive-button" title="<?php echo lang('mediachat::receive') ?>"><i class="ion-android-call"></i></a>
			<a href="#" id="mediachat-drop-button" title="<?php echo lang('mediachat::end') ?>">
				<svg class="" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
					<path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
				</svg>
			</a>
		</div>
	</div>
</div>