<?php pusher()->reset('conference.call'); ?>
<?php pusher()->reset('conference'); ?>
<div class="box">
    <div class="container">
        <?php foreach (get_friends() as $friend) : ?>
            <?php $friend = find_user($friend);
            $stream_support = Mediachat::streamSupport($friend['id']);
            if (user_is_online($friend)) : ?>
                <div class="d-flex justify-content-between align-items-center">
                    <h6 class="font-bold text-sm"><?= $friend['username']; ?></h6>
                    <button title="<?php echo $stream_support ? lang('mediachat::video-call') : lang('mediachat::user-unavailable-video-call'); ?>" data-user-id="<?= $friend['id']; ?>" class="text-lg icon ion-ios-videocam conference-call-button"></button>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</div>