<?php if(is_loggedIn()): ?>
	<?php load_functions("relationship::relationship"); $limit = 20;
	$users = relationship_suggest($limit, null, true); ?>
	<?php if($users->total): ?>
		<div class="box users-box people-suggestion-box" id="people-suggestion-box">
			<div class="title">
				<?php echo lang('relationship::people-suggestion') ?>
				<a ajax="true" href="<?php echo url_to_pager('suggestions') ?>"><i class="ion-ios-arrow-forward pull-right"></i></a>
			</div>
            <div class="clearfix slider-side-widget">
                    <?php foreach($users->results() as $user): ?>
                        <div class="suggestion-container">
                            <a class="suggestion-a" title="<?php echo get_user_name($user) ?>" ajax="true" href="<?php echo profile_url('', $user) ?>">
                                <img class="suggestion-img" src="<?php echo get_avatar(200, $user) ?>"/>
                            </a>
                            <div class="suggestion-info">
                                <a class="media-heading name" ajax="true" href="<?php echo profile_url(null, $user) ?>"><?php echo get_user_name($user) ?> <?php echo verify_badge($user) ?></a>
                                <div class="mutual-friends">
                                    <?php if(is_loggedIn() and $user['id'] != get_userid()): ?>
                                        <?php $count = count(get_mutual_friends($user['id'])) ?>
                                        <?php if($count > 0 ) :?>
                                            <i class="ion-android-person-add"></i> <?php echo $count ?> <?php echo lang('mutual-friends') ?>
                                        <?php elseif ($user['country']): ?>
                                            <i class="ion-ios-location"></i> <?php echo ucwords($user['country']) ?>
                                        <?php else: ?>
                                            <i class="ion-android-people"></i> <?php echo count(get_friends($user['id'])) ?> <?php echo lang('friends') ?>
                                        <?php endif ?>
                                    <?php endif ?>
                                </div>
                                <div class="action">
                                    <?php if(plugin_loaded('relationship')): ?>
                                        <?php echo view('relationship::button', array('userid' => $user['id'])) ?>
                                    <?php endif ?>
                                </div>
                            </div>
                        </div>
                    <?php endforeach ?>
                </div>
    	</div>
	<?php endif ?>
<?php endif ?>
