<div class="wrapper">
	<div class="wrapper-title">
		<?php echo lang('business::business-plans') ?>
		<a href="<?php echo url_to_pager('admin-business-add-plan') ?>" class="btn btn-success btn-sm"><?php echo lang('business::add-plan') ?></a>
	</div>
	<div class="wrapper-content">
		<div class="row list-table-select-actions hide" data-group="users">
			<div class="col-sm-12">
				<a href="<?php echo url_to_pager('admin-business-batch-action') ?>?action=delete_plan"
				   class="action-link list-table-select-action" data-group="users"><?php echo lang('delete') ?></a>
			</div>
		</div>
		<div class="table-responsive">
			<table class="table table-striped list-table">
				<thead>
				<tr>
					<th>
						<div class="list-table-select" data-group="users" data-id="0"></div>
					</th>
					<th>ID</th>
					<th><?php echo lang('business::title') ?></th>
					<th><?php echo lang('business::description') ?></th>
					<th><?php echo lang('business::days-limit') ?></th>
					<th><?php echo lang('business::featured') ?></th>
					<th><?php echo lang('business::price') ?></th>
					<th><?php echo lang('business::actions') ?></th>
				</tr>
				</thead>
				<tbody>
				<?php foreach($plans as $plan): ?>
					<tr>
						<td>
							<div class="list-table-select" data-group="users"
							     data-id="<?php echo $plan['id'] ?>"></div>
						</td>
						<td><?php echo $plan['id'] ?></td>
						<td><?php echo lang($plan['title']) ?></td>
						<td><?php echo lang($plan['description']) ?></td>
						<td><?php echo $plan['days'] <= 0 ? lang('business::unlimited') : $plan['days'] ?></td>
						<td><?php echo $plan['featured'] ? lang('business::yes') : lang('business::no') ?></td>
						<td><?php echo $plan['price'] <= 0 ? lang('business::free') : $plan['price'].' '.config('default-currency') ?></td>
						<td>
							<div class="dropdown actions">
								<a href="#" data-toggle="dropdown">
									<i class="ion-android-settings"></i>
								</a>
								<div class="dropdown-menu dropdown-menu-right">
									<a class="ion-edit" href='<?php echo url_to_pager('admin-business-edit-plan').'?id='.$plan['id'] ?>'></a>
									<a class="admin-confirm ion-android-delete" href="<?php echo url_to_pager('admin-business-delete-plan').'?id='.$plan['id'] ?>"></a>
								</div>
							</div>
						</td>


					</tr>
				<?php endforeach ?>
				</tbody>
			</table>
		</div>
	</div>
</div>