
<div class="box-content">
    <div class="title"><?php echo $entry['title']; ?></div>
    <div class="box-content video-player-container">
        <?php if($entry['source'] == 'upload'): ?>
            <?php if($entry['status'] == 0): ?>
                <div class="video-in-processing">
                    <?php echo lang('video::video-in-processing') ?>
                </div>
            <?php else: ?>
                <iframe id="video-iframe" class="video-iframe" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true" style="border: none;padding: 0 !important;margin:0 10px;border-radius: 3px;overflow: hidden;width: 96%;" src="<?php echo url_to_pager("play-video").'?link='.$entry['file_path'] ?>&height=430" width="94%" height="450"></iframe>
            <?php endif ?>
        <?php else: ?>
            <div class="external-video"><?php echo set_iframe_link_param($entry['code'], array('rel' => 0)) ?></div>
        <?php endif ?>
    </div>

    <div class="box-content post">
        <?php echo $entry['description'] ?>
    </div>
</div>
<?php echo view("contest::footer-like",array('refName'=>$entry['ref_name'],'refId'=>$entry['id'])); ?>