<div class="box">
    <div class="title"><?php echo fire_hook('profile.livestream.title', lang('livestream::livestreams')) ?></div>
    <div class="livestream-list">
        <div class="body">
            <div class="listings">
                <div class="listing row">
                    <?php foreach ($livestreams->results() as $livestream) : ?>
                        <div class="col-md-6">
                            <?php echo view('livestream::livestream/list_item', array('livestream' => $livestream)) ?>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>
        </div>
    </div>
    <div class="box-content">
        <?php if (!$livestreams->total) : ?>
            <div class="alert alert-info"><?php echo lang('livestream::no-livestream-found') ?></div>
        <?php else : ?>
            <?php echo $livestreams->append(array('category' => input('category'), 'term' => input('term'), 'type' => 'user-profile'))->links(); ?>
        <?php endif ?>
    </div>
</div>