<div class="_27i-">
	<div class="_4-u2 _1htl _4-u8">
		<div id="u_fetchstream_11_1">
			<div class="_3c6v  _9bp _50z3">
				<div class="_50zm" style="height: 72px;">
					<div style="width: 176px; height: 72px;">
						<div class="_50zn clearfix" style="width: 4920px; height: 72px; margin-left: 0px;">
							<div role="article" aria-hidden="false" aria-posinset="0" aria-setsize="28" class="_3el8 clearfix">
								<div class="_3el6 _3el7">
                                    <span display="inline">
                                        <a href="/groups/?ref=category_discover_landing_carousel&amp;discover_category_id=212609529249058">
                                            <div class="_3c6x">
                                                <div class="uiScaledImageContainer _3c6w" style="width:168px;height:72px;">
                                                    <img class="scaledImageFitWidth img" src="https://scontent.fpry1-1.fna.fbcdn.net/v/t39.8221-6/s168x128/18898727_1463526737045202_7199870823241351168_n.jpg?oh=f862bdeffbb0c26348707a65994033df&amp;oe=5B12465C" style="top:0px;" alt="" width="168" height="112"></div><div class="_44y-"><span class="_3c6_">Recommended</span></div>
                                            </div>
                                        </a>
                                    </span>
								</div>
							</div>
						</div>
					</div>
					<a class="_50z1 _39kr accessible_elem _-op _-oq" role="button" aria-disabled="true" aria-label="Previous" href="#"><span display="inline"><i class="img sp_JcuMFSClstw sx_4e53d1"><u>Previous</u></i></span></a>
					<a class="_50z2 _39kr  _-op" role="button" aria-disabled="false" aria-label="Next" href="#"><span display="inline"><i class="img sp_JcuMFSClstw sx_52779a"><u>Next</u></i></span></a>
				</div>
			</div>
		</div>
	</div>
</div>

<style>
	._27i- {
		overflow: hidden;
		position: fixed;
		top: 87px;
		width: 1012px;
		z-index: 199;
	}

	._2yq ._4rkc ._1htl {
		border-radius: 0 0 3px 3px;
		border-top: 0;
		height: 96px;
	}

	._2yq ._4-u2 {
		border-color: transparent;
		border-left-width: 0;
		border-right-width: 0;
		position: relative;
	}

	._2yq ._4-u2 {
		border-color: transparent;
		border-left-width: 0;
		border-right-width: 0;
		position: relative;
	}

	._4-u8 {
		background-color: #fff;
	}

	element.style {
	}

	#facebook ._-kb div {
		font-family: inherit;
	}

	._2yq ._4rkc ._1htl {
		border-radius: 0 0 3px 3px;
		border-top: 0;
		height: 96px;
	}

	._2yq ._4-u2 {
		border-color: transparent;
		border-left-width: 0;
		border-right-width: 0;
		position: relative;
	}

	._2ltu ._4-u2 {
		border: 1px solid #dddfe2;
	}

	._4-u8 {
		background-color: #fff;
	}

	._4-u2 {
		border: 1px solid;
		border-color: #e5e6e9 #dfe0e4 #d0d1d5;
		border-radius: 3px;
	}

	user agent stylesheet
	div {
		display: block;
	}

	#facebook ._-kb div {
		font-family: inherit;
	}

	#facebook ._-kb div {
		font-family: inherit;
	}

	#facebook ._-kb div {
		font-family: inherit;
	}

	#facebook ._-kb div {
		font-family: inherit;
	}

	._3p8r {
		-webkit-font-smoothing: antialiased;
	}

	#facebook ._-kb div {
		font-family: inherit;
	}

	#facebook ._-kb div {
		font-family: inherit;
	}

	#facebook ._-kb div {
		font-family: inherit;
	}

	body, button, input, label, select, td, textarea {
		font-family: Helvetica, Arial, sans-serif;
		font-size: 12px;
	}

	body {
		background: #fff;
		color: #1d2129;
		direction: ltr;
		line-height: 1.34;
		margin: 0;
		padding: 0;
		unicode-bidi: embed;
	}

	._2yq ._4rkc ._1htl::before {
		border-radius: 0 0 3px 3px;
	}

	._2yq._2ltu ._4-u2:before {
		border: 1px solid #dddfe2;
	}

	element.style {
	}

	#facebook ._-kb div {
		font-family: inherit;
	}

	._2yq ._4rkc ._1htl {
		border-radius: 0 0 3px 3px;
		border-top: 0;
		height: 96px;
	}

	._2yq ._4-u2 {
		border-color: transparent;
		border-left-width: 0;
		border-right-width: 0;
		position: relative;
	}

	._2ltu ._4-u2 {
		border: 1px solid #dddfe2;
	}

	._4-u8 {
		background-color: #fff;
	}

	._4-u2 {
		border: 1px solid;
		border-color: #e5e6e9 #dfe0e4 #d0d1d5;
		border-radius: 3px;
	}

	user agent stylesheet
	div {
		display: block;
	}

	#facebook ._-kb div {
		font-family: inherit;
	}

	#facebook ._-kb div {
		font-family: inherit;
	}

	#facebook ._-kb div {
		font-family: inherit;
	}

	#facebook ._-kb div {
		font-family: inherit;
	}

	._3p8r {
		-webkit-font-smoothing: antialiased;
	}

	#facebook ._-kb div {
		font-family: inherit;
	}

	#facebook ._-kb div {
		font-family: inherit;
	}

	#facebook ._-kb div {
		font-family: inherit;
	}

	body, button, input, label, select, td, textarea {
		font-family: Helvetica, Arial, sans-serif;
		font-size: 12px;
	}

	body {
		background: #fff;
		color: #1d2129;
		direction: ltr;
		line-height: 1.34;
		margin: 0;
		padding: 0;
		unicode-bidi: embed;
	}

	._2yq ._4rkc ._1htl::before {
		border-radius: 0 0 3px 3px;
	}

	._2yq._2ltu ._4-u2:before {
		border: 1px solid #dddfe2;
	}

	._2yq ._4-u2::before {
		border: 1px solid;
		border-color: #e5e6e9 #dfe0e4 #d0d1d5;
		border-radius: 4px;
		bottom: -1px;
		content: '';
		left: -1px;
		pointer-events: none;
		position: absolute;
		right: -1px;
		top: -1px;
	}

	._3c6v {
		padding: 12px;
	}

	._1htl ._50zm {
		overflow: visible;
	}

	._50zm {
		overflow: hidden;
		position: relative;
	}

	._9bp ._50zn {
		clear: both;
	}

	._50zn {
		overflow: visible;
		position: absolute;
	}

	.clearfix {
		zoom: 1;
	}

	._9bp ._3el8 {
		float: left;
	}

	._3c6v ._3el6 {
		margin-right: 8px;
	}

	._3el6 {
		display: inline-block;
		vertical-align: top;
	}

	._3c6v ._3el6 ._3c6x {
		position: relative;
	}

	._3c6v ._3el6 ._3c6w {
		border-radius: 3px;
		-webkit-filter: brightness(70%);
	}

	.uiScaledImageContainer {
		position: relative;
		overflow: hidden;
	}

	.uiScaledImageContainer img {
		height: 100%;
		min-height: 100%;
		position: relative;
	}

	.uiScaledImageContainer img {
		height: 100%;
		min-height: 100%;
		position: relative;
	}

	._3c6v ._3el6 ._44y- {
		align-items: center;
		display: flex;
		height: 100%;
		position: absolute;
		top: 0;
		width: 100%;
	}

	._3c6v ._3el6 ._3c6_ {
		color: #fff;
		font-size: 14px;
		font-weight: bold;
		line-height: 18px;
		text-align: center;
		text-shadow: 0 1px rgba(0, 0, 0, .5);
		width: 100%;
	}
</style>