<div class="box">
	<div class="title"><?php echo lang("livestream::livestreams") ?></div>
	<div id="livestreams-list-container" class="box-content clearfix list-listing-container">
		<?php foreach($livestreams->results() as $livestream): ?>
			<?php echo view('livestream::list_item', array('livestream' => $livestream)) ?>
		<?php endforeach ?>
	</div>
	<?php if($livestreams->total): ?>
		<div class="box-content">
			<?php echo $livestreams->append(array('c' => input('c'), 's' => input('s')))->links(); ?>
		</div>
	<?php else: ?>
		<div class="box-content">
			<div class="alert alert-info"><?php echo lang('livestream::no-livestreams-found-here') ?></div>
		</div>
	<?php endif ?>
</div>