<div class="img-circle-wrapper">
    <div class="img-circle-wrapper-cover-to-content">
        <a href="<?php echo profile_url(null, $user); ?>" ajax="true">
            <img class="img-circle img-user-birth" src="<?php echo get_avatar(200, $user) ?>"/>
        </a>
        <span class="birth-name"><a href="<?php echo profile_url(null, $user); ?>" ajax="true"
                                    title="<?php echo get_user_name($user); ?>"><?php echo str_limit(get_user_name($user), 20); ?></a></span>
        <?php if ($user['birth_day'] && $user['birth_month']): ?>
            <span class="birth-icon-and-date"><span class="">
                            <img src="<?php echo img("birthday::image/c.jpeg") ?>"
                                 class="cake-icon"/> </span>
                        <?php echo ltrim($user['birth_day'], 0) ?> <?php echo ucwords($user['birth_month']); ?> </span>

        <?php endif; ?>



        <?php if (plugin_loaded('relationship')): ?>
            <div class="friend-btn-birth">
                <?php echo view('relationship::button', array('userid' => $user['id'])) ?>
            </div>
        <?php endif ?>
    </div>
</div>