 <div class="modal-form-header">
     <button type="button" class="close" data-dismiss="modal">&times;</button>
     <p class="modal-title"><?php echo lang('feed::share-on-friend-timeline') ?></p>
 </div>
 <div class="modal-body">
     <div class="row">
         <div class="col-md-12">
             <?php echo view('feed::page', array('feed' => $feed))?>
         </div>
     </div>
     <div class="row">
         <div class="col-md-12 friends">
             <div class="row">
                 <div class="col-md-12">
                     <div class="feed-search-friends-wrapper" style="margin: 14px">
                         <input type="text" placeholder="<?php echo lang('search') ?>" data-result="#chat-group-modal .online-friend-list"/>
                     </div>
                 </div>
             </div>
             <div class="row online-lists slimscroll" data-height="280px">
                 <div class="col-md-12 online-friend-list">
                     <?php $users = array_merge(get_few_offlines(), chat_get_onlines()); ?>
                     <?php if(count($users) > 0): ?>
                         <?php foreach($users as $user): ?>
                            <div class="row" id="feed-send-user-message-<?php echo $user['id']?>">
                                <div class="col-md-6">
                                    <a onclick=" re"  href="">
                                        <div class="media media-sm">
                                            <div class="media-left">
                                                <div class="media-object">
                                                    <img src="<?php echo get_avatar(75, $user) ?>"/>
                                                </div>
                                            </div>
                                            <div class="media-body">
                                                <h6 class="media-heading"><?php echo get_user_name($user) ?></h6>
                                            </div>
                                        </div>
                                    </a>
                                </div>

                                <div style="border-left: 1px green solid;" class="col-md-4 selected">

                                </div>
                            </div>
                         <?php endforeach; ?>
                     <div class="box">
                         <div class="box-content pull-right">
                             <a class="btn btn-primary">Share</a>
                         </div>
                     </div>
                     <?php else: ?>
                         <div><?php echo lang('chat::no-friends-online') ?></div>
                     <?php endif ?>
                 </div>
             </div>
         </div>
     </div>
 </div>
