<div class="wrapper">
    <div class="wrapper-title clearfix">
        <?php echo lang('creditgift::credit-sale-plan') ?>
        <button type="button" class="btn btn-info" data-toggle="modal" data-target="#addPlan" style="float: right;"><?php echo lang('creditgift::add-plan') ?></button>
    </div>
    <div class="wrapper-content">
        <div class="row list-table-select-actions hide" data-group="users">
            <div class="col-sm-12">
                <a href="<?php echo url_to_pager('admin-creditgift-batch-action') ?>?action=delete_plan"
                   class="action-link list-table-select-action" data-group="users"><?php echo lang('delete') ?></a>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-responsive list-table">
                <tr>
                    <th>
                        <div class="list-table-select" data-group="users" data-id="0"></div>
                    </th>
                    <th><?php echo lang('creditgift::unit') ?></th>
                    <th><?php echo lang('creditgift::description') ?></th>
                    <th><?php echo lang('creditgift::cost') ?></th>
                    <th><?php echo lang('creditgift::action') ?></th>
                </tr>
                <?php foreach ($plans->results() as $plan): ?>
                    <tr>
                        <td>
                            <div class="list-table-select" data-group="users"
                                 data-id="<?php echo $plan['id'] ?>"></div>
                        </td>
                        <td><?php echo $plan['unit']; ?></td>
                        <td><?php echo $plan['description']; ?></td>
                        <td><?php echo $plan['cost']; ?></td>
                        <td>
                            <div class="dropdown actions">
                                <a href="#" data-toggle="dropdown">
                                    <i class="ion-android-settings"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a class="ion-edit" href='<?php echo url_to_pager('admincp-editplan') ?>?action=edit&id=<?php echo $plan['id'] ?>'></a>
                                    <a class="admin-confirm ion-android-delete" href="<?php echo url_to_pager('admincp-editplan') ?>?action=delete&id=<?php echo $plan['id'] ?>"></a>
                                </div>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
    <?php echo $plans->links(); ?>
</div>
<!-- Modal -->
<div id="addPlan" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <form enctype="multipart/form-data" action="" method="post" class="form-control">
                <div class="modal-header">
                    <h4 class="modal-title"><?php echo lang('creditgift::add-plan') ?></h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                </div>
                <div>
                    <label><?php echo lang('creditgift::unit') ?>:</label>
                    <input id="inputsm" class="form-control" type="number" name="val[unit]" required="">
                </div>
                <div>
                    <label><?php echo lang('creditgift::description') ?>:</label>
                    <input id="inputsm" class="form-control input-sm" type="text" name="val[description]" required="">
                </div>
                <div>
                    <label><?php echo lang('creditgift::cost') ?>:</label>
                    <input id="inputsm" class="form-control input-sm" type="number" name="val[cost]" required="">
                </div>
                <br />
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success"><?php echo lang('add') ?></button>
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo lang('close') ?></button>
                </div>
            </form>
        </div>
    </div>
</div>
