<div data-success="<?php echo lang('report::report-success') ?>" data-error="<?php echo lang('unknown-error') ?>" id="reportModal" class="modal fade " tabindex="-1" role="dialog" aria-labelledby="myLikesModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title"><?php echo lang('report::report-content') ?></h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
					<span class="sr-only"><?php echo lang('close') ?></span>
				</button>
			</div>
			<form action="" method="post">
				<?php CSRFProtection::embed() ?>
				<div class="modal-body">
					<input type="hidden" name="val[link]" class="link"/>
					<input type="hidden" name="val[type]" class="type"/>
                    <?php fire_hook("report.modal.options") ?>
					<textarea class="auto-grow-input form-control" data-height="90px" name="val[reason]" placeholder="<?php echo lang('report::report-reason') ?>"></textarea>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal"><?php echo lang('cancel') ?></button>
					<button class="btn btn-primary"><?php echo lang('report::report') ?></button>
				</div>
			</form>
		</div>
	</div>
</div>