<div class="wrapper">
    <div class="wrapper-title"><?php echo lang('themes') ?></div>
    <div class="wrapper-content">
        <div class="list-table-container">
            <div class="table-responsive">
                <table class="table list-table">
            <thead>
            <tr>
                <th><?php echo lang('preview') ?></th>
                <th><?php echo lang('name') ?></th>
                <th><?php echo lang('author') ?></th>
                <th><?php echo lang('description') ?></th>
                <th><?php echo lang('version') ?></th>
                <th><?php echo lang('action') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach (get_all_themes() as $theme => $details): ?>
                <tr>
                    <td>
                        <img style="width: 150px" src="<?php echo $details['preview'] ?>"/>
                    </td>
                    <td><?php echo $details['info']['name'] ?></td>
                    <td><?php echo $details['info']['author'] ?></td>
                    <td><?php echo $details['info']['description'] ?></td>
                    <td><?php echo $details['info']['version'] ?></td>
                    <td>
                        <?php if (get_active_theme() == $theme): ?>
                            <button disabled class="btn btn-sm btn-success"><?php echo lang('active') ?></button>
                        <?php else: ?>
                            <a class="btn btn-sm btn-success"
                               href="<?php echo url_to_pager("admin-themes") ?>?action=activate&theme=<?php echo $theme ?>"><?php echo lang('set-as-active') ?></a>
                        <?php endif ?>

                        <a class="btn btn-sm btn-info"
                           href="<?php echo url_to_pager('admin-customize-themes', array('theme' => $theme)) ?>"><i
                                    class="ion-edit"></i> <?php echo lang('customize') ?>
                        </a>
                    </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
            </div>
        </div>
    </div>
</div>