<div class="wrapper">
	<div class="wrapper-title">
		<?php echo lang('group::edit-category') ?>
	</div>
	<div class="wrapper-content">
		<form class="wrapper-form" method="post" action="" enctype="multipart/form-data">
			<?php CSRFProtection::embed() ?>
			<div class="form-group row">
				<label class="col-sm-3 form-control-label"><?php echo lang('group::category-title') ?></label>
				<div class="col-sm-9">
					<label>(English)</label>
					<input type="text" name="val[title][english]" value="<?php echo get_phrase('english', $category['title']) ?>" class="form-control" placeholder="<?php echo lang('group::category-title') ?>"/>
					<a href="" class="other-languages-link" onclick="return show_other_languages('#group-category-info-other-languages')"><?php echo lang('edit-other-languages') ?></a>
					<div class="other-languages" id="group-category-info-other-languages">
						<?php foreach(get_all_languages() as $language): ?>
							<?php if($language['language_id'] != 'english'): ?>
								<input class="form-control" value="<?php echo get_phrase($language['language_id'], $category['title']) ?>" type="text" name="val[title][<?php echo $language['language_id'] ?>]" placeholder="<?php echo lang('group::category-title') ?>"/>
								<br>
								<p class="help-block"><?php echo $language['language_title'] ?></p>
							<?php endif ?>
						<?php endforeach ?>
					</div>
				</div>
			</div>
			<div class="row form-group">
				<label class="col-sm-3 form-control-label"> </label>
				<div class="col-sm-9">
					<input type="file" name="image" class="form-control">
				</div>
			</div>
			<button class="btn btn-info"><?php echo lang('save-category') ?></button>
		</form>
	</div>
</div>