<div class="box video">
	<div class="global-filter-container" data-url="<?php echo url('videos') ?>">
		<form id="video-list-search" method="post" onsubmit="return run_global_filter()" action="" class="form-inline list-search">
			<?php CSRFProtection::embed() ?>
			<input type="hidden" class="filter-input form-control" data-name="type" value="<?php echo input('type', 'browse') ?>"/>
			<i class="search-icon ion-ios-search"></i>
			<input value="<?php echo input('term') ?>" type="text" class="form-control search-box filter-input" data-name="term" placeholder="<?php echo lang('search') ?>"/>
		</form>
		<div class="list-head">
			<h3 class="heading"><?php echo lang('video::videos') ?></h3>
		</div>
		<div class="filter-pane">
			<select id="video-category-list" onchange="return run_global_filter()" data-name="category" class="c-select filter-input">
				<option <?php echo (input('category', 'all') == 'all') ? 'selected' : null ?> value="all"><?php echo lang('video::all-categories') ?></option>
				<?php foreach(get_video_categories() as $category): ?>
					<?php $subCategories = get_video_parent_categories($category['id']) ?>
					<?php if($subCategories): ?>
						<optgroup label="<?php echo lang($category['title']) ?>">
							<?php foreach($subCategories as $cat): ?>
								<option <?php echo (input('category', 'all') == $cat['id']) ? 'selected' : null ?> value="<?php echo $cat['id'] ?>"><?php echo lang($cat['title']) ?></option>
							<?php endforeach ?>
						</optgroup>
					<?php else: ?>
						<option <?php echo (input('category', 'all') == $category['id']) ? 'selected' : null ?> value="<?php echo $category['id'] ?>"><?php echo lang($category['title']) ?></option>
					<?php endif ?>
				<?php endforeach ?>
			</select>
			<select id="video-filter-select" onchange="return run_global_filter()" data-name="filter" class="c-select filter-input">
				<option value="all"><?php echo lang('all') ?></option>
				<option <?php echo (input('filter') == 'top') ? 'selected' : null ?> value="top"><?php echo lang('video::top') ?></option>
				<option <?php echo (input('filter') == 'featured') ? 'selected' : null ?> value="featured"><?php echo lang('video::featured') ?></option>
			</select>
            <div class="list-layout-type">
                <a href="" onclick="return change_listing_layout('#videos-list-container', 'list', 'video')"><i class="ion-ios-list-outline"></i></a>
                <a href="" onclick="return change_listing_layout('#videos-list-container', 'grid', 'video')"><i class="ion-android-apps"></i></a>
            </div>
		</div>
	</div>
	<div id="videos-list-container" class="box-content clearfix <?php echo ($list_type == 'list') ? 'list-listing-container' : 'grid-listing-container' ?>">
		<?php foreach($videos->results() as $video): ?>
			<?php echo view('video::video', array('video' => $video)) ?>
		<?php endforeach ?>
	</div>
	<?php if($videos->total): ?>
		<div class="box-content">
			<?php $appends = array(); ?>
			<?php if(input('category')) $appends['category'] = input('category'); ?>
			<?php if(input('term')) $appends['term'] = input('term'); ?>
			<?php if(input('type')) $appends['type'] = input('type'); ?>
			<?php echo $videos->append($appends)->links(); ?>
		</div>
	<?php else: ?>
		<div class="box-content">
			<div class="alert alert-info"><?php echo lang('video::no-videos-found-here') ?></div>
		</div>
	<?php endif ?>
</div>