<?php
$ed = Educational::getInstance();
$books = $ed->getTopDownloads($limit);
?>

<?php if ($books->total): ?>
    <div class="box">
        <div class="title">
            <?php _lang('educational::top-downloads-books'); ?>
            <a ajax="true" href="<?php echo url('books?filter=downloads') ?>"><i
                    class="ion-ios-arrow-forward pull-right"></i></a>
        </div>
        <div class="box-content">
            <?php foreach ($books->results() as $book):
                //print_r($book);
                $user = find_user($book['user_id'])?>
                <?php echo view("educational::widget/gen",array('user'=>$user,'book'=>$book,'ed'=>$ed)); ?>
            <?php endforeach ?>
        </div>
    </div>
<?php endif ?>