<div class="wrapper store-container">
    <div class="wrapper-title">
        <?php _lang('store::edit-seller'); ?>
    </div>
    <div class="wrapper-content" style="padding: 20px 10%">

        <?php if($message): ?>
            <div class="alert alert-danger"><?php echo $message ?></div>
        <?php endif; ?>

        <form action="" method="post" enctype="multipart/form-data">
            <?php CSRFProtection::embed()?>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::store-name')?><span class="important">*</span></label>
                <div class="col-sm-8">
                    <input value="<?php echo ($seller['name'])? $seller['name'] : input('val.name')?>" type="text" name="val[name]" class="form-control"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::location')?><span class="important">*</span></label>
                <div class="col-sm-8">
                    <select class="c-select" name="val[location]">
                        <option><?php _lang('select-country')?></option>
                        <?php load_functions("country"); ?>
                        <?php foreach(get_countries() as $country => $name):?>
                            <option <?php echo (input("val.location") == $name) || $seller['location']==$name ? "selected" : null?> value="<?php echo $name?>"><?php echo ucwords($name)?></option>
                        <?php endforeach?>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::desc')?><span class="important">*</span></label>
                <div class="col-sm-8">
                    <textarea name="val[desc]" class="ckeditor"><?php echo ($seller['describ'])? $seller['describ'] : input('val.desc')?></textarea>
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::cover-picture')?><span class="important">*</span></label>
                <div class="col-sm-8">
                    <?php if($seller['image']):  ?>
                        <img src="<?php echo url_img($seller['image'],200) ?>" class="img img-responsive" style="width: 30px;height: 30px" />
                    <?php endif; ?>
                    <input type="file" name="image[]" class="form-control"/>
                </div>
            </div>
            <?php echo fire_hook("more.store.input.fields",null,array($seller)); ?>
            <div class="divider"></div>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::contact-name')?><span class="important">*</span></label>
                <div class="col-sm-8">
                    <input value="<?php echo ($seller['cname'])? $seller['cname'] : input('val.cname')?>" type="text" name="val[cname]" class="form-control"/>

                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::email-address')?></label>
                <div class="col-sm-8">
                    <input value="<?php echo ($seller['email'])? $seller['email'] : input('val.email')?>" type="text" name="val[email]" class="form-control"/>
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::address')?></label>
                <div class="col-sm-8">
                    <input value="<?php echo ($seller['address'])? $seller['address'] : input('val.address')?>" type="text" name="val[address]" class="form-control"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::phone')?></label>
                <div class="col-sm-8">
                    <input value="<?php echo ($seller['phone'])? $seller['phone'] : input('val.phone')?>" type="text" name="val[phone]" class="form-control"/>
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::website')?></label>
                <div class="col-sm-8">
                    <input value="<?php echo ($seller['website'])? urldecode($seller['website']) : input('val.website')?>" type="text" name="val[website]" class="form-control"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php echo  lang('paypal-corporate-email');?></label>
                <div class="col-sm-8">
                    <input value="<?php echo ($seller['corporate_email'])? $seller['corporate_email'] : input('val.corporate_email')?>" type="text" name="val[corporate_email]" class="form-control"/>
                </div>
            </div>

            <!--<div class="form-group row">
                <label class="control-label col-sm-4"><?php /*_lang('store::enable-paypal')*/?></label>
                <div class="col-sm-8">
                    <select name="val[enable_paypal]" class="form-control c-select">
                        <option value="0"><?php /*_lang('store::no'); */?></option>
                        <option value="1"><?php /*_lang('store::yes'); */?></option>
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-sm-4"><?php /*_lang('store::paypal-username')*/?></label>
                <div class="col-sm-8">
                    <input value="<?php /*echo ($seller['paypal_username'])? $seller['paypal_username'] : input('val.paypal_username')*/?>" type="text" name="val[paypal_username]" class="form-control"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php /*_lang('store::paypal-password')*/?></label>
                <div class="col-sm-8">
                    <input value="<?php /*echo ($seller['paypal_password'])? $seller['paypal_password'] : input('val.paypal_password')*/?>" type="text" name="val[paypal_password]" class="form-control"/>
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-sm-4"><?php /*_lang('store::paypal-signature')*/?></label>
                <div class="col-sm-8">
                    <input value="<?php /*echo ($seller['paypal_signature'])? $seller['paypal_signature'] : input('val.paypal_signature')*/?>" type="text" name="val[paypal_signature]" class="form-control"/>
                </div>
            </div>-->
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::feature-store')?></label>
                <div class="col-sm-8">
                    <select name="val[featured]" class="form-control c-select">
                        <option <?php echo (!$seller['featured']) ? 'selected' : '' ?> value="0"><?php _lang('store::no'); ?></option>
                        <option <?php echo ($seller['featured']) ? 'selected' : '' ?> value="1"><?php _lang('store::yes'); ?></option>
                    </select>
                </div>
            </div>
            <input type="hidden" value="<?php echo $seller['s_id']; ?>" name="val[store_id]" />
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::status')?></label>
                <div class="col-sm-8">
                    <select name="val[status]" class="form-control c-select">
                        <option <?php echo (!$seller['status']) ? 'selected' : '' ?> value="0"><?php _lang('store::not-approved'); ?></option>
                        <option <?php echo ($seller['status']) ? 'selected' : '' ?> value="1"><?php _lang('store::approved'); ?></option>
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-sm-4"><?php echo ucwords(lang('store::verified')); ?></label>
                <div class="col-sm-8">
                    <select name="val[verified]" class="form-control c-select">
                        <option <?php echo (!$seller['verified']) ? 'selected' : '' ?> value="0"><?php _lang('store::not-verified'); ?></option>
                        <option <?php echo ($seller['verified']) ? 'selected' : '' ?> value="1"><?php _lang('store::verified'); ?></option>
                    </select>
                </div>
            </div>
            <br/>
            <div class="form-group row">
                <div class="col-sm-5">
                </div>
                <div class="col-sm-4">
                    <div class="input-field col s12">
                        <input type="submit" value="<?php echo lang('store::save') ?>" class="btn btn-info btn-sm" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>