<div style="margin:5px"><strong><?php echo lang("store::have-a-coupon").' '; ?><a href="" id="couponSlide"><?php echo lang("store::click-to-add-coupon") ?></a> </strong></div>
<div class="coupon-box">
    <div class="input-group">
        <div class="indicator"><img src="<?php echo img('images/loading.gif')?>"/></div>
        <input type="text" class="form-control" id="couponCode" placeholder="<?php echo lang("store::coupon-code") ?>">
                  <span class="input-group-btn">
                    <button class="btn btn-info btn-info" id="submitCouponCode" type="button"><?php echo lang('store::apply-coupon') ?></button>
                  </span>
    </div><!-- /input-group -->
</div>