<div class="wrapper">
	<div class="wrapper-title">
		<?php echo lang('contest::start-a-contest') ?>

	</div>
	<div class="wrapper-content">

		<form class="wrapper-form wrapper-admin-form-admincp" action="" enctype="multipart/form-data" method="post">
			<?php CSRFProtection::embed() ?>
			<?php if($message): ?>
				<div class="alert alert-danger"><?php echo $message ?></div>
			<?php endif ?>
            <input type="hidden" name="val[entity]" value="user-<?php echo get_userid() ?>" />
            <?php echo view("contest::contest-form-fields",array('admin'=>'yes')); ?>

			<button class="btn btn-info" style="margin-top: 20px"><?php echo lang("contest::publish-contest") ?></button>
		</form>

	</div>
</div>