<?php if($users->total): ?>
	<div class="box">
		<div class="title"><?php echo lang('search::people') ?></div>
		<div class="search-users-result box-content">
			<?php foreach($users->results() as $user): ?>

				<?php echo view('user/display', array('user' => $user)) ?>
			<?php endforeach ?>


		</div>
		<a href="<?php echo form_search_link('user', $term) ?>">
			<div class="title" style="text-align: center"><?php echo lang('search::more-results') ?></div>
		</a>
	</div>
<?php endif ?>

	<h5><?php echo lang('search::results-from-posts') ?></h5>

	<div id="feed-lists" data-type="search" data-type-id="<?php echo $term ?>" data-offset="0" style="margin-top: 0">
		<?php $i = 0;
		foreach($feeds as $feed):fire_hook('feed.lists.inline', null, array($i));
			$i++ ?>
			<?php echo view('feed::feed', array('feed' => $feed)) ?>
		<?php endforeach ?>


	</div>

<?php if(count($feeds)): ?>
	<div class="feed-load-more">
		<div class="col-sm-2 no-padding"></div>
		<div class="col-sm-10 no-padding">
			<div class="feed-loading">
				<div class="feed_loading_post">
					<div class="feed_loading_post_child2">

					</div>
				</div>
			</div>
		</div>
	</div>
<?php endif ?>