<?php $rator = find_user($business['rator_id']) ?>
<div id="notification-<?php echo $notification['notification_id'] ?>" class="notification media media-md  <?php echo ($notification['mark_read'] == 0) ? 'notification-unread' : null ?>">
	<div class="media-left">
		<div class="media-object">
			<a ajax="true" href="<?php echo url_to_pager('view-business') ?>?business=<?php echo $business['id'] ?>"><img src="<?php echo get_avatar(75, $rator) ?>"/></a>
		</div>
	</div>
	<div class="media-body">
		<a ajax="true" href="<?php echo url_to_pager('view-business') ?>?business=<?php echo $business['id'] ?>">
			<h6 class="media-heading">
				<?php echo get_user_name($rator) ?>
				<?php echo lang('business::rated-your-business') ?>: <?php echo $business['rate'] ?>
			</h6>
			<?php if($notification['content']): ?>
				<span class="help-block">"<?php echo strip_tags(preg_replace('/<br>.*/', '', output_text(str_limit($notification['content'], 50)))) ?>"</span>
			<?php endif ?>
		</a>
		<span style="display: block" class="timeago" title="<?php echo date('c', $notification['time']) ?>"><?php echo date('c', $notification['time']) ?></span>
		<div class="actions">
			<a
					class="mark-button"
					data-status="<?php echo $notification['mark_read'] ?>"
					data-read="<?php echo lang('notification::read') ?>"
					data-mark="<?php echo lang('notification::mark-as-read') ?>"
					title="<?php echo ($notification['mark_read'] == 1) ? lang('notification::read') : lang('notification::mark-as-read') ?> "
					onclick="return notification.markRead('<?php echo $notification['notification_id'] ?>')"
					href="#!"><i class="ion-checkmark-circled"></i></a>
			<a onclick="return notification.delete('<?php echo $notification['notification_id'] ?>')" href="#!"><i class="ion-close"></i></a>
		</div>
	</div>
</div>