<?php
$don = Donation::getInstance();
$donations = $don->getDonations('featured',null,null);
if(!is_array($donations)){
    $donations = $donations->results();
}
if(count($donations) > 0):?>
<div class="box">
    <div class="title"><?php echo lang("donation::featured").' '.lang("donation::campaigns");?></div>
    <div class="box-content">
        <?php foreach($donations as $donation): ?>
             <?php echo view("donation::iframe/content",array('id'=>$donation['id'],'featured'=>1)); ?>
            <hr/>
        <?php endforeach; ?>
     </div>
</div>
<?php endif; ?>
