<div class="box">
    <div  class="title"><?php echo lang("donation::categories"); ?></div>
    <div class="box-content">
        <ul class="menu">
            <?php $don = Donation::getInstance(); ?>
            <?php foreach($don->get_categories() as $category): ?>
            <li><a href="<?php echo url('donations')?>" ajax="true" ><?php echo lang($category['title']); ?></a></li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>