<div class="livestream-wrapper">
    <div id="livestream-modal" class="livestream-modal modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-form-header">
                    <button type="button" class="close">&times;</button>
                    <p class="modal-title pull-left"></p>
                </div>
                <div class="modal-body livestream-content main">
                </div>
            </div>
        </div>
    </div>
</div>
