<div id="photos-list-container" class="box box-content clearfix list-listing-container">
	<div class="global-filter-container" data-url="">
		<div class="row">
			<div class="col-sm-6">
				<h3><?php echo lang('photo::photos') ?></h3>
			</div>
			<!--
            <div class="col-sm-6">
                <form id="photo-list-search" method="post" onsubmit=" return run_global_filter()" action="" class="form-inline pull-right">
					<?php CSRFProtection::embed() ?>
                    <input type="hidden" class="photo-type-input filter-input" data-name="type" value="<?php echo input('type', 'browse') ?>"/>
                    <input value="<?php echo input('term') ?>" type="text" class="form-control filter-input" data-name="term" placeholder="<?php echo lang('photo::search-photos') ?>"/>
                    <button class="btn btn-info"><i class="ion-search"></i></button>
                </form>
            </div>
            -->
		</div>
	</div>
	<div id="photos-list" class="photos-list photo-directory" data-type="all" data-offset="0" style="margin: 0px;box-shadow: 0px 0px 0px #FFFFFF;border-radius: 0px;border: none;">
		<?php if(is_loggedIn()): ?>
			<div class="photo upload-photo">
                <div class="local">
                    <form data-error="Something went wrong. try again" action="" method="post" enctype="multipart/form-data">
                        <?php CSRFProtection::embed() ?>
                        <span class="file-input"><input onchange="upload_photos()" multiple type="file" accept="image/*" id="photo-upload-input" name="photos[]" style="position: absolute; cursor:pointer; width: 100%; height: 100%; opacity: 0; z-index: 10; display: none"/></span>
                        <a onclick="return file_chooser('#photo-upload-input')" href=""><i class="ion-ios-cloud-upload-outline"></i><span><?php echo lang('photo::click-or-drag-photo') ?></span></a>
                    </form>
                    <div class="indicator">
                        <img src="<?php echo img('images/loading.gif') ?>"/> <?php echo lang('photo::uploading') ?>
                        <span>0%</span>
                    </div>
                </div>
                <div class="remote">
                    <div data-toggle="modal" data-target="#photo-modal">
                        <i id="urlLink" class="ion-android-upload"></i><span>
                    </div>
                </div>
			</div>
		<?php endif ?>
		<?php foreach($photos as $photo): ?>
			<?php $user = find_user($photo['user_id']); $username = $user['username']; $first_name = $user['first_name']; $last_name = $user['last_name']; $user_name = "$first_name $last_name"; $user_name = trim($user_name) == '' ? $username : $user_name; ?>
			<div class="photo">
				<a data-image="<?php echo url_img($photo['path'], 920) ?>" data-id="<?php echo $photo['id'] ?>" class="image photo-viewer" style="background-image:url(<?php echo url_img($photo['path'], 600) ?>)" href=""></a>
			</div>
		<?php endforeach ?>
	</div>
	<a id="photos-list-indicator" href="" onclick="return paginate_album_photos()" class="title" style="display: block;text-align: center"><?php echo lang('view-more') ?>
		<img src="<?php echo img('images/loading.gif') ?>" style="width: 10px;display: none"/></a>
</div>

<div class="modal modal-photo" tabindex="-1" role="dialog" id="photo-modal" aria-hidden="true" aria-labelledby="photo">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="modal-title"><?php echo lang("photo::url-image-upload") ?></h4>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<div class="photo-modal-error"></div>
				<div class="indicatorUrl" style="display: none">
					<img src="<?php echo img('images/loading.gif') ?>"/> <?php echo lang('photo::uploading') ?>
					<span>0%</span>
				</div>
				<div class="indicatorUrlFilter" style="display: none">
					<?php echo lang('photo::initiating-filter') ?>
				</div>
				<div class="form-group">
					<input name="urlLink" id="urlLink" class="form-control urlLink" type="text" placeholder="<?php echo lang('photo::url-image-upload') ?>"/>
				</div>
				<div class="form-group">
					<button onclick="return uploadUrlImage()" id="urlLinkButton" class="form-control btn btn-primary urlLinkButton" type="submit"> Upload</button>
				</div>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div>