<?php if(isset(app()->profilePage)): ?>
	<div class="box">
		<div class="box-content" style="font-size: 15px;padding: 10px">
			<?php if(plugin_loaded('like')): ?>
				<a onclick="return show_likes('page', '<?php echo app()->profilePage['page_id'] ?>')" href="">
					<i class="fa fa-thumbs-o-up"></i>
					<span class="like-count-page-<?php echo $app->profilePage['page_id'] ?>"><?php echo count_likes('page', $app->profilePage['page_id']) ?></span>
				</a> <?php echo lang('like::people-like-this') ?>
			<?php endif ?>
		</div>
	</div>
	<!--latest likes custom starts-->
		<div class="box page-analytics-box">
				<?php if(plugin_loaded('like')): ?>
					<div class="title"><?php echo lang('Page Likes Analytics') ?></div>
					<ul class="menu">
						<li>
							<span class="left"><?php echo lang('This Year') ?></span><a onclick="return show_page_likes('page', '<?php echo app()->profilePage['page_id'] ?>', 'year')" href=""><span class="right"><?php echo count_page_likes('page', $app->profilePage['page_id'], 'year') ?></span></a>
						</li>
						<li>
							<span class="left"><?php echo lang('This Month') ?></span><a onclick="return show_page_likes('page', '<?php echo app()->profilePage['page_id'] ?>', 'month')" href=""><span class="right"><?php echo count_page_likes('page', $app->profilePage['page_id'], 'month') ?></span></a>
						</li>
						<li>
							<span class="left"><?php echo lang('This Week') ?></span><a onclick="return show_page_likes('page', '<?php echo app()->profilePage['page_id'] ?>', 'week')" href=""><span class="right"><?php echo count_page_likes('page', $app->profilePage['page_id'], 'week') ?></span></a>
						</li>
						<li>
							<span class="left"><?php echo lang('Today') ?></span><a onclick="return show_page_likes('page', '<?php echo app()->profilePage['page_id'] ?>', 'today')" href=""><span class="right"><?php echo count_page_likes('page', $app->profilePage['page_id'], 'today') ?></span></a>
						</li>
					</ul>
				<?php endif ?>
		</div>
	<!--latest likes custom ends-->
	<div class="box ">
		<div class="title"><?php echo lang('about') ?>
			<a href="<?php echo page_url('about', app()->profilePage) ?>" class="more-link pull-right"><i class="ion-ios-arrow-forward"></i></a>
		</div>

		<ul id="profile-side-info">
			<li>
				<span><i class="ion-ios-list-outline"></i> <?php echo lang('page::category') ?>:</span> <?php echo get_page_category_title(get_page_details('page_category_id')) ?>
			</li>
			<li>
				<span><i class="ion-ios-information-outline"></i> <?php echo lang('page::about') ?>:</span> <?php echo output_text(app()->profilePage['page_desc']) ?>
			</li>
            <?php fire_hook('page.more.info', app()->profilePage)?>
			<?php $i = 0;
			foreach(get_all_custom_fields('page') as $field): ?>
				<?php if($i <= 3 and get_page_details($field['title'], app()->profilePage)): ?>
					<li>
						<span><i class="ion-ios-information-outline"></i> <?php echo lang($field['title']) ?>:</span> <?php echo output_text(get_page_details($field['title'], $app->profilePage)) ?>
					</li>
				<?php else:break;endif ?>
				<?php $i++; endforeach ?>
		</ul>
	</div>
<?php endif ?>