<div class="box">
    <?php $edu = Educational::getInstance(); ?>
    <div class="box-content">
        <form class="form" action="<?php echo url('books') ?>">
            <div class="form-group">
                <label><?php echo lang("educational::search"); ?></label>
                <input type="text" class="form-control" placeholder="<?php _lang('educational::search-books')?>" name="term" value="<?php echo input('term'); ?>" />
            </div>
            <div class="form-group">
                <label><?php echo lang("educational::browse-type"); ?></label>
                <select class="form-control" name="type" >
                    <option <?php echo (input('type') == 'all') ? 'selected' : '';  ?> value="all"><?php echo lang("all"); ?></option>
                    <option <?php echo (input('type') == 'mine') ? 'selected' : '';  ?> value="mine"><?php echo lang("educational::mine"); ?></option>
                </select>
            </div>
            <div class="form-group">
                <label><?php echo ucwords(lang("educational::genre")); ?></label>
                <input type="text" class="form-control" name="genre" value="<?php echo input('genre'); ?>" />
            </div>
            <div class="form-group">
                <label><?php echo ucwords(lang("educational::author")); ?></label>
                <input type="text" class="form-control" name="author" value="<?php echo input('author'); ?>" />
            </div>
            <div class="form-group">
                <select class="form-control" name="category" >
                    <option <?php echo (input('category', 'all') == 'all') ? 'selected'  : null?>  value="all"><?php _lang('educational::all-categories')?></option>
                    <?php foreach($edu->get_categories() as $category):?>
                        <option <?php echo (input('category', 'all') == $category['id']) ? 'selected'  : null?> value="<?php echo $category['id']?>"><?php _lang($category['title'])?></option>
                    <?php endforeach?>
                </select>
            </div>
            <div class="form-group">
                <button class="btn btn-info" type="submit"><?php echo lang("search") ?></button>
            </div>
        </form>
    </div>
</div>