<?php $onlinetvs = get_onlinetvs(null, null, null, null, $limit, 'featured'); ?>
<?php if($onlinetvs->total): ?>
	<div class="box">
		<div class="title">
			<?php echo lang('onlinetv::featured-onlinetvs') ?>
			<a ajax="true" href="<?php echo url('onlinetvs?filter=featured') ?>"><i class="ion-ios-arrow-forward pull-right"></i></a>
		</div>
		<div class="box-content">
			<?php foreach($onlinetvs->results() as $onlinetv): ?>
				<?php $onlinetv = arrange_onlinetv($onlinetv); ?>
				<?php $user = find_user($onlinetv['user_id']) ?>
				<div class="media media-sm">
					<div class="media-left">
						<div class="media-object">
							<img src="<?php echo ($onlinetv['image']) ? url_img($onlinetv['image'], 700) : get_avatar(200, $user) ?>"/>
						</div>
					</div>
					<div class="media-body">
						<h4 class="media-heading" style="margin-top:0">
							<a ajax="true" href="<?php echo url('onlinetv/'.$onlinetv['slug']) ?>"><?php echo $onlinetv['name'] ?></a>
						</h4>
						<span class="help-block" style="display: block;font-size:12px">
                                    <?php echo lang('onlinetv::publisher') ?>: <a ajax="true" href="<?php echo url($onlinetv['publisher']['id']) ?>"><?php echo $onlinetv['publisher']['name'] ?></a>
                                    <br/><?php echo $onlinetv['views']; ?> <?php echo lang('onlinetv::views') ?>
                                </span>

					</div>
				</div>
			<?php endforeach ?>
		</div>
	</div>
<?php endif ?>