<?php echo view('layouts/menu') ?>
<div class="dashboard-content" style="padding: 0">
	<?php theme_extend('main.extend') ?>
	<!--Side bar menu-->
	<?php $enable_side_menu = (isset(app()->leftMenu) && app()->leftMenu) || (!isset(app()->leftMenu) && config('show-sidebar', true) && in_array(app()->currentColumn, array(ONE_COLUMN_LAYOUT, TWO_COLUMN_RIGHT_LAYOUT, TOP_TWO_COLUMN_RIGHT_LAYOUT, BOTTOM_TWO_COLUMN_RIGHT_LAYOUT, TOP_NO_CONTAINER_TWO_COLUMN_RIGHT_LAYOUT, TOP_ONE_COLUMN_LAYOUT))) ?>
    <?php $enable_side_menu = fire_hook("custom.enable.side.menu",array($enable_side_menu), array($enable_side_menu))[0]; ?>
	<?php if($enable_side_menu): ?>
		<div class="container">
			<div class="row">
				<div class="main-sidebar-menu col-md-2">
					<?php echo view('layouts/sidemenu'); ?>
				</div>
				<div class="col-md-10">
					<?php echo $content ?>
				</div>
			</div>
		</div>
	<?php else: ?>
		<?php echo $content ?>
	<?php endif ?>
</div>