<div class="box store-above-slide">
    <div class="store-above-slide__direct_child">
        <div class="store-top-mobile-customization">
            <div id="dashboard-filter-menu" class="clearfix">


                <div class="nop top-menu-store">


                    <div class="each-row-st-menu">
                        <a aria-expanded="false" class="btn btn-lg dropdown-toggle nav-link" data-toggle="dropdown"
                           href="<?php echo url_to_pager("comparete"); ?>">
                            <i class="ion-android-menu"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <?php if (config('enable-guest-product-purchase', 1) || is_loggedIn()): ?>
                                <li><a class="dropdown-item" href="<?php echo url_to_pager('products-home') ?>"
                                       ajax="true"><?php _lang('store::all-products') ?></a></li>
                                <li><a class="dropdown-item"
                                       href="<?php echo url_to_pager('products-categories-list') ?>"
                                       ajax="true"><?php _lang('store::products-categories') ?></a></li>
                                <li><a class="dropdown-item" href="<?php echo url('store/products?type=mine') ?>"
                                       ajax="true"><?php _lang('store::my-products') ?></a></li>
                                <li><a class="dropdown-item" href="<?php echo url_to_pager('my_orders') ?>"
                                       ajax="true"><?php _lang('store::my-orders') ?></a></li>
                                <li><a class="dropdown-item" href="<?php echo url_to_pager('my-wish-list') ?>"
                                       ajax="true"><?php _lang('store::my-wishlist') ?></a></li>
                                <li><a class="dropdown-item" href="<?php echo url('stores') ?>"
                                       ajax="true"><?php echo ucwords(lang('store::stores')); ?></a></li>

                            <?php endif ?>
                            <?php if (is_loggedIn() and user_has_permission('can-create-store') and (config('allow-members-create-store', true))): ?>
                                <li>
                                    <a ajax="true"
                                       href="<?php echo (!is_seller()) ? url_to_pager("add-seller") : url_to_pager("store-manager"); ?>"
                                       class="dropdown-item"><?php echo (!is_seller()) ? lang('store::add-store') : lang('store::manage_your-store'); ?></a>
                                </li>
                            <?php endif ?>
                        </ul>
                    </div>

                    <div class="each-row-st-menu">
                        <a class="btn btn-lg dropdown-toggle nav-link"
                           style="padding-top: 5px;padding-bottom: 5px;"
                           onclick="return toggle_view('.saf-categories-box-mobile-wrapper') "
                           href="">
                            Categories
                        </a>
                    </div>

                    <div class="cart-menu-dd store-container-menu each-row-st-menu">
                        <?php $cart = session_get('my_product_cart_' . get_userid(), array()); ?>
                        <a class="btn btn-lg cart-modal-toggle" href="<?php echo url_to_pager("comparete"); ?>"> <i
                                    class="ion-ios-cart"></i>
                            <span class="ProductCount"> <?php echo count($cart); ?></span> <?php echo lang("store::item-s") ?>
                        </a>


                    </div>
                </div>

                <!--<ul class="pull-left left">
                <li class="">
                    <a ajax="true" class="btn-bd-default" href="<?php /*echo url('stores') */ ?>"><?php /*echo lang('store::all-stores') */ ?></a>
                </li>
                <li class="">
                    <a ajax="true" class="btn-bd-default" href="<?php /*echo url_to_pager('store-manager'); */ ?>"><?php /*echo lang('store::my-stores') */ ?></a>
                </li>
                <li class="">
                    <a ajax="true" style=" border: 1px solid #16a2e4 !important;" class="btn-bd-default" href="<?php /*echo url_to_pager('add-seller') */ ?>"><?php /*echo lang('store::add-new-store') */ ?></a>
                </li>
            </ul>-->
                <br/>

                <div class="pull-right action">
                    <!--<a href="<?php /*echo url_to_pager('add-seller') */ ?>" onclick="return toggle_view('.saf-categories-box-mobile')"  class="btn btn-info btn-sm">Categories</a>-->
                    &nbsp
                </div>
                <div id="cartModal" class="modal fade" tabindex="-1" role="dialog"
                     aria-labelledby="confirmModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-md">
                        <div class="modal-content">
                            <div class="modal-body">
                                <div class="mcart-products-wraper">
                                    <?php echo view("store::products/cart-list", array('cart' => $cart)); ?>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary"
                                        data-dismiss="modal"><?php echo lang('store::continue-shopping'); ?></button>
                                <a type="button" ajax="true" href="<?php echo url_to_pager("product-cart"); ?>"
                                   class="btn btn-primary"><?php echo lang('store::checkout') ?></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- categories customization start -->
    <div class="box saf-categories-box-mobile-wrapper"
         style="left: 8%;margin-top: 0;margin-bottom: 0;border-bottom: 0;border-radius : 0;display:none;position:absolute;z-index: 9999;">
        <div class="clearfix box-content top-with-cateogory-wrapper">
            <div class="">
                <?php $count = 0; ?>
                <div class="col-sm-12">
                    <div class="row">
                        <div class="nop col-sm-12">
                            <div class="saf-categories-box-mobile" style="display: block !important;">
                                <ul class="grand-parent-category store-category-list"
                                    style="text-align: center;margin: 0!important;">
                                    <?php $categories = lp_store_categories('get_categories');
                                    foreach ($categories as $category):
                                        if ($count == 10) break;
                                        ?>
                                        <li class="parent-category storebtnfloat"
                                            data-img="<?php echo storeCategoryImage($category); ?>">
                                            <a ajax="true" class="storebtn"
                                               href="<?php echo url_to_pager('store-categories-page', array('slugs' => $category['id'])); ?>">
                                                <?php echo strtoupper(lang($category['title'])); ?>
                                            </a>
                                            <?php
                                            /*                                        $subcategories = get_store_subcategories($category['id']);
                                                                                    if ($subcategories): */
                                            ?><!--
                                            <ul class="">
                                                <?php /*foreach ($subcategories as $sb): */
                                            ?>
                                                    <li class="col-sm-3 store-sub-with-image"
                                                        data-img="<?php /*echo storeCategoryImage($sb); */
                                            ?>"><a
                                                                class="<?php /*echo (input('category') == lang($sb['title'])) ? 'active' : ''; */
                                            ?>"
                                                                ajax="true"
                                                                href="<?php /*echo url_to_pager('products-categories-home', array('slugs' => $sb['id'] . '_' . toAscii(lang($category['title'])) . '_' . toAscii(lang($sb['title'])))); */
                                            ?>"><?php /*_lang($sb['title']); */
                                            ?></a>
                                                    </li>
                                                <?php /*endforeach; */
                                            ?>
                                            </ul>
                                        --><?php /*endif; */
                                            ?>
                                        </li>
                                        <?php $count++; endforeach ?>
                                    <!--<li class="parent-category all-cat storebtnfloat"><a ajax="true" class="storebtn"
                                                                                         href="<?php /*echo url_to_pager("products-categories-list"); */?>"><?php /*echo strtoupper(lang("store::all-catgegories")); */?></a>
                                    </li>-->
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .slideshow {
        margin-top: 0 !important;
    }
</style>
