<div class="wrapper">
    <div class="wrapper-title"><?php _lang('store::add-category')?>  </div>
    <div class="wrapper-content">
        <form method="post" action="" enctype="multipart/form-data" class="wrapper-form">
            <?php CSRFProtection::embed()?>
            <?php if($message):?>
                <div class="alert alert-danger"><?php echo $message?></div>
            <?php endif?>
            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('video::category-title')?></label>
                <div class="col-sm-9">
                    <label>(English)</label>
                    <input type="text" name="val[title][english]" class="form-control" placeholder="<?php _lang('video::category-title')?>"/>
                    <a href="" class="other-languages-link" onclick="return show_other_languages('#store-category-info-other-languages')"><?php _lang('edit-other-languages')?></a>
                    <div class="other-languages" id="store-category-info-other-languages">
                        <?php foreach(get_all_languages() as $language):?>
                            <?php if($language['language_id'] != 'english'):?>
                                <input class="form-control"   type="text" name="val[title][<?php echo $language['language_id']?>]" placeholder="<?php _lang('video::category-title')?>"/><br>
                                <p class="help-block"><?php echo $language['language_title']?></p>
                            <?php endif?>
                        <?php endforeach?>
                    </div>

                </div>

            </div>

            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('store::parent-category')?></label>
                <div class="col-sm-9">
                    <select class="c-select" name="val[category]">
                        <option value="0"><?php _lang('store::none')?></option>
                        <?php $categories = lp_store_categories('get_categories'); ?>
                        <?php if(!empty($categories)): ?>
                            <?php foreach( $categories as $category):?>
                                <option value="<?php echo $category['id']?>"><?php _lang($category['title'])?></option>
                            <?php endforeach?>
                        <?php endif; ?>
                    </select>

                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('store::category-image')?></label>
                <div class="col-sm-9">
                    <input type="file" name="image" class="form-control" />
                </div>
            </div>

            <button class="btn btn-info"><?php _lang('store::add-category')?></button>
        </form>
    </div>
</div>