<div class="wrapper">
    <div class="wrapper-title"><?php _lang('blog::manage-category')?>  </div>
    <div class="wrapper-content">
        <form method="post" action="" enctype="multipart/form-data" class="wrapper-form">
            <?php CSRFProtection::embed()?>
            <?php if($message):?>
                <div class="alert alert-danger"><?php echo $message?></div>
            <?php endif?>
            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('blog::category-title')?></label>
                <div class="col-sm-9">
                    <?php foreach(get_all_languages() as $language):?>
                        <input value="<?php echo get_phrase($language['language_id'], $cat['title'])?>" class="form-control" type="text" name="val[title][<?php echo $language['language_id']?>]" placeholder="<?php _lang('store::category-title')?>"/><br>
                        <p class="help-block"><?php echo $language['language_title']?></p>
                    <?php endforeach?>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('store::parent-category')?></label>
                <div class="col-sm-9">
                    <select class="c-select" name="val[category]">
                        <option value="0"><?php _lang('store::none')?></option>
                        <?php $categories = lp_store_categories('get_categories'); ?>
                        <?php if(!empty($categories)): ?>
                            <?php foreach( $categories as $category):?>
                                <option value="<?php echo $category['id']?>" <?php echo ($category['id'] == $cat['parent_id'])? 'selected' :null;  ?>><?php _lang($category['title'])?></option>
                            <?php endforeach?>
                        <?php endif; ?>
                    </select>

                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php _lang('store::category-image')?></label>
                <div class="col-sm-9">
                    <input type="file" name="image" class="form-control" />
                </div>
            </div>
            <div class="col-sm-6">
                <img src="<?php echo storeCategoryImage($cat,200); ?>" class="img img-responsive" style="height:70px; width:100px" />
            </div>
            <br/>


            <button class="btn btn-info"><?php _lang('blog::save-category')?></button>
        </form>
    </div>
</div>