<div class="wrapper">
    <div class="wrapper-title">
        <?php _lang('store::parent-categories')?>
         - <a class="btn btn-success" href="<?php echo url_to_pager('admin-store-add-category')?>"><?php _lang('store::add-category')?></a>
    </div>
    <div class="wrapper-content">
        <table class="table storeTable">
            <thead>
                <tr>
                    <th>ID</th>
                    <th><?php _lang('title')?></th>
                    <th><?php echo lang('store::image')?></th>
                    <th><?php echo lang('store::number-of-subcategories')?></th>
                    <th><?php _lang('actions')?></th>
                </tr>
            </thead>
            <?php  ?>
            <?php if(!empty($categories)): ?>

            <tbody data-url="<?php echo url_to_pager('admin-store-categories-manager').'?action=order'?>" class="admincp-sortable" style="position: relative">
            <?php foreach($categories as $category):?>
                <tr style="" class="item" id="<?php echo $category['id']?>">
                    <td style="width: 10%"><?php echo $category['id']?></td>
                    <td style="width: 30%"><?php _lang($category['title']) ?></td>
                    <td style="width: 20%"><img src="<?php echo storeCategoryImage($category,200); ?>" style="height:50px;width:50px" /></td>
                    <td><?php echo count(get_store_subcategories($category['id'])); ?></td>
                    <td style="width: 20%">
                        <a class="btn btn-sm btn-warning" href="<?php echo url_to_pager('admin-store-categories-manager').'?action=edit&slug='.$category['slug'] ?>"><?php _lang('edit')?></a>
                        <a class="btn btn-sm btn-success" href="<?php echo url_to_pager('admin-store-categories-manager').'?action=manage&slug='.$category['slug'] ?>"><?php _lang('manage')?></a>
                        <a class="btn btn-sm btn-danger admin-confirm" href="<?php echo url_to_pager('admin-store-categories-manager').'?action=delete&slug='.$category['slug']?>"><i class="ion-android-delete"></i></a>
                    </td>
                </tr>
            <?php endforeach?>

            </tbody>

            <?php else: ?>
                <div class="alert alert-info"><?php echo lang('store::no-category-found'); ?></div>
            <?php endif; ?>

        </table>
    </div>
</div>