<div class="box">
    <div class="title"><?php echo lang('giftshop::giftshop') ?></div>
    <div class="box-content row">
        <?php if ($gift_ids): ?>
            <?php foreach ($gift_ids as $gift_id): ?>
                <?php $gifts = get_giftshop_mygift_id($gift_id['gift_id']); ?>
                <?php foreach ($gifts->results() as $gift): ?>
                    <div style="margin-bottom: 20px;" class="col-md-4">
                        <div style="border: solid 1px #4C4C4C;">
                            <?php $avatar = url_img($gift['image']); ?>
                            <div style="background-color: rgba(0, 0, 0, 0.7);overflow: hidden;text-align: center;color: gold;">
                                <h5 style="padding: 10px; margin: 0; white-space: nowrap !important; overflow: hidden; text-overflow: ellipsis;"><?php echo $gift['name']; ?></h5>
                            </div>
                            <?php $credit = get_giftshop_userbalance(); $user_credit = $credit[0]['credit_balance']; ?>
                            <div>
                                <a class="modal-caller" href="#gift-modal" onclick="return show_modal_mine('<?php echo url($avatar) ?>','<?php echo $gift['id'] ?>','<?php echo $gift['name'] ?>')">
                                    <?php $img = $gift['price']; ?>
                                    <div style="width:100%;height:200px;background-image:url(<?php echo $avatar ?>);background-position:center;background-size:cover"></div>
                                </a>
                            </div>
                            <div style="background-color: rgba(0, 0, 0, 0.7);overflow: hidden;text-align: center;color: gold; padding: 0 10px;">
                                <div class="pull-left"><?php echo lang('giftshop::category') ?>: <?php echo $gift['category']; ?></div>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
    <div class="box-content">
        <?php echo $gifts->links() ?>
    </div>
</div>
<div id="gift-modal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content" style="max-width:500px">
            <div class="modal-header">
                <h4 class="modal-title" id="giftTitle" style="margin: 0px; padding: 0px 10px;"></h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <a id="eazyzoom-a" href="">
                    <img src="image" id="image" data-zoom-image="" class="img-responsive"
                         style="width:100%; height:350px;">
                </a>
            </div>
            <div class="modal-footer">
                <form method="post" action="">
                    <input type="hidden" name="giftId" id="giftId" value=""/>
                    <a href="#giftshop-show-friends" onclick="return gifthop_show_friends(this, event)"
                       class="btn btn-success show_gf" id="submit"><?php echo lang('giftshop::buy') ?></a>
                </form>
            </div>
        </div>
    </div>
</div>
<div id="giftshop-show-friends" class="modal fade" role="dialog"></div>