<div class="modal fade" id="adBlockerPopup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <!--<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>-->
                <h4 class="modal-title text-center" id="myModalLabel"><?php echo lang('antiadsblock::adblock-detected') ?></h4>
            </div>
            <div class="modal-body">
                <div>
                    <p>
                        <?php echo lang('antiadsblock::please') ?>, <strong><?php echo lang('antiadsblock::turn-off') ?></strong> <?php echo lang('antiadsblock::your-ads-blocker-inorder-to-continue') ?>.
                    </p>
                    
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="adBlockerPopupRefresh">
                    <i class="fa fa-refresh" aria-hidden="true"></i> <?php echo lang('antiadsblock::refresh-the-page') ?>
                </button>
            </div>
        </div>
    </div>
</div>