<div class="box marketplace">
    <div class="box-content">
        <div class="marketplace-listings list grid row">
            <?php $colors = array('red', 'red', 'pink', 'purple', 'deep-purple', 'indigo', 'blue', 'light-blue', 'cyan', 'teal', 'green', 'light-green', 'lime', 'yellow', 'amber', 'orange', 'deep-orange', 'brown', 'grey', 'blue-grey') ?>
            <?php foreach ($listings->results() as $listing): ?>
                <?php $listing_image = $listing['image'] ? url_img($listing['image'], 920) : img('marketplace::images/no_image.jpg', 75) ?>
                <?php $description = trim($listing['description']) == '' ? '<em>'.lang('marketplace::no-description').'</em>' : $listing['description'] ?>
                <?php $price = is_numeric($listing['price']) ? config('currency', '$').$listing['price'] : $listing['price']; ?>
                <?php $price = trim($listing['price']) == '' ? lang('marketplace::free') : $price; ?>
                <?php $color = $colors[(int)((substr(str_pad($listing['id'], 2, '0', STR_PAD_LEFT), 0, 1) % 2 == 0 ? '' : '1').substr(str_pad($listing['id'], 2, '0', STR_PAD_LEFT), -1))]; ?>
                <div class="col-sm-4">
                    <div class="item <?php echo $color ?>">
                        <div class="head">
                            <img class="image" src="<?php echo $listing_image ?>" alt="<?php echo $listing['title'] ?>">
                        </div>
                        <div class="body">
                            <h5 class="title"><?php echo $listing['title'] ?></h5>
                            <small class="category muted"><?php echo lang($listing['category_title']) ?></small>
                            <p class="description"><?php echo str_limit($description, 50) ?></p>
                        </div>
                        <div class="overlay">
                            <?php if ($listing['approved'] == 1 && $listing['active'] == 1): ?>
                                <a href="#" class="btn btn-outline-info link"><?php echo lang('marketplace::view') ?></a>
                            <?php endif ?>
                            <div class="foot">
                                <a target="_blank" href="#" class="btn btn-outline-info" title="<?php echo lang('marketplace::profile') ?>"><i class="ion-person"></i></a>
                                <?php if (filter_var($listing['link'], FILTER_VALIDATE_URL)): ?>
                                    <a target="_blank" href="#" class="btn btn-outline-info" title="<?php echo lang('marketplace::link') ?>"><i class="ion-link"></i></a>
                                <?php endif ?>
                            </div>
                        </div>
                        <div class="tags">
                            <div class="tag price<?php echo trim($listing['price']) == '' ? ' free' : '' ?>"><?php echo $price ?></div>
                            <?php if ($listing['featured'] == 1): ?>
                                <div class="tag"><?php echo lang('marketplace::featured') ?></div>
                            <?php endif ?>
                        </div>
                    </div>
                </div>
            <?php endforeach ?>
        </div>
    </div>
    <?php if ($listings->total): ?>

    <?php else: ?>
        <div class="alert alert-info" style="width: 100%; margin: 0px 14px;"><?php echo lang('marketplace::no-listing-found') ?></div>
    <?php endif ?>
</div>