<div class="wrapper">
	<div class="wrapper-title"><?php echo lang('contest::manage-category') ?>  </div>
	<div class="wrapper-content">
		<form method="post" action="" enctype="multipart/form-data" class="wrapper-form">
			<?php CSRFProtection::embed() ?>
			<?php if($message): ?>
				<div class="alert alert-danger"><?php echo $message ?></div>
			<?php endif ?>
            <div class="form-group row">
                <label class="col-sm-3 form-control-label"><?php echo lang('contest::category-title') ?></label>
                <div class="col-sm-9">
                    <label>(English)</label>
                    <input type="text" name="val[title][english]" value="<?php echo get_phrase('english', $category['title']) ?>" class="form-control" placeholder="<?php echo lang('contest::category-title') ?>"/>
                    <a href="" class="other-languages-link" onclick="return show_other_languages('#contest-category-info-other-languages')"><?php echo lang('edit-other-languages') ?></a>
                    <div class="other-languages" id="contest-category-info-other-languages">
                        <?php foreach(get_all_languages() as $language): ?>
                            <?php if($language['language_id'] != 'english'): ?>
                                <input class="form-control" value="<?php echo get_phrase($language['language_id'], $category['title']) ?>" type="text" name="val[title][<?php echo $language['language_id'] ?>]" placeholder="<?php echo lang('contest::category-title') ?>"/>
                                <br>
                                <p class="help-block"><?php echo $language['language_title'] ?></p>
                            <?php endif ?>
                        <?php endforeach ?>
                    </div>

                </div>


            </div>

			<button class="btn btn-info"><?php echo lang('contest::save-category') ?></button>
		</form>
	</div>
</div>