<div class="wrapper">
	<div class="wrapper-title">
		<?php echo lang('contest::manage-contest-categories') ?>

        <a class="btn btn-danger pull-right" href="<?php echo url_to_pager('admincp-contest-categories-add') ?>"><i class="ion-plus"></i> <?php echo lang('add') ?></a>
	</div>
	<div class="wrapper-content">
		<div class="list-table-container">
			<div class="table-responsive">
				<table class="table table-striped list-table">
					<thead>
					<tr>

						<th>ID</th>
						<th><?php echo lang('title') ?></th>
						<th><?php echo lang('actions') ?></th>
					</tr>
					</thead>
					<tbody data-url="<?php echo url_to_pager('admincp-contest-manage-category').'?action=order' ?>" class="admincp-sortable" style="position: relative">
					<?php foreach($categories as $category): ?>
						<tr class="item" id="<?php echo $category['id'] ?>">

							<td style="width: 10%"><?php echo $category['id'] ?></td>
							<td style="width: 30%"><?php echo lang($category['title']) ?></td>

							<td>
								<div class="dropdown actions">
									<a href="#" data-toggle="dropdown">
										<i class="ion-android-settings"></i>
									</a>
									<div class="dropdown-menu dropdown-menu-right">
                                        <?php if(!input('id')): ?>
                                            <a ajax="true" class="ion-settings"
                                               href='<?php echo url_to_pager('admincp-contest-categories').'?id='.$category['id'] ?>'></a>
                                        <?php endif; ?>
										<a class="ion-edit" href='<?php echo url_to_pager('admincp-contest-manage-category').'?action=edit&id='.$category['id'] ?>'></a> |
										<a class="admin-confirm ion-android-delete" href="<?php echo url_to_pager('admincp-contest-manage-category').'?action=delete&id='.$category['id'] ?>"></a>
									</div>
								</div>
							</td>


						</tr>
					<?php endforeach ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>