<?php if ($notification['data']):?>
<?php $cid = unserialize($notification['data'])?>
<?php $slug = isset($group['group_name']) ? $group['group_name'] : $notification['type_id'] ?>
<div id="notification-<?php echo $notification['notification_id'] ?>" class="notification media media-md  <?php echo ($notification['mark_read'] == 0) ? 'notification-unread' : null ?>">
	<div class="media-left">
		<div class="media-object">
			<a ajax="true" href="<?php echo group_url('messages', $group) ?>"><img src="<?php echo get_group_logo(200, $group) ?>"/></a>
		</div>
	</div>
	<div class="media-body">
        <?php if (is_group_admin($group)): ?>
        <a ajax="true" href="<?php echo group_url('messages', $group) ?>?cid=<?php echo $cid?>">
            <h6 class="media-heading">
                <?php $user = find_user($notification['from_userid']); echo get_user_name($user).' '.lang('group::messaged-you').' '.lang($group['group_title']) ?>
            </h6>
        </a>
        <?php else: ?>
            <a onclick="return Chat.open(null, '<?php echo get_userid() ?>', '<?php echo $group['group_title'] ?>', '<?php echo get_group_logo(200, $group) ?>', null, null, this, 'group', '<?php echo $group['group_id'] ?>')" href="<?php echo group_url('messages', $group) ?>">
                <h6 class="media-heading">
                    <?php echo lang($group['group_title']).' '.lang('group::messaged-you')?>
                </h6>
            </a>
        <?php endif; ?>
        <span class="timeago " title="<?php echo date('c', $notification['time']) ?>"><?php echo date('c', $notification['time']) ?></span>
		<div class="actions">
			<a
					class="mark-button"
					data-status="<?php echo $notification['mark_read'] ?>"
					data-read="<?php echo lang('notification::read') ?>"
					data-mark="<?php echo lang('notification::mark-as-read') ?>"
					title="<?php echo ($notification['mark_read'] == 1) ? lang('notification::read') : lang('notification::mark-as-read') ?> "
					onclick="return notification.markRead('<?php echo $notification['notification_id'] ?>')"
					href="#!"><i class="ion-checkmark-circled"></i></a>
			<a onclick="return notification.delete('<?php echo $notification['notification_id'] ?>')" href="#!"><i class="ion-close"></i></a>
		</div>
	</div>
</div>
<?php endif;?>
