<div class="box ">
    <div class="title"><?php _lang('whos_online::whos_online') ?></div>
    <div class="box-content" style="padding-top: 0">
        <div class="row">
        <div class="container whos_online" style="display: block">
        <?php echo view('whos_online::online',array('limit'=>$limit)); ?>
        </div>
        </div>
    </div>
    <a ajax="true" href="<?php echo url_to_pager('online-members') ?>" class="right btn-flat ">
        <div class="title">
            <?php _lang('more') ?>
            <i class="ion-ios-arrow-forward pull-right"></i>
        </div>
    </a>
</div>