<?php
$refName = "onlinetv";
?>
<div class="box">
	<div class="title"><?php echo lang("onlinetv::onlinetvs") ?></div>
    <div id="onlinetvs-list-container" class="box-content clearfix onlinetv-listing-container">
		<?php if($onlinetvs->total): ?>
			<?php foreach($onlinetvs->results() as $onlinetv): ?>
				<?php $onlinetv = arrange_onlinetv($onlinetv); ?>
				<?php $user = find_user($onlinetv['user_id']);
                $refId = $onlinetv['id'];
				?>
                <div class="each-item clearfix onlinetv-grid">
                    <?php /*if($onlinetv['category_id']): */?><!--
                <?php /*$category = get_onlinetv_category($onlinetv['category_id']); */?>
                <?php /*if($category): */?>
                <span class="tv-category"><a href="<?php /*echo url('onlinetvs').'?category='.$onlinetv['category_id']; */?>" ajax="true">
                                        <?php /* echo lang($category['title']); */?></a></span>
                <?php /*endif; */?>
                --><?php /*endif; */?>
                    <div class="left">
                        <?php if($onlinetv['featured']): ?>
                            <span class="featured-tag"><?php echo lang('featured') ?></span>
                        <?php endif ?>
                        <a ajax="true" href="<?php echo url('onlinetv/'.$onlinetv['slug']) ?>" style="background-image:url(<?php echo ($onlinetv['image']) ? url_img($onlinetv['image'], 700) : get_avatar(200, $user) ?>)"></a>
                    </div>
                    <div class="right">
                        <span class="item-title"><a ajax="true" href="<?php echo url('onlinetv/'.$onlinetv['slug']) ?>"><?php echo $onlinetv['name'] ?></a></span>
                        <div class="item-info">
                            <span><b><?php echo lang('onlinetv::tv-information'); ?></b></span>
                            <span class="help-block" style="display: block">
                                <?php /*echo lang('onlinetv::By') */?><!--  :--> <b><a href="<?php echo url($onlinetv['publisher']['id']) ?>"><?php echo $onlinetv['publisher']['name'] ?></a></b>
                                <br/>
                                <?php echo date('M j , Y', $onlinetv['time']) ?>
                                <br/>

                                <span><?php /*echo lang("onlinetv::price"); */?><!-- : --><span class="owo-color"><?php echo ($onlinetv['price'] == 0) ? lang('onlinetv::free') : $onlinetv['price'].' '.config('default-currency','USD');   ?></span></span>
                            </span>
                        </div>
                        <!--<p class="item-desc"><?php /*echo strip_tags(str_limit($onlinetv['description'], 20)) */?></p>-->
                        <p>
                            <strong><?php echo $onlinetv['views']; ?></strong> <?php echo lang('onlinetv::views'); ?>
                            <strong><?php $likes = count_likes($refName, $refId);
                                echo $likes; ?></strong> <?php if($likes > 1) {
                                echo lang('onlinetv::likes');
                            } else {
                                echo lang('onlinetv::like');
                            } ?>
                        </p>
                    </div>
                </div>
			<?php endforeach ?>
			<?php echo $onlinetvs->links() ?>
		<?php else: ?>
			<div class="alert alert-info"><?php echo lang('onlinetv::onlinetvs-list-empty') ?></div>
		<?php endif ?>
	</div>
</div>