<?php $contest_menus = get_menus("contests-menu") ?>
<?php if($contest_menus || (is_loggedIn() && user_has_permission('can-create-contest') and config('allow-members-create-contest', true))): ?>
    <div class="box">
        <div class="box-content">
            <a href="<?php echo url('contest/add') ?>" class="btn btn-info btn-block" type="button" data-toggle="modal" data-target="#create-contest-modal"><?php echo lang('contest::start-a-contest') ?></a>
            <div class="modal fade" id="create-contest-modal" role="dialog">
                <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <form action="<?php echo url_to_pager('contest-add'); ?>" method="post" enctype="multipart/form-data" class="ajax-form contest-start-form">
                            <div class="modal-form-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <p class="modal-title"><?php echo lang('contest::start-a-contest') ?></p>
                            </div>
                            <div class="modal-body">
                                <?php CSRFProtection::embed() ?>
                                <?php echo view("contest::contest-form-fields"); ?>
                            </div>
                            <div class="modal-footer">
                                <div class="submit">
                                    <input type="submit" class="btn btn-info" value="<?php echo lang("contest::publish-contest") ?>"/>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <ul class="menu">
            <?php foreach($contest_menus as $menu): ?>
                <li>
                    <a <?php echo $menu->ajax ? 'ajax="true"' : null ?> <?php echo ($menu->tab) ? 'onclick="return window.open(\''.$menu->link.'\')"' : null ?> href="<?php echo ($menu->tab) ? 'javascript:void(0)' : $menu->link ?>"><?php echo lang($menu->title) ?></a>
                </li>
            <?php endforeach ?>
            <?php if(is_loggedIn()): ?>
                <li>
                    <a href="<?php echo url('contests?type=mine') ?>" ajax="true"><?php echo lang('contest::my-contests') ?></a>
                </li>

                <li class="<?php echo (input('method') == 'mine') ? 'active' : ''; ?>"><a ajax="true"
                            href="<?php echo url_to_pager('contests-my-entries').'?method=mine' ?>"><?php _lang('contest::my-entries') ?></a></li>

                <li class="<?php echo (input('method') == 'recent') ? 'active' : ''; ?>"><a ajax="true"
                                                                                            href="<?php echo url_to_pager('contests-my-entries').'?method=recent' ?>"><?php _lang('contest::recent-entries') ?></a></li>
            <?php endif ?>

        </ul>
    </div>
<?php endif ?>
