<?php if(isMobile()): ?><!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd"><?php else: ?><!DOCTYPE html><?php endif ?>
<html lang="en">
<head>
    <title><?php echo html_entity_decode($title, ENT_QUOTES) ?></title><?php echo render_meta_tags() ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=PT+Sans:400,700" rel="stylesheet">
    <link rel="shortcut icon" type="image/x-icon"
          href="<?php echo (config('site-favicon')) ? url_img(config('site-favicon')) : img('images/favicon.ico') ?>"/><?php echo render_assets('css') ?>
    <style>
        #header #loading-line {
            background-color: <?php echo config('loading-line-color', '#F62459') ?>;
        }

        #header {
            background-color: <?php echo config('header-bg-color', '#4C4C4E') ?> !important;
        }

        #header .navbar-brand {
            color: <?php echo config('header-brand-color', '#FFFFFF') ?>;
        }

        #header .nav-item,
        #header .nav-link {
            color: <?php echo config('header-menu-color','#FFFFFF') ?>;
        }

        #header .nav-link i {
            color: <?php echo config('header-menu-icon-color','#FFFFFF') ?>;
        }

        #header #header-search input[type=text]::placeholder {
            color: <?php echo config('header-search-placeholder-color','#FFFFFF') ?>;
        }

        #header #header-search input[type=text] {
            color: <?php echo config('header-search-color','#FFFFFF') ?>;
        }

        #home-login-container .login-content {
            background-color: <?php echo config('landing-reg-bg-color','rgba(46, 62, 69, 0.36)') ?> !important;
        }


        #welcome-notes {
            font-family: <?php echo  config('welcomes-notes-font','Segoe UI, Arial, sans-serif') ?> !important;
        }

        .btn-post {
            background-color: <?php echo config('header-bg-color','#1c2331') ?> !important;
            color: white;
        }

        a {
            color: <?php echo config('link-color','#2b354f') ?>;
        }

        #explore-menu {
            background-color: <?php echo config('explorer-bg-color','#F4F4F4') ?>;
        }

        #explore-menu .container > .explore-menu-bar > .explore-menu-item a {
            color: <?php echo config('explorer-link-color','#1c2331') ?>;
        }

        #explore-menu .container > .explore-menu-bar .arrow-up {
            border-bottom-color: <?php echo app()->design['color'] ?>
        }

        #explore-menu .container #all-container > a {
            background-color: <?php echo config('explorer-dropdown-bg-color','#626A73') ?>;
            color: <?php echo config('explorer-dropdown-text-color','#808080') ?>;
        }

        body {
            background-color: <?php echo app()->design['color'] ?>;
        }

        #main-wrapper {
            background-color: <?php echo app()->design['color'] ?>;
            background-image: <?php echo (app()->design['image']) ? "url(".app()->design['image'].")" : 'none' ?>;
            background-attachment: fixed;
            background-position: top<?php echo app()->design['position'] ?>;
            background-repeat: <?php echo app()->design['repeat'] ?>;
        }

        #main-wrapper > .container {
        <?php if(app()->design['container']): ?> background: <?php echo app()->design['container'] ?>;
            padding: 10px;
        <?php endif ?>
        }

        #main-wrapper > .container a {
            color: <?php echo app()->design['link'] ?>
        }

        #chat-boxes-container .onlines-container .main > ul,
        #chat-boxes-container .onlines-container {
            background-color: <?php echo app()->design['color'] ?> !important;
        }

        .btn-info {
            background: <?php echo config('button-bg-color','#0abde3') ?> !important;
            border: none !important;
            -webkit-appearance: normal !important;
        }

        .verify-badge {
            color: <?php echo config('verify-badge-color','#19B5FE') ?>
        }

        #topo #slides .slide-1 {
            background-image: url(<?php echo url_img(config('default-theme-topography-image-1','themes/default/images/topography/one.jpg')) ?>) !important;
        }

        #topo #slides .slide-2 {
            background-image: url(<?php echo url_img(config('default-theme-topography-image-2','themes/default/images/topography/two.jpg')) ?>) !important;
        }

        #topo #slides .slide-3 {
            background-image: url(<?php echo url_img(config('default-theme-topography-image-3','themes/default/images/topography/three.jpg')) ?>) !important;
        }

    </style>
    <?php echo html_entity_decode(config('google-analytics-code'), ENT_QUOTES) ?>
</head>
<body class=" <?php echo is_loggedIn() ? 'logged-in' : 'logged-out';
echo !segment(0) ? ' home' : '';
echo segment(0) == 'login' ? ' login-page' : '';
echo segment(0) == 'signup' ? ' signup-page' : '';
echo isset(app()->fullContainer) && app()->fullContainer ? ' full-container' : '';
echo is_loggedIn() && !isMobile() && user_has_permission('can-send-message') && (isset(app()->sideChat) && app()->sideChat || !isset(app()->sideChat)) ? ' chat-opened' : '' ?>"
      data-general-error="<?php echo lang('something-went-wrong') ?>">
<?php if ($app->onHeader): ?>
    <?php $logo = config('site-logo');
    $logo_url = !$logo ? img('images/logo.png') : url_img($logo); ?>
    <nav id="header" class="navbar navbar-expand-lg" style="">
        <div id="loading-line"></div>
        <?php if ($app->onHeaderContent): ?>
            <div class="container">
                <?php if (is_loggedIn()): ?>
                    <a href="" onclick="return open_sidebar_menu()" class="header-menu-trigger">
                        <i class="ion-android-menu"></i>
                    </a>
                    <a class="navbar-brand" href="<?php echo url('feed') ?>" ajax="true">
                        <?php if (config('show-nav-brand-logo', 1)): ?>
                            <img src="<?php echo $logo_url ?>"/>
                        <?php endif ?>
                        <?php if (config('show-nav-brand-title', 0)): ?>
                            <?php echo config('site_title') ?>
                        <?php endif ?>
                    </a>
                    <form action="<?php echo url_to_pager("search") ?>" id="header-search"
                          class="form-inline nav-link  hide-in-mobile">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="header-search-button"><i class="ion-ios-search"></i></span>
                            </div>
                            <input id="header-search-input" type="text" name="term" class="form-control"
                                   placeholder="<?php echo lang('search::search-placeholder') ?>" autocomplete="off"
                                   aria-label="<?php echo lang('search') ?>" aria-describedby="header-search-button"
                                   onkeyup="process_search_dropdown()" onfocus="process_search_dropdown()">
                        </div>
                    </form>

                    <ul class="navbar-nav left-nav-links">
                        <li class="nav-item  hide-in-mobile">
                            <a data-toggle="tooltip" data-original-title="<?php echo lang('browse-videos') ?>"
                               href="<?php echo url('videos') ?>"
                               class="nav-link"><?php _lang('video::browse-videos') ?></a>
                        </li>

                        <li class="nav-item dropdown  hide-in-mobile">
                            <a href="#!" class="nav-link dropdown-toggle"
                               data-toggle="dropdown"><?php _lang('explore') ?></a>
                            <div class="dropdown-menu explore-more-menu dropdown-menu-right">
                                <?php $menus = get_menus("main-menu");
                                $limit = config('main-menu-limit', 4); ?>
                                <?php $i = 1;
                                foreach ($menus as $menu): ?>
                                    <a class="dropdown-item <?php echo $menu->id ?>" <?php echo ($menu->ajax) ? 'ajax="true"' : null ?> <?php echo ($menu->tab) ? 'onclick="return window.open(\'' . $menu->link . '\')"' : null ?>
                                       href="<?php echo ($menu->tab) ? 'javascript:void(0)' : $menu->link ?>">
                                        <span><?php echo lang($menu->title) ?></span>
                                    </a>
                                <?php endforeach ?>
                            </div>
                        </li>

                    </ul>

                    <ul class="navbar-nav ml-auto">


                        <li class="nav-item  hide-in-mobile">
                            <a data-toggle="tooltip" data-original-title="<?php echo lang('upload videos') ?>"
                               ajax="true" href="<?php echo url('videos') ?>"
                               class="btn btn-info  video-create-nav"><?php _lang('video::upload-videos') ?></a>
                        </li>
                        <?php if (plugin_loaded('chat')): ?>
                            <li class="nav-item" id="message-dropdown-container">
                                <a data-toggle="tooltip" data-original-title="<?php echo lang('message') ?>"
                                   class="nav-link hide-in-mobile" onclick="return show_message_dropdown()" href="#">
                                    <i class="la la-comments"></i> </a>
                                <a class="nav-link show-in-mobile" ajax="true" href="<?php echo url('messages') ?>">
                                    <i class="la la-comments"></i> </a>
                                <div class="header-dropdown message-dropdown">
                                    <div class="arrow-up "></div>
                                    <div class="message-dropdown-content header-dropdown-content z-depth-1">
                                        <div class="dropdown-title">
                                            <?php echo lang('chat::messages') ?> -
                                            <a ajax="true" href="<?php echo url_to_pager("messages") ?>?cid=new">
                                                <?php echo lang('chat::new-message') ?>
                                            </a>
                                            <img src="<?php echo img('images/loading.gif') ?>"
                                                 id="message-dropdown-indicator" class="dropdown-indicator pull-right"/>
                                        </div>
                                        <div data-height="330px"
                                             class="slimscroll message-dropdown-result-container dropdown-result-container"></div>
                                        <a ajax="true" class="see-all-message see-all-button"
                                           href="<?php echo url_to_pager("messages") ?>"><?php echo lang('see-all') ?></a>
                                    </div>
                                </div>
                            </li>
                        <?php endif ?>
                        <?php if (plugin_loaded('relationship') and config('relationship-method', 3) > 1): ?>
                            <li id="friend-request-dropdown-container" class="nav-item">
                                <a data-toggle="tooltip" data-original-title="<?php echo lang('friend-request') ?>"
                                   onclick="return show_friend_request_dropdown()" href="#"
                                   class="nav-link hide-in-mobile">
                                    <i class="la la-user-plus"></i> </a>
                                <a ajax="true" href="<?php echo url('friend/requests') ?>"
                                   class="nav-link show-in-mobile">
                                    <i class="la la-user-plus"></i> </a>
                                <div class="friend-request-dropdown header-dropdown">
                                    <div class="arrow-up "></div>
                                    <div class="friend-request-dropdown-content header-dropdown-content z-depth-1">
                                        <div class="dropdown-title"><?php echo lang('relationship::friend-requests') ?>
                                            <img style="" src="<?php echo img('images/loading.gif') ?>"
                                                 id="friend-request-dropdown-indicator"
                                                 class="dropdown-indicator pull-right"/>
                                        </div>
                                        <div data-height="330px"
                                             class="slimscroll friend-request-dropdown-result-container dropdown-result-container"></div>
                                        <a ajax="true" class="see-all-friend-request see-all-button"
                                           href="<?php echo url_to_pager("friend-requests") ?>"><?php echo lang('relationship::see-all-friend-request') ?></a>
                                    </div>
                                </div>
                            </li>
                        <?php endif ?>
                        <?php load_functions("notification::notification");
                        if (plugin_loaded("notification")): ?>
                            <li class="nav-item" id="notification-dropdown-container">
                                <a data-toggle="tooltip" data-original-title="<?php echo lang('notifications') ?>"
                                   class="nav-link hide-in-mobile" onclick="return notification.dropdown.show()"
                                   href="#">
                                    <i class="la la-bell"></i>
                                </a>
                                <a ajax="true" class="nav-link show-in-mobile"
                                   href="<?php echo url('notifications') ?>">
                                    <i class="la la-bell"></i>
                                </a>
                                <div style="" class="notifications-dropdown header-dropdown">
                                    <div class="arrow-up"></div>
                                    <div class="header-dropdown-content z-depth-1">
                                        <div class="dropdown-title"><?php echo lang('notification::notifications') ?>
                                            <img src="<?php echo img('images/loading.gif') ?>"
                                                 id="notification-dropdown-indicator"
                                                 class="dropdown-indicator pull-right"/>
                                        </div>
                                        <div data-height="330px"
                                             class="dropdown-result-container slimscroll notification-dropdown-result-container"></div>
                                        <a ajax="true" class="see-all-button"
                                           href="<?php echo url_to_pager("notifications") ?>"><?php echo lang('notification::see-all-notifications') ?></a>
                                    </div>
                                </div>
                            </li>
                        <?php endif ?>
                        <li class="dropdown text-link nav-item hide-in-mobile" id="header-account-menu">
                            <a aria-expanded="false" class="dropdown-toggle nav-link" data-toggle="dropdown"
                               href="<?php echo profile_url() ?>">
										<span class="span">
											<img src="<?php echo get_avatar(75) ?>"/>
										</span>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-right <?php echo !isRTL() ? 'dropdown-menu-right' : null ?>"
                                id="account-menu-dropdown">
                                <li>
                                    <a class="dropdown-item" href="<?php echo profile_url() ?>"
                                       ajax="true"><?php echo lang('my-profile') ?></a>
                                </li>
                                <li class="dropdown-divider"></li>
                                <?php foreach (get_menus("header-account-menu") as $menu): ?>
                                    <li>
                                        <a class="dropdown-item" <?php echo ($menu->ajax) ? 'ajax="true"' : null ?> <?php echo ($menu->tab) ? 'onclick="return window.open(\'' . $menu->link . '\')"' : null ?>
                                           href="<?php echo ($menu->tab) ? 'javascript:void(0)' : $menu->link ?>"><?php echo lang($menu->title) ?></a>
                                    </li>
                                <?php endforeach ?>
                                <li>
                                    <a href="<?php echo url_to_pager('saved') ?>" class="dropdown-item"
                                       ajax="true"><?php echo lang('saved') ?></a>
                                </li>
                                <li>
                                    <a ajax="true" class="dropdown-item"
                                       href="<?php echo url_to_pager('account') ?>"><?php echo lang('account-settings') ?></a>
                                </li>
                                <?php if (is_admin()): ?>
                                    <li>
                                        <a class="dropdown-item"
                                           href="<?php echo url_to_pager('admin-statistic') ?>"><?php echo lang('go-to-admincp') ?></a>
                                    </li>
                                <?php endif ?>
                                <li style="margin: 0" class="dropdown-divider"></li>
                                <li>
                                    <a class="dropdown-item"
                                       href="<?php echo url('logout') ?>"><?php echo lang('logout') ?></a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                <?php else: ?>
                    <a class="navbar-brand" href="<?php echo url() ?> ">
                        <?php if (config('show-nav-brand-logo', 1)): ?>
                            <img src="<?php echo $logo_url ?>"/>
                        <?php endif ?>
                        <?php if (config('show-nav-brand-title', 0)): ?>
                            <?php echo config('site_title') ?>
                        <?php endif ?>
                    </a>
                    <button class="right-menu-toggler" type="button">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <form style="position:absolute; left: 200px !important;"
                          action="<?php echo url_to_pager("search") ?>" id="header-search"
                          class="form-inline nav-link hide-in-mobile">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="header-search-button"><i class="ion-ios-search"></i></span>
                            </div>
                            <input id="header-search-input" type="text" name="term" class="form-control"
                                   placeholder="<?php echo lang('search::search-placeholder') ?>" autocomplete="off"
                                   aria-label="<?php echo lang('search') ?>" aria-describedby="header-search-button"
                                   onkeyup="process_search_dropdown()" onfocus="process_search_dropdown()">
                        </div>
                    </form>

                    <div id="header-right" class="right">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item hide-in-mobile">
                                <a style="position: relative;bottom:5px" href="<?php echo url('videos') ?>"
                                   class="nav-link"><?php _lang('video::browse-videos') ?></a>
                            </li>

                            <li class="nav-item dropdown hide-in-mobile">
                                <a style="position: relative;bottom:5px" href="" class="nav-link dropdown-toggle"
                                   data-toggle="dropdown"><?php _lang('explore') ?></a>
                                <div class="dropdown-menu explore-more-menu dropdown-menu-right">
                                    <?php $menus = get_menus("main-menu");
                                    $limit = config('main-menu-limit', 4); ?>
                                    <?php $i = 1;
                                    foreach ($menus as $menu): ?>
                                        <a class="dropdown-item <?php echo $menu->id ?>" <?php echo ($menu->ajax) ? 'ajax="true"' : null ?> <?php echo ($menu->tab) ? 'onclick="return window.open(\'' . $menu->link . '\')"' : null ?>
                                           href="<?php echo ($menu->tab) ? 'javascript:void(0)' : $menu->link ?>">
                                            <span><?php echo lang($menu->title) ?></span>
                                        </a>
                                    <?php endforeach ?>
                                </div>
                            </li>
                            <!--li class="nav-item  hide-in-mobile">
                                <a ajax="true" href="<?php echo url('videos') ?>"
                                   class="btn btn-info  video-create-nav"><?php _lang('video::upload-videos') ?></a>
                            </li-->
                        </ul>

                    </div>
                <?php endif; ?>
            </div>
        <?php endif ?>
        <a id="feed-top-update-alert" href="">
            <div>
                <span></span> <br/><?php echo lang('feed::new-feeds') ?>
            </div>
        </a>
    </nav>
    <?php theme_extend('header') ?>
<?php endif ?>
<div id="site-wide-notification" class="success">
    <span class="message"></span> <a href="#" onclick="return closeNotify()" class="close"><i class="ion-close"></i>
    </a>
</div>
<div class="modal fade" id="quick-post-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body"><p>One fine body&hellip;</p></div>
        </div>
    </div>
</div>
<div id="sidebar-menu">
    <?php if (is_loggedIn()): ?>
        <form action="<?php echo url_to_pager("search") ?>" class="form-inline search-pane" method="post">
            <?php CSRFProtection::embed() ?>
            <input autocomplete="off" name="term" style="" class="form-control" type="text"
                   placeholder="<?php echo lang('search::search') ?>">
            <button class="btn btn-info btn-sm" type="submit"><i class="ion-search"></i></button>
        </form>
    <?php endif ?>
    <ul class="nav slimscroll" data-height="90%">
        <?php
        $images = fire_hook('shortcut.menu.images', array(
            'ion-android-alarm-clock' => img('images/icons/auction.png'),
            'ion-android-calendar' => img('images/icons/events.png'),
            'ion-android-cart' => img('images/icons/marketplace.png'),
            'ion-android-checkbox' => img('images/icons/poll.png'),
            'ion-ios-help' => img('images/icons/anonymous.png'),
            'ion-android-clipboard' => img('images/icons/edit.png'),
            'ion-chatbubbles' => img('images/icons/faq.png'),
            'ion-chatbox-working' => img('images/icons/feedback.png'),
            'ion-android-mail' => img('images/icons/send_message.png'),
            'ion-android-people' => img('images/icons/people.png'),
            'ion-android-person-add' => img('images/icons/add_friend.png'),
            'ion-bag' => img('images/icons/gift.png'),
            'ion-briefcase' => img('images/icons/handshake.png'),
            'ion-card' => img('images/icons/flag.png'),
            'ion-chatboxes' => img('images/icons/acquaintances.png'),
            'ion-home' => img('images/icons/news_feed.png'),
            'ion-images' => img('images/icons/picture.png'),
            'ion-ios-contact-outline' => img('images/icons/person.png'),
            'ion-ios-game-controller-b-outline' => img('images/icons/games.png'),
            'ion-ios-people' => img('images/icons/group.png'),
            'ion-ios-pricetag' => img('images/icons/property.png'),
            'ion-ios-videocam-outline' => img('images/icons/video.png'),
            'ion-music-note' => img('images/icons/music.png'),
            'ion-pound' => img('images/icons/hashtag.png'),
            'ion-radio-waves' => img('images/icons/stream.png'),
            'ion-social-bitcoin' => img('images/icons/bitcoin.png')
        ));
        ?>
        <?php if (is_loggedIn() or (config('show-main-menu-guest', false) and !isMobile())): ?>
            <?php $menus = get_menus("main-menu"); ?>
            <?php foreach ($menus as $menu): ?>
                <li class="<?php echo $menu->id ?>">
                    <a <?php echo $menu->ajax ? 'ajax="true"' : null ?> <?php echo $menu->tab ? 'onclick="return window.open(\'' . $menu->link . '\')"' : null ?>
                            href="<?php echo $menu->tab ? 'javascript:void(0)' : $menu->link ?>">

                        <?php if (array_key_exists($menu->icon, $images)): ?>
                            <img style="width: 15px" src="<?php echo $images[$menu->icon] ?>">
                        <?php else: ?>
                            <i class="<?php echo $menu->icon ?>"></i>
                        <?php endif ?>
                        <span><?php echo lang($menu->title) ?></span> </a>
                    <?php if ($menu->isActive()): ?>
                        <div class="arrow-up"></div>
                    <?php endif ?>
                </li>
            <?php endforeach ?>
        <?php endif ?>
        <?php if (is_loggedIn()): ?>
            <li>
                <a href="<?php echo url('logout') ?>" class="dropdown-item"><i
                            class="ion-log-out"></i> <?php echo lang('logout') ?>
                </a></li>
        <?php else: ?>
            <li>
                <a href="<?php echo url_to_pager('login') ?>" class="dropdown-item"><i
                            class="ion-log-in"></i> <?php echo lang('signin') ?>
                </a></li>
        <?php endif; ?>
    </ul>
</div>
<div id="main-wrapper"<?php echo $app->onHeader ? ' class="header-space"' : '' ?>>