<div class="box">
	<div class="title"><?php echo lang('group::group-members') ?></div>
	<?php if($users): ?>
		<div class="box-content two-line-media clearfix">
			<?php foreach($users->results() as $user): ?>
				<div class="media <?php echo (isset($type)) ? $type : 'media-lg' ?> user">
					<div class="media-left">
						<a ajax="true" href="<?php echo profile_url(null, $user) ?>" class="media-object"><img class="responsive-img" src="<?php echo get_avatar(75, $user) ?>"/></a>
					</div>
					<div class="media-body">
						<a ajax="true" href="<?php echo profile_url(null, $user) ?>"><?php echo get_user_name($user) ?></a>
						<div class="action">
							<?php if(is_group_admin($app->profileGroup) || is_group_moderator($app->profileGroup)): ?>
								<?php if(is_group_admin($app->profileGroup)): ?>
									<select onchange="return process_group_role(this,'<?php echo $app->profileGroup['group_id'] ?>', '<?php echo $user['id'] ?>')" class="c-select">
									<option value="0"><?php echo lang('group::member') ?></option>
									<option value="1" <?php echo (is_group_moderator($app->profileGroup, $user['id'])) ? 'selected' : null ?>><?php echo lang('group::moderator') ?></option>
                                    <?php fire_hook("add.group.role.option",$app->profileGroup, array($user))?>
								</select>
								<?php endif ?>
								<?php if($app->profileGroup['user_id'] != $user['id'] and $user['id'] != get_userid()): ?>
									<a href="#" data-user-id="<?php echo $user['id'] ?>" data-group-id="<?php echo $app->profileGroup['group_id'] ?>" class="btn btn-danger group-remove-member-button"><i class="ion-android-delete"></i></a>
								<?php endif ?>
							<?php endif ?>
						</div>
					</div>
				</div>
			<?php endforeach ?>
		</div>
		<div class="box-content">
			<?php echo $users->links(true) ?>
		</div>
	<?php endif ?>
</div>