<?php $type = "business"; $typeId = null; ?>
<input id="businesscompare" type="button" value="Compare" class="business_button btn btn-primary businesscompare" onclick="return businessCompare()" />
<div class="business box">
	<div class="business-list">
		<div class="head">
			<div class="cover" style="background-image: url(<?php echo url_img(config('business-list-cover', 'plugins/business/images/cover.jpg'), 920); ?>)">
				<div class="title"><?php echo isset($title) ? $title : lang('business::businesses') ?></div>
				
			</div>
			<div class="filters filter-pane global-filter-container" data-url="<?php echo url_to_pager('businesses') ?>">
                <div class="top">
                    <form id="business-list-search" method="post" onsubmit="return businessGetBusinessesPage(getBusinessFilters())" action="" class="search form-inline list-search">
                        <?php CSRFProtection::embed() ?>
                        <input id="business-filter-search" type="search" value="<?php echo input('s') ?>" class="form-control search-box filter-input" data-name="s" placeholder="<?php echo lang('business::search-businesses') ?>" />
                        <button type="submit">
                            <i class="search-icon icon ion-ios-search"></i>
                        </button>
                    </form>
                </div>
                <div class="bottom">
                    <i class="icon ion-android-options"></i>
                    <select id="business-filter-category" onchange="return businessGetBusinessesPage(getBusinessFilters())" class="c-select filter-input" name="c">
                            <option value="all"><?php echo lang('business::all-categories') ?></option>
                        <?php foreach (business_get_categories() as $category): ?>
                            <option <?php echo (input('c') == $category['id']) ? 'selected' : null ?> value="<?php echo $category['category'] ?>"><?php echo lang($category['category']) ?></option>
                        <?php endforeach ?>
                    </select>
                    <select id="business-filter-type" onchange="return businessGetBusinessesPage(getBusinessFilters())" class="c-select filter-input">
                            <option value="all"><?php echo lang('business::all-businesses') ?></option>
                            <option <?php echo (input('m')) ? 'selected' : null ?> value="m"><?php echo lang('business::my-business') ?></option>
                            <option <?php echo (input('f')) ? 'selected' : null ?> value="f"><?php echo lang('business::featured') ?></option>
                    </select>
                    <form action="" method="post" onsubmit="return businessFilterFormSubmit(this)" class="business-filter-bottom">
                        <?php CSRFProtection::embed() ?>
                        <?php if(config('business-enable-location-filter', true)): ?>
                            <input type="text" name="l" value="<?php echo input('l') ?>" class="c-input filter-input" placeholder="<?php echo lang('business::location') ?>"/>
                        <?php endif ?>
                        <?php if(config('business-enable-price-filter', true)): ?>
                            <input type="number" min="0" step="0.5" name="p0" value="<?php echo input('p0') ?>" class="c-input filter-input" placeholder="<?php echo lang('business::min') ?>"/>
                            <input type="number" min="0" step="0.5" name="p1" value="<?php echo input('p1') ?>" class="c-input filter-input" placeholder="<?php echo lang('business::max') ?>"/>
                        <?php endif ?>
                        <?php if(config('business-enable-feature-filter', true)): ?>
                            <input type="checkbox" class="c-input filter-input" name="f"<?php echo input('f') ? ' checked' : null ?> value="1"/> <?php echo lang('business::featured') ?>
                        <?php endif ?>
                        <?php if(config('business-enable-mine-filter', true)): ?>
                            <input type="checkbox" class="c-input filter-input" name="m"<?php echo input('m') ? ' checked' : null ?> value="1"/> <?php echo lang('business::my-businesses') ?>
                        <?php endif ?>
                        <?php if(config('business-enable-photo-filter', true)): ?>
                            <input type="checkbox" class="c-input filter-input" name="i"<?php echo input('i') ? ' checked' : null ?> value="1"/> <?php echo lang('business::has-photo') ?>
                        <?php endif ?>
                        <div class="business-w-search">
                            <input type="search" name="s" value="<?php echo input('s') ?>" class="form-control search-box filter-input" placeholder="<?php echo lang('business::keywords') ?>"/>
                            <button type="submit">
                                <i class="search-icon icon ion-ios-search"></i>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div id="businesses-list-container" class="box-content clearfix">
        <?php foreach ($businesses->results() as $business): ?>
            <?php $typeId = $business['id'] ?>
            <?php $owner = find_user($business['user_id']); ?>
            <?php $business_image = $business['company_logo'] ? url_img($business['company_logo'], 920) : img('business::images/no_image.jpg', 920) ?>
            <?php $description = trim($business['description']) == '' ? '<em>'.lang('business::no-description').'</em>' : $business['description'] ?>
            <?php $price = is_numeric($business['price']) ? config('currency', '$').$business['price'] : $business['price']; ?>
            <?php $price = !trim($business['price']) ? lang('business::free') : $price; ?>
            <div class="col-sm-4">
                <div class="item green">
                    <div class="head">
                        <img class="image" src="<?php echo $business_image ?>" />
                        <?php if ($business['featured']): ?>
                            <div class="featured">
                                <i class="ion-ios-star-outline"></i>
                            </div>
                        <?php endif; ?>
                    </div>
                    <div class="body">
                        <?php $rating = get_ratings($type, $typeId); ?>
                        <div class="rating user-<?php echo $type ?>-<?php echo $typeId ?>">
                            <i class="ion-ios-star star <?php echo $rating >= 1 ? 'filled' : '' ?>" onclick="return ratings(this,'<?php echo $type ?>', '<?php echo $typeId ?>')"></i>
                            <i class="ion-ios-star star <?php echo $rating >= 2 ? 'filled' : '' ?>" onclick="return ratings(this,'<?php echo $type ?>', '<?php echo $typeId ?>')"></i>
                            <i class="ion-ios-star star <?php echo $rating >= 3 ? 'filled' : '' ?>" onclick="return ratings(this,'<?php echo $type ?>', '<?php echo $typeId ?>')"></i>
                            <i class="ion-ios-star star <?php echo $rating >= 4 ? 'filled' : '' ?>" onclick="return ratings(this,'<?php echo $type ?>', '<?php echo $typeId ?>')"></i>
                            <i class="ion-ios-star star <?php echo $rating >= 5 ? 'filled' : '' ?>" onclick="return ratings(this,'<?php echo $type ?>', '<?php echo $typeId ?>')"></i>
                        </div>
                        <small class="category muted"><?php echo lang($business['category_title']) ?></small>
                        <p class="description"><?php echo str_limit(sanitizeText($description, null, true), 90) ?></p>
                    </div>
                    <div class="overlay">
                        <a href="<?php echo url_to_pager('business-page', array('slug' => $business['slug'])) ?>" class="btn btn-outline-info link" ajax="true"><?php echo lang('business::view') ?></a>
                        <div class="foot">
                            <div class="stat">
                                <a target="_blank" href="#!" title="<?php echo lang('business::views') ?>"><i class="ion-eye"></i> <?php echo viewCounts($business['id']) ?>
                                </a>
                                <a target="_blank" href="#!" title="<?php echo lang('business::reviews') ?>"><i class="ion-android-create"></i> <?php echo reviewcounts($business['id']) ?>
                                </a>
                                <a target="_blank" href="#!" title="<?php echo lang('business::members') ?>"><i class="ion-android-people"></i> <?php echo rowscount('business_member', $business['id']) ?>
                                </a>
                            </div>
                            <div class="tel">
                                <i class="ion-android-call"></i>
                                <?php echo $business['business_number'] ?>
                            </div>
                            <div class="checkbox compare" title="<?php echo lang('business::compare') ?>">
                                <label>
                                    <input type="checkbox" value="<?php echo $business['id'] ?>" name="compare[]" />
                                    <span class="cr"><i class="cr-icon ion-checkmark-round"></i></span>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="info">
                        <div class="location"><?php echo $business['company_address'] ?></div>
                        <div class="title"><?php echo $business['business_name'] ?></div>
                    </div>
                </div>
            </div>
        <?php endforeach ?>
    </div>
    </div>
    <div class="box-content">
        <?php if($businesses->total): ?>
            <?php if ($businesses->total > config('business-list-limit', 20)): ?>
                <?php echo $businesses->links(true) ?>
            <?php endif ?>
        <?php else: ?>
            <div class="alert alert-info"><?php echo lang('business::no-business-found') ?></div>
        <?php endif ?>
    </div>
</div>
<div class="modal fade" tabindex="-1" role="dialog" id="error-modal" aria-hidden="true" aria-labelledby="contact">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="modal-title"> Error</h4>
            </div>
            <div class="modal-body">
                <span id="error-body"></span>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

