<div id="delete-business" class="business business-content box">
	<form action="" method="post" class="adm">
		<?php CSRFProtection::embed() ?>
		<div class="alert alert-info"><?php echo lang('business::claim-warning') ?>
			<strong><?php echo $business['business_name'] ?></strong>?
		</div>
		<div class="row">
			<div class="col-sm-5"></div>
			<div class="col-sm-7">
				<input type="submit" value="<?php echo lang('business::claim-confirm') ?>" class="btn btn-primary"/>
			</div>
		</div>
		<input type="hidden" name="val[business_id]" value="<?php echo $business['id'] ?>"/>
		<input type="hidden" name="val[type]" value="claim_business"/>
	</form>
</div>