<style>
	#content-stage {
		background: #ffffff;
		padding-left: 20px;
		padding-right: 20px;
		padding-bottom: 20px;
	}

	._block_breadcrumb {
		display: inline-block;
		display: block;
	}
</style>
<div class="box business">
	<div id="content-stage" class="bg-tran">
		<div class="">
			<div class="_block_breadcrumb">
				<div class="row hide-overflow breadcrumbs-holder">
					<div class="clearfix breadcrumbs-top">
						<div class="pull-left">
							<div class="breadcrumbs-list">
								<a class="ajax_link">Membership Notice</a>
							</div>
						</div>
						<div class="pull-right breadcrumbs_right_section">
							<div class="page_breadcrumbs_menu">
								<a href="" class="btn btn-success"><span></span>My Subscriptions
								</a>
								<a href="" class="btn btn-success"><span></span>Membership Packages
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12" id="content">

				<div class="_block_content">
					<div class="extra_info">
						The feature or section you are attempting to use is not permitted with your membership level.
					</div>
				</div>
			</div>
		</div>
	</div>
</div>