<div id="feed-lists" data-type="feed" data-type-id="" data-offset="0">
	<div class="line"></div>
	<?php $i = 0;
	foreach($feeds as $feed):
		$i++ ?>
		<?php echo view('export::feed/feed', array('feed' => $feed)) ?>
	<?php endforeach ?>

</div>
<?php if(!count($feeds)): ?>
	<div class="feed-empty text-center">
		<i class="ion-android-bicycle"></i>
		<h3><?php echo lang('no-post-show') ?></h3>
		<a href="<?php echo url('suggestions') ?>" ajax="true" class="btn btn-secondary btn-upper"><?php echo lang('find-people') ?></a>
	</div>
<?php endif ?>
