<div class="box">
	<div class="title"><?php echo lang('page::my-pages') ?></div>
	<div class="box-content">
		<?php if($pages->total): ?>
			<?php foreach($pages->results() as $page): ?>
				<?php echo view('page::display', array('page' => $page)) ?>
			<?php endforeach ?>

			<?php echo $pages->links() ?>
		<?php else: ?>
			<?php echo lang('no-saved-content') ?>
		<?php endif ?>
	</div>
</div>