<?php if(is_loggedIn() && isset($app->profileEvent)): ?>
	<div class="box">
		<div class="title"><?php echo lang('event::event-subscribers') ?></div>
		<div class="box-content">
			<?php foreach(get_event_subscribers($limit)->results() as $subscriber): ?>
				<?php $user = $subscriber['user_id']; ?>
				<div class="media media-sm">
					<div class="media-left">
						<div class="media-object">
							<img src="<?php echo get_avatar(75, find_user($user)) ?>"/>
						</div>
					</div>
					<div class="media-body">
						<h6 class="media-heading"><?php echo get_user_name($user) ?></h6>
					</div>
				</div>
			<?php endforeach ?>
		</div>
	</div>
<?php endif ?>