<div class="box livestream-content">
	<div class="global-filter-container" data-url="<?php echo url('livestreams') ?>">
		<form id="livestream-list-search" method="post" onsubmit="return run_global_filter()" action="" class="form-inline list-search">
			<?php CSRFProtection::embed() ?>
			<i class="search-icon ion-ios-search"></i>
			<input value="<?php echo input('s') ?>" type="text" class="form-control search-box filter-input" data-name="s" placeholder="<?php echo lang('search') ?>"/>
            <?php if(input('u')): ?>
    			<input value="<?php echo input('u') ?>" type="hidden" class="form-control filter-input" data-name="u" />
            <?php endif; ?>
		</form>
		<div class="list-head">
			<h3 class="heading"><?php echo lang('livestream::livestreams') ?></h3>
		</div>
		<div class="filter-pane">
			<select id="livestream-category-list" onchange="return run_global_filter()" data-name="c" class="c-select filter-input">
				<option <?php echo (input('c', 'all') == 'all') ? 'selected' : null ?> value="all"><?php echo lang('livestream::all-categories') ?></option>
				<?php foreach(Livestream::getCategories() as $category): ?>
					<?php $sub_categories = Livestream::getCategories($category['id']) ?>
					<?php if($sub_categories): ?>
						<optgroup label="<?php echo lang($category['title']) ?>">
							<?php foreach($sub_categories as $cat): ?>
								<option <?php echo (input('c', 'all') == $cat['id']) ? 'selected' : null ?> value="<?php echo $cat['id'] ?>"><?php echo lang($cat['title']) ?></option>
							<?php endforeach ?>
						</optgroup>
					<?php else: ?>
						<option <?php echo (input('c', 'all') == $category['id']) ? 'selected' : null ?> value="<?php echo $category['id'] ?>"><?php echo lang($category['title']) ?></option>
					<?php endif ?>
				<?php endforeach ?>
			</select>
			<select id="livestream-filter-select" onchange="return run_global_filter()" data-name="t" class="c-select filter-input">
				<option value="all"><?php echo lang('all') ?></option>
				<option <?php echo (input('t') == 'f') ? 'selected' : '' ?> value="f"><?php echo lang('livestream::featured') ?></option>
				<option <?php echo (input('t') == 'o') ? 'selected' : '' ?> value="o"><?php echo lang('livestream::ongoing') ?></option>
			</select>
		</div>
	</div>
	<div id="livestreams-list-container" class="box-content clearfix list-listing-container">
		<?php foreach($livestreams->results() as $livestream): ?>
			<?php echo view('livestream::livestream/list_item', array('livestream' => $livestream)) ?>
		<?php endforeach ?>
	</div>
	<?php if($livestreams->total): ?>
		<div class="box-content">
			<?php $appends = array(); ?>
			<?php if(input('c')) $appends['c'] = input('c'); ?>
			<?php if(input('s')) $appends['s'] = input('s'); ?>
			<?php if(input('t')) $appends['t'] = input('t'); ?>
			<?php echo $livestreams->append($appends)->links(); ?>
		</div>
	<?php else: ?>
		<div class="box-content">
			<div class="alert alert-info"><?php echo lang('livestream::no-livestreams-found-here') ?></div>
		</div>
	<?php endif ?>
</div>