<div class="editor-action col-md-4">
    <a id="feed-editor-livestream-start" href="<?php echo url_to_pager('livestream-add') ?>" data-toggle="modal" data-target="#livestream-modal" data-title="<?php echo lang('livestream::stream-live') ?>" title="<?php echo lang('livestream::stream-live') ?>">
        <i class="ion-radio-waves"></i>
        <label><?php echo lang('livestream::go-live') ?></label>
    </a>
</div>