 <?php if(is_loggedIn()): ?>
	<?php load_functions("relationship::relationship");
	$users = relationship_suggest($limit, null, true); ?>
	<?php if($users->total): ?>
		<div class="box users-box" id="people-suggestion-box">
			<div class="title">
				<?php echo lang('relationship::people-suggestion') ?>
				<a ajax="true" href="<?php echo url_to_pager('suggestions') ?>"><i class="ion-ios-arrow-forward pull-right"></i></a>
			</div>
			<div class="clearfix slider-side-widget">
				<?php foreach($users->results() as $user): ?>
					<a style="background-image: url(<?php echo get_avatar(200, $user) ?>)" class="user" ajax="true" href="<?php echo profile_url(null, $user) ?>">

						<h6 class="name"><?php echo get_user_name($user) ?> <?php echo verify_badge($user) ?></h6>
					</a>
				<?php endforeach ?>
			</div>
		</div>
	<?php endif ?>
<?php endif ?>