<div class="wrapper">
	<div class="wrapper-title">
		<?php echo lang('bulk-text-messaging') ?>
	</div>
	<div class="wrapper-content">
		<form method="post" action="" enctype="multipart/form-data" class="" style="margin: 20px auto;width: 70%">
			<?php CSRFProtection::embed() ?>
			<?php if($message): ?>
				<div class="alert alert-info"><?php echo $message ?></div>
			<?php endif ?>
			<div class="form-group row">
				<label class="col-sm-3 form-control-label"><?php echo lang('text-message-recipients') ?></label>
				<div class="col-sm-9">
					<select onchange="open_text_messaging_selector(this)" class="c-select" name="val[to]">
						<option value="all"><?php echo lang('all-members') ?></option>
						<option value="selected"><?php echo lang('selected-members') ?></option>
						<option value="non-active"><?php echo lang('non-active-members') ?></option>
					</select>
					<div class="text-message-to-selectors" id="text-message-selected-members">
						<div class="">
							<input onkeyup="suggest_text_message_users(this)" type="text" placeholder="Type member name"/>
						</div>
						<div class="user-suggestion"></div>
					</div>
					<div class="text-message-to-selectors" id="text-message-non-active-members">
						<label class="form-control-label"><?php echo lang('non-active-for-last') ?></label>
						<div class="row">
							<div class="col-sm-6">
								<input type="text" name="val[non][number]" value="1" class="form-control"/>
							</div>
							<div class="col-sm-6">
								<select class="c-select" name="val[non][type]">
									<option value="month"><?php echo lang('month') ?></option>
									<option value="day"><?php echo lang('day') ?></option>
									<option value="year"><?php echo lang('year') ?></option>
								</select>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-3 form-control-label"><?php echo lang('text-message-body') ?></label>
				<div class="col-sm-9">
					<textarea name="val[body]" rows="10" class="form-control"></textarea>
				</div>
			</div>
			<button class="btn btn-info"><?php echo lang('send-text-message') ?></button>
		</form>
	</div>
</div>