<?php $user = find_user($notification['type_id']); ?>
<?php $gender = (isset($user['gender']) and $user['gender']) ? $user['gender'] : null ?>
<?php $gender_image = ($gender) ? img("images/avatar/{$gender}.png") : img("images/avatar.png") ?>
<?php $user_image = $user['avatar'] ? url_img($user['avatar'], 75) : $gender_image ?>
<div id="notification-<?php echo $notification['notification_id'] ?>" class="notification media media-md  <?php echo ($notification['mark_read'] == 0) ? 'notification-unread' : null ?>">
    <div class="media-left">
        <div class="media-object">
            <a ajax="true" href="<?php echo url_to_pager('matchmaker-matches') ?>"><img src="<?php echo $user_image; ?>" /></a>
        </div>
    </div>
    <div class="media-body">
        <a ajax="true" href="<?php echo url_to_pager('matchmaker-matches') ?>">
            <h6 class="media-heading">
                <?php echo lang('matchmaker::you-and') ?>
                <?php echo get_user_name($user); ?>
                <?php echo lang('matchmaker::matched-you') ?>
            </h6>
        </a>
        <span style="display: block" class="timeago" title="<?php echo date('c', $notification['time']) ?>"><?php echo date('c', $notification['time']) ?></span>
        <div class="actions">
            <a class="mark-button" data-status="<?php echo $notification['mark_read'] ?>" data-read="<?php echo lang('notification::read') ?>" data-mark="<?php echo lang('notification::mark-as-read') ?>" title="<?php echo ($notification['mark_read'] == 1) ? lang('notification::read') : lang('notification::mark-as-read') ?> " onclick="return notification.markRead('<?php echo $notification['notification_id'] ?>')" href="#!"><i class="ion-checkmark-circled"></i></a>
            <a onclick="return notification.delete('<?php echo $notification['notification_id'] ?>')" href="#!"><i class="ion-close"></i></a>
        </div>
    </div>
</div>