<div class="box-content">
    <form action="" method="post" enctype="multipart/form-data" class="ajax-form blog-contest-add">
        <div class="form-group">
            <label><?php echo lang("contest::blog-title"); ?></label>
            <input type="text" class="form-control" name="val[title]" value="<?php echo isset($entry['title']) ? $entry['title'] : input('title'); ?>"/>
        </div>
        <div class="form-group">
            <label><?php echo lang("contest::blog-image"); ?></label>
            <div class="magic-input-image-preview" data-name="image">
                <span class="dimension"></span>
            </div>

            <?php if(isset($entry['image'])): ?>
            <div class="box-content">
                <img src="<?php echo url_img($entry['image']) ?>" style="height:50px;width: 50px " />
            </div>
            <?php endif; ?>
        </div>
        <div class="form-group">
            <label><?php echo lang("contest::blog-content"); ?></label>
            <textarea name="val[content]" class="ckeditor"
                      placeholder="<?php echo lang('blog::blog-content') ?>"><?php echo isset($entry['content']) ? $entry['content'] : input('content'); ?></textarea>
        </div>
        <div class="form-group">
            <button class="btn btn-info"><?php echo lang("contest::submit-entry") ?></button>
            <?php if($entry): ?>
            <a href="<?php echo getEntryContestUrl($contest,$entry).'?action=del'; ?>" class="btn btn-danger"><?php echo lang("contest::delete-entry") ?></a>
            <?php endif; ?>
        </div>
    </form>
</div>