<?php if(!$details): ?>
<?php else: ?>
	<div class="link-content-container">
		<input class="editor-form-data" type="hidden" value="<?php echo perfectSerialize($details) ?>" name="val[link_details]"/>
		<?php if(isset($editor) and $editor): ?>
			<a onclick="return feed.editor.removeLinkDetails()" class="close-button" href=""><i class="ion-close"></i></a>
		<?php endif ?>
		<?php if(($details['type'] == 'link' || !$details['code'] || (isset($_SERVER["HTTPS"]) && $_SERVER["HTTPS"] == 'on') && preg_match('/^http:\/\//i', $details['link'])) && !preg_match('/^(https?\:\/\/)?(www\.)?(youtube\.com|youtu\.?be|vineo\.com|dailymotion\.com)\/(.+)$/i', $details['link'])): ?>
			<div class="link">
				<?php if(empty($details['image'])): ?>
					<div class="link-desc">
						<a nofollow='nofollow' href='javascript:void(0)' onclick="return window.open('<?php echo $details['link'] ?>')">
							<h6 class="link-title"><?php echo sanitizeText($details['title']) ?></h6>
						</a>
						<?php if($details['description']): ?>
							<p class="help-block"><?php echo sanitizeText(str_limit($details['description'], 200)) ?></p>
						<?php endif ?>
					</div>
					<?php //elseif($details['imageWidth'] < 150):?>
					<!-- <div class="media">
                        <div class="media-left">
                            <a style="background-image:url(<?php echo $details['image'] ?>)" nofollow='nofollow' href='javascript:void(0)' onclick="return window.open('<?php echo $details['link'] ?>')"><img src="<?php echo $details['image'] ?>" style="display: none;" /></a>
                        </div>
                        <div class="media-body">
                            <a nofollow='nofollow' href='javascript:void(0)' onclick="return window.open('<?php echo $details['link'] ?>')"><h6 class="link-title"><?php echo sanitizeText($details['title']) ?></h6></a>
                            <?php if($details['description']): ?>
                                <p class="help-block"><?php echo sanitizeText(str_limit($details['description'], 200)) ?></p>
                            <?php endif ?>

                        </div>
                    </div> -->
				<?php else: ?>
					<div class="media">
						<div class="image">
						<?php $details['image'] = isset($_SERVER["HTTPS"]) && $_SERVER["HTTPS"] == 'on' ? preg_replace('/^http:/i', 'https:', $details['image']) : $details['image'] ?>
							<a style="background-image:url(<?php echo $details['image'] ?>)" nofollow='nofollow' href='javascript:void(0)' onclick="return window.open('<?php echo $details['link'] ?>')"><img src="<?php echo $details['image'] ?>" style="display: none;"/></a>
						</div>
						<div class="media-desc">
							<a nofollow='nofollow' href='javascript:void(0)' onclick="return window.open('<?php echo $details['link'] ?>')">
								<h6 class="link-title"><?php echo sanitizeText($details['title']) ?></h6>
							</a>
							<?php if($details['description']): ?>
								<p class="help-block"><?php echo sanitizeText(str_limit($details['description'], 200)) ?></p>
							<?php endif ?>
						</div>
					</div>
				<?php endif ?>
			</div>
		<?php else: ?>
			<div class="embed">
				<div class="feed-video-embed-container" id="feed-video-embed-container-<?php echo isset($feed['feed_id']) ? $feed['feed_id'] : abs(crc32(uniqid())); ?>">
					<?php $code = $details['code'] ? $details['code'] : '<iframe src="'.preg_replace('/(youtube|dailymotion)\.com\/watch\?(.*?)(v=([a-zA-Z0-9_]{6,}))(.*)?/i', '$1.com/embed/$4/', $details['link'], 1).'" frameborder="0" allowfullscreen></iframe>' ?>
					<?php //$code = isset($_SERVER["HTTPS"]) && $_SERVER["HTTPS"] == 'on' ? str_replace('http://', 'https://', $code) : $code ?>
					<?php echo preg_replace('/(width=)("|\')(.*?)("|\')/i', '${1}${2}100%${4}', $code) ?>
				</div>
				<div class="desc">
					<a nofollow='nofollow' href='javascript:void(0)' onclick="return window.open('<?php echo $details['link'] ?>')">
						<h6 class="link-title"><?php echo sanitizeText($details['title']) ?></h6>
					</a>
					<?php if($details['description']): ?>
						<p class="help-block"><?php echo sanitizeText(str_limit($details['description'], 200)) ?></p>
					<?php endif ?>
					<p class="help-block"><?php echo $details['provider-url'] ?></p>
				</div>
			</div>
		<?php endif ?>
	</div>
<?php endif ?>