<div class="row">
	<div class="col-sm-12">
		<div class="box">
			<div class="hashtag-list">
				<div class="head">
					<div class="cover" style="background-image: url(<?php echo url_img(config('hashtag-list-cover', 'plugins/hashtag/images/cover.jpg'), 920); ?>)">
						<div class="title"><?php echo lang('discover') ?></div>
					
					</div>
					<div class="box-content">
						<div id="trending-wide" class="clearfix">
							<?php foreach(get_top_hashtags(6) as $hashtag): ?>
								<a ajax="true" href="<?php echo url_to_pager('hashtag') ?>?t=<?php echo str_replace('#', '', $hashtag['hashtag']) ?>"><?php echo $hashtag['hashtag'] ?></a>
							<?php endforeach ?>
						</div>
						<form action="" method="post">
							<?php CSRFProtection::embed() ?>
							<input value="<?php echo input('t') ?>" name="t" type="text" class="form-control" placeholder="<?php echo lang('hashtag::discover-hashtag') ?>"/>
							<button class="btn btn-sm btn-info"><?php echo lang('discover') ?></button>
						</form>

					</div>
				</div>
			</div>
		</div>

		<div id="feed-lists" data-type="hashtag" data-type-id="<?php echo input('t') ?>" data-offset="0">
			<?php $i = 0;
			foreach($feeds as $feed):fire_hook('feed.lists.inline', null, array($i));
				$i++ ?>
				<?php echo view('feed::feed', array('feed' => $feed)) ?>
			<?php endforeach ?>


		</div>
		<?php if(!count($feeds)): ?>
			<div class="feed-empty text-center">
				<i class="ion-android-bicycle"></i>
				<h3><?php echo lang('no-post-show') ?></h3>
				<a href="" class="btn btn-secondary btn-upper"><?php echo lang('find-people') ?></a>
			</div>
		<?php endif ?>
		<?php if(count($feeds)): ?>
			<div class="feed-load-more">
				<div class="col-sm-2 no-padding"></div>
				<div class="col-sm-10 no-padding">
					<div class="feed-loading">
						<div class="feed_loading_post">
							<div class="feed_loading_post_child2">

							</div>
						</div>
					</div>
				</div>
			</div>
		<?php endif ?>
	</div>
</div>