<div class="box">
    <div class="title"><?php echo $contest['name'].' / '.lang("contest::entries"); ?>
        <span class="pull-right">(<?php echo $entry->total ?>) <?php echo lang("contest::entries-bracket") ?></span>
    </div>
    <div class="global-filter-container" data-url="<?php echo contestUrl($contest).'/entries' ?>">
        <form id="blog-list-search" method="post" onsubmit="return run_global_filter()" action="" class="form-inline list-search">
            <?php CSRFProtection::embed() ?>
            <i class="search-icon ion-ios-search"></i>
            <input value="<?php echo input('term') ?>" type="text" class="form-control search-box filter-input" data-name="term" placeholder="<?php echo lang('contest::search-entries') ?>"/>
        </form>
        <!--<div class="list-head">
            <h3 class="heading"><?php /*echo lang('blog::blogs') */?></h3>
        </div>-->
        <div class="filter-pane">

            <select id="video-filter-select" onchange="return run_global_filter()" data-name="filter" class="c-select filter-input">
                <option value="all"><?php echo lang('contest::sort-by') ?></option>
                <option <?php echo (input('filter') == 'latest') ? 'selected' : null ?> value="latest"><?php echo lang('contest::recently-add') ?></option>
                <option <?php echo (input('filter') == 'most-views') ? 'selected' : null ?> value="most-views"><?php echo lang('contest::most-views') ?></option>
                <option <?php echo (input('filter') == 'highest-votes') ? 'selected' : null ?> value="highest-votes"><?php echo lang('contest::highest-votes') ?></option>
            </select>
        </div>
    </div>
<div class="box-content">

    <?php if($entry->total): ?>
        <?php foreach($entry->results() as $blog): ?>
        <?php $user = find_user($blog['user_id']); ?>
            <div class="media media-sm">
                <div class="media-left">
                    <div class="media-object">
                        <img src="<?php echo ($blog['image']) ? url_img($blog['image'], 200) : get_avatar(200, $user) ?>"/>
                    </div>
                </div>
                <div class="media-body">
                    <h4 class="media-heading" style="margin-top:0">
                        <a ajax="true" href="<?php echo getEntryContestUrl($contest,$blog); ?>"><?php echo ($blog['title']) ? $blog['title'] : lang('contest::untitled') ?></a>
                    </h4>
                    <span class="help-block" style="display: block;font-size:12px">
                            <?php echo lang('blog::posted-by') ?>:
            <a ajax="true" href="<?php echo profile_url(null,$user); ?>"><?php echo get_user_name($user); ?></a>
                        <br/><b><?php echo ucwords(lang('contest::on')) ?> : </b> <?php echo date('M j , Y  h:i A', $blog['time']) ?>
                        <?php if($contest['user_id'] == get_userid()): ?>
                            <span class="pull-right">
                            <a href="" class="text-danger re-by-ca"
                               data-cid="<?php echo $contest['id']; ?>"
                               data-eid="<?php echo $blog['id']; ?>"
                               data-etype="<?php echo $blog['ref_name']; ?>"
                            ><i class="ion-android-delete"></i> <em><?php echo lang("contest::remove-this-entry") ?></em></a>
                        </span>
                        <?php endif; ?>
                        <br/><b><?php echo lang('contest::views') ?> :  </b> <?php echo $blog['views']; ?>&nbsp;&nbsp;
                        <b><?php echo lang('contest::votes') ?> : </b> <?php echo contestEntryVoteCount($blog['ref_name'],$blog['id']) ?>

                    </span>
                </div>
            </div>
            <hr/>
        <?php endforeach; ?>
        <div class="box-content">
            <?php echo $entry->links(); ?>
        </div>
    <?php else: ?>
        <div class="alert alert-info"><?php echo lang("contest::empty-lists") ?></div>
    <?php endif; ?>
</div>
</div>