<div class="box store-container">
    <div class="title">
        <?php _lang('store::add-producer'); ?>
    </div>
    <div class="box-content" style="padding: 20px 10%">

        <?php if($message): ?>
            <div class="alert alert-danger"><?php echo $message ?></div>
        <?php endif; ?>

        <form class="producer-form" action="" method="post" enctype="multipart/form-data">
            <?php CSRFProtection::embed()?>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::name')?><span class="important">*</span></label>
                <div class="col-sm-8">
                    <input value="<?php echo input('val.name')?>" type="text" name="val[name]" class="form-control"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::email')?></label>
                <div class="col-sm-8">
                    <input value="<?php echo input('val.email')?>" type="text" name="val[email]" class="form-control"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::phone')?></label>
                <div class="col-sm-8">
                    <input value="<?php echo input('val.phone')?>" type="text" name="val[phone]" class="form-control"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::address')?></label>
                <div class="col-sm-8">
                    <input value="<?php echo input('val.address')?>" type="text" name="val[address]" class="form-control"/>
              </div>
                </div>
         <!--   <div class="form-group row">
                <label class="control-label col-sm-4"><?php /*_lang('store::category')*/?><span class="important">*</span></label>
                <div class="col-sm-8">
                    <select class="c-select" name="val[category]">
                        <option value=""><?php /*echo lang("store::select-one") */?></option>
                   <?php
/*                      foreach(lp_store_categories('get_categories') as $c):
                   */?>
                       <option value="<?php /*echo lang($c['title']); */?>"><?php /*echo lang($c['title']); */?></option>

                        <?php /*endforeach; */?>
                    </select>
                </div>
            </div>-->


            <div class="form-group row">
                <div class="col-sm-5">
                </div>
                <div class="col-sm-4">
                    <div class="input-field col s12">
                        <input type="submit" value="<?php echo lang('store::create') ?>" class="btn btn-info btn-sm" />
                    </div>
                </div>
            </div>


        </form>
   </div>
</div>