<div class="box store-container">
    <div class="title">
        <?php _lang('store::edit-producer'); ?>
    </div>
    <div class="box-content" style="padding: 20px 10%">

        <?php if($message): ?>
            <div class="alert alert-danger"><?php echo $message ?></div>
        <?php endif; ?>

        <form class="producer-form" action="" method="post" enctype="multipart/form-data">
            <?php CSRFProtection::embed()?>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::name')?><span class="important">*</span></label>
                <div class="col-sm-8">
                    <input value="<?php echo ($producer['name'])? $producer['name'] :input('val.name')?>" type="text" name="val[name]" class="form-control"/>
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::email')?></label>
                <div class="col-sm-8">
                    <input value="<?php echo ($producer['email'])? $producer['email'] :input('val.email')?>" type="text" name="val[email]" class="form-control"/>
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::address')?></label>
                <div class="col-sm-8">
                    <input value="<?php echo ($producer['address'])? $producer['address'] :input('val.address')?>" type="text" name="val[address]" class="form-control"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::phone')?></label>
                <div class="col-sm-8">
                    <input value="<?php echo ($producer['phone'])? $producer['phone'] :input('val.phone');?>" type="text" name="val[phone]" class="form-control"/>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-5">
                </div>
                <div class="col-sm-4">
                    <div class="input-field col s12">
                        <input type="submit" value="<?php _lang('save'); ?>" class="btn btn-info btn-sm" />
                    </div>
                </div>
            </div>


        </form>
    </div>
</div>