<div class="box">
	<div class="global-filter-container" data-url="<?php echo url('groups') ?>">
		<div class="row">
			<div class="col-sm-6">
				<h3><?php echo lang('group::groups') ?></h3>
			</div>

		</div>
	</div>
	<div id="group-list-container" class="box-content clearfix list-listing-container">
		<?php foreach($groups->results() as $group): ?>
			<?php echo view('group::display', array('group' => $group)) ?>
		<?php endforeach ?>
	</div>
	<div class="box-content">
		<?php if(!$groups->total): ?>
			<?php echo lang('group::no-grouo-found') ?>
		<?php else: ?>
			<?php echo $groups->links(true) ?>
		<?php endif ?>
	</div>
</div>