<div class="box">
	<div class="title">
		<?php echo lang('creditgift::send-credit') ?>
	</div>
	<div class="box-content">
		<form action="" method="post">
            <div class="row" style="margin: 0px">
                <div class="col-sm-6" style="padding: 0px">
                    <input min="1" type="number" id="credit_quantity" class="form-control" />
                </div>
                <div class="col-sm-6" style="padding: 0px 0px 0px 15px">
                    <a href="#" onclick="return creditgift_show_friends(this, event)" class="btn btn-info action-button" id="submit"><?php echo lang('creditgift::send-credit') ?></a>
                </div>
            </div>
		</form>
	</div>
</div>