<div class="wrapper">
	<div class="wrapper-title">
		<?php echo lang('ads::ads-plan') ?>
		<a class="btn btn-secondary"
		   href="<?php echo url_to_pager('admin-ads-add-plan') ?>"><?php echo lang('ads::add-plan') ?></a>
	</div>
	<div class="wrapper-content">
		<div class="list-table-container">
			<div class="row list-table-select-actions hide" data-group="users">
				<div class="col-sm-12">
					<a href="<?php echo url_to_pager('admin-ads-plan-batch-action') ?>?action=delete"
					   class="action-link list-table-select-action" data-group="users"><?php echo lang('delete') ?></a>
				</div>
			</div>
			<div class="table-responsive">
				<table class="table table-striped list-table">
					<thead>
					<tr>
						<th>
							<div class="list-table-select" data-group="users" data-id="0"></div>
						</th>
						<th style="width: 10%">ID</th>
						<th style="width: 30%"><?php echo lang('ads::plan-name') ?></th>
						<th style="width: 20%"><?php echo lang('ads::plan-type') ?></th>
						<th style="width: 15%"><?php echo lang('ads::plan-price') ?></th>
						<th style="width: 15%"><?php echo lang('ads::plan-quantity') ?></th>
						<th style="width: 20%"><?php echo lang('actions') ?></th>
					</tr>
					</thead>
					<tbody data-url="<?php echo url_to_pager('admin-ads-manage-plan').'?action=order' ?>"
					       class="admincp-sortable" style="position: relative">
					<?php foreach($plans as $plan): ?>
						<tr class="item" id="<?php echo $plan['id'] ?>">
							<th>
								<div class="list-table-select" data-group="users" data-id="<?php echo $plan['id'] ?>"></div>
							</th>
							<td><?php echo $plan['id'] ?></td>
							<td><?php echo lang($plan['name']) ?></td>
							<td><?php echo ($plan['type'] == 1) ? lang('ads::clicks') : lang('ads::impression') ?></td>
							<td><?php echo $plan['price'] ?> (<?php echo config('default-currency', 'USD') ?>)</td>
							<td><?php echo $plan['quantity'] ?></td>
							<!--td>
                            <a class="btn btn-sm btn-success"
                               href="<?php echo url_to_pager('admin-ads-manage-plan').'?action=edit&id='.$plan['id'] ?>"><?php echo lang('edit') ?></a>
                            <a class="btn btn-sm btn-danger"
                               href="<?php echo url_to_pager('admin-ads-manage-plan').'?action=delete&id='.$plan['id'] ?>"><i
                                        class="ion-android-delete"></i></a>
                        </td-->

							<td>
								<div class="dropdown actions">
									<a href="#" data-toggle="dropdown">
										<i class="ion-android-settings"></i>
									</a>
									<div class="dropdown-menu dropdown-menu-right">
										<a class="ion-edit"
										   href='<?php echo url_to_pager('admin-ads-manage-plan').'?action=edit&id='.$plan['id'] ?>'></a>
										|
										<a class="admin-confirm ion-android-delete"
										   href="<?php echo url_to_pager('admin-ads-manage-plan').'?action=delete&id='.$plan['id'] ?>"></a>
									</div>
								</div>
							</td>
						</tr>
					<?php endforeach ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>