<?php $ed = Educational::getInstance(); ?>
<input type="hidden" id="RatingStatus" value="<?php echo ($ed->hasRated('books',$book['id'])) ? 'yes' : 'no' ?>"/>
<div data-type="books" data-typeid="<?php echo $book['id'] ?>" class="books-rating-container"
     data-myrating="<?php echo $ed->getUserRating('books', $book['id']) ?>">
    <?php $r = $ed->getItemRatings('books', $book['id']);
    //print_r($r);
    $rating = $ed->getAverageRating($r);
    ?>

    <span>
                                <input type="hidden" id="myBookrating"
                                       value="<?php echo $ed->getUserRating('books', $book['id']) ?>"/>
                                <i data-id="1"
                                   class="ion-android-star <?php echo ($rating > 0) ? 'background-rating' : '' ?> star1 rating-books"></i>
                                <i data-id="2"
                                   class="ion-android-star <?php echo ($rating > 1) ? 'background-rating' : '' ?>  star2 rating-books"></i>
                                <i data-id="3"
                                   class="ion-android-star <?php echo ($rating > 2) ? 'background-rating' : '' ?> star3 rating-books"></i>
                                <i data-id="4"
                                   class="ion-android-star <?php echo ($rating > 3) ? 'background-rating' : '' ?> star4 rating-books"></i>
                                <i data-id="5"
                                   class="ion-android-star <?php echo ($rating > 4) ? 'background-rating' : '' ?> star5 rating-books"></i>
                            </span>
    <span>
        <?php
        echo (int)count($r).' ';
        echo ' '.(count($r) > 1) ? lang('educational::rating') : lang('educational::ratings')
        ?></span>


</div>