<div class="feed-footer">
    <ul class=" feed-footer-menu clearfix">
        <?php if(plugin_loaded('like')):?>
            <?php load_functions('like::like');?>
            <li><a  onclick="return like_item('<?php echo $refName?>', '<?php echo $refId?>')" data-status="<?php echo (has_liked($refName, $refId)) ? '1'  : 0?>" class=" like-button-<?php echo $refName?>-<?php echo $refId?> like-button <?php echo (has_liked($refName, $refId)) ? 'liked'  : null?>" href=""> <i class="ion-thumbsup"></i> <?php echo lang('like::like')?></a> </li>
            <?php if (config('enable-dislike', false)):?>
                <li><a id="" onclick="return dislike_item('<?php echo $refName?>', '<?php echo $refId?>')" data-status="<?php echo (has_disliked($refName, $refId)) ? '1'  : 0?>" class="dislike-button-<?php echo $refName?>-<?php echo $refId?> like-button <?php echo (has_disliked($refName, $refId)) ? 'disliked'  : null?>" href=""> <i class="ion-thumbsdown"></i> <?php echo lang('like::dislike')?></a> </li>
            <?php endif?>
        <?php endif?>
        <li class="blog-social-share"><?php if(plugin_loaded('sharer')) echo view('sharer::share_link', array('link' => getFullUrl())) ?></li>
        <?php fire_hook('more-feed-footer',null,array($refName,$refId)); ?>
        <li class="pull-right">
            <ul class="feed-statistics">
                <?php if(plugin_loaded('like')):?>
                    <li><a onclick="return show_likes('<?php echo $refName?>', '<?php echo $refId?>')" href=""> <i class="ion-thumbsup"></i> <span class="like-count-<?php echo $refName?>-<?php echo $refId?>"><?php echo count_likes($refName, $refId)?></span></a></li>
                    <?php if (config('enable-dislike', false)):?>
                        <li><a onclick="return show_dislikes('<?php echo $refName?>', '<?php echo $refId?>')" href=""> <i class="ion-thumbsdown"></i> <span class="dislike-count-<?php echo $refName?>-<?php echo $refId?>"><?php echo count_dislikes($refName, $refId)?></span></a></li>
                    <?php endif?>

                <?php endif?>

                <?php if(plugin_loaded('comment')):?>
                    <?php load_functions('comment::comment')?>
                    <?php $countComments = count_comments($refName, $refId);?>
                    <li> <i class="ion-chatbubbles"></i> <span class="comment-count-<?php echo $refName?>-<?php echo $refId?>"><?php echo ($countComments) ? $countComments : null?></span></li>
                <?php endif?>
                <?php fire_hook('more-feed-footer-count',null,array($refName,$refId)); ?>
            </ul>
        </li>
    </ul>
</div>