<div class="box">
	<div class="title"><?php echo lang('photo::create-new-album') ?></div>
	<div class="box-content" style="padding: 10px 10%">
		<?php if($message): ?>
			<div class="alert alert-danger"><?php echo $message ?></div>
		<?php endif ?>
		<form action="" method="post">
			<?php CSRFProtection::embed() ?>
			<div class="form-group row">
				<label class="control-label col-sm-4"><?php echo lang('photo::album-title') ?></label>
				<div class="col-sm-8">
					<input value="<?php echo input('val.name') ?>" type="text" name="val[name]" class="form-control"/>
				</div>
			</div>

			<div class="form-group row">
				<label class="control-label col-sm-4"><?php echo lang('photo::album-description') ?></label>
				<div class="col-sm-8">
					<textarea name="val[description]" data-height="100px" style="height: 100px" class="form-control auto-grow-input"><?php echo input('val.description') ?></textarea>
				</div>
			</div>
			<div class="form-group row">
				<label class="control-label col-sm-4"><?php echo lang('privacy') ?></label>
				<div class="col-sm-8">
					<?php fire_hook('privacy.select'); ?>
				</div>
			</div>
			<button class="btn btn-primary"><?php echo lang('photo::create-album') ?></button>
		</form>
	</div>
</div>