<div class="wrapper">
	<div class="wrapper-title">
		<p><?php echo lang('business::add-category') ?></p>
		<span><?php echo lang('business::add-category-desc') ?></span>
	</div>
	<div class="wrapper-content">
		<?php if(isset($message)): ?>
			<div class="alert alert-danger"><?php echo $messages ?></div>
		<?php endif ?>
		<form action="" class="adm" method="post">
			<?php CSRFProtection::embed() ?>
			<div class="form-group row">
				<label class="col-sm-3 form-control-label"><?php echo lang('business::category-title') ?></label>
				<div class="col-sm-9">
					<input class="form-control" type="text" name="val[title]" placeholder="<?php echo lang('property::category-title') ?>"/><br>
					<p class="help-block"><?php ?></p>

				</div>
			</div>
			<div class="row">
				<div class="col-sm-5"></div>
				<div class="col-sm-7">
					<input type="submit" value="<?php echo lang('business::add-cat') ?>" class="btn btn-info"/>
				</div>
			</div>
			<input type="hidden" name="val[type]" value="add_category"/>
		</form>
	</div>
</div>