<div class="container">
	<div id="error-page-content">
		<svg width="100%" height="80vh" xmlns="http://www.w3.org/2000/svg">
			<defs>
				<linearGradient id="bicolored">
					<stop offset="50%" stop-color="<?php echo config('header-bg-color', '#4C4C4E') ?>" />
					<stop offset="50%" stop-color="#FFFFFF" />
				</linearGradient>
				<linearGradient id="bicolored-inverted">
					<stop offset="50%" stop-color="#FFFFFF" />
					<stop offset="50%" stop-color="<?php echo config('header-bg-color', '#4C4C4E') ?>" />
				</linearGradient>
			</defs>
			<rect x="0" y="0" width="100%" height="100%" fill="url(#bicolored-inverted)"></rect>
			<text x="50%" y="30%" fill="url(#bicolored)" text-anchor="middle" class="text-xl">404</text>
			<text x="50%" y="60%" fill="url(#bicolored)" text-anchor="middle" class="text-l hide-in-mobile"><?php echo lang('not-found') ?></text>
			<text x="50%" y="50%" fill="url(#bicolored)" text-anchor="middle" class="text-l show-in-mobile"><?php echo lang('not-found') ?></text>
			<text x="50%" y="80%" fill="url(#bicolored)" text-anchor="middle" class="text-s hide-in-mobile"><?php echo lang('page-not-available') ?></text>
			<text x="50%" y="65%" fill="url(#bicolored)" text-anchor="middle" class="text-s show-in-mobile"><?php echo split_phrase(lang('page-not-available'))[0] ?></text>
			<text x="50%" y="70%" fill="url(#bicolored)" text-anchor="middle" class="text-s show-in-mobile"><?php echo split_phrase(lang('page-not-available'))[1] ?></text>
			<text x="50%" y="90%" fill="url(#bicolored)" text-anchor="middle" class="text-xs hide-in-mobile"><?php echo lang('page-not-available-note') ?></text>
			<text x="50%" y="80%" fill="url(#bicolored)" text-anchor="middle" class="text-xs show-in-mobile"><?php echo split_phrase(lang('page-not-available-note'))[0] ?></text>
			<text x="50%" y="85%" fill="url(#bicolored)" text-anchor="middle" class="text-xs show-in-mobile"><?php echo split_phrase(lang('page-not-available-note'))[1] ?></text>
		</svg>
	</div>
</div>