<?php if(isset(app()->contest)): ?>
	<?php $contests = get_contests('related', null, null, null, $limit, null, app()->contest); ?>
	<?php if($contests->total): ?>
		<div class="box">
			<div class="title">
				<?php echo lang('contest::related-contests') ?>
				<a ajax="true" href="<?php echo url('contests') ?>"><i class="ion-ios-arrow-forward pull-right"></i></a>
			</div>
			<div class="box-content">
				<?php foreach($contests->results() as $contest): ?>
					<?php $contest = arrange_contest($contest); ?>
                    <?php echo view("contest::widget-view",array('contest'=>$contest)); ?>
				<?php endforeach ?>
			</div>
		</div>
	<?php endif ?>
<?php endif ?>