<div class="box">
    <div class="title"><?php echo fire_hook('profile.music.title', lang('music::musics')) ?></div>
    <div class="music-list">
        <div class="body">
            <div class="listings">
                <div class="listing row">
                    <?php foreach($musics->results() as $music): ?>
                        <div class="col-md-6">
                            <?php echo view('music::music', array('music' => $music, 'playlist' => $playlist)) ?>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>
        </div>
    </div>
    <div class="box-content">
        <?php if(!$musics->total): ?>
            <div class="alert alert-info"><?php echo lang('music::no-music-found') ?></div>
        <?php else: ?>
            <?php echo $musics->append(array('category' => input('category'), 'term' => input('term'), 'type' => 'user-profile'))->links(); ?>
        <?php endif ?>
    </div>
</div>