<div class="panel-container login">
    <div class="pane-title">
        <?php $logo = config('site-logo');
        $logo_url = !$logo ? img('images/logo.png') : url_img($logo); ?>
        <a href="<?php echo url() ?>"><img class="logo" src="<?php echo $logo_url ?>" /></a>
    </div>
    <div class="title">
        <span><?php echo lang('login') ?></span>
    </div>
    <div class="card-block">
        <?php if ($message): ?>
            <div class="alert alert-danger">
                <?php echo $message ?>
                <br />
                <?php if (get_setting("login-trial-enabled", true) && session_get("sv_login_tries")): ?>
                    <strong><?php echo lang('trials') ?> : <?php echo session_get("sv_login_tries") ?></strong><?php endif; ?>
            </div>
        <?php endif ?>
        <form action="<?php echo url_to_pager('login') ?>" method="post">
            <?php CSRFProtection::embed() ?>
            <fieldset class="form-group">
                <input type="text" class="form-control form-control-lg" name="val[username]" placeholder="<?php echo lang('username-email-address') ?>" tabindex="1" />
            </fieldset>
            <fieldset class="form-group">
                <input type="password" class="form-control form-control-lg" name="val[password]" placeholder="<?php echo lang('your-password') ?>" />
            </fieldset>
            <div class="clearfix">
                <div class="checkbox pull-left">
                    <label class="c-input c-checkbox">
                        <input name="val[remember]" checked type="checkbox">
                        <span class="c-indicator"></span>
                        <?php echo lang('remember-me') ?>
                    </label>
                </div>
                <a ajax="true" href="<?php echo url_to_pager('forgot-password') ?>" class="pull-right"><?php echo lang('forgot-password') ?></a>
            </div>
            <button class="btn-submit"><?php echo lang('sign-in') ?></button>
        </form>
        <?php if (config('enable-facebook', false) || config('enable-twitter', false) || config('enable-googleplus', false) || config('enable-vk', false)): ?>
            <div id="social-links-container" style="background-color:transparent">
                <div class="sign-with-container">
                    <div class="text"><?php echo lang('login-with') ?></div>
                    <div class="line"></div>
                </div>
                <div class="content">
                    <ul id="home-social-links">
                        <?php if (config('enable-facebook', false)): ?>
                            <li>
                                <a class="facebook" href="<?php echo url_to_pager('facebook-auth') ?>"><i class="icon ion-social-facebook"></i>
                                </a>
                            </li>
                        <?php endif ?>
                        <?php if (config('enable-twitter', false)): ?>
                            <li>
                                <a class="twitter" href="<?php echo url_to_pager('twitter-auth') ?>"><i class="icon ion-social-twitter"></i>
                                </a>
                            </li>
                        <?php endif ?>
                        <?php if (config('enable-googleplus', false)): ?>
                            <li>
                                <a class="googleplus" href="<?php echo url_to_pager('googleplus-auth') ?>"><i class="fa fa-google"></i>
                                </a>
                            </li>
                        <?php endif ?>
                        <?php if (config('enable-vk', false)): ?>
                            <li>
                                <a class="vk" href="<?php echo url_to_pager('vk-auth') ?>"><i class="fa fa-vk"></i>
                                </a>
                            </li>
                        <?php endif ?>
                        <?php echo fire_hook('extend.third.party.auth', null, array()); ?>
                    </ul>
                </div>
            </div>
        <?php endif ?>
        <div class="divider"></div>
        <hr />
        <a ajax="true" href="<?php echo url_to_pager('signup') ?>" class="" style="text-align: center;display: block"><?php echo lang('signup-for-account') ?></a>
    </div>
</div>