<div class="panel-container card">
	<div class="pane-title">
		<?php $logo = config('site-logo');
		$logo_url = !$logo ? img('images/logo.png') : url_img($logo); ?>
		<img class="logo" src="<?php echo $logo_url ?>"/>
	</div>
	<div class="title">
		<span><?php echo lang('reset-password') ?></span>
	</div>

	<div class="card-block">
		<?php if($message): ?>
			<div class="alert <?php echo $messageType == 0 ? 'alert-danger' : 'alert-success' ?>">
				<?php echo $message ?>
				<br/>
			</div>
		<?php endif ?>
		<form action="" class="col s12" method="post">
			<?php CSRFProtection::embed() ?>
			<fieldset class="form-group">
				<label class="control-label"><?php echo lang('your-email-address') ?></label>
				<input type="text" class="form-control form-control-lg rounded-input" name="email">
			</fieldset>
			<button class="btn btn-info btn-block"><?php echo lang('request-new-password') ?> </button>
		</form>
	</div>
</div>