<div class="panel-container card">
    <div class="pane-title">
        <?php $logo = config('site-logo');
        $logo_url = !$logo ? img('images/logo.png') : url_img($logo); ?>
        <a href="<?php echo url() ?>"><img class="logo" src="<?php echo $logo_url ?>" /></a>
    </div>
    <div class="title">
        <span><?php echo lang('reset-password') ?></span>
    </div>
    <div class="card-block">
        <div class="card-title"><?php echo lang('reset-password') ?></div>
        <div class="alert alert-danger"><?php echo lang('link-has-expired') ?></div>
    </div>
</div>