<div class="panel-container card">
    <div class="pane-title">
        <?php $logo = config('site-logo');
        $logo_url = !$logo ? img('images/logo.png') : url_img($logo); ?>
        <a href="<?php echo url() ?>"><img class="logo" src="<?php echo $logo_url ?>" /></a>
    </div>
    <div class="title">
        <span><?php echo lang('reset-password') ?></span>
    </div>
    <div class="card-block">
        <?php if ($message): ?>
            <div class="alert alert-danger">
                <?php echo $message ?>
                <br />
            </div>
        <?php endif ?>
        <form action="" class="col s12" method="post">
            <?php CSRFProtection::embed() ?>
            <fieldset class="form-group">
                <label for="exampleInputEmail1"><?php echo lang('choose-new-password') ?></label>
                <input name="val[password]" type="password" class="form-control form-control-lg" id="exampleInputEmail1" value="<?php echo input('val.password') ?>">
            </fieldset>
            <fieldset class="form-group">
                <label for="InputConfirmPassword"><?php echo lang('confirm-new-password') ?></label>
                <input name="val[confirm_password]" type="password" class="form-control form-control-lg" id="InputConfirmPassword" value="<?php echo input('val.password') ?>">
            </fieldset>
            <button class="btn btn-block btn-info"><?php echo lang('reset-password') ?></button>
        </form>
    </div>
</div>
