<div class="business business-filter box">
	<div class="title"><?php echo lang('business::search') ?></div>
	<div class="box-content">
		<form action="" method="post" onsubmit="return businessFilterFormSubmit(this)">
			<?php CSRFProtection::embed() ?>
			<?php if(config('business-enable-category-filter', true)): ?>
				<div class="form-group">
					<div><?php echo lang('business::category') ?></div>
					<div>
						<select name="c">
							<option value="all"><?php echo lang('business::all-categories') ?></option>
							<?php foreach(business_get_categories() as $category): ?>
								<option<?php echo input('c') == $category['id'] ? ' selected' : null ?> value="<?php echo $category['slug'] ?>"><?php echo lang($category['category']) ?></option>
							<?php endforeach ?>
						</select>
					</div>
				</div>
			<?php endif ?>
			<?php if(config('business-enable-location-filter', true)): ?>
				<div class="form-group">
					<div><?php echo lang('business::location') ?></div>
					<div>
						<input type="text" name="l" value="<?php echo input('l') ?>" class="form-control" placeholder="<?php echo lang('business::location') ?>"/>
					</div>
				</div>
			<?php endif ?>
			<?php if(config('business-enable-price-filter', true)): ?>
				<div class="form-group">
					<div><?php echo lang('business::price-range') ?></div>
					<div class="row">
						<div class="col-sm-6">
							<input type="number" min="0" step="0.5" name="p0" value="<?php echo input('p0') ?>" class="form-control" placeholder="<?php echo lang('business::min') ?>"/>
						</div>
						<div class="col-sm-6">
							<input type="number" min="0" step="0.5" name="p1" value="<?php echo input('p1') ?>" class="form-control" placeholder="<?php echo lang('business::max') ?>"/>
						</div>
					</div>
				</div>
			<?php endif ?>
			<?php if(config('business-enable-feature-filter', true)): ?>
                <div class="form-group">
                    <div>
                        <input type="checkbox" name="f"<?php echo input('f') ? ' checked' : null ?> value="1"/> <?php echo lang('business::featured') ?>
                    </div>
				</div>
			<?php endif ?>
			<?php if(config('business-enable-mine-filter', true)): ?>
				<div class="form-group">
					<div>
						<input type="checkbox" name="m"<?php echo input('m') ? ' checked' : null ?> value="1"/> <?php echo lang('business::my-businesses') ?>
					</div>
				</div>
			<?php endif ?>
			<?php if(config('business-enable-photo-filter', true)): ?>
				<div class="form-group">
					<div>
						<input type="checkbox" name="i"<?php echo input('i') ? ' checked' : null ?> value="1"/> <?php echo lang('business::has-photo') ?>
					</div>
				</div>
			<?php endif ?>
			<div class="form-group">
				<div><?php echo lang('business::keywords') ?></div>
				<div>
					<input type="text" name="s" value="<?php echo input('s') ?>" class="form-control" placeholder="<?php echo lang('business::keywords') ?>"/>
				</div>
			</div>
			<div class="form-group">
				<input value="<?php echo lang('business::search') ?>" class="btn btn-info btn-block" name="submit" type="submit">
			</div>
		</form>
	</div>
</div>