<div class="row">
	<div class="col-md-4 left-col-container">
		<div class="box <?php //echo (($cid and $cid != 'mobile') or input('userid')) ? 'hidden-md-down' : null?>" id="message-left-pane">
			<div class="title"><?php echo lang('chat::conversations') ?>
				<a href="<?php echo url_to_pager('messages') ?>?cid=new" ajax="true" class="btn btn-info btn-sm action"><i class="ion-compose"></i></a>
			</div>
			<div class="conversation-list paginate slimscroll" data-height="<?php echo isMobile() ? '150px' : '450px' ?>" data-offset="<?php echo $conversations_limit ?>" data-limit="<?php echo $conversations_limit ?>" data-cid="<?php echo $cid ?>" data-loading="0" data-status="1">
				<?php foreach($conversations as $conversation): ?>
					<?php echo view('chat::conversation/display', array('conversation' => $conversation, 'cid' => $cid)) ?>
				<?php endforeach ?>
			</div>
		</div>
	</div>
	<div class="col-md-8 right-col-container">
		<div class="box message-box-<?php echo $cid ?> <?php echo ((!$cid and !input('userid')) or $cid == 'mobile') ? 'hidden-md-down' : null ?>" id="message-right-pane">
			<form id="message-chat-form" enctype="multipart/form-data" action="" method="post" onsubmit="return false">
				<?php CSRFProtection::embed() ?>
				<input type="hidden" name="val[cid]" id="message-cid-input" value="<?php echo ($cid != 'new') ? $cid : null ?>"/>
				<?php if($cid == 'new'): ?>
					<div class="message-to-container">
						<span><?php echo lang('chat::to') ?>: </span>
						<span id="message-to-lists">
                            <?php if($userid): $user = find_user($userid, false); ?>
	                            <span class='user' id='message-user-<?php echo $user['id'] ?>'><?php echo get_user_name($user) ?>
		                            <input type='hidden' name='val[user][]' value='<?php echo $user['id'] ?>'/><a href=''><i class='ion-close'></i></a> </span>
                            <?php endif ?>
							<input type="text" data-target="#message-user-suggestion" class="user-tag-input" <?php echo config('relationship-method', 3) == 1 ? '' : 'data-friend-only="true"' ?> placeholder="<?php echo lang('chat::type-a-friend-name') ?>"/>
                            <div style="width: 300px" class="user-suggestion-list box" id="message-user-suggestion"></div>
                        </span>
					</div>
				<?php endif ?>
				<div class="messages-pane-title title" style="<?php echo ($cid == 'new') ? 'display:none' : null ?> ">
					<h5 class="message-title"><?php echo ($conversate) ? $conversate['title'] : null ?></h5>
					<div class="action" style="top: 5px">
						<div class="btn-group">
							<?php if($conversate['type'] == 'single'): ?>
								<?php $user_id = $conversate['user1'] == get_userid() ? $conversate['user2'] : $conversate['user1']; ?>
								<?php echo fire_hook('mediachat.button.call', null, array($user_id)); ?>
                            <?php endif ?>
                            <a href="<?php echo url_to_pager('messages') ?>?cid=new" ajax="true" class="btn btn-secondary btn-sm hidden-md-down"><i class="mbri-edit"></i></a>
                            <?php if($conversate['type'] == 'multiple'): ?>
                                <a href="#!" onclick="return confirm.url('<?php echo url('chat/leave/conversation').'?cid='.$cid ?>')" class="btn btn-secondary btn-sm "><i class="mbri-trash"></i></a>
							<?php else: ?>
                                <a href="#!" onclick="return delete_conversation()" class="btn btn-secondary btn-sm "><i class="mbri-trash"></i></a>
							<?php endif ?>
                            <?php echo fire_hook('chat.settings', ' ', array($cid))?>
						</div>
					</div>
				</div>
				<div id="messages-pane-<?php echo $cid ?>" data-offset="0" class="messages-pane slimscroll" data-height="350px" data-sending="<?php echo lang('chat::sending') ?>">
					<?php if($messageContent): ?>
						<?php echo $messageContent ?>
					<?php endif ?>

				</div>
				<div class="message-editor">
					<div>
						<textarea id="message-editor-textarea" placeholder="<?php echo lang('chat::write-a-message') ?>" name="val[message]"></textarea>
						<div>
                            <span class="pull-left sender">
                                <?php $privacy = get_privacy('chat-send-button', false) ?>
                                <button id="chat-send-button" class="btn btn-sm btn-info" style="<?php echo !$privacy ? 'display:none' : null ?>"><?php echo lang('chat::send') ?></button>
                                <span class="hidden-sm-down setting"><input id="chat-send-input" onchange="switch_chat_send_button(this)" type="checkbox" name="" <?php echo (!$privacy) ? 'checked' : null ?>> <?php echo lang('chat::press-enter-to-send') ?></span>
                            </span>
							<span class="pull-right message-editor-actions" style="position: relative">
                                <ul>
									<li>
										<?php if(config('enable-chat-voice-message', 1)): ?>
											<div href="#" id="alt-chat-editor-voice-recorder" class="alt-chat-editor-voice-recorder chat-editor-voice-recorder voice-recorder">
												<input name="voice" type="hidden" value="" class="voice-input"/>
												<a href="#" class="control">
													<i class="ion-mic-a record"></i>
													<i class="ion-stop stop"></i>
												</a>
												<div class="actions">
													<a class="ion-close close" href="#"></a>
													<a class="ion-play play" href="#"></a>
												</div>
											</div>
										<?php endif; ?>
									</li>
	                                <?php if(plugin_loaded('emoticons')): ?>
		                                <li style="position: relative;">
                                            <div class="emoticon-box emoticon-bottom"></div>
                                            <a data-target="message-editor-textarea" data-action="1" title="<?php echo lang('emoticons::add-emoticons') ?>" class="emoticon-button" href="javascript::void(0)"><i class="ion-android-sad emo-button"></i></a>
                                            <span class="file-input"><input multiple type="file" name=""/> </span>
                                        </li>
                                        <li>
                                            <a id="alt-chat-gif-selector" href="#" class="alt-chat-gif-selector chat-gif-selector gif-selector">
                                                <i class="gif-icon"></i>
                                                <div class="chat-gif-box gif-box" data-callback="Chat.onGIFClick">
                                                    <div class="gif-box-head">
                                                        <span><?php echo lang('gif') ?></span>
                                                        <i class="gif-box-close-button ion-close"></i>
                                                    </div>
                                                    <div class="gif-box-body">
                                                        <input type="text" class="form-control chat-gif-search-input gif-search-input" placeholder="<?php echo lang('gif-search') ?>"/>
                                                        <div class="gif-search-result"></div>
                                                    </div>
                                                    <div class="gif-box-arrow"></div>
                                                    <input name="gif" type="hidden" value="" class="chat-gif-input gif-input"/>
                                                </div>
                                            </a>
                                        </li>
                                    <?php endif ?>
                                    <li>
                                        <a onclick="return file_chooser('#chat-message-image-input')" href=""><i class="ion-image"></i></a>
                                        <span class="file-input"><input onchange="chat_message_upload()" type="file" id="chat-message-image-input" name="image"/> </span>
                                    </li>
                                    <li>
                                        <a href="" onclick="return file_chooser('#chat-message-file-input')"><i class="ion-android-attach"></i></a>
                                        <span class="file-input"><input onchange="chat_message_upload()" type="file" id="chat-message-file-input" name="file"/> </span>
                                    </li>
                                </ul>
                            </span>
							<div class="clearfix"></div>
						</div>
					</div>
				</div>
			</form>
		</div>

	</div>
</div>