<div class="box">
    <div class="title"><?php echo lang('creditgift::payment-status') ?></div>
	<div class="box-content">
		<div class="alert alert-success">
			<?php echo lang('creditgift::creditgift-purchase-success') ?>
		</div>
        <a href="<?php echo url_to_pager('creditgift-purchase') ?>" ajax="true" class="btn btn-info btn-block action-button"><?php echo lang('creditgift::credit-purchase') ?></a>
	</div>
</div>