<div class="box">
    <div class="title"><?php echo $seller['name'].' '.'<em>'.lang("store::followers").'</em>'; ?>
        <span style="color: #00000080; font-size: 11px"> (<?php echo count($users) ?>)</span>
    </div>
    <?php if($users): ?>
        <div class="box-content two-line-media clearfix">
            <?php foreach($users as $user):
                $user = find_user($user);
                ?>
                <?php echo view('user/display', array('user' => $user)) ?>
            <?php endforeach ?>
        </div>
        <!--<div class="box-content">
            <?php /*echo $users->links(true) */?>
        </div-->>
    <?php else: ?>
        <div class="box-content">
            <div class="alert alert-info"><?php echo lang('no-members-to-display') ?></div>
        </div>
    <?php endif ?>
</div>