<?php echo view('layouts/menu') ?>
<div class="container">
    <div data-width="950" class="profile-container" id="group-profile-container" data-id="<?php echo $app->profileStore['s_id']; ?>">
        <div id="profile-cover" class="box">
            <div class="profile-cover-indicator">
                <img src="<?php echo img('images/loading.gif') ?>"/>
            </div>
            <a href="javascript::void(0)" id="profile-cover-viewer" data-id="<?php echo ($app->profileStore['store_cover']) ? get_media_id($app->profileStore['store_cover']) : null ?>" data-image="<?php echo get_store_cover(app()->profileStore) ?>" class="<?php echo ($app->profileStore['store_cover']) ? 'photo-viewer' : null ?>">
                <div class="profile-cover-wrapper">
                    <img src="<?php echo get_store_cover(app()->profileStore, false) ?>"/>
                </div>
            </a>
            <?php if(is_store_owner(app()->profileStore)): ?>
                <div class="profile-resize-cover-wrapper">
                    <div class="drag-info"><?php echo lang('drag-to-position-cover') ?></div>
                    <img src="<?php echo get_store_cover(app()->profileStore) ?>" />
                </div>
                <form id="profile-cover-change-form" enctype="multipart/form-data" method="post">
                    <?php CSRFProtection::embed() ?>
                    <span class="file-input"><input accept="image/*" multiple onchange="return upload_store_profile_cover()" type="file" id="user-profile-cover-input" name="image"/> </span>
                    <div class="dropdown">
                        <button class="btn btn-sm btn-info dropdown-toggle" data-toggle="dropdown">
                            <i class="ion-camera"></i> <?php echo lang('change-cover') ?>
                        </button>
                        <ul style="width: 240px" class="dropdown-menu dropdown-menu-right" id="profile-cover-dropdown-menu">
                            <li>
                                <a class="dropdown-item" onclick="return file_chooser('#user-profile-cover-input')" href=""><?php echo lang('upload-photo') ?>...</a>
                            </li>
                            <li class="hide-in-mobile">
                                <a class="dropdown-item" onclick="return reposition_user_profile_cover()" href=""><?php echo lang('reposition') ?>...</a>
                            </li>
                            <li>
                                <a class="dropdown-item" onclick="return remove_store_profile_cover('<?php echo img("images/cover.jpg") ?>')" href=""><?php echo lang('remove') ?>...</a>
                            </li>
                        </ul>
                    </div>
                </form>
                <div class="profile-cover-reposition-button">
                    <input type="hidden" id="profile-cover-resized-top" value="0"/>
                    <a onclick="return cancel_profile_cover_position()" class="btn-danger-outline btn btn-sm" href="#!"><?php echo lang('cancel') ?></a>
                    <a onclick="return save_store_profile_cover()" class="btn btn-success btn-upper btn-sm" href=""><?php echo lang('save') ?></a>
                </div>
            <?php endif ?>
            <div class="user-avatar box">
                <?php if(is_store_owner($app->profileStore)): ?>
                    <form data-id="<?php echo $app->profileStore['s_id'] ?>" id="group-profile-image-form" action="" method="post" enctype="multipart/form-data">
                        <?php CSRFProtection::embed() ?>
                        <span class="file-input"><input accept="image/*" multiple onchange="upload_store_logo()" type="file" id="group-avatar-input" name="logo"/></span>
                        <a class="profile-image-selector" id="profile-image-selector" href="" <?php echo config('profile-avatar-crop', true) ? 'onclick="return false"' : 'onclick="return file_chooser(\'#group-avatar-input\')"' ?>><i class="ion-ios-camera"></i><span></span></a>
                    </form>
                <?php endif ?>
                <div class="profile-image-indicator">
                    <img src="<?php echo img("images/loading.gif") ?>"/>
                    <span class="percent-indicator">0%</span>
                </div>

                <a id="profile-image-viewer" style="display: block" href="javascript::void(0)" data-id="<?php echo ($app->profileStore['image']) ? get_media_id($app->profileStore['image']) : null ?>" data-image="<?php echo get_store_logo(920, app()->profileStore) ?>" class="<?php echo ($app->profileStore['image']) ? 'photo-viewer' : null ?>">
                    <img id="profile-image" class="profile-image" src="<?php echo get_store_logo(200, app()->profileStore) ?>"/>
                </a>

            </div>
            <div class="user-info">
                <h4 class="user-name left"><?php echo get_store_details('name') ?> <?php echo verify_badge($app->profileStore) ?></h4>
            </div>

            <nav id="profile-menu" class="">
                <div class="navbar navbar-light">
                    <ul id="menu" class="nav navbar-nav">
                        <?php foreach(get_menus("store-profile") as $menu): ?>
                            <li class="<?php echo ($menu->isActive() == 1) ? 'active' : null ?>">
                                <a ajax="true" href="<?php echo $menu->link ?>"><?php echo $menu->title ?></a>
                            </li>
                        <?php endforeach ?>
                        <?php $store_profie_more = get_menus("store-profile-more") ?>
                        <?php if(!empty($store_profie_more)): ?>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="ion-ios-more"></i></a>
                                <ul style="width: 200px;" id="profile-more-menu" class="dropdown-menu dropdown-menu-right">
                                    <?php foreach($store_profie_more as $menu): ?>
                                        <li>
                                            <a class="dropdown-item" href="<?php echo $menu->link ?>"><?php echo $menu->title ?></a>
                                        </li>
                                    <?php endforeach ?>
                                    <?php $store_profie_more = get_menus("store-profile-more") ?>
                                    <?php if(!empty($store_profie_more)): ?>
                                        <li class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                                <i class="ion-ios-more"></i></a>
                                            <ul style="width: 250px;" id="profile-more-menu" class="dropdown-menu">
                                                <?php foreach($store_profie_more as $menu): ?>
                                                    <li>
                                                        <a ajax="true" class="dropdown-item" href="<?php echo $menu->link ?>"><?php echo $menu->title ?></a>
                                                    </li>
                                                <?php endforeach ?>

                                            </ul>
                                        </li>
                                    <?php endif ?>
                                </ul>
                            </li>
                        <?php endif ?>
                    </ul>

                </div>
            </nav>
        </div>

        <div class="profile-actions">
            <?php if(is_loggedIn() and is_store_owner($app->profileStore)):?>
            <a ajax="true" href="<?php echo url_to_pager("store-manager"); ?>" class="btn btn-info"><?php echo lang("store::manage-all-stores") ?></a>
            <?php endif; ?>
            <span class="group-social-share"><?php if(plugin_loaded('sharer')) echo view('sharer::share_link', array('link' => url(store_url('', $app->profileStore)))) ?></span>
            <?php if(is_loggedIn()): ?>
                <?php if(plugin_loaded('like')): ?>
                    <?php load_functions('like::like'); ?>
                    <!--<a onclick="return like_item('store', '<?php /*echo $app->profileStore['s_id'] */?>')" data-status="<?php /*echo (has_liked('store', $app->profileStore['s_id'])) ? '1' : 0 */?>" class="btn btn-secondary like-button-store-<?php /*echo $app->profileStore['s_id'] */?> like-button <?php /*echo (has_liked('store', $app->profileStore['s_id'])) ? 'liked' : null */?>" href="">
                        <i class="fa fa-thumbs-o-up"></i> <?php /*echo lang('like::like') */?>
                    </a>-->
                    <?php if(is_loggedIn() and $app->storeUser['id'] != get_userid() and can_send_message($app->storeUser['id'])): ?>
                        <a ajax="true" href="<?php echo url('messages?userid='.$app->storeUser['id']) ?>" class="btn btn-secondary btn-sm message-me-small"><?php echo lang('store::contact-seller') ?></a>
                        <a href="" onclick="return Chat.open(null, '<?php echo $app->storeUser['id'] ?>', '<?php echo htmlentities(get_user_name($app->storeUser)) ?>', '<?php echo get_avatar(75, $app->storeUser) ?>')" class="btn btn-secondary btn-sm message-me-large"><?php echo lang('store::contact-seller') ?></a>
                    <?php endif ?>
                    <a href="" data-sid="<?php echo $app->profileStore['s_id'] ?>" onclick="return storeFollowingStatus(this)" data-follow="<?php echo lang('store::follow'); ?>" data-unfollow="<?php echo lang("store::unfollow") ?>" data-status="<?php echo isFollowingStore($app->profileStore['s_id']) ? 1: 0 ?>" class="btn btn-sm <?php echo isFollowingStore($app->profileStore['s_id']) ? 'btn-danger': 'btn-success'; ?>">
                        <?php echo isFollowingStore($app->profileStore['s_id']) ? lang('store::unfollow'): lang("store::follow"); ?></a>
                <?php endif ?>
                <?php if(is_loggedIn() and is_store_owner($app->profileStore)):?>
                    <a ajax="true" href="<?php echo url_to_pager("store-profile-edit",array('slug'=>$app->profileStore['slug'])); ?>" class="btn btn-secondary "><i class="ion-edit"></i> <?php echo lang('edit') ?>
                    </a>
                <?php endif ?>
            <?php endif ?>

            <?php if(is_loggedIn() and plugin_loaded('report') and !is_store_owner($app->profileStore)): ?>
                <a data-type="store" data-link="<?php echo store_url(null, $app->profileStore) ?>" class="report-btn btn btn-secondary " href=""><i class="ion-flag"></i></a>
            <?php endif ?>

            <?php if(is_loggedIn()): ?>
                <span class="dropdown">
                        <a href="" class="dropdown-toggle btn btn-secondary" data-toggle="dropdown" style=""><i class="ion-android-more-vertical"></i></a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li>
                                <a onclick="return process_user_save(this, 'store', '<?php echo $app->profileStore['s_id'] ?>')" href="" class="dropdown-item user-save" data-status="<?php echo (user_saved('store', $app->profileStore['s_id'])) ? 1 : 0 ?>">
                                    <i class="ion-android-bookmark"></i>
                                    <span><?php echo (user_saved('store', $app->profileStore['s_id'])) ? lang('unsave-post') : lang('save-post') ?></span>
                                </a>
                            </li>
                            <?php fire_hook('profile.actions.store', null, array()); ?>
                        </ul>
                    </span>
            <?php endif ?>
        </div>
    </div>

</div>
<?php echo $content ?>
<div class="container" id="crop-avatar">

    <!-- Cropping modal -->
    <div class="modal fade" id="avatar-modal" aria-hidden="true" aria-labelledby="avatar-modal-label" role="dialog" tabindex="-1">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <form id="avatar-crop-form" class="avatar-form" action="<?php echo $url = url('store/change/logo').'?id='.$app->profileStore['s_id'] ?>" enctype="multipart/form-data" method="post">
                    <?php CSRFProtection::embed() ?>
                    <div class="modal-header">
                        <h4 class="modal-title" id="avatar-modal-label">Change Avatar</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <div class="avatar-body">

                            <!-- Upload image and data -->
                            <div class="avatar-upload">
                                <input type="hidden" class="avatar-src" name="avatar_src">
                                <input type="hidden" class="avatar-data" name="avatar_data">
                                <label for="avatarInput">Local upload</label>
                                <input type="file" class="avatar-input" id="avatarInput" name="avatar_file">
                            </div>

                            <!-- Crop and preview -->
                            <div class="row">
                                <div class="col-md-9">
                                    <div class="avatar-wrapper"></div>
                                </div>
                                <div class="col-md-3">
                                    <div class="avatar-preview preview-lg"></div>
                                    <div class="avatar-preview preview-md"></div>
                                    <div class="avatar-preview preview-sm"></div>
                                </div>
                            </div>

                            <div class="row avatar-btns">
                                <div class="col-md-9">
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-primary" data-method="rotate" data-option="-90" title="Rotate -90 degrees">Rotate Left</button>
                                        <button type="button" class="btn btn-primary" data-method="rotate" data-option="-45">-45deg</button>
                                        <button type="button" class="btn btn-primary" data-method="rotate" data-option="-30">-30deg</button>
                                        <button type="button" class="btn btn-primary" data-method="rotate" data-option="-15">-15deg</button>
                                        <button type="button" class="btn btn-primary" data-method="rotate" data-option="15">15deg</button>
                                        <button type="button" class="btn btn-primary" data-method="rotate" data-option="30">30deg</button>
                                        <button type="button" class="btn btn-primary" data-method="rotate" data-option="45">45deg</button>
                                        <button type="button" class="btn btn-primary" data-method="rotate" data-option="90" title="Rotate 90 degrees">Rotate Right</button>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <button type="submit" class="btn btn-primary btn-block avatar-save">Done</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div> -->
                </form>
            </div>
            <!-- Loading state -->
            <div class="loading" aria-label="Loading" role="img" tabindex="-1"></div>
        </div>
    </div><!-- /.modal -->
</div>

