<?php $products = getMyStoreProducts($seller['s_id'], 'all'); ?>
<?php echo view("store::store-top-menu"); ?>
<div class="box">
    <div class="title">
        <?php echo $seller['name'] . ' ' . '<em>' . lang("store::products") . '</em>'; ?>
        <span class="pull-right"><em><?php echo $products->total; ?> <?php echo lang("store::products"); ?></em></span>
    </div>
    <div class="box-content">
        <div class="container nop">
            <div class="row">

                <?php if ($products->total): ?>
                    <?php foreach ($products->results() as $p):$user = find_user($p['user_id']);
                        $productStoreOwner = lpGetStoreById($p['store_id']);
                        ?>
                        <?php echo view("store::products/product-box", array('p' => $p, 'user' => $productStoreOwner)); ?>
                    <?php endforeach ?>
                <?php else: ?>
                    <div class="alert alert-info"><?php _lang('store::products-list-empty') ?></div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>