<div class="each-item clearfix">
	<div class="left">
		<?php if($video['featured']): ?>
			<span class="featured-tag"><?php echo lang('featured') ?></span>
		<?php endif ?>
		<a href="<?php echo get_video_url($video) ?>" ajax="true" style="background-image: url(<?php echo ($video['photo_path']) ? url_img($video['photo_path']) : img('video::images/preview.png') ?>);"></a>
		<a href="<?php echo get_video_url($video) ?>" ajax="true" class="video-thumb-hover<?php echo $video['thumbnail'] ? '' : ' static'?>"  <?php echo $video['thumbnail'] ? 'data-image="'.url_img($video['thumbnail'], 75).'"' : 'style="background-image: url('.img('video::images/play.png').')"'?>></a>
	</div>
	<?php $owner = get_video_owner($video); ?>
	<div class="right">
		<span class="item-title"><a ajax="true" href="<?php echo get_video_url($video) ?>"><?php echo ($video['title']) ? $video['title'] : lang('video::untitled-video') ?></a> </span>
		<div class="item-info">
            <span>
            <?php if(fire_hook('video.custom.display', true)): ?>
	            <?php echo $video['views'] ?> <?php echo lang('video::views') ?> -
            <?php endif; ?>
	            <span class="feed-time"> <span class="timeago " title="<?php echo date('c', $video['time']) ?>"><?php echo date('c', $video['time']) ?></span></span></span>
			<?php echo lang('video::by') ?>
			<a ajax="true" href="<?php echo $owner['link'] ?>"><?php echo $owner['name'] ?></a>
		</div>
		<?php if(fire_hook('video.custom.display', true)): ?>
            <?php fire_hook('video.custom.display', $video, array('video')) ?>
			<p class="item-desc"><?php echo str_limit($video['description'], 120) ?></p>
			<span class="video-social-share-link"><?php if($video['privacy'] == 1 && plugin_loaded('sharer')) echo view('sharer::share_link', array('link' => url("video/".$video['slug']))) ?></span>
		<?php endif; ?>
	</div>
</div>