<div class="wrapper">
    <div class="wrapper-title">
        <?php _lang('store::slides')?>
         - <a class="btn btn-success" href="<?php echo url_to_pager('admin-store-add-category').'?type=slides'; ?>"><?php _lang('store::add-slide')?></a>
    </div>
    <div class="wrapper-content">
        <table class="table storeTable">
            <thead>
                <tr>
                    <th>ID</th>
                    <th><?php echo lang('store::image')?></th>
                    <th>External Link</th>
                    <th><?php _lang('actions')?></th>
                </tr>
            </thead>
            <?php  ?>
            <?php if(!empty($categories)): ?>

            <tbody data-url="<?php echo url_to_pager('admin-store-categories-manager').'?action=order&type=slides'?>" class="admincp-sortable" style="position: relative">
            <?php foreach($categories as $category):?>
                <tr style="" class="item" id="<?php echo $category['id']?>">
                    <td style="width: 10%"><?php echo $category['id']?></td>
                    <td style="width: 30%"><img src="<?php echo storeCategoryImage($category,200); ?>" style="height:50px;width:50px" /></td>
                    <td>
                        <?php if($category['somelink']): ?>
                            <a href="<?php echo urldecode($category['somelink']); ?>" target="_blank"><?php echo urldecode($category['somelink']); ?></a>
                        <?php endif; ?>
                    </td>
                    <td style="width: 20%">
                        <a class="btn btn-sm btn-warning" href="<?php echo url_to_pager('admin-store-categories-manager').'?action=edit&type=slides&slug='.$category['slug'] ?>"><?php _lang('edit')?></a>
                        <a class="btn btn-sm btn-danger admin-confirm" href="<?php echo url_to_pager('admin-store-categories-manager').'?action=delete&type=slides&slug='.$category['slug']?>"><i class="ion-android-delete"></i></a>
                    </td>
                </tr>
            <?php endforeach?>

            </tbody>

            <?php else: ?>
                <div class="alert alert-info"><?php echo lang('store::no-slides-found'); ?></div>
            <?php endif; ?>

        </table>
    </div>
</div>