<?php $rating = get_user_rating($type, $type_id); ?>
<div class="rating user-<?php echo $type ?>-<?php echo $type_id ?>">
    <button value="1" class="ion-ios-star star <?php echo $rating >= 1 ? 'filled' : '' ?>" onclick="return ratings(this, '<?php echo $type ?>', '<?php echo $type_id ?>')"></button>
    <button value="2" class="ion-ios-star star <?php echo $rating >= 2 ? 'filled' : '' ?>" onclick="return ratings(this, '<?php echo $type ?>', '<?php echo $type_id ?>')"></button>
    <button value="3" class="ion-ios-star star <?php echo $rating >= 3 ? 'filled' : '' ?>" onclick="return ratings(this, '<?php echo $type ?>', '<?php echo $type_id ?>')"></button>
    <button value="4" class="ion-ios-star star <?php echo $rating >= 4 ? 'filled' : '' ?>" onclick="return ratings(this, '<?php echo $type ?>', '<?php echo $type_id ?>')"></button>
    <button value="5" class="ion-ios-star star <?php echo $rating >= 5 ? 'filled' : '' ?>" onclick="return ratings(this, '<?php echo $type ?>', '<?php echo $type_id ?>')"></button>
</div>