
<?php $sellers = lp_get_stores('featured'); ?>

<?php if($sellers->total):?>

    <div class="box">
        <div class="title">
            <?php echo lang("store::featured-sellers")?>
            <a ajax="true" href="<?php echo url('products')?>"><i class="ion-ios-arrow-forward pull-right"></i></a>
        </div>
        <div class="box-content">

            <?php foreach($sellers->results() as $s):
                 $user = find_user($s['user_id']);
                ?>

                <div  class="media media-lg">
                    <div class="media-left">
                        <div class="media-object">
                            <img src="<?php echo getStoreLogo($s);?>"/>
                        </div>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading" style="margin-top:0"><a ajax="true" href="<?php echo url('store/'.$s['slug'])?>"><?php echo $s['name']?></a></h4>
                                <span class="help-block" style="display: block;font-size:12px; "> <?php echo lang("store::store-owner") ?> :
                                <a style="color:#555 !important; font-weight: bold" href="<?php echo profile_url(null,$user) ?>" ajax="true">  <?php echo get_user_name($user); ?></a>
                                </span>
                    </div>
                </div>
            <?php endforeach?>
        </div>
    </div>
<?php endif?>