<div id="forum-create-thread" class="forum ajax">
	<div class="forum-content create-thread-content box">
		<div class="forum-title">
			<h1><?php echo lang('forum::create-topic') ?></h1>
		</div>
		<?php if(!is_loggedIn()): ?>
			<span class="error"><?php echo lang('forum::forum-create-login-error') ?></span>
		<?php else: ?>
			<?php if($messages): ?>
				<div class="alert alert-danger"><?php echo $messages ?></div>
			<?php endif ?>
			<form action="" method="post" id="postform" class="ajax-form">
				<?php CSRFProtection::embed() ?>
				<div class="field">
					<div class="left">
						<label for="category"><?php echo lang('forum::category') ?>: </label>
					</div>
					<div class="right">
						<div class="magic-select" data-name="category_id" data-width="200px">
							<div class="magic-select-toggle">
								<?php echo lang('select-category') ?>
							</div>
							<div class="magic-select-content slimscroll" data-height="200px">
								<?php foreach($categories as $category): ?>
									<div class="magic-select-option" data-value="<?php echo $category['id'] ?>">
										<?php echo lang($category['title']) ?>
									</div>
								<?php endforeach ?>
							</div>
						</div>
						<p class="form-description"><?php echo lang('forum::create-thread-category-desc') ?></p>
					</div>
				</div>
				<div class="field">
					<div class="left">
						<label for="subject"><?php echo lang('forum::subject') ?>: </label>
					</div>
					<div class="right">
						<input name="subject" type="text" class="form-control" />
						<p class="form-description"><?php echo lang('forum::create-thread-subject-desc') ?></p>
					</div>
				</div>
				<div class="field">
					<div class="left">
						<label for="post"><?php echo lang('forum::post') ?>: </label>
					</div>
					<div class="right">
						<textarea name="postbox" id="postbox" class="ckeditor"></textarea>
						<p class="form-description"><?php echo lang('forum::create-thread-post-desc') ?></p>
					</div>
				</div>
				<div class="field">
					<div class="left">
						<label for="tags"><?php echo lang('forum::tags') ?>: </label>
					</div>
					<div class="right">
                        <?php $tags = forum_get_tags() ?>
                        <?php foreach($tags as $index => $tag): ?>
                            <?php $tags[$index]['value'] = $tag['title'] ?>
                            <?php $tags[$index]['slug'] = $tag['title'] ?>
                        <?php endforeach; ?>
                        <input type="text" name="tags" value="<?php echo input('tags', '[]') ?>" data-whitelist-object='<?php echo str_replace("'", '&apos;', json_encode($tags)) ?>' class="form-control tagify" />
						<p class="form-description"><?php echo lang('forum::create-thread-tags-desc').implode(', ', forum_get_tag_names()) ?>.</p>
					</div>
				</div>
				<div class="submit">
					<input type="submit" value="<?php echo lang('forum::create') ?>" class="btn btn-primary"/>
				</div>
				<input type="hidden" name="val" value=true />
				<input type="hidden" name="type" value="create_thread" />
			</form>
		<?php endif ?>
	</div>
</div>