<div class="wrapper">
	<div class="wrapper-title">
		<?php echo lang('manage-members') ?>
		<span><?php echo lang('manage-members-desc') ?></span>
	</div>
	<div class="wrapper-content">
		<?php if($message): ?>
			<div class="alert alert-danger">
				<?php echo $message ?>
			</div>
		<?php endif ?>
		<form method="post" action="" class="wrapper-form">
			<?php CSRFProtection::embed() ?>
			<div class="form-group row">
				<div class="col-sm-6">
					<label class="form-control-label"><?php echo lang('first_name') ?></label>
					<div>
						<input type="text" class="form-control" name="val[first_name]" value="<?php echo input('val.first_name') ?>" required/>
					</div>
				</div>
				<div class="col-sm-6">
					<label class="form-control-label"><?php echo lang('last_name') ?></label>
					<div>
						<input type="text" class="form-control" name="val[last_name]" value="<?php echo input('val.last_name') ?>" required/>
					</div>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-6">
					<label class="form-control-label"><?php echo lang('username') ?></label>
					<div>
						<input type="text" class="form-control" name="val[username]" value="<?php echo input('val.username') ?>" required/>
					</div>
				</div>
				<div class="col-sm-6">
					<label class="form-control-label"><?php echo lang('email-address') ?></label>
					<div>
						<input type="email" class="form-control" name="val[email_address]" value="<?php echo input('val.email_address') ?>" required/>
					</div>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-6">
					<label class="form-control-label"><?php echo lang('password') ?></label>
					<div>
						<input type="password" class="form-control" name="val[password]" value="<?php echo input('val.password') ?>" required/>
					</div>
				</div>
				<div class="col-sm-6">
					<label class="form-control-label"><?php echo lang('confirm-password') ?></label>
					<div>
						<input type="password" class="form-control" name="val[cpassword]" value="<?php echo input('val.cpassword') ?>" required/>
					</div>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-6">
					<div class="row">
						<div class="col-sm-6">
							<label class="form-control-label"><?php echo lang('verified') ?></label>
							<div>
								<select name="val[verified]" class="form-control" required>
									<option value="0"><?php echo lang('no') ?></option>
									<option value="1"><?php echo lang('yes') ?></option>
								</select>
							</div>
						</div>
						<div class="col-sm-6">
							<label class="form-control-label"><?php echo lang('activated') ?></label>
							<div>
								<select name="val[activated]" class="form-control" required>
									<option value="0"><?php echo lang('no') ?></option>
									<option value="1"><?php echo lang('yes') ?></option>
								</select>
							</div>
						</div>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="row">
						<div class="col-sm-6">
							<label class="form-control-label"><?php echo lang('gender') ?></label>
							<div>
								<select class=" form-control" name="val[country]" required>
									<option value=""><?php echo lang('select-country') ?></option>
									<?php load_functions('country') ?>
									<?php foreach(get_countries() as $country => $name): ?>
										<option <?php echo (input("val.country") == $name) ? "selected" : null ?> value="<?php echo $name ?>"><?php echo ucwords($name) ?></option>
									<?php endforeach ?>
								</select>
							</div>
						</div>
						<div class="col-sm-6">
							<label class="form-control-label"><?php echo lang('gender') ?></label>
							<div>
								<select class=" form-control" name="val[gender]" required>
                                    <?php $value = input('val.gender'); $genders = get_genders(); ?>
                                    <?php foreach ($genders as $gender): ?>
                                        <option <?php echo $value == $gender ? 'selected' : '' ?> value="<?php echo $gender ?>"><?php echo lang($gender) ?></option>
                                    <?php endforeach; ?>
								</select>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="form-group row">
				<div class="col-sm-6">
					<div class="row">
						<div class="col-sm-6">
							<label class="form-control-label"><?php echo lang('featured') ?></label>
							<div>
								<select name="val[featured]" class="form-control" required>
									<option value="0"><?php echo lang('no') ?></option>
									<option value="1"><?php echo lang('yes') ?></option>
								</select>
							</div>
						</div>
						<div class="col-sm-6">
							<label class="form-control-label"><?php echo lang('role') ?></label>
							<div>
								<select name="val[role]" class="form-control" required>
									<?php foreach(list_user_roles() as $role): ?>
										<option value="<?php echo $role['role_id'] ?>"><?php echo $role['role_title'] ?></option>
									<?php endforeach ?>
								</select>
							</div>
						</div>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="row">
						<div class="col-sm-6">
							<div class="submit-button-container">
								<button class="btn btn-info form-control"><?php echo lang('add') ?></button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>
