<div class="wrapper">
	<div class="wrapper-title">
		<?php echo lang('verification-requests') ?>
	</div>
	<div class="wrapper-content">
		<div class="table-responsive">
			<table class="table table-striped list-table">
				<thead>
				<tr>
					<th><div class="list-table-select" data-group="users" data-id="0"></div></th>
					<th style="width: 10%">ID</th>
					<th style="width: 25%"><?php echo lang('entity') ?></th>
					<th style="width: 15%"><?php echo lang('type') ?></th>
					<th style="width: 15%"><?php echo lang('time') ?></th>
					<?php fire_hook('more.verified.extend.head', null, array()); ?>
					<th style="width: 24%; text-align:center;"><?php echo lang('actions') ?></th>
				</tr>
				</thead>
				<tbody>
				<?php foreach($requests->results() as $request): ?>
					<tr>
						<td>
							<div class="list-table-select" data-group="users" data-id="<?php echo $request['type_id'] ?>"></div>
						</td>
						<td><?php echo $request['type_id'] ?></td>
						<td>
							<?php if($request['type'] == 'user'): $user = find_user($request['type_id']) ?>
								<a href="<?php echo profile_url(null, $user) ?>">
									<img src="<?php echo get_avatar(75, $user) ?>" width="30" height="30"/>
									<h6><?php echo get_user_name($user) ?></h6>
								</a>
							<?php else: $page = find_page($request['type_id']) ?>
								<a href="<?php echo page_url(null, $page) ?>">
									<img src="<?php echo get_page_logo(75, $page) ?>" width="30" height="30"/>
									<h6><?php echo $page['page_title'] ?></h6>
								</a>
							<?php endif ?>
						</td>
						<td><?php echo ucwords($request['type']) ?></td>
						<td><?php echo date('d F Y g:i', $request['time']) ?></td>
						<?php fire_hook('more.verified.extend.body', $request, array()); ?>
						<td>
							<div class="dropdown actions">
								<a href="#" data-toggle="dropdown">
									<i class="ion-android-settings"></i>
								</a>
								<div class="dropdown-menu dropdown-menu-right">
									<a href="#" data-toggle="modal" data-target="#myModal-<?php echo $request['type'] ?>-<?php echo $request['type_id'] ?>" class="offer-img ion-eye text-primary" title="<?php echo lang('view') ?>"></a>
									<a href="<?php echo url('admincp/verify/action?type=ignore&id='.$request['id']) ?>" class="<?php echo $request['approved'] ? 'ion-android-delete text-danger' : 'ion-ios-close text-info' ?>" title="<?php echo $request['approved'] ? lang('revoke') : lang('ignore') ?>"></a>
									<?php if(!$request['approved']): ?>
										<a href="<?php echo url('admincp/verify/action?type=approve&id='.$request['id']) ?>" data-uid="<?php echo $request['type_id']; ?>" class="ion-ios-checkmark text-success <?php echo ($request['type'] == 'user') ? 'approve-entitiy' : ''; ?>" title="<?php echo lang('approve') ?>"></a>
									<?php endif ?>
								</div>
							</div>
						</td>
					</tr>
				<?php endforeach ?>
				</tbody>
			</table>
		</div>
		<?php foreach($requests->results() as $request): ?><?php $request_answers = get_verification_answers($request['id']) ?><?php if($request['type'] == 'user'): ?><?php $user = find_user($request['type_id']) ?><?php else: ?><?php $page = find_page($request['type_id']) ?><?php endif ?><?php if($request['type'] == 'user'): ?>
			<div class="modal fade" id="myModal-<?php echo $request['type'] ?>-<?php echo $request['type_id'] ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
				<div class="modal-dialog" role="document">
					<div class="modal-content modal-info">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close">
								<span aria-hidden="true">&times;</span>
							</button>
						</div>
						<div class="modal-body">
							<!----User details---->
							<div class="info widget-shadow info-box">
								<div class="info-title">
									<h4><?php echo get_user_name($user) ?> </h4>
								</div>
								<div class="info-body dash">
									<center>
										<img src="<?php echo get_avatar(75, $user) ?>" width="150px" height="100px"/>
									</center>
									<table width="90%" height="180" style="margin:auto; max-height:130px; text-align:left">
										<?php foreach($request_answers as $answer): ?>
											<tr>
												<td class="bold"><?php echo $answer ['question'] ?></td>
												<?php if($answer['input_type'] == 'text' || $answer['input_type'] == 'boolean'): ?>
													<td class="italic"><?php echo $answer ['answer'] ?> </td>
												<?php elseif($answer['input_type'] == 'file'): ?>
													<td class="italic">
														<a href="<?php echo url($answer['answer']) ?>" download><i style="font-size: 22px;" class="ion-ios-cloud-download-outline"></i></a>
													</td>
												<?php endif ?>
											</tr>
										<?php endforeach ?>
									</table>
									<div class="clear"></div>
									<table class="button_table">
										<tr>
											<td align="center">
												<a href="<?php echo url('admincp/verify/action?type=ignore&id='.$request['id']) ?>">
													<button type="button" class="btn btn-sm btn-danger"><?php echo $request['approved'] ? lang('revoke') : lang('ignore') ?></button>
												</a>
											</td>
                                            <?php if(!$request['approved']): ?>
                                                <td align="center">
                                                    <a href="<?php echo url('admincp/verify/action?type=approve&id='.$request['id']) ?>">
                                                        <button type="button" class="btn btn-sm btn-success"><?php echo lang('approve') ?></button>
                                                    </a>
                                                </td>
                                            <?php endif; ?>
										</tr>
									</table>
									<div class="clear"></div>
								</div>
							</div>
							<!---//User details--->
						</div>
					</div>
				</div>
			</div>
		<?php elseif($request['type'] == 'page'): ?>
			<div class="modal fade" id="myModal-<?php echo $request['type'] ?>-<?php echo $request['type_id'] ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
				<div class="modal-dialog" role="document">
					<div class="modal-content modal-info">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close">
								<span aria-hidden="true">&times;</span>
							</button>
						</div>
						<div class="modal-body">
							<!----User details---->
							<div class="info widget-shadow info-box">
								<div class="info-title">
									<h4><?php echo $page['page_title'] ?></h4>
								</div>
								<div class="info-body dash">
									<center>
										<img src="<?php echo get_page_logo(75, $page) ?>" width="150px" height="100px"/>
									</center>
									<table width="90%" height="180" style="margin:auto; max-height:130px; text-align:left">
										<?php foreach($request_answers as $answer): ?>
											<tr>
												<td class="bold"><?php echo $answer ['question'] ?></td>
												<?php if($answer['input_type'] == 'text' || $answer['input_type'] == 'boolean'): ?>
													<td class="italic"><?php echo $answer ['answer'] ?> </td>
												<?php elseif($answer['input_type'] == 'file'): ?>
													<td class="italic">
														<a href="<?php echo url($answer['answer']) ?>" download><i style="font-size: 22px;" class="ion-ios-cloud-download-outline"></i></a>
													</td>
												<?php endif ?>
											</tr>
										<?php endforeach ?>
									</table>
									<div class="clear"></div>
									<table class="button_table">
										<tr>
											<td align="center">
												<a href="<?php echo url('admincp/verify/action?type=ignore&id='.$request['id']) ?>">
                                                    <button type="button" class="btn btn-sm btn-danger"><?php echo $request['approved'] ? lang('revoke') : lang('ignore') ?></button>
												</a>
											</td>
                                            <?php if(!$request['approved']): ?>
                                                <td align="center">
                                                    <a href="<?php echo url('admincp/verify/action?type=approve&id='.$request['id']) ?>">
                                                        <button type="button" class="btn btn-sm btn-success"><?php echo lang('approve') ?></button>
                                                    </a>
                                                </td>
                                            <?php endif ?>
										</tr>
									</table>
									<div class="clear"></div>
								</div>
							</div>
							<!---//User details--->
						</div>
					</div>
				</div>
			</div>
		<?php endif ?><?php endforeach ?>
		<?php echo $requests->links(); ?>
	</div>
</div>