<div class="wrapper">
	<div class="wrapper-title">
		<?php echo lang("announcement::manage-announcement") ?>
		<a href="<?php echo url_to_pager('admin-announcement-create') ?>"
		   class="btn  btn-info"><?php echo lang('announcement::add-new') ?></a>
	</div>

	<div class="wrapper-content">
		<div class="list-table-container">
			<div class="row list-table-select-actions hide" data-group="users">
				<div class="col-sm-12">
					<a href="<?php echo url_to_pager('admin-video-batch-action') ?>?action=delete_cat"
					   class="action-link list-table-select-action" data-group="users"><?php echo lang('delete') ?></a>
				</div>
			</div>
			<div class="table-responsive">
				<table class="table table-striped list-table">
					<thead>
					<tr>
						<th>
							<div class="list-table-select" data-group="users"
							     data-id="0"></div>
						</th>
						<th style="width:10%">ID</th>
						<th style="with:50%"><?php echo lang('content') ?></th>
						<th style="with:20%"><?php echo lang('type') ?></th>
						<th style="width:20%"><?php echo lang('actions') ?></th>
					</tr>
					</thead>
					<tbody>
					<?php $announcements = get_admin_announcements() ?>
					<?php foreach($announcements->results() as $announcement): ?>
						<tr>
							<th>
								<div class="list-table-select" data-group="users"
								     data-id="<?php echo $announcement['id'] ?>"></div>
							</th>
							<td><?php echo $announcement['id'] ?></td>
							<td><?php echo lang($announcement['content']) ?></td>
							<td><?php echo ucwords($announcement['type']) ?></td>

							<td>
								<div class="dropdown actions">
									<a href="#" data-toggle="dropdown">
										<i class="ion-android-settings"></i>
									</a>
									<div class="dropdown-menu dropdown-menu-right">
										<a ajax="true" class="ion-edit"
										   href='<?php echo url_to_pager("admin-announcement-manage") ?>?action=edit&id=<?php echo $announcement['id'] ?>'></a>
										|
										<a ajax="true" class="admin-confirm ion-android-delete"
										   href="<?php echo url_to_pager("admin-announcement-manage") ?>?action=delete&id=<?php echo $announcement['id'] ?>"></a>
									</div>
								</div>
							</td>
						</tr>
					<?php endforeach ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>