<div class="box">
    <div class="title"><?php echo fire_hook('profile.blog.title', lang('blog::blogs')) ?></div>
    <div class="blog-list">
        <div class="body">
            <div class="listings">
                <div class="listing">
                    <?php foreach($blogs->results() as $blog): ?>
                        <?php $blog = arrange_blog($blog); ?>
                        <?php $user = find_user($blog['user_id']) ?>
                        <?php $refId = $blog['id']; $refName = 'blog'; ?>
                        <div class="item">
                            <div class="top">
                                <small class="time muted"><?php echo date('M j , y  h:i A', $blog['time']) ?></small>
                            </div>
                            <a ajax="true" href="<?php echo url('blog/'.$blog['slug']) ?>" class="thumb">
                                <img class="image" src="<?php echo $blog['image'] ? url_img($blog['image'], 700) : get_avatar(200, $user) ?>" alt="<?php echo $blog['title'] ?> "/>
                                <?php if($blog['featured']): ?>
                                    <div class="featured">
                                        <i class="ion-ios-star-outline"></i>
                                    </div>
                                <?php endif ?>
                            </a>
                            <div class="details">
                                <a ajax="true" href="<?php echo url('blog/'.$blog['slug']) ?>" class="title"><?php echo $blog['title'] ?></a>
                                <p class="description"><?php echo str_limit(strip_tags($blog['content']), 100) ?></p>
                                <div class="stat">
                                    <div class="left">
                                        <div class="user">
                                            <div class="avatar">
                                                <img src="<?php echo get_avatar(200, $user) ?>" alt="<?php echo $blog['publisher']['name'] ?>"/>
                                            </div>
                                            <a ajax="true" href="<?php echo url($blog['publisher']['id']) ?>" class="name"><?php echo $blog['publisher']['name'] ?></a>
                                        </div>
                                        <div class="count view"><?php echo $blog['views']; ?> <?php echo lang('blog::views'); ?></div>
                                        <div class="count like">
                                            <?php $likes = count_likes($refName, $refId); ?>
                                            <?php echo $likes; ?>
                                            <?php echo $likes > 1 ? lang('blog::likes') : lang('blog::like'); ?>
                                        </div>
                                    </div>
                                    <div class="right">
                                        <div class="actions">
                                            <a ajax="true" href="<?php echo url('blog/'.$blog['slug']) ?>" class="view"><?php echo lang('blog::continue-reading'); ?></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
    <div class="box-content">
        <?php if(!$blogs->total): ?>
            <div class="alert alert-info"><?php echo lang('blog::no-blog-found') ?></div>
        <?php else: ?>
            <?php echo $blogs->append(array('category' => input('category'), 'term' => input('term'), 'type' => 'user-profile'))->links(); ?>
        <?php endif ?>
    </div>
</div>