<div class="wrapper">
    <div class="wrapper-title">
        <?php echo lang("store::manage-products") ?>
    </div>
    <div class="wrapper-content">
        <div class="box-content">
            <table class="table table-striped table-bordered storeTable" cellspacing="0" width="100%" >
                <thead>
                <tr>
                    <th><?php _lang('store::product_id') ?></th>
                    <th><?php echo lang('store::product-name') ?></th>
                    <th><?php echo lang('store::quantity') ?></th>
                    <th><?php echo lang("store::price") ?></th>
                    <th><?php echo lang('store::product-type') ?></th>
                    <th><?php _lang('status') ?></th>
                    <th><?php _lang('store::action'); ?></th>
                </tr>
                </thead>
                <tbody>
                <?php if($products->total): ?>
                    <?php foreach($products->results() as $p ):;?>
                        <tr>
                            <td><?php echo $p['id']; ?></td>
                            <td><?php echo $p['name']; ?></td>
                            <td><?php echo $p['quantity'] ?></td>
                            <td><?php echo config('currency-sign','$').''.number_format((float)getProductPrice($p),2,'.',',');; ?></td>
                            <td><?php echo ucwords($p['type']); ?></td>
                            <td><?php echo ($p['status']) ? '<span class="label label-success">'.lang('store::approved') .'</span>': '<span class="label label-warning">'.lang('store::not-approved').'</span>' ?></td>
                            <td>
                                <?php if($p['type'] == 'intangible'): ?>
                                    <a data-toggle="tooltip" title="<?php _lang('download-file')?>" href="<?php echo url_to_pager('feed-download')?>?file=<?php echo url_img($p["product_path"])?>&name=<?php echo $p['name']?>" class="btn btn-secondary-outline btn-sm"><i class="ion-android-download"></i></a>
                                <?php endif; ?>
                                <a ajax="true" href="<?php echo url_to_pager('admincp-product-manage-single') ?>?action=edit&pid=<?php echo $p['id']; ?>" class="btn btn-sm btn-warning"><?php _lang('edit') ?></a>
                                <a href="<?php echo url_to_pager("admincp-product-manage-single").'?action=delete&pid='.$p['id'] ?>" class="btn btn-sm btn-danger admin-confirm" data-id="<?php echo $p['id'] ?>"> <i class="ion-trash-b"></i> </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr class="alert alert-info">
                        <?php _lang('store::no-result-found') ?>
                    </tr>
                <?php endif;?>
                </tbody>
            </table>
        </div>
    </div>
</div>