<div class="auction">
	<div class="box">
		<div class="box-content">
			<div class="title"><?php //echo $count_bid; ?>&nbsp;&nbsp;<?php echo lang('auction::auction-my-friends-bid-on') ?></div>
			<?php foreach(get_friends_auctions_bid() as $f_auction_id) : ?>
				<?php foreach(get_auction_all($f_auction_id['user_id']) as $auction): ?>
					<div class="media" id="list">
						<div class="media-left">
							<a class="" href="<?php echo url_to_pager('auction-details').'?id='.$auction['id'].'&title='.$auction['title']; ?>">
								<img id="auction_img" src="<?php echo ($auction['picture']) ? url_img($auction['picture'], 700) : get_avatar(200) ?>" width="200" height="200"/>
							</a>
						</div>
						<div class="media-body">
							<a href="<?php echo url_to_pager('auction-details').'?id='.$auction['id']; ?>" class="">
								<h6>
									<strong id="my-bids"><?php echo $auction['title']; ?></strong>
								</h6>
							</a>
							<p>
								<i class="fa fa-user" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo lang('auction::by') ?> <?php echo get_user_name($auction['user_id']); ?>&nbsp;&nbsp;&nbsp;&nbsp;
								<i class="fa fa-gavel" aria-hidden="true"></i><?php echo count_auction_bid($auction['id']); ?> Bids
							</p>
							<p>Current Bid:
								<strong>$<?php echo $auction['current_bid']; ?>.00</strong>
							</p>
							<p>
								<i class="fa fa-clock-o" aria-hidden="true"></i><?php echo lang('auction::time-left') ?><?php echo time_countdown($auction['end_date']); ?>
							</p>
							<p>
								<input type="checkbox" name=""/><?php echo lang('auction::add-to-compare') ?>
							</p>
						</div>
					</div>
				<?php endforeach;
			endforeach; ?>
		</div>
	</div>
</div>