<div class="auction">
	<div class="box">
		<div class="box-content">
			<div class="title">
				<strong><?php echo lang('auction::my-auction') ?></strong>
			</div>
			<?php if(isset($_GET['status']) && $_GET['status'] == 'OK') { ?>
				<div class="alert alert-success"><?php echo lang('auction::successfully-approved') ?></div>
			<?php } ?>
			<table border="0" class="table table-responsive" id="auction-table">
				<tr>
					<td width=""><?php echo lang('auction::auctions') ?></td>
					<td width=""><?php echo lang('auction::category') ?></td>
					<td width=""><?php echo lang('auction::reserved-price') ?></td>
					<td width=""><?php echo lang('auction::buy-now-price') ?></td>
					<td width=""><?php echo lang('auction::offer') ?></td>
					<td width=""><?php echo lang('auction::bid(s)') ?></td>
					<td width=""><?php echo lang('auction::bid-current') ?></td>
					<td width=""><?php echo lang('auction::current-bidder') ?></td>
					<td width=""><?php echo lang('auction::option') ?></td>
				</tr>
				<?php foreach(get_my_auction() as $auction) { ?><?php $cat = get_auction_category($auction['category_id']); ?><?php $bid = count_auction_bid($auction['id']); ?><?php $offer = count(get_auction_bid($auction['id'])); ?>
					<tr id="row-id">
						<td>
							<a href="<?php echo url_to_pager('auction-details').'?id='.$auction['id']; ?>" class="">
								<h6>
									<strong id="hides"><?php echo $auction['title']; ?></strong>
								</h6>
							</a>
						</td>
						<td><?php echo lang($cat['title']); ?></td>
						<td>$<?php echo $auction['reserved_price']; ?>.00</td>
						<td>$<?php echo $auction['buy_price']; ?>.00</td>
						<td><?php echo $offer; ?></td>
						<td><?php echo $bid; ?></td>
						<td>$<?php echo $auction['current_bid']; ?>.00</td>
						<td>&nbsp;</td>
						<td>
							<a href="" class="btn btn-warning" data-toggle="modal" data-target="#offerModal<?php echo $auction['id']; ?>"><?php echo lang('auction::offer') ?></a>
							<a href="" class="btn btn-info" data-toggle="modal" data-target="#bidModal<?php echo $auction['id']; ?>"><?php echo lang('auction::bid') ?></a>
						</td>
					</tr><!-- Bids Modal -->
					<div id="bidModal<?php echo $auction['id']; ?>" class="modal fade" role="dialog">
						<div class="modal-dialog">
							<!-- Modal content-->
							<div class="modal-content">
								<div class="modal-header">
									<h4 class="modal-title"><?php echo $auction['title']; ?><?php echo lang('auction::bid') ?></h4>
									<button type="button" class="close" data-dismiss="modal">&times;</button>
								</div>
								<div class="modal-body">
									<p>
										<span class="username"><?php echo lang('auction::username') ?></span>
										<span class="price" style="margin-left: 110px"><?php echo lang('auction::price') ?></span>
										<span class="option" style="margin-left: 130px"><?php echo lang('auction::option') ?></span>
									</p>
									<?php $get_approved = auction_select_approve($auction['id'], 1); $count = count($get_approved); if($count <= 0) { ?>
										<?php foreach(get_auction_bid_all($auction['id']) as $bid) { ?>
											<p>
												<span class="username-content"><?php echo get_user_name($bid['user_id']); ?></span>
												<span class="price-content">$<?php echo $bid['price']; ?>.00</span>
												<span class="option-content"><a href="<?php echo url_to_pager('auction-approve').'?auction-id='.$auction['id'].'&user_id='.$bid['user_id'].'&type=approve'; ?>" class="btn btn-primary"><?php echo lang('auction::approve') ?></a></span>
											</p>
										<?php } ?>
									<?php } else { ?>
										<p>
											<span class="username-content"><?php echo get_user_name($get_approved['user_id']); ?></span>
											<span class="price-content">$<?php echo $get_approved['price']; ?>.00</span>
											<span class="option-content"><a href="<?php echo url_to_pager('auction-approve').'?auction-id='.$auction['id'].'&user_id='.$get_approved['user_id'].'&price='.$get_approved['price'].'&type=cancel'; ?>" class="btn btn-danger"><?php echo lang('auction::cancel') ?></a><!--<a href="" class="btn btn-danger">Decline</a>--></span>
										</p>
									<?php } ?>
								</div>
								<div class="modal-footer">
									<button type="button" class="btn btn-default" data-dismiss="modal"><?php echo lang('auction::close') ?></button>
								</div>
							</div>
						</div>
					</div><!-- End Modal --><!-- Offer Modal -->
					<div id="offerModal<?php echo $auction['id']; ?>" class="modal fade" role="dialog">
						<div class="modal-dialog">
							<!-- Modal content-->
							<div class="modal-content">
								<div class="modal-header">
									<h4 class="modal-title"><?php echo $auction['title']; ?>&nbsp;<?php echo lang('auction::offer') ?></h4>
									<button type="button" class="close" data-dismiss="modal">&times;</button>
								</div>
								<div class="modal-body">
									<p>
										<span class="username"><?php echo lang('auction::username') ?></span><span class="price">Price</span><span class="option"><?php echo lang('auction::option') ?></span>
									</p>
									<?php foreach(get_auction_offer_all($auction['id']) as $offer): ?>
										<p>
											<span class="username-content"><?php echo get_user_name($offer['user_id']); ?></span>
											<span class="price-content">$<?php echo $offer['price']; ?>.00</span>
											<span class="option-content">
                                                <a href="<?php echo url_to_pager('auction-approve').'?auction-id='.$auction['id']; ?>" class="btn btn-primary"><?php echo lang('auction::approve') ?></a>&nbsp;|&nbsp;
                                                <a href="" class="btn btn-danger"><?php echo lang('auction::decline') ?></a>
                                                <a href="<?php echo url_to_pager('auction-approve').'?auction-id='.$auction['id']; ?>" class="btn btn-info">Approve</a>&nbsp;|&nbsp;
                                                <a href="" class="btn btn-danger">Decline</a>
                                            </span>
										</p>
									<?php endforeach; ?>
								</div>
								<div class="modal-footer">
									<button type="button" class="btn btn-danger" data-dismiss="modal"><?php echo lang('auction::close') ?></button>
								</div>
							</div>
						</div>
					</div><!-- End Modal -->
				<?php } ?>
			</table>
		</div>
	</div>
</div>