<?php
/**
 * @var string $title
 * @var string $description
 * @var string $content
 * @var array $links
 * */
?>
<div class="wrapper">
    <div class="wrapper-title">
        <?php echo $title ?>
        <?php foreach ($links as $link): ?>
            <a class="btn btn-sm btn-outline-<?php echo $link['type'] ?> admin-header-buttons" href="<?php echo $link['url'] ?>" <?php echo !$link['modal'] ?: 'data-toggle="modal" data-target="#mediachat-modal"' ?> data-title="<?php echo $link['title'] ?>"><?php echo $link['title'] ?></a>
        <?php endforeach; ?>
    </div>
    <div class="wrapper-content">
        <?php echo $content ?>
    </div>
</div>
<div id="mediachat-modal" class="modal fade mediachat-modal" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"><?php echo lang('add-server') ?></h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>