<div class="panel-container" style="padding: 0px;">
	<div class="title" style="margin: 0px 0px; padding: 16px 0px;">
		<i class="ion-android-person-add"></i> <?php echo lang('social::import-contacts') ?>
	</div>
	<div>
		<div class="getstarted-content">
			<div id="social-import-services-pane">
				<h6><?php echo lang('social::search-address-for-friends') ?></h6>
				<?php echo lang('social::search-address-for-friends-note') ?>
				<ul class="services">
					<li class="clearfix">
						<div class="pull-left">
							<img src="<?php echo img('images/social/facebook.png') ?>"/> Facebook
						</div>
						<div class="pull-right">
							<button class="btn btn-secondary facebook-send-dialog " data-url="<?php echo 'https://www.facebook.com/dialog/send?app_id='.config('facebook-app-id').'&link='.url().'&redirect_uri='.url_to_pager('social-import-facebook') ?>"><?php echo lang('social::find-friends') ?></button>
						</div>
					</li>
					<li class="clearfix">
						<div class="pull-left">
							<img src="<?php echo img('images/social/gmail.png') ?>"/> Gmail
						</div>
						<div class="pull-right">
							<button class="btn btn-secondary facebook-send-dialog " data-url="<?php echo url_to_pager('social-import-gmail') ?>"><?php echo lang('social::find-friends') ?></button>
						</div>
					</li>
				</ul>
			</div>
			<div id="social-imported-contacts-pane">

			</div>
		</div>

		<div class="getstarted-footer clearfix">
			<div class="pull-right">
				<a href="<?php echo url_to_pager("signup-welcome").'?step=finish' ?>" class="btn btn-secondary"><?php echo lang('skip') ?></a>
				<a ajax="true" href="<?php echo url_to_pager("signup-welcome").'?step=add-people' ?>" class="btn btn-info"><?php echo lang('continue') ?></a>
			</div>
		</div>

	</div>
</div>