<div id="feedback-menu-widget" class="box">
	<div class="box-content">
		<a ajax="true" href="<?php echo url_to_pager('creditgift') ?>" class=" btn btn-secondary btn-block"><?php echo lang('creditgift::my-transactions') ?></a>
		<a ajax="true" href="<?php echo url_to_pager('creditgift-creditrank') ?>" class=" btn btn-secondary btn-block"><?php echo lang('creditgift::credits-rank') ?></a>
	</div>

</div>