<?php $app = app() ?>
<div class="box">
    <div class="title"><?php echo lang('about') ?><?php echo get_user_name($app->profileUser) ?></div>
    <div class="box-content">
        <div class="row">
            <div class="col-sm-5">
                <ul>
                    <li>
                        <a href="<?php echo profile_url('about?type=overview', $app->profileUser) ?>"><?php echo lang('overview') ?></a>
                    </li>
                    <?php foreach (get_custom_field_categories("user") as $category): ?>
                        <li>
                            <a href="<?php echo profile_url('about?type='.$category['id'], $app->profileUser) ?>"><?php echo lang($category['title']) ?></a>
                        </li>
                    <?php endforeach ?>
                </ul>
            </div>
            <div class="col-sm-7">
                <?php if ($type == 'overview'): ?>
                    <ul>
                        <?php if (config('enable-last-seen', true)): ?>
                            <li>
                                <span class="online-status <?php echo get_online_status_icon($app->profileUser) ?>"></span>
                                <span style="margin-left:10px;color:grey !important"><span style="color:#ABACAD !important;font-weight:normal !important" class="timeago " title="<?php echo date('c', $app->profileUser['online_time']) ?>"><?php echo date('c', $app->profileUser['online_time']) ?></span></span>
                            </li>
                        <?php endif ?>
                        <?php if ($app->profileUser['country']): ?>
                            <li>
                                <span><i class="ion-ios-location"></i> <?php echo lang('from') ?></span>
                                <?php echo ($app->profileUser['city'] ? $app->profileUser['city'].', ' : '').($app->profileUser['state'] ? $app->profileUser['state'].', ' : '').ucwords($app->profileUser['country']) ?>
                            </li>
                        <?php endif ?>
                        <?php if (config('enable-gender', true) && fire_hook("none-human.entity.custom", $app->profileUser, array(true))): ?>
                            <?php if ($app->profileUser['gender']): ?>
                                <li>
                                    <span><i class="<?php echo $app->profileUser['gender'] == 'female' ? 'ion-woman' : 'ion-man' ?>"></i></span> <?php echo ucwords(lang($app->profileUser['gender'])) ?>
                                </li>
                            <?php else: ?>
                                <?php fire_hook('enable.gender.exception'); ?>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if (config('enable-birthdate', true) && $app->profileUser['birth_day']): ?>
                            <li><span><i class="ion-android-calendar"></i></span>
                                <?php echo $app->profileUser['birth_day'].', '.lang($app->profileUser['birth_month']).(can_view_birthdate($app->profileUser) ? ', '.$app->profileUser['birth_year'] : '') ?>
                            </li>
                        <?php endif ?>
                        <?php fire_hook('enable.gender.exception'); ?>
                        <?php if ($app->profileUser['bio'] && $app->profileUser['bio']): ?>
                            <li>
                                <span><i class="ion-ios-information-outline"></i> <?php echo lang('bio') ?></span> <?php echo output_text($app->profileUser['bio']) ?>
                            </li>
                        <?php endif ?>
                    </ul>
                <?php else: ?>
                    <?php foreach (get_custom_fields('user', $type) as $field): ?>
                        <?php if (get_user_data($field['title'], $app->profileUser)): ?>
                            <ul>
                                <li>
                                    <strong><?php echo lang($field['title']) ?> : </strong> <?php echo get_user_data($field['title'], $app->profileUser) ?>
                                </li>
                            </ul>
                        <?php endif ?>
                    <?php endforeach ?>
                <?php endif ?>
            </div>
        </div>
    </div>
</div>