<input type="hidden" name="val[id]" value="<?php echo $pageInfo['slug'] ?>"/>
<?php if($pageInfo['page_type'] == 'auto'): ?>
	<div class="form-group">
		Page Url :
		<strong><a href="<?php echo url($pageInfo['slug']) ?>"><?php echo url($pageInfo['slug']) ?></a></strong>
	</div>
<?php endif ?>
<div class="form-group">
	<label><?php echo lang('page-title') ?>(English)</label>
	<input type="text" name="val[title][english]" class="form-control" <?php echo $pageInfo['page_type'] == 'manual' ? 'disabled' : '' ?> value="<?php echo get_phrase('english', $pageInfo['title']) ?>"/>
	<a href="" class="other-languages-link" onclick="return show_other_languages('#page-info-other-languages')"><?php echo lang('edit-other-languages') ?></a>
	<div class="other-languages" id="page-info-other-languages">
		<?php foreach(get_all_languages() as $language): ?>
			<?php if($language['language_id'] != 'english'): ?>
				<input class="form-control" <?php echo ($pageInfo['page_type'] == 'manual') ? 'disabled' : null ?> value="<?php echo get_phrase($language['language_id'], $pageInfo['title']) ?>" type="text" name="val[title][<?php echo $language['language_id'] ?>]" placeholder="<?php echo lang('page-title') ?>"/>
				<br>
				<p class="help-block"><?php echo $language['language_title'] ?></p>
			<?php endif ?>
		<?php endforeach ?>
	</div>
</div>

<div class="form-group">
	<label><?php echo lang('page-url-slug') ?></label>
	<input type="text" name="val[slug]" class="form-control" value="<?php echo $pageInfo['slug'] ?>"/>
</div>

<div class="form-group">
	<label><?php echo lang('page-description') ?></label>
	<input type="text" name="val[description]" class="form-control" value="<?php echo $pageInfo['description'] ?>"/>
</div>

<div class="form-group">
	<label><?php echo lang('page-keywords') ?></label>
	<input type="text" name="val[keywords]" class="form-control" value="<?php echo $pageInfo['keywords'] ?>"/>
</div>

<?php if($pageInfo['page_type'] == 'auto'): ?>
	<textarea name="val[content][english]" class="ckeditor"><?php echo get_phrase('english', $pageInfo['content']) ?></textarea>
	<br>
	<a href="" class="other-languages-link" onclick="return show_other_languages('#page-info-other-languages-content')"><?php echo lang('edit-other-languages') ?></a>
	<br>
	<div class="other-languages" id="page-info-other-languages-content">
		<?php foreach(get_all_languages() as $language): ?>
			<?php if($language['language_id'] != 'english'): ?>
				<textarea name="val[content][<?php echo $language['language_id'] ?>]" class="ckeditor"><?php echo get_phrase($language['language_id'], $pageInfo['content']) ?></textarea>
				<br>
				<p class="help-block"><?php echo $language['language_title'] ?></p>
			<?php endif ?>
		<?php endforeach ?>
	</div>
<?php endif ?>