<div class="box">
	<div class="title"><?php echo lang('delete-my-account') ?></div>
	<div class="box-content" style="padding:30px 10%">
		<p class="help-block"><?php echo lang('delete-account-info') ?></p>
		<?php if($message): ?>
			<div class="alert alert-danger"><?php echo $message ?></div>
		<?php endif ?>

		<form action="" method="post">
			<?php CSRFProtection::embed() ?>
			<div class="field">
				<div class="top">
					<label class="control-label"><?php echo lang('current-password') ?></label>
				</div>
				<div class="bottom">
					<input class="form-control" type="password" name="password" placeholder=""/>
				</div>
			</div>
			<div class="divider"></div>
			<div class="submit">
				<button class="btn btn-danger action-button"><i style="margin-right: 2px" class="font-awesome-ismall fa fa-trash"></i>  <?php echo lang('delete-my-account') ?></button>
			</div>
		</form>
	</div>
</div>