<div class="box" id="account-menu">
	<div class="media media-md" style="border: none">
		<div class="media-left">
			<div class="media-object">
				<img src="<?php echo get_avatar(75) ?>"/>
			</div>
		</div>
		<div class="media-body">
			<h6 class="media-heading"><?php echo get_user_name() ?></h6>
			<a href="<?php echo profile_url() ?>" ajax="true" data-container="#user-profile-content-container"><?php echo lang('profile') ?></a>
			|
			<a ajax="true" href="<?php echo url_to_pager('account') ?>"><i style="margin-right: 2px" class="font-awesome-ismall fa fa-edit"></i> <?php echo lang('edit-profile') ?></a>
		</div>
	</div>
</div>