<div class="box">
	<div class="title"><?php echo lang('change-your-password') ?></div>
	<div class="box-content">
		<p class="help-block">
			<?php echo lang('change-password-info') ?>
		</p>
		<?php if($message): ?>
			<div class="alert alert-danger"><?php echo $message ?></div>
		<?php endif ?>
		<?php if($success): ?>
			<div class="alert alert-success"><?php echo $success ?></div>
		<?php endif ?>
		<form action="" method="post" class="ajax-form">
			<?php CSRFProtection::embed() ?>
			<div class="field">
				<div class="left">
					<label class="control-label"><?php echo lang('current-password') ?></label>
				</div>
				<div class="right">
					<input class="form-control" type="password" name="val[current]" placeholder="" />
				</div>
			</div>
			<div class="dropdown-divider"></div>
			<div class="field">
				<div class="left">
					<label class="control-label"><?php echo lang('new-password') ?></label>
				</div>
				<div class="right">
					<input class="form-control" type="password" name="val[new]" placeholder="" />
				</div>
			</div>
			<div class="field">
				<div class="left">
					<label class="control-label"><?php echo lang('confirm-new-password') ?></label>
				</div>
				<div class="right">
					<input class="form-control" type="password" name="val[confirm]" placeholder=""/>
				</div>
			</div>
			<div class="divider"></div>
			<div class="submit">
				<button class="btn btn-info action-button"><i style="margin-right: 2px" class="font-awesome-ismall fa fa-check-square-o"></i> <?php echo lang('change') ?></button>
			</div>
		</form>
	</div>
</div>