<?php if (!config('disable-side-site-sharer', false)): ?>
    <?php $link = url();
    $bits = parse_url($link);
    if (count(explode('.', $bits['host'])) < 3 && !in_array($bits['host'], array('::1', 'localhost')) && !ip2long($bits['host'])) {
        $link = $bits['scheme'].'://'.(substr($bits['host'], 0, 4) !== 'www.' ? 'www.'.$bits['host'] : $bits['host']).(isset($bits['port']) ? ':'.$bits['port'] : '').$bits['path'].(!empty($bits['query']) ? '?'.$bits['query'] : '');
    }
    $link = urlencode(urldecode($link));
    $link0 = urldecode(preg_replace('/^.*?:\/\//i', '', $link));
    $link1 = $link;
    $name = get_setting("site_title", "Crea8social");
    $specs = 'width = 500, height = 500, scrollbars = yes' ?>
    <div class="sharer share-site hide-in-mobile <?php echo config('share-site-button-size', 'medium') ?>">
        <?php if (config('facebook-button', true)): ?>
            <button class="share-button ion-social-facebook" onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=<?php echo $link1 ?>', '<?php echo $name ?>', '<?php echo $specs ?>')"></button>
        <?php endif ?>
        <?php if (config('twitter-button', true)): ?>
            <button class="share-button ion-social-twitter" onclick="window.open('https://twitter.com/home?status=<?php echo $link1 ?>', '<?php echo $name ?>', '<?php echo $specs ?>')"></button>
        <?php endif ?>
        <?php if (config('googleplus-button', true)): ?>
            <button class="share-button fa fa-google" onclick="window.open('https://plus.google.com/share?url=<?php echo $link1 ?>', '<?php echo $name ?>', '<?php echo $specs ?>')"></button>
        <?php endif ?>
        <?php if (config('linkedin-button', true)): ?>
            <button class="share-button ion-social-linkedin" onclick="window.open('https://www.linkedin.com/cws/share?url=<?php echo $link1 ?>', '<?php echo $name ?>', '<?php echo $specs ?>')"></button>
        <?php endif ?>
        <?php if (config('whatsapp-button', true)): ?>
            <button class="share-button ion-social-whatsapp" onclick="window.open('https://api.whatsapp.com/send?text=<?php echo $link1 ?>', '<?php echo $name ?>', '<?php echo $specs ?>')"></button>
        <?php endif ?>
        <?php if (config('pinterest-button', true)): ?>
            <!--<button class="share-button ion-social-pinterest" onclick="window.open('https://pinterest.com/pin/create/button/?url=<?php echo $link1 ?>&media=<?php echo $name ?>&description=', '<?php echo $name ?>', '<?php echo $specs ?>')"></button>-->
            <button class="share-button ion-social-pinterest" onclick="window.open('https://pinterest.com/pin/create/button/?url=<?php echo $link1 ?>', '<?php echo $name ?>', '<?php echo $specs ?>')"></button>
        <?php endif ?>
        <?php if (config('telegram-button', true)): ?>
            <button class="share-button ion-android-send" onclick="window.open('https://telegram.me/share/url?url=<?php echo $link1 ?>', '<?php echo $name ?>', '<?php echo $specs ?>')"></button>
        <?php endif ?>
        <?php if (config('email-button', true)): ?>
            <button class="share-button ion-email" onclick="window.open('mailto:?subject=<?php echo $app->title ?>&body=<?php echo $link1 ?>', '_self', '<?php echo $specs ?>')"></button>
        <?php endif ?>
        <?php if (config('feed-button', true)): ?>
            <!--<button class="share-button ion-share" onclick="window.open('<?php echo url('sharer') ?>?url=<?php echo $link ?>', '<?php echo $link1 ?>', '<?php echo $specs ?>')"></button>-->
        <?php endif ?>
    </div>
<?php endif ?>