<?php if (!config('disable-inline-link-sharer', false)): ?>
    <?php $link = isset($link) ? $link : sharer_self_url();
    $bits = parse_url($link);
    if (count(explode('.', $bits['host'])) < 3 && !in_array($bits['host'], array('::1', 'localhost')) && !ip2long($bits['host'])) {
        $link = $bits['scheme'].'://'.(substr($bits['host'], 0, 4) !== 'www.' ? 'www.'.$bits['host'] : $bits['host']).(isset($bits['port']) ? ':'.$bits['port'] : '').$bits['path'].(!empty($bits['query']) ? '?'.$bits['query'] : '');
    }
    $link = urlencode(urldecode($link));
    $link0 = urlencode(preg_replace('/^.*?:\/\//i', '', $link));
    $link1 = $link;
    $button_class = isset($button_class) ? $button_class : 'btn btn-secondary';
    $name = get_setting('site_title', 'Crea8social');
    $specs = 'width = 500, height = 500, scrollbars = yes' ?>
    <div class="dropup sharer share-link">
        <button class="<?php echo $button_class ?> dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" title="<?php echo lang('sharer::share')?>">
            <i class="ion-android-share-alt"></i>
            <?php if(!isset($disable_text) || (isset($disable_text) && !$disable_text)): ?>
                <?php echo lang('sharer::share') ?>
            <?php endif; ?>
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
            <?php if (config('facebook-button', true)): ?>
            <a href="javascript:void(0)" class="ion-social-facebook" onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=<?php echo $link1 ?>', '<?php echo $name ?>', '<?php echo $specs ?>')"></a><?php endif ?>
            <?php if (config('twitter-button', true)): ?>
                <a href="javascript:void(0)" class="ion-social-twitter" onclick="window.open('https://twitter.com/home?status=<?php echo $link1 ?>', '<?php echo $name ?>', '<?php echo $specs ?>')"></a>
            <?php endif ?>
            <?php if (config('googleplus-button', true)): ?>
                <a href="javascript:void(0)" class="fa fa-google" onclick="window.open('https://plus.google.com/share?url=<?php echo $link1 ?>', '<?php echo $name ?>', '<?php echo $specs ?>')"></a>
            <?php endif ?>
            <?php if (config('linkedin-button', true)): ?>
                <a href="javascript:void(0)" class="ion-social-linkedin" onclick="window.open('https://www.linkedin.com/cws/share?url=<?php echo $link1 ?>', '<?php echo $name ?>', '<?php echo $specs ?>')"></a>
            <?php endif ?>
            <?php if (config('whatsapp-button', true)): ?>
                <a href="javascript:void(0)" class="ion-social-whatsapp" onclick="window.open('https://api.whatsapp.com/send?text=<?php echo $link1 ?>', '<?php echo $name ?>', '<?php echo $specs ?>')"></a>
            <?php endif ?>
            <?php if (config('pinterest-button', true)): ?>
                <!--<a href="javascript:void(0)" class="ion-social-pinterest" onclick="window.open('https://pinterest.com/pin/create/button/?url=<?php echo $link1 ?>&media=<?php echo $name ?>&description=', '<?php echo $name ?>', '<?php echo $specs ?>')"></a> -->
                <a href="javascript:void(0)" class="ion-social-pinterest" onclick="window.open('https://pinterest.com/pin/create/button/?url=<?php echo $link1 ?>', '<?php echo $name ?>', '<?php echo $specs ?>')"></a>
            <?php endif ?>
            <?php if (config('telegram-button', true)): ?>
                <a href="javascript:void(0)" class="ion-android-send" onclick="window.open('https://telegram.me/share/url?url=<?php echo $link1 ?>', '<?php echo $name ?>', '<?php echo $specs ?>')"></a>
            <?php endif ?>
            <?php if (config('email-button', true)): ?>
                <a href="javascript:void(0)" class="ion-email" onclick="window.open('mailto:?subject=<?php echo $app->title ?>&body=<?php echo $link1 ?>', '_self', '<?php echo $specs ?>')"></a>
            <?php endif ?>
            <?php if (config('feed-button', true)): ?>
                <a href="javascript:void(0)" class="ion-share" onclick="window.open('<?php echo url('sharer') ?>?url=<?php echo $link1 ?>', '<?php echo $name ?>', '<?php echo $specs ?>')"></a>
            <?php endif ?>
        </div>
    </div>
<?php endif ?>