<div class="wrapper">
	<div class="wrapper-title">
		Manage Quizes
	</div>
	<div class="wrapper-content">
		<form action="" method="get" style="margin: 20px 0">
			<?php CSRFProtection::embed() ?>
			<input type="text" class="form-control" name="term" placeholder="<?php echo lang('search') ?>"/>

			<button class="btn btn-sm btn-secondary" style="margin-top: 10px"><?php echo lang('search') ?></button>
		</form>
		<div class="list-table-container">
			<div class="table-responsive">
				<table class="table table-striped list-table">
					<thead>
					<tr>
						<th>
							<div class="list-table-select" data-group="users" data-id="0"></div>
						</th>
						<th>ID</th>
						<th><?php echo lang('title') ?></th>
						<th><?php echo lang('quiz::written-by') ?></th>
						<th><?php echo lang('quiz::views') ?></th>
						<th><?php echo lang('status') ?></th>
						<th><?php echo lang('featured') ?></th>
						<th><?php echo lang('quiz::last-update') ?></th>
						<th><?php echo lang('actions') ?></th>
					</tr>
					</thead>
					<tbody>
					<?php foreach($quizes->results() as $quiz): ?>
						<?php $quiz = arrange_quiz($quiz); ?>
						<tr class="item" id="<?php echo $quiz['id'] ?>">
							<td>
								<div class="list-table-select" data-group="users" data-id="<?php echo $quiz['id'] ?>"></div>
							</td>
							<td><?php echo $quiz['id'] ?></td>
							<td>
								<a href="<?php echo url('quiz/'.$quiz['slug']) ?>"><?php echo lang($quiz['title']) ?></a>
							</td>
							<td>
								<a ajax="true" href="<?php echo url($quiz['publisher']['id']) ?>"><?php echo $quiz['publisher']['name'] ?></a>
							</td>
							<td>
								<?php echo $quiz['views'] ?>
							</td>
							<td>
								<?php echo ($quiz['status']) ? 'Published' : 'Draft' ?>
							</td>
							<td>
								<?php echo ($quiz['featured']) ? 'Yes' : 'No' ?>
							</td>
							<td>
								<?php echo date('d F Y  g:ia', $quiz['update_time']) ?>
							</td>

							<td>
								<div class="dropdown actions">
									<a href="#" data-toggle="dropdown">
										<i class="ion-android-settings"></i>
									</a>
									<div class="dropdown-menu dropdown-menu-right">
										<a class="ion-edit" href='<?php echo url_to_pager('admincp-quiz-manage').'?action=edit&id='.$quiz['id'] ?>'></a>
										<?php if(!is_published($quiz['id'])): ?>
										<a class="fa fa-quiz" href='<?php echo url_to_pager('admincp-quiz-manage-question').'?action=view&id='.$quiz['id'] ?>'>+</a>
										<?php endif ?>
										<?php if(is_published($quiz['id'])): ?>
										<a class="ion-eye" href='<?php echo url_to_pager('admincp-quiz-manage-question').'?action=add&id='.$quiz['id'] ?>'></a>
										<?php endif; ?>
										<a class="admin-confirm ion-android-delete" href="<?php echo url_to_pager('admincp-quiz-manage').'?action=delete&id='.$quiz['id'] ?>"></a>
									</div>
								</div>
							</td>


						</tr>
					<?php endforeach ?>
					</tbody>
				</table>
			</div>
		</div>
		<?php echo $quizes->links() ?>
	</div>
</div>