<div class="box">
    <div class="title"><?php echo lang("store::my-order") ?></div>
    <div class="box-content">
        <?php if($orders->total) : ?>
        <div class="table-responsive">
            <table class="table table-bordered storeTable">
                <thead>
                <tr>

                    <th><?php echo lang("store::order-id") ?></th>
                    <th><?php echo lang("store::order-code") ?></th>
                    <th><?php echo lang("store::payment-type") ?></th>
                    <th><?php  echo lang("store::status")?></th>
                    <th><?php echo ucfirst(lang("store::total")); ?></th>
                    <th><?php  echo lang("store::date")?></th>
                    <th><?php _lang("action")?></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($orders->results() as $o): ?>
                     <tr>
                         <td><?php echo $o['id']; ?></td>
                         <td><?php echo "ORDER_".$o['id']; ?></td>
                         <td><?php echo $o['payment_type']; ?></td>
                         <td><?php echo getOrderStatus($o);?></td>
                         <td><?php echo formatPriceNumber($o['total_price'] + $o['shipping_price']); ?></td>
                         <td><?php echo date('d F, Y',$o['time']) ?></td>
                         <td><a href="<?php echo  url_to_pager("my_orders").'?id='.$o['id']; ?>" class="btn btn-sm btn-primary"> <?php echo lang("store::view"); ?></a></td>
                     </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
            <!--<div class="box-content">
                <?php /*echo  $orders->links() */?>
            </div>-->
        <?php else: ?>
             <div class="alert alert-info"><?php echo lang("store::no-order-available") ?></div>
        <?php endif; ?>
    </div>
</div>