<div class="box">
	<?php if($message): ?>
		<div class="alert alert-success"><?php echo lang('photo::photo-created') ?></div>
	<?php endif ?>
	<div class="global-filter-container" data-url="">
		<div class="row">
			<div class="col-sm-6">
				<h3><?php echo lang('photo::add-new-photo') ?></h3>
			</div>
		</div>
	</div>
	<div class="box-content" style="padding: 20px 10%">
		<form data-error="Something went wrong. try again" action="" method="post" enctype="multipart/form-data">
			<?php CSRFProtection::embed() ?>
			<input type="hidden" name="val[user_id]" value="<?php echo input('id', get_userid()) ?>"/>
			<input type="hidden" name="val[entity_id]" value="<?php echo get_userid() ?>"/>
			<input type="hidden" name="val[entity_type]" value="user"/>
			<!--
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php echo lang('photo::photo-title') ?></label>
                <div class="col-sm-8">
                    <input type="text" name="val[name]" class="form-control" placeholder="<?php echo lang('photo::photo-title') ?>" required=""/>
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php echo lang('photo::photo-description') ?></label>
                <div class="col-sm-8">
                    <textarea name="val[description]" data-height="100px" style="height: 100px" class="form-control auto-grow-input" placeholder="<?php echo lang('photo::photo-description') ?>"></textarea>
                </div>
            </div>
            -->
			<div class="form-group row">
				<label class="control-label col-sm-4"><?php echo lang('privacy') ?></label>
				<div class="col-sm-8">
					<?php fire_hook('privacy.select'); ?>
				</div>
			</div>
			<div class="form-group row">
				<label class="control-label col-sm-4"><?php echo lang('photo::select-photo') ?></label>
				<div class="col-sm-8">
					<input name="image" class="form-control form-control-lg" type="file"/>
				</div>
			</div>
			<button class="btn btn-primary" required=""><?php echo lang('photo::add-photo') ?></button>
		</form>
	</div>
</div>