<div class="box">
	<div class="global-filter-container" data-url="">
		<div class="row">
			<div class="col-sm-6">
				<h3><?php echo lang('photo::edit-album') ?></h3>
			</div>
		</div>
	</div>
	<div class="box-content" style="padding: 20px 10%">
		<form action="" method="post">
			<?php CSRFProtection::embed() ?>
			<input type="hidden" name="val[entity_type]" value="<?php echo input('type', 'user') ?>"/>
			<input type="hidden" name="val[entity_id]" value="<?php echo input('id', get_userid()) ?>"/>
			<div class="form-group row">
				<label class="control-label col-sm-4"><?php echo lang('photo::album-title') ?></label>
				<div class="col-sm-8">
					<input type="text" name="val[name]" class="form-control" placeholder="<?php echo lang('photo::album-title') ?>" value="<?php echo input('val.name', $album['title']); ?>" required/>
				</div>
			</div>
			<div class="form-group row">
				<label class="control-label col-sm-4"><?php echo lang('photo::album-description') ?></label>
				<div class="col-sm-8">
					<textarea name="val[description]" data-height="100px" style="height: 100px" class="form-control auto-grow-input" placeholder="<?php echo lang('photo::album-description') ?>"><?php echo input('val.description', $album['description']); ?></textarea>
				</div>
			</div>
			<div class="form-group row">
				<label class="control-label col-sm-4"><?php echo lang('privacy') ?></label>
				<div class="col-sm-8">
					<?php $default = input('val.privacy', $album['privacy']); ?>
					<?php fire_hook('privacy.select', 'relationship', array($default)); ?>
				</div>
			</div>
			<button class="btn btn-primary" type="submit" name="addAlbum"><?php echo lang('photo::save-album') ?></button>
		</form>
	</div>
</div>