<?php if(is_loggedIn()): ?>
	<?php
	$textLimit = (isset($textLimit) and $textLimit) ? $textLimit : false;
	$avatar = (isset($avatar)) ? $avatar : get_avatar(75);
	$entityId = (isset($entityId)) ? $entityId : get_userid();
	$entityType = (isset($entityType)) ? $entityType : 'user';
	$mt = explode(' ', microtime());
	$generatedId = md5($mt[1].$mt[0].$type.$typeId);
	?>
	<form data-type="<?php echo $type ?>" data-type-id="<?php echo $typeId ?>" enctype="multipart/form-data" action="" class="comment-editor comment-editor-<?php echo $generatedId ?>">
		<?php CSRFProtection::embed() ?>
		<input type="hidden" name="val[type]" value="<?php echo $type ?>"/>
		<input type="hidden" name="val[type_id]" value="<?php echo $typeId ?>"/>
		<input type="hidden" name="val[entity_id]" value="<?php echo $entityId ?>"/>
		<input type="hidden" name="val[entity_type]" value="<?php echo $entityType ?>"/>
		<div data-error="<?php echo lang('comment::comment-editor-error') ?>" class="alert alert-warning" style="margin: 0;margin-bottom: 10px;display: none"></div>
		<div class="media">
			<div class="media-left">
				<div class="media-object">
					<img class="res-img" src="<?php echo $avatar ?>"/>
				</div>
			</div>
			<div class="media-body" style="position: relative;overflow: visible">
				<textarea id="comment-editor-textarea-<?php echo $generatedId ?>" data-mention=".comment-editor-mention-<?php echo $generatedId ?>" name="val[text]" data-target=".comment-editor-<?php echo $generatedId ?>" data-height="35px" class="auto-grow-input mention-input <?php echo ($textLimit) ? 'textarea-limit' : null ?> comment-editor-textarea-<?php echo $generatedId ?>" data-text-limit="<?php echo $textLimit ?>" data-text-limit-count-target=".comment-text-limit-counter-<?php echo $generatedId ?>" placeholder="<?php echo lang('comment::write-comment') ?>"></textarea>
				<div class="mention-user-list comment-editor-mention-<?php echo $generatedId ?> box">
					<img src="<?php echo img('images/loading.gif') ?>" class="indicator"/>
					<div class="listing user-suggestion-list"></div>
                    <div style="background: #f6f7f7;" class="gif-comment-wrapper"></div>
				</div>
				<div class="comment-editor-footer clearfix">
					<div class="pull-left">
						<button data-id="<?php echo $generatedId ?>" class="btn btn-sm btn-info comment-reply-button"><?php echo lang('comment::reply') ?></button>
						<?php if($textLimit): ?>
							<span style="display: inline-block;margin: 10px 5px" class="comment-text-limit-counter-<?php echo $generatedId ?>"><?php echo $textLimit ?></span>
						<?php endif ?>
						<img src="<?php echo img('images/loading.gif') ?>" class="comment-editor-indicator"/>
					</div>
					<div class="pull-right">
						<span class="file-input"><input accept="image/*" class="comment-editor-<?php echo $generatedId ?>-image" type="file" name="image"/></span>
						<?php if(config('enable-voice-comment', 1)): ?>
							<div id="comment-editor-voice-recorder-<?php echo $generatedId ?>" class="comment-editor-voice-recorder voice-recorder" data-toggle="tooltip"
			                    data-original-title="<?php echo lang('comment::voice') ?>" data-id="<?php echo $generatedId ?>">
								<input name="voice" type="hidden" value="" class="voice-input" />
								<a href="#" class="control">
									<i class="ion-mic-a record"></i>
									<i class="ion-stop stop"></i>
								</a>
								<div class="actions">
									<a class="ion-close close" href="#"></a>
									<a class="ion-play play" href="#"></a>
								</div>
							</div>
						<?php endif; ?>
						<a onclick="return file_chooser('.comment-editor-<?php echo $generatedId ?>-image')" data-toggle="tooltip"
			                 data-original-title="<?php echo lang('comment::images') ?>"href="" class="file-chooser">
							<i class="ion-camera"></i></a>
						<?php if(plugin_loaded('emoticons')): ?>
							<span style="position: relative">
                                <a data-target="comment-editor-textarea-<?php echo $generatedId ?>" data-action="0" data-toggle="tooltip"  
			                       data-original-title="<?php echo lang('emoticon::add-emoticons') ?>" class="emoticon-button" href="javascript::void(0)"><i class="ion-android-sad emo-button"></i></a>
                                <div class="emoticon-box emoticon-bottom"></div>
                            </span>
                            <span style="position: relative">
								<a data-toggle="tooltip"
			                       data-original-title="<?php echo lang('comment::add-gif') ?>"href="#" class="comment-gif-selector gif-selector">
									<i class="gif-icon"></i>
									<div class="comment-gif-box gif-box" data-callback="comment.editor.onGIFClick">
										<div class="gif-box-head">
											<span><?php echo lang('gif') ?></span>
											<i class="gif-box-close-button ion-close"></i>
										</div>
										<div class="gif-box-body">
											<input type="text" class="form-control comment-gif-search-input gif-search-input" placeholder="<?php echo lang('gif-search') ?>"/>
											<div class="gif-search-result"></div>
										</div>
										<div class="gif-box-arrow"></div>
										<input name="gif" type="hidden" value="" class="comment-gif-input gif-input"/>
									</div>
								</a>
                            </span>
						<?php endif ?>
					</div>
				</div>
			</div>
		</div>
	</form>
<?php endif ?>