<div class="box marketplace">
    <div class="global-filter-container" data-url="<?php echo url('marketplace') ?>">
        <form id="marketplace-list-search" method="post" onsubmit="return marketplace.filter()" action="" class="form-inline list-search">
            <?php CSRFProtection::embed() ?>
            <i class="search-icon ion-ios-search"></i>
            <input id="marketplace-keyword-filter" value="<?php echo input('s') ?>" type="text" class="form-control search-box filter-input" name="s" data-name="s" placeholder="<?php echo lang('search') ?>" />
        </form>
        <div class="list-head">
            <h3 class="heading"><?php echo lang('marketplace::marketplace') ?></h3>
        </div>
        <div class="filter-pane">
            <form id="marketplace-list-filter" method="post" onsubmit="return marketplace.filter()" action="" class="form-inline list-filter">
                <select id="marketplace-category-filter" name="c" data-name="c" class="c-select filter-input">
                    <option value=""><?php echo lang('marketplace::all-categories') ?></option>
                    <?php foreach (marketplace_get_categories() as $category): ?>
                        <option <?php echo input('c') == $category['id'] ? 'selected' : '' ?> value="<?php echo $category['id'] ?>"><?php echo lang($category['title']) ?></option>
                    <?php endforeach ?>
                </select>
                <input id="marketplace-min-price-filter" type="number" name="p0" data-name="p0" min="0" value="<?php echo input('p0') ?>" class="c-input filter-input" placeholder="<?php echo lang('marketplace::min-price') ?>" />
                <input id="marketplace-max-price-filter" type="number" name="p1" data-name="p1" min="0" value="<?php echo input('p1') ?>" class="c-input filter-input" placeholder="<?php echo lang('marketplace::max-price') ?>" />
                <input id="marketplace-location-filter" type="text" name="l" data-name=l" value="<?php echo input('l') ?>" class="c-input filter-input marketplace-geocomplete" placeholder="<?php echo lang('marketplace::location') ?>" />
                <input id="marketplace-featured-filter" type="checkbox" name="f" data-name="f" value="1" <?php echo input('f') ? 'checked' : '' ?> class="c-input filter-input" /><label for="marketplace-featured-filter"><?php echo lang('marketplace::featured') ?></label>
                <input id="marketplace-submit-filter" type="submit" value="<?php echo lang('filter') ?>" class="filter-input" />
            </form>
        </div>
    </div>
    <div class="box-content">
        <div class="marketplace-listings list grid row">
            <?php echo $message ?>
            <?php $colors = array('red', 'red', 'pink', 'purple', 'deep-purple', 'indigo', 'blue', 'light-blue', 'cyan', 'teal', 'green', 'light-green', 'lime', 'yellow', 'amber', 'orange', 'deep-orange', 'brown', 'grey', 'blue-grey') ?>
            <?php foreach ($listings->results() as $listing): ?>
                <?php $listing_image = $listing['image'] ? url_img($listing['image'], 920) : img('marketplace::images/no_image.jpg', 75) ?>
                <?php $description = trim($listing['description']) == '' ? '<em>'.lang('marketplace::no-description').'</em>' : $listing['description'] ?>
                <?php $price = is_numeric($listing['price']) ? config('currency', '$').$listing['price'] : $listing['price']; ?>
                <?php $price = trim($listing['price']) == '' ? lang('marketplace::free') : $price; ?>
                <?php $color = $colors[(int)((substr(str_pad($listing['id'], 2, '0', STR_PAD_LEFT), 0, 1) % 2 == 0 ? '' : '1').substr(str_pad($listing['id'], 2, '0', STR_PAD_LEFT), -1))]; ?>
                <div class="col-sm-4">
                    <div class="item <?php echo $color ?>">
                        <div class="head">
                            <img class="image" src="<?php echo $listing_image ?>" alt="<?php echo $listing['title'] ?>">
                        </div>
                        <div class="body">
                            <h5 class="title"><?php echo $listing['title'] ?></h5>
                            <small class="category muted"><?php echo lang($listing['category_title']) ?></small>
                            <p class="description"><?php echo str_limit($description, 50) ?></p>
                        </div>
                        <div class="overlay">
                            <?php if ($listing['approved'] == 1 && $listing['active'] == 1): ?>
                                <a href="<?php echo url_to_pager('marketplace-listing', array('slug' => $listing['slug'])) ?>" class="btn btn-outline-info link" ajax="true"><?php echo lang('marketplace::view') ?></a>
                            <?php endif ?>
                            <div class="foot">
                                <a target="_blank" href="<?php echo url($listing['username']) ?>" class="btn btn-outline-info" title="<?php echo lang('marketplace::profile') ?>"><i class="ion-person"></i></a>
                                <?php if (filter_var($listing['link'], FILTER_VALIDATE_URL)): ?>
                                    <a target="_blank" href="<?php echo $listing['link'] ?>" class="btn btn-outline-info" title="<?php echo lang('marketplace::link') ?>"><i class="ion-link"></i></a>
                                <?php endif ?>
                                <?php echo plugin_loaded('sharer') ? view('sharer::share_link', array('link' => url_to_pager('marketplace-listing', array('slug' => $listing['slug'])), 'button_class' => 'btn btn-outline-info', 'disable_text' => true)) : '' ?>
                            </div>
                        </div>
                        <div class="tags">
                            <div class="tag price<?php echo trim($listing['price']) == '' ? ' free' : '' ?>"><?php echo $price ?></div>
                            <?php if ($listing['featured'] == 1): ?>
                                <div class="tag"><?php echo lang('marketplace::featured') ?></div>
                            <?php endif ?>
                        </div>
                    </div>
                </div>
            <?php endforeach ?>
        </div>
    </div>
    <?php if ($listings->total): ?>
        <?php if ($listings->total > config('pagination-limit-listings', 20)): ?>
            <div class="box-content"><?php echo $listings->links() ?></div>
        <?php endif ?>
    <?php else: ?>
        <div class="alert alert-info" style="width: 100%; margin: 0px 14px;"><?php echo lang('marketplace::no-listing-found') ?></div>
    <?php endif ?>
</div>