<div class="box">
    <div class="title"><?php echo lang('group::groups') ?></div>
    <div class="group-list">
        <div class="body">
            <div class="listings">
                <div class="listing row">
                    <?php foreach($groups->results() as $group): ?>
                        <div class="col-md-6">
                            <?php echo view('group::display', array('group' => $group)) ?>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>
        </div>
    </div>
    <div class="box-content">
        <?php if(!$groups->total): ?>
            <div class="alert alert-info">
                <?php echo lang('group::no-group-found') ?>
            </div>
        <?php else: ?>
            <?php echo $groups->append(array('term' => input('term'), 'type' => input('type', 'recommend'), 'filter' => input('filter')))->links(true) ?>
        <?php endif ?>
    </div>
</div>