<div class="wrapper">
	<div class="wrapper-title"><?php echo lang('event::manage-categories') ?>
		<a
				href="<?php echo url_to_pager('admin-event-category-add') ?>"><?php echo lang('game::add-category') ?></a>
	</div>
	<div class="wrapper-content">
		<div class="list-table-container">
			<div class="row list-table-select-actions hide" data-group="users">
				<div class="col-sm-12">
					<a href="<?php echo url_to_pager('admin-event-batch-action') ?>?action=delete_cat"
					   class="action-link list-table-select-action" data-group="users"><?php echo lang('delete') ?></a>
					<?php fire_hook('admin.user.list.actions'); ?>
				</div>
			</div>
			<div class="table-responsive">
				<table class="table table-striped list-table">
					<thead>
					<tr>
						<th>
							<div class="list-table-select" data-group="users"
							     data-id="0"></div>
						</th>
						<th style="width: 10%">ID</th>
						<th style="width: 30%"><?php echo lang('event::category-title') ?></th>

						<th style="width: 20%"><?php echo lang('actions') ?></th>
					</tr>
					</thead>
					<tbody data-url="<?php echo url_to_pager('admin-event-manage-category').'?action=order' ?>"
					       class="admincp-sortable" style="position: relative">
					<?php foreach($categories as $category): ?>
						<tr class="item" id="<?php echo $category['id'] ?>">
							<td>
								<div class="list-table-select" data-group="users"
								     data-id="<?php echo $category['id'] ?>"></div>
							</td>
							<td style="width: 10%"><?php echo $category['id'] ?></td>
							<td style="width: 30%"><?php echo lang($category['title']) ?></td>

							<td>
								<div class="dropdown actions">
									<a href="#" data-toggle="dropdown">
										<i class="ion-android-settings"></i>
									</a>
									<div class="dropdown-menu dropdown-menu-right">
										<a class="ion-edit"
										   href='<?php echo url_to_pager('admin-event-manage-category').'?action=edit&id='.$category['id'] ?>'></a>
										|
										<a class="admin-confirm ion-android-delete"
										   href="<?php echo url_to_pager('admin-event-manage-category').'?action=delete&id='.$category['id'] ?>"></a>
									</div>
								</div>
							</td>


						</tr>
					<?php endforeach ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>