<div style="background-color: #FFFFFF">
    <div class=" lg-title" style="background-color: transparent; margin-top: 50px; border-bottom: none;"><?php echo lang('choose-plan') ?></div>
    <div class="container">
        <div class="membership-plans-container">
            <?php foreach (get_membership_plans() as $plan): ?>
                <div class="each-plan <?php echo ($plan['recommend']) ? 'recommend' : false ?>">
                    <span class="title"><?php echo lang($plan['title']) ?></span>
                    <span class="description"><?php echo lang($plan['description']) ?></span>
                    <span class="price"><?php echo $plan['price'] ?><?php echo config('default-currency') ?></span>
                    <?php if ($plan['type'] == 'recurring'): ?>
                        <span class="price-add"></span>
                    <?php endif ?>
                    <span class="type">
                        <?php if ($plan['type'] == 'recurring'): ?>
                            <?php echo lang('recurring-per', array('n' => $plan['expire_no'], 'm' => lang(''.$plan['expire_type'].'s'))) ?>
                        <?php else: ?>
                            <?php echo lang("".$plan['type']) ?>
                        <?php endif ?>
                        </span>
                    <a href="<?php echo url("membership/payment?plan=".$plan['id']) ?>" class="btn btn-info btn-sm"><?php echo lang('choose-plan') ?></a>
                </div>
            <?php endforeach ?>
        </div>
    </div>
</div>