<?php $hide_icons = isset($hide_icons) ? $hide_icons : false; $hide_counts = isset($hide_counts) ? $hide_counts : false; $show_separator = isset($show_separator) ? $show_separator : false; ?>

<?php if(config('feed-like-type', 'regular') == 'regular'): ?>
	<li id="feed-reaction-container-<?php echo $typeId ?>">
        <a onclick="return like_item('<?php echo $type ?>', '<?php echo $typeId ?>')" data-status="<?php echo has_liked($type, $typeId) ? '1' : 0 ?>" data-hide-icon="<?php echo $hide_icons ? 1 : 0 ?>" data-hide-count="<?php echo $hide_counts ? 1 : 0 ?>" class=" like-button-<?php echo $type ?>-<?php echo $typeId ?> like-button <?php echo has_liked($type, $typeId) ? 'liked' : null ?>" href="">
            <?php if(!$hide_icons): ?>
                <i class="fa fa-thumbs-o-up font-awesome-i"></i>
            <?php endif; ?>
            <span data-toggle="tooltip" data-original-title="<?php echo lang('like::like') ?>" class="hidden-md-down"><?php echo lang('like::like') ?></span>
        </a>
    </li>
<?php else: ?>
	<li class="feed-react">
		<div class="react-items react-items-<?php echo $typeId ?>">
			<ul>
				<li><a data-type="<?php echo $type ?>" data-target="<?php echo $typeId ?>" data-hide-icon="<?php echo $hide_icons ? 1 : 0 ?>" data-hide-count="<?php echo $hide_counts ? 1 : 0 ?>" href="" data-code="1" data-toggle="tooltip" title="<?php echo lang('like::like') ?>"><img src="<?php echo img('images/reaction/like.gif') ?>"/></a></li>
				<li><a data-type="<?php echo $type ?>" data-target="<?php echo $typeId ?>" data-hide-icon="<?php echo $hide_icons ? 1 : 0 ?>" data-hide-count="<?php echo $hide_counts ? 1 : 0 ?>" href="" data-code="4" data-toggle="tooltip" title="<?php echo lang('like::love') ?>"><img src="<?php echo img('images/reaction/love.gif') ?>"/></a></li>
				<li><a data-type="<?php echo $type ?>" data-target="<?php echo $typeId ?>" data-hide-icon="<?php echo $hide_icons ? 1 : 0 ?>" data-hide-count="<?php echo $hide_counts ? 1 : 0 ?>" href="" data-code="5" data-toggle="tooltip" title="<?php echo lang('like::haha') ?>"><img src="<?php echo img('images/reaction/haha.gif') ?>"/></a></li>
				<li><a data-type="<?php echo $type ?>" data-target="<?php echo $typeId ?>" data-hide-icon="<?php echo $hide_icons ? 1 : 0 ?>" data-hide-count="<?php echo $hide_counts ? 1 : 0 ?>" href="" data-code="7" data-toggle="tooltip" title="<?php echo lang('like::wow') ?>"><img src="<?php echo img('images/reaction/wow.gif') ?>"/></a></li>
				<li><a data-type="<?php echo $type ?>" data-target="<?php echo $typeId ?>" data-hide-icon="<?php echo $hide_icons ? 1 : 0 ?>" data-hide-count="<?php echo $hide_counts ? 1 : 0 ?>" href="" data-code="8" data-toggle="tooltip" title="<?php echo lang('like::sad') ?>"><img src="<?php echo img('images/reaction/sad.gif') ?>"/></a></li>
				<li><a data-type="<?php echo $type ?>" data-target="<?php echo $typeId ?>" data-hide-icon="<?php echo $hide_icons ? 1 : 0 ?>" data-hide-count="<?php echo $hide_counts ? 1 : 0 ?>" href="" data-code="9" data-toggle="tooltip" title="<?php echo lang('like::angry') ?>"><img src="<?php echo img('images/reaction/angry.gif') ?>"/></a></li>
			</ul>
		</div>
        <a id="react-button-<?php echo $type ?>-<?php echo $typeId ?>" data-type="<?php echo $type ?>" data-target="<?php echo $typeId ?>" data-status="<?php echo has_reacted($type, $typeId) ? '1' : 0 ?>" data-hide-icon="<?php echo $hide_icons ? 1 : 0 ?>" data-hide-count="<?php echo $hide_counts ? 1 : 0 ?>" class="react-button-<?php echo $type ?>-<?php echo $typeId ?> react-button <?php echo has_reacted($type, $typeId) && !has_disliked($type, $typeId) ? 'liked' : null ?>" href="">
			<?php $has_reacted = has_reacted($type, $typeId); ?>
			<?php if($has_reacted): ?>
				<?php echo view("like::react-img", array('type' => $type, 'type_id' => $typeId, 'hide_icon' => $hide_icons, 'hide_count' => $hide_counts)) ?>
			<?php else: ?>
                <?php if(!$hide_icons): ?>
                    <i class="fa fa-thumbs-o-up font-awesome-i"></i>
                <?php endif; ?>
    			<span class="hidden-md-down"><?php echo lang('like::like') ?></span>
            <?php endif; ?>
        </a>
	</li>
<?php endif ?>
<?php if(config('enable-dislike', false)): ?>
    <li>
        <?php if($show_separator): ?>
            <span class="hidden-md-down">· </span>
        <?php endif; ?>
        <a onclick="return dislike_item('<?php echo $type ?>', '<?php echo $typeId ?>')" data-status="<?php echo has_disliked($type, $typeId) ? '1' : 0 ?>" data-hide-icon="<?php echo $hide_icons ? 1 : 0 ?>" data-hide-count="<?php echo $hide_counts ? 1 : 0 ?>" class="dislike-button-<?php echo $type ?>-<?php echo $typeId ?> like-button <?php echo has_disliked($type, $typeId) ? 'disliked' : null ?>" href="">
            <?php if(!$hide_icons): ?>
                <i class="fa fa-thumbs-o-down font-awesome-i"></i>
            <?php endif; ?>
            <span class="hidden-md-down"><?php echo lang('like::dislike') ?></span>
        </a>
    </li>
<?php endif ?>