<div class="box">
    <div class="box-content">
        <div id="people-list-container" class="box-content members clearfix grid-listing-container">
            <?php foreach($users->results() as $user): ?>
                <?php $gender = (isset($user['gender']) and $user['gender']) ? $user['gender'] : null ?>
                <?php $gender_image = ($gender) ? img("images/avatar/{$gender}.png") : img("images/avatar.png") ?>
                <?php $user_image = $user['avatar'] ? url_img($user['avatar'], 200) : $gender_image ?>
                <?php $user_name = trim($user['first_name'].$user['last_name']) == '' ? $user['username'] : $user['first_name'].' '.$user['last_name'] ?>
                <?php $online_status = $user['online_time'] > (time() - 50) ? 'online' : 'offline' ?>
                <?php $info = array() ?>
                <?php if(!empty($user['gender'])) $info[] = lang($user['gender']); ?>
                <?php if(!empty($user['country'])) $info[] = ucwords($user['country']); ?>


                <?php $friends = count(get_friends($user['id'])); $followers = count(get_followers($user['id'])); $followings = count(get_following($user['id'])); $posts = count_user_posts($user['id']); ?>
                <?php if($user['id'] != $app->profileUser['id']): ?>
                    <?php echo view('user/display', array('user' => $user)) ?>
                <?php endif; ?>
            <?php endforeach ?>
        </div>
    </div>
    <div class="box-content">
        <?php echo $users->links(true) ?>
    </div>
</div>
<style>
    .user-card-widget .user .avatar {
        width: 100%;
        border-radius: 50%;
        border: solid 4px #fff;
    }

    .grid-listing-container .each-item {
        height: 350px !important;
        border-radius: 4px;
    }
    .user-card-widget .actions{
        display: table;
        align-items: center;
        justify-content: center;
        width: 100%;
        height: 20%;
        text-align: center;
        margin: 0 auto;
        position: relative;
    }
    .message-me-large{
        display:inline-block !important;
    }
    .message-me-small {
        display: inline-block !important;
    }
    .user-card-widget .s-count {
        padding: 0px 10px 10px 10px !important;
    }
    .user-card-widget .stats {
        background-color: #f9fafa !important;
        padding: 0px 10px 10px 10px !important;
    }
    .grid-listing-container .each-item {
        background: #ffffff;
    }
    .user-card-widget .item-info{
        position: absolute;
        top: 175px;
        background-color: #f9fafa;
        min-height: 175px;
    }
    .user-card-widget .stats {
        padding: 0px 10px 10px 10px !important;
    }
    .actions .btn-secondary {
        color: #ffffff !important;
        background-color: #6381f0 !important;
    }
    .user-card-widget .stats .question{
        background: #f0f8fc;
        border-radius: 50%;
        height: 44px;
        width: 44px;
        display: table;
        text-align: center;
        margin: 0 auto;
        margin-top: 5px;
        color: #6381f0;
    }
    .user-card-widget .stats .question > i{
        margin-top: 12px
    }
    .user-card-widget .stats .badge-check{
        background: #e0f4ea;
        border-radius: 50%;
        height: 44px;
        width: 44px;
        display: table;
        text-align: center;
        margin: 0 auto;
        margin-top: 5px;
        color: #1fc9ab;
    }
    .user-card-widget .stats .badge-check > i {
        margin-top: 12px
    }
    .user-card-widget .stats .comments{
        background: #f9f6e6;
        border-radius: 50%;
        height: 44px;
        width: 44px;
        display: table;
        text-align: center;
        margin: 0 auto;
        margin-top: 5px;
        color: #ffd322;
    }
    .user-card-widget .stats .comments > i {
        margin-top: 12px
    }
</style>