<div class="box store-container">
    <div class="title">
        <?php _lang('store::add-store'); ?>
    </div>
    <div class="box-content" style="padding: 20px 10%">

        <?php if($message): ?>
           <div class="alert alert-danger"><?php echo $message ?></div>
        <?php endif; ?>

        <form action="" method="post" enctype="multipart/form-data">
            <?php CSRFProtection::embed()?>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::store-name')?><span class="important">*</span></label>
                <div class="col-sm-8">
                    <input value="<?php echo input('val.name')?>" type="text" name="val[name]" class="form-control"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::location')?><span class="important">*</span></label>
                <div class="col-sm-8">
                    <select class="c-select" name="val[location]">
                        <option value=""><?php _lang('select-country')?></option>
                        <?php load_functions("country"); ?>
                        <?php foreach(get_countries() as $country => $name):?>
                            <option <?php echo (input("val.location") == $name) ? "selected" : null?> value="<?php echo $name?>"><?php echo ucwords($name)?></option>
                        <?php endforeach?>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::desc')?><span class="important">*</span></label>
                <div class="col-sm-8">
                    <textarea name="val[desc]" class="ckeditor"><?php echo input('val.desc')?></textarea>
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::cover-picture')?><span class="important">*</span></label>
                <div class="col-sm-8">
                    <input type="file" name="image" class="form-control"/>

                </div>
            </div>
            <?php echo fire_hook("more.store.input.fields",null,array()); ?>
            <div class="divider"></div>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::contact-name')?><span class="important">*</span></label>
                <div class="col-sm-8">
                    <input value="<?php echo input('val.cname')?>" type="text" name="val[cname]" class="form-control"/>

                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::email-address')?> <span class="important">*</span></label>
                <div class="col-sm-8">
                    <input value="<?php echo input('val.email')?>" type="text" name="val[email]" class="form-control"/>
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::address')?> <span class="important">*</span></label>
                <div class="col-sm-8">
                    <input value="<?php echo input('val.address')?>" type="text" name="val[address]" class="form-control"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::phone')?> <span class="important">*</span></label>
                <div class="col-sm-8">
                    <input value="<?php echo input('val.phone')?>" type="text" name="val[phone]" class="form-control"/>
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-sm-4"><?php _lang('store::website')?></label>
                <div class="col-sm-8">
                    <input value="<?php echo input('val.website')?>" type="text" name="val[website]" class="form-control"/>
                </div>
            </div>

           <!-- <div class="form-group row">
                <label class="control-label col-sm-4"><?php /*_lang('store::enable-paypal')*/?></label>
                <div class="col-sm-8">
                    <select name="val[enable_paypal]" class="form-control c-select">
                        <option value="0"><?php /*_lang('store::no'); */?></option>
                        <option value="1"><?php /*_lang('store::yes'); */?></option>
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-sm-4"><?php /*_lang('store::paypal-username')*/?></label>
                <div class="col-sm-8">
                    <input value="<?php /*echo input('val.paypal_username')*/?>" type="text" name="val[paypal_username]" class="form-control"/>
                </div>
            </div>-->
            <div class="form-group row">
                <label class="control-label col-sm-4"><?php echo lang('paypal-corporate-email');?></label>
                <div class="col-sm-8">
                    <input value="<?php echo input('val.corporate_email')?>" type="text" name="val[corporate_email]" class="form-control"/>
                </div>
            </div>
<!--            <div class="form-group row">
                <label class="control-label col-sm-4"><?php /*_lang('store::paypal-password')*/?></label>
                <div class="col-sm-8">
                    <input value="<?php /*echo input('val.paypal_password')*/?>" type="text" name="val[paypal_password]" class="form-control"/>
                </div>
            </div>

            <div class="form-group row">
                <label class="control-label col-sm-4"><?php /*_lang('store::paypal-signature')*/?></label>
                <div class="col-sm-8">
                    <input value="<?php /*echo input('val.paypal_signature')*/?>" type="text" name="val[paypal_signature]" class="form-control"/>
                </div>
            </div>-->
            <br/>
            <div class="form-group row">
                <div class="col-sm-5">
                </div>
                <div class="col-sm-4">
                    <div class="input-field col s12">
                        <input type="submit" value="<?php echo lang('store::create') ?>" class="btn btn-info btn-sm" />
                    </div>
                </div>
            </div>
            </form>
        </div>
    </div>