<?php echo view("store::store-top-menu"); ?>
<div class="box">
    <div class="title"><?php echo lang("store::all-products-categories"); ?></div>
    <div class="box-content">
        <div class="">
            <div class="row">
                <?php $categories = lp_store_categories('get_categories');
                foreach ($categories as $category): ?>
                    <div class="col-sm-4 cat-list-each">
                        <div class="card">
                            <div class="card-header">
                                <img class="img-of-category" src="<?php echo storeCategoryImage($category); ?>" />
                                <a ajax="true"
                                   href="<?php echo url_to_pager('products-categories-home',
                                       array('slugs' => $category['id'] . '_' . toAscii(lang($category['title'])))); ?>">
                                    <?php echo strtoupper(lang($category['title'])); ?>
                                    </a>
                            </div>
                            <?php $subcategories = get_store_subcategories($category['id']);
                            if ($subcategories): ?>
                            <ul class="list-group list-group-flush">
                                <?php foreach ($subcategories as $sb): ?>
                                <li class="list-group-item">
                                    <img class="img-of-category" src="<?php echo storeCategoryImage($sb); ?>" />
                                    <a
                                            class="<?php echo (input('category') == lang($sb['title'])) ? 'active' : ''; ?>"
                                            ajax="true"
                                            href="<?php echo url_to_pager('products-categories-home', array('slugs' => $sb['id'] . '_' . toAscii(lang($category['title'])) . '_' . toAscii(lang($sb['title'])))); ?>"><?php _lang($sb['title']); ?>
                                        <span class="product-categories-counter"><?php  echo getProductsCatCount($sb); ?></span>
                                    </a>
                                </li>
                                <?php endforeach; ?>
                            </ul>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>