<div class="box">
    <div class="title">
        <?php echo lang("store::manage-products") ?>
    </div>
    <div class="box-content">
        <?php echo view("store::customization/change-select-store"); ?>
        <div class="box-content">
            <div class="table-responsive">
            <table class="table table-striped table-bordered storeTable" cellspacing="0" width="100%" >
                <thead>
                <tr>
                    <th><?php _lang('store::product_id') ?></th>
                    <th><?php echo lang('store::product-name') ?></th>
                    <th><?php echo lang('store::quantity') ?></th>
                    <th><?php echo lang('store::product-type') ?></th>
                    <th><?php _lang('status') ?></th>
                    <th style="width: 20%"><?php _lang('store::action'); ?></th>
                </tr>
                </thead>
                <tbody>
                <?php if($products->total): ?>
                    <?php foreach($products->results() as $p ):;?>
                        <tr>
                            <td><?php echo $p['id'] ?></td>
                            <td><?php echo $p['name']; ?></td>
                            <td><?php echo $p['quantity'] ?></td>
                            <td><?php echo ucwords($p['type']); ?></td>
                            <td><?php echo ($p['status']) ? '<span class="label label-success">'.lang('store::approved') .'</span>': '<span class="label label-warning">'.lang('store::not-approved').'</span>' ?></td>
                            <td>
                                <a ajax="true" href="<?php echo url_to_pager('store-manage-single-product') ?>?action=edit&pid=<?php echo $p['id']; ?>" class="btn btn-sm btn-warning"><?php _lang('edit') ?></a>
                                <a href="#" data-url="<?php echo url_to_pager('store-manage-single-product') ?>?action=delete&pid=<?php echo $p['id']; ?>" class="btn btn-sm btn-danger remove_product" data-id="<?php echo $p['id'] ?>"> <i class="ion-trash-b"></i> </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr class="alert alert-info">
                        <?php _lang('store::no-result-found') ?>
                    </tr>
                <?php endif;?>
                </tbody>
            </table>
            </div>
        </div>

    </div>
</div>