<div class="modal fade" id="store-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" style="background: #ccc">
                <span class="me-head" style="font-size: 16px"></span>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>

            </div>
            <div class="modal-body">
                <div class="indicator"><img style="margin: auto; width: 30px;" src="<?php echo img('images/loading.gif')?>"/></div>

            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<input type="hidden" id="compare-added-msg" value="<?php echo lang("store::compare-added-msg"); ?>" />
<input type="hidden" id="remove-from-compare_txt" value="<?php echo lang("store::remove-from-compare"); ?>" />
<input type="hidden" id="add-to-compare_text" value="<?php echo lang("store::add-to-compare"); ?>" />