<?php echo view("store::customization/new-top-menu"); ?>
<div class="box">
    <div class="clearfix box-content top-with-cateogory-wrapper">
        <div class="">
            <?php $count = 0; ?>
            <div class="col-sm-12">
                <div class="row">
                <div class="nop col-sm-3">
                    <ul class="grand-parent-category">
                        <?php $categories = lp_store_categories('get_categories');
                        foreach ($categories as $category):
                            if($count == 10) break;
                            ?>
                            <li class="parent-category" data-img="<?php echo storeCategoryImage($category); ?>">
                                <a ajax="true"
                                   href="<?php echo url_to_pager('products-categories-home', array('slugs' => $category['id'] . '_' . toAscii(lang($category['title'])))); ?>"><?php echo strtoupper(lang($category['title'])); ?>
                                    <i class="ion-arrow-right-b"></i></a>
                                <?php
                                $subcategories = get_store_subcategories($category['id']);
                                if ($subcategories): ?>
                                    <ul class="">
                                        <?php foreach ($subcategories as $sb): ?>
                                            <li class="col-sm-3 store-sub-with-image"
                                                data-img="<?php echo storeCategoryImage($sb); ?>"><a
                                                        class="<?php echo (input('category') == lang($sb['title'])) ? 'active' : ''; ?>"
                                                        ajax="true"
                                                        href="<?php echo url_to_pager('products-categories-home', array('slugs' => $sb['id'] . '_' . toAscii(lang($category['title'])) . '_' . toAscii(lang($sb['title'])))); ?>"><?php _lang($sb['title']); ?></a>
                                            </li>
                                        <?php endforeach; ?>
                                    </ul>
                                <?php endif; ?>
                            </li>
                        <?php $count++; endforeach ?>
                        <li class="parent-category all-cat" ><a ajax="true" href="<?php echo url_to_pager("products-categories-list"); ?>"><?php echo strtoupper(lang("store::all-catgegories")); ?><i class="ion-plus"></i></a></li>
                    </ul>
                </div>
                <div class="col-sm-9">
                    <div class="category-wrapper-content">
                        <div class="row">
                        <div class="col-sm-9 nop">
                            <div class="category-put"></div>
                        </div>
                        <div class="col-sm-3" style="overflow:hidden">
                            <img src="" style="min-height:150px;min-width:150px" class="img img-responsive"/>
                        </div>
                        </div>
                    </div>
                    <div class="store-banner-slider">
                        <div class="store-can-hold-arrow"></div>
                        <div class="store-banner-slider-content">
                        <?php foreach (lp_store_categories('get_categories', 'all', 'slides') as $sb): ?>
                            <div class="step-child-store-banner"
                                 style="background-image : url(<?php echo storeCategoryImage($sb,920); ?>); "></div>
                        <?php endforeach; ?>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>


