<div class="box">
    <div class="title"><?php echo lang("store::wired-transfer-set-up"); ?></div>
    <div class="container" id="wired-transfer">
        <?php if($message): ?>
            <div class="alert alert-danger"> <?php echo $message; ?></div>
        <?php endif; ?>
        <!--<div style="display: block">
           <h4><?php /*echo "Wired Transfer"; */?></h4>
            <img src="<?php /*echo img("store::images/wire-transfer-logo.png"); */?>" alt="Wired Transfer" />
        </div>-->

        <form action="" method="post">
            <h5><?php echo lang("store::bank-details") ?></h5>
            <fieldset>
                <div class="col-sm-4">
                    <label><?php echo lang("store::bank-swift-code") ?></label>
                </div>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="val[swift_code]" value="<?php echo ($settings['swift_code']) ? $settings['swift_code'] : input('val.swift_code') ?>" />
                </div>
            </fieldset>

            <fieldset>
                <div class="col-sm-4">
                    <label><?php echo lang("store::bank_name") ?></label>
                </div>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="val[bank_name]" value="<?php echo ($settings['bank_name']) ? $settings['bank_name'] : input('val.bank_name') ?>" />
                </div>
            </fieldset>

            <fieldset>
                <div class="col-sm-4">
                    <label><?php echo lang("store::bank_address"); ?></label>
                </div>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="val[bank_address]" value="<?php echo ($settings['bank_address']) ? $settings['bank_address'] : input('val.bank_address') ?>" />
                </div>
            </fieldset>

            <hr/>
            <h5><?php echo lang('store::account-holder-information'); ?></h5>

            <fieldset>
                <div class="col-sm-4">
                    <label><?php echo lang("store::account-number"); ?></label>
                </div>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="val[account_number]" value="<?php echo ($settings['account_number']) ? $settings['account_number'] : input('val.account_number') ?>" />
                </div>
            </fieldset>

            <fieldset>
                <div class="col-sm-4">
                    <label><?php echo lang("store::account-name"); ?></label>
                </div>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="val[account_name]" value="<?php echo ($settings['account_name']) ? $settings['account_name'] : input('val.account_name') ?>" />
                </div>
            </fieldset>

            <fieldset>
                <div class="col-sm-4">
                    <label><?php echo lang("store::address"); ?></label>
                </div>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="val[address]" value="<?php echo ($settings['address']) ? $settings['address'] : input('val.address') ?>" />
                </div>
            </fieldset>

            <fieldset>
                <div class="col-sm-4">
                    <label><?php echo lang("store::phone"); ?></label>
                </div>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="val[phone]" value="<?php echo ($settings['phone']) ? $settings['phone'] : input('val.phone') ?>" />
                </div>
            </fieldset>

            <fieldset>
                <div class="col-sm-4">
                    <label><?php echo lang("store::city_state"); ?></label>
                </div>
                <div class="col-sm-8">
                    <input type="text" class="form-control" name="val[city_state]" value="<?php echo ($settings['city_state']) ? $settings['city_state'] : input('val.city_state') ?>" />
                </div>
            </fieldset>

            <fieldset>
                <div class="col-sm-4">
                    <label><?php echo lang("store::country"); ?></label>
                </div>
                <div class="col-sm-8">
                    <select class=" form-control" name="val[country]">
                        <option value=""><?php _lang('select-country')?></option>
                        <?php echo load_functions("country"); ?>
                        <?php foreach(get_countries() as $country => $name):?>
                            <option <?php echo ($settings['country'] == $name) ? "selected" : null?> value="<?php echo $name?>"><?php echo ucwords($name)?></option>
                        <?php endforeach?>
                    </select>
                </div>
            </fieldset>

            <fieldset>
                <div class="col-sm-4">
                    <label><?php echo lang("store::additional-information"); ?></label>
                </div>
                <div class="col-sm-8">
                    <textarea class="form-control" name="val[add_info]" ><?php echo ($settings['add_info']) ? $settings['add_info'] : input('val.add_info') ?></textarea>
                </div>
            </fieldset>
            <div class="alert alert-warning">
                <?php echo lang("store::saving-this-will-overwrite-exiting-active-payment-method") ?>
            </div>

            <fieldset>
                <div class="col-sm-offset-4" style="margin-bottom: 20px">
                    <button class="btn btn-info"><?php echo lang('save')?></button>
                    <a ajax="true" href="<?php echo url_to_pager("manager-settings"); ?>" class="btn btn-secondary"><?php echo lang('cancel')?></a>
                </div>

            </fieldset>
            </form>



        </div>
    </div>
