<div class="wrapper">
	<div class="wrapper-title">
		<?php echo lang('feed::manage-lists') ?>
		-
		<a class="btn btn-success" href="<?php echo url_to_pager('admin-feeds-add-list') ?>"><?php echo lang('feed::add-list') ?></a>
	</div>
	<div class="wrapper-content">
		<div class="list-table-container">
			<div class="table-responsive">
				<table class="table table-striped list-table">
					<thead>
					<tr>
						<th>
							<div class="list-table-select" data-group="users" data-id="0"></div>
						</th>
						<th>ID</th>
						<th><?php echo lang('title') ?></th>
						<th><?php echo lang('Icon');?></th>
						<th><?php echo lang('actions') ?></th>
					</tr>
					</thead>
					<tbody data-url="<?php //echo url_to_pager('admincp-blog-manage-category').'?action=order' ?>" class="admincp-sortable" style="position: relative">
					<?php foreach($lists as $list): ?>
						<tr class="item" id="<?php echo $list['id'] ?>">
							<td>
								<div class="list-table-select" data-group="users" data-id="<?php echo $list['id'] ?>"></div>
							</td>

							<td style="width: 10%"><?php echo $list['id'] ?></td>
							<td style="width: 30%"><?php echo lang($list['title']) ?></td>
							<td style="width: 20%"><i style="color:red" class="<?php echo $list['icon']; ?>"></i></td>
							<td>
								<div class="dropdown actions">
									<a href="#" data-toggle="dropdown">
										<i class="ion-android-settings"></i>
									</a>
									<div class="dropdown-menu dropdown-menu-right">
										<a class="ion-edit" href='<?php echo url_to_pager('admin-feeds-list').'?action=edit&id='.$list['id'] ?>'></a>
										<a class="admin-confirm ion-android-delete" href="<?php echo url_to_pager('admin-feeds-list').'?action=delete&id='.$list['id'] ?>"></a>
									</div>
								</div>
							</td>


						</tr>
					<?php endforeach ?>
					</tbody>
				</table>
			</div>
		</div>
	</div>