<div class="box ">
	<div class="box-content">
		<?php if(user_has_permission('can-create-page') && is_loggedIn()): ?>
			<a class="btn btn-info btn-block action-button" href="<?php echo url_to_pager('page-create') ?>" data-toggle="modal" data-target="#page-create-modal">
				<i class="ion-plus"></i>
				<?php echo lang('page::create-a-page') ?>
			</a>
			<div id="page-create-modal" class="modal fade" role="dialog">
				<div class="modal-dialog modal-lg1">
					<div class="modal-content">
						<form action="<?php echo url('page/create') ?>" method="post" class="ajax-form">
							<div class="modal-form-header">
								<button type="button" class="close" data-dismiss="modal">&times;</button>
								<p class="modal-title pull-left"><?php echo lang('create-a-page') ?></p>
							</div>
							<div class="modal-body">
								<?php CSRFProtection::embed() ?>
								<div class="field">
									<div class="top">
										<label class="control-label"><?php echo lang('page::select-category') ?></label>
									</div>
									<div class="bottom">
										<div class="magic-select" data-name="val[category]" data-width="200px">
											<div class="magic-select-toggle">
												<?php echo lang('select-category') ?>
											</div>
											<div class="magic-select-content">
												<?php $categories = get_page_categories(); ?>
												<?php foreach($categories as $category): ?>
													<div class="magic-select-option" data-value="<?php echo $category['category_id'] ?>">
														<?php echo lang($category['category_title']) ?>
													</div>
												<?php endforeach ?>
											</div>
										</div>
									</div>
								</div>
								<div class="field">
									<div class="top">
										<label class="control-label"><?php echo lang('page-title') ?></label>
									</div>
									<div class="bottom">
										<input value="<?php echo input('val.name') ?>" type="text" name="val[name]" class="form-control"/>
									</div>
								</div>
								<div class="field">
									<div class="top">
										<label class="control-label"><?php echo lang('page::description') ?></label>
									</div>
									<div class="bottom">
										<textarea name="val[description]" data-height="50px" class="form-control auto-grow-input"><?php echo input('val.description') ?></textarea>
									</div>
								</div>
                                <?php fire_hook('page.create.view')?>
								<?php $customsField = get_form_custom_fields('page'); ?>
								<?php if(count($customsField) > 0): ?>
									<div class="field">
										<div class="top">
											<label class="control-label col-sm-4">Custom</label>
										</div>
										<div class="bottom">
											<?php foreach($customsField as $field): ?>
												<?php echo view("custom-field/display", array('field' => $field, 'offDescription' => true)) ?>
											<?php endforeach ?>
										</div>
									</div>
								<?php endif ?>
							</div>
							<div class="modal-footer">
								<div class="submit">
									<button class="btn btn-info pull-right"><?php echo lang('page::create-page') ?></button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		<?php endif ?>
	</div>
	<ul class="menu">
		<li class="<?php echo isset(app()->pageType) && app()->pageType == 'browse' ? 'active' : null ?>">
			<a ajax="true" href="<?php echo url_to_pager('pages') ?>"><?php echo lang('page::all-pages') ?></a>
		</li>
		<?php if(is_loggedIn()): ?>
			<li class="<?php echo isset(app()->pageType) && app()->pageType == 'mine' ? 'active' : null ?>">
				<a ajax="true" href="<?php echo url_to_pager('pages') ?>?type=mine"><?php echo lang('page::my-pages') ?></a>
			</li>
		<?php endif ?>
	</ul>
</div>
