<div id="dashboard-filter-menu" class="box  clearfix">
    <ul class="pull-left left">
        <li class="<?php echo segment(0) === 'ads' && !segment(1) ? 'active' : null ?>">
            <a ajax="true" href="<?php echo url_to_pager('ads-manage') ?>"><?php echo lang('ads::ads') ?></a>
        </li>
        <li class="<?php echo segment(0) === 'ads' && segment(1) === 'create' ? 'active' : null ?>">
            <a ajax="true" href="<?php echo url_to_pager('ads-create') ?>"><?php echo lang('ads::create-ads') ?></a>
        </li>
    </ul>
    <div class="pull-right action">
        <?php if(user_has_permission('can-create-ads')): ?>
            <a href="<?php echo url_to_pager('ads-create') ?>" ajax="true" class="btn btn-info btn-sm"><?php echo lang('ads::create-ads') ?></a>
        <?php endif ?>
    </div>
</div>