<div class="md-container">
    <div class="box">
        <div class="title"><?php echo lang('contest::start-a-contest') ?></div>
        <div>
            <?php if ($message): ?>
                <div class="alert alert-danger"><?php echo $message ?></div>
            <?php endif ?>
            <form action="" method="post" enctype="multipart/form-data" class="ajax-form contest-start-form">
                <?php CSRFProtection::embed() ?>
                <?php if ($message): ?>
                    <div class="alert alert-danger"><?php echo $message ?></div>
                <?php endif ?>
                <?php echo view("contest::contest-form-fields"); ?>
                <div class="submit">
                    <button class="btn btn-info"><?php echo lang("contest::publish-contest") ?></button>
                </div>
            </form>
        </div>
    </div>
</div>