<?php $id = $contest['id']; ?>
<?php $ann = getContestAnnouncements($id); ?>
<div class="box" style="border:none">
    <div class="box-content">
        <?php if(is_contest_owner($contest)): ?>
        <div class="clearfix">
        <a id="ann-btn"
           data-acid="<?php echo $id; ?>"
           data-aid="<?php echo '0'; ?>"
           data-atype="<?php echo 'new'; ?>"
           class="btn btn-info pull-right"
           href=""><?php echo lang("contest::add-new-annoucement"); ?></a>
        </div>
        <?php endif; ?>
        <br/>
        <?php if($ann->total): ?>
            <div id="contest-ann">
                <?php foreach ($ann->results() as $a): ?>
                <h3><?php echo $a['title']; ?> <i class="ion-chevron-down"></i> </h3>
                <div>
                    <p class="">
                        <?php if(is_contest_owner($a)): ?>
                        <span class="pull-right">
                             <a href=""
                                class="edit-contest-annoucement"
                                data-acid="<?php echo $id; ?>"
                                data-aid="<?php echo $a['id']; ?>"
                                data-atype="<?php echo 'update'; ?>"
                                data-alink="<?php echo urldecode($a['link']); ?>"
                                data-acontent="<?php echo $a['content']; ?>"
                                data-atitle="<?php echo $a['title']; ?>"
                             ><i class="ion-edit"></i> <?php echo lang("edit") ?> </a> &nbsp; | &nbsp;
                            <a href="javascript::void(0)"
                               onclick="return confirm.url('<?php echo url_to_pager("contest-annoucement").'?action=del&aid='.$a['id'].'&cid='.$id; ?>')"

                               class="text-danger"><i class="ion-android-delete"></i> <?php echo lang("delete") ?> </a>
                        </span>
                        <?php endif; ?>
                        <span class="pull-right"><small><em><?php echo date('M j, Y',$a['time']); ?></em></small>&nbsp; | &nbsp;</span>
                    </p><br/>
                    <?php if($a['link']): ?>
                    <p><?php echo output_text(urldecode($a['link'])); ?></p>
                    <?php endif; ?>
                    <p><?php echo nl2br($a['content']); ?></p>
                </div>
                <?php endforeach; ?>
            </div>
        <?php else :?>
        <div class="alert alert-info"><?php echo lang("contest::empty-list"); ?></div>
        <?php endif;?>
    </div>
</div>

<div id="annModal" class="modal fade " tabindex="-1" role="dialog" aria-labelledby="myLikesModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><?php echo lang('contest::announcement') ?></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only"><?php echo lang('close') ?></span>
                </button>
            </div>
            <div class="modal-body">
                <form action="<?php echo url_to_pager("contest-annoucement") ?>" method="post" enctype="multipart/form-data" class="ajax-form">
                    <?php CSRFProtection::embed() ?>
                    <div class="form-group">
                        <input type="hidden" id="acid" name="val[contest_id]" value="<?php echo $contest['id'] ?>"/>
                        <input type="hidden" id="atype" name="val[atype]" value="new"/>
                        <input type="hidden" id="aid" name="val[aid]" value="0"/>
                        <label><?php echo lang("contest::news-headline") ?> * </label>
                        <input autocomplete="off" type="text" id="atitle" name="val[headline]" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label><?php echo lang("contest::link"); ?></label>
                        <input autocomplete="off" type="text" id="alink" name="val[link]" class="form-control" />
                    </div>

                    <div class="form-group">
                        <label><?php echo lang("contest::content"); ?> * </label>
                        <textarea id="acontent" name="val[content]" id="acontent" class="form-control"></textarea>
                    </div>

                    <div class="submit">
                        <button class="btn btn-info"><?php echo lang("save"); ?></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>