<div class="md-container">
    <div class="box">
        <div class="title"><?php echo lang('contest::manage-contest') ?></div>
        <div>
            <?php if ($message): ?>
                <div class="alert alert-danger"><?php echo $message ?></div>
            <?php endif ?>
            <form action="" method="post" enctype="multipart/form-data" class="ajax-form contest-start-form">
                <?php CSRFProtection::embed() ?>
                <?php if ($message): ?>
                    <div class="alert alert-danger"><?php echo $message ?></div>
                <?php endif ?>
                <?php echo view("contest::contest-form-fields",array('contest'=>$contest)); ?>
                <div class="submit">
                    <button class="btn btn-info"><?php echo lang("contest::save-contest") ?></button>
                    <a href="javascript::void(0)" onclick="return confirm.url('<?php echo url('contest/manage?type=delete&id='.$contest['id']) ?>')" class="btn btn-danger action-button">
                        <?php echo lang('contest::delete-contest') ?></a>
                </div>
                <div class="box-content">
                    <div class="alert alert-warning">
                        <?php echo lang("contest::contest-delete-warning"); ?>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>