<div class="box">
    <div class="box-content">
        <div class="alert alert-info">
        <?php echo lang("contest::you-can-only-submit-x-entries",array('max'=>$max)); ?>
            <br/>
            <?php echo lang("contest::edit-or-delete-your-current-entries") ?>
            <br/>
            <a href="<?php echo contestUrl($contest) ?>"><i class="ion-android-arrow-back"></i> <?php echo lang("contest::go-back"); ?></a>
        </div>
    </div>
</div>