<div class="">
    <div style="max-height: 600px;
    overflow: hidden;
    padding:5px;
    width: 300px;
    border:1px solid #f2f4f6;
    border-radius: 5px;
    font-family: /* Roman */ -apple-system, system-ui, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Fira Sans, Ubuntu, Oxygen, Oxygen Sans, Cantarell, Droid Sans, Lucida Grande, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Emoji, Segoe UI Symbol, /* CJK */ Hiragino Kaku Gothic Pro, Meiryo, Hiragino Sans GB W3, /* Arabic */ Noto Naskh Arabic, Droid Arabic Naskh, Geeza Pro, Simplified Arabic, /* Thai */ Noto Sans Thai, Thonburi, Dokchampa, Droid Sans Thai, /* Sans Fallbacks */ Droid Sans Fallback, '.SFNSDisplay-Regular', /* CJK Fallbacks */ Heiti SC, Microsoft Yahei;
    margin: 0 auto;" class="contest-promote-preview">
        <div style="border:1px solid #f2f4f6;
    padding: 5px;
    margin-bottom: 10px;" class="contest-promote-preview-bf">
            <?php if($img == 1): ?>
            <div class="contest-image-promote"
                 style="display:block;
                     height: 200px;
                     width: 100%;
                     max-width: 600px;
                     background-size: contain;
                     background-position:center;
                     background-repeat: no-repeat;;background-image : url(<?php echo get_contest_image($contest) ?>)"></div>
            <?php endif; ?>
            <p><a style="text-decoration : none ; font-size: ;14px; color : <?php echo config('header-bg-color', '#4C4C4E'); ?>"
                  href="<?php echo contestUrl($contest); ?> "><?php echo $contest['name']; ?></a></p>
            <?php if($desc == 1): ?>
            <p class="sub-contest-description"><?php echo str_limit(strip_tags($contest['description']), 80); ?></p>
            <?php endif; ?>
        </div>
        <p><a style="background: <?php echo config('button-bg-color','#0abde3') ?> !important;
                width: 100%;padding: 12px;color : #fff;text-decoration: none;display: block;text-align: center"
                class="btn btn-block btn-info btn-lg"
              href="<?php echo contestUrl($contest) ?>"><?php echo lang("contest::join-contest") ?></a></p>
    </div>
</div>