<?php
$refId = $contest['id'];
$refName = 'contest';
?>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
        <?php echo view("contest::top-menu"); ?>
        </div>
        <?php echo view("contest::lhs", array('contest' => $contest)); ?>
        <div class="col-sm-8">
            <div class="box">
                <div class="title">
                    <div style="width:80%">
                        <?php echo $contest['name'] ?>
                        <div class="action">
                            <?php if (is_contest_owner($contest)): ?>
                                <a href="<?php echo url('contest/manage?type=edit&id=' . $contest['id']) ?>"
                                   class="btn btn-secondary btn-sm " ajax="true"><i
                                            class="ion-edit"></i> <?php echo lang('edit') ?></a>
                            <?php elseif (is_loggedIn() and plugin_loaded('report')): ?>
                                <a data-type="contest"
                                   data-link="<?php echo url_to_pager('contest-page', array('slugs' => $contest['slug'])) ?>"
                                   class="report-btn btn btn-secondary" href=""><i class="ion-flag"></i></a>
                            <?php endif ?>
                        </div>
                    </div>
                </div>
                <?php echo view("contest::contest-head", array('contest' => $contest)) ?>
                <div class="box-content">


                    <div class="menu-contest-wrapper">

                        <ul class="nav nav-tabs nav-pills nav-fill" id="myTab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab"
                                   aria-controls="home" aria-selected="true">
                                    <?php echo strtoupper(lang("contest::description")); ?>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab"
                                   aria-controls="profile"
                                   aria-selected="false"><?php echo strtoupper(lang("contest::award")); ?></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab"
                                   aria-controls="contact"
                                   aria-selected="false"><?php echo strtoupper(lang("contest::announcement")); ?></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="entries-tab" data-toggle="tab" href="#entries" role="tab"
                                   aria-controls="entries"
                                   aria-selected="false"><?php echo strtoupper(lang("contest::entries")); ?></a>
                            </li>
                        </ul>
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                <br/>
                                <?php echo output_text($contest['description']); ?>
                            </div>
                            <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                <br/>
                                <?php echo $contest['award']; ?>
                            </div>
                            <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
                                <?php echo view("contest::announcement",array('contest'=>$contest)); ?>
                            </div>
                            <div class="tab-pane fade" id="entries" role="tabpanel" aria-labelledby="contact-tab">
                                <br/>
                                <?php $entries = getContestEntries($contest, 4); ?>
                                <div class="box">
                                    <div class="title">

                                        <?php if($entries->total): ?>
                                            <a class="btn btn-sm btn-info pull-right" href="<?php echo contestUrl($contest).'/entries' ?>"><?php echo ucwords(lang("contest::view-all-entries")); ?></a>
                                        <?php endif; ?>
                                        <br/>
                                    </div>
                                    <div class="box-content">

                                        <?php if ($entries->total): ?>
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <?php foreach ($entries->results() as $blog):
                                                        $user = find_user($blog['user_id']);
                                                        ?>
                                                        <div class="col-sm-6">
                                                            <div class="media media-sm">
                                                                <div class="media-left">
                                                                    <div class="media-object">
                                                                        <img src="<?php echo ($blog['image']) ? url_img($blog['image'], 200) : get_avatar(200, $user) ?>"/>
                                                                    </div>
                                                                </div>
                                                                <div class="media-body">
                                                                    <h4 class="media-heading" style="margin-top:0">
                                                                        <a ajax="true"
                                                                           href="<?php echo getEntryContestUrl($contest, $blog); ?>">
                                                                            <?php if($blog['title']): ?>
                                                                            <?php echo str_limit($blog['title'],25); ?>
                                                                            <?php else: ?>
                                                                            <?php echo lang("contest::untititle") ?>
                                                                            <?php endif; ?>
                                                                        </a>
                                                                    </h4>
                                                                    <span class="help-block" style="display: block;font-size:14px">
                                                            <span style="font-s"><i class="ion-eye"></i>  <?php echo $blog['views'] ?></span>
                                                            &nbsp;&nbsp;&nbsp;
                                                            <span><i class="ion-thumbsup"></i> <?php echo contestEntryVoteCount($blog['ref_name'],$blog['id']) ?> </span>
                                                        </span>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    <?php endforeach; ?>
                                                </div>
                                            </div>
                                        <?php else: ?>
                                            <div class="alert alert-info"><?php echo lang("contest::empty-lists"); ?></div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- start entries -->
                    <?php echo view("contest::footer-like",array('refName'=>$refName,'refId'=>$refId)); ?>
                </div>
            </div>
            <?php echo view("contest::participants",array('contest'=>$contest)); ?>
            <!-- comment section start-->
            <?php echo view("contest::footer-comment",array('refName'=>$refName,'refId'=>$refId)); ?>
            <!-- comment section end-->
        </div>
    </div>
</div>

