<div class="contact box">
	<div class="title"><?php echo lang('contact::contact-form-message') ?></div>
	<form action="" method="post">
		<?php if($message): ?>
			<div class="alert alert-success"><?php echo $message ?></div><?php endif ?>
		<?php echo CSRFProtection::embed() ?>
		<div class="box-content">
			<div class="row">
				<div class="col-sm-4">
					<label><?php echo lang('contact::name') ?></label>
				</div>
				<div class="col-sm-8">
					<input name='val[name]' type="text" required="" class="form-control">
				</div>
				<div class="col-sm-4">
					<label><?php echo lang('contact::email') ?>:</label>
				</div>
				<div class="col-sm-8">
					<input name='val[email]' type="email" required="" class="form-control">
				</div>
				<div class="col-sm-4">
					<label><?php echo lang('contact::subject') ?>:</label>
				</div>
				<div class="col-sm-8">
					<input name='val[subject]' type="text" required="" class="form-control">
				</div>
				<div class="col-sm-4">
					<label><?php echo lang('contact::message') ?>:</label>
				</div>
				<div class="col-sm-8">
					<textarea name='val[message]' class="form-control ckeditor"></textarea>
				</div>
                <?php fire_hook('contact-us.footer'); ?>
                <div class="col-sm-4"></div>
                <div class="col-sm-8">
                    <?php if(get_setting("enable-captcha")): ?>
                        <?php if(get_setting("enable-captcha") == '1'): ?>
                            <div class="row">
                                <div class="col-md-6">
                                    <input class="form-control" type="text" placeholder="<?php echo lang('enter-text-below') ?>" name="captcha" id="captcha-input"/>
                                </div>
                                <div class="col s6">
                                    <img id="captcha-image" src="<?php echo url("captcha.php") ?>"/>
                                    <a href="#" onclick="document.getElementById('captcha-image').src='<?php echo url('captcha.php') ?>?' + Math.random(); document.getElementById('captcha-input').focus();">
                                        <i class="ion-ios-reload"></i>
                                    </a>
                                    <br/>
                                </div>
                            </div>
                        <?php else: ?>
                            <div class="g-recaptcha" data-sitekey="<?php echo config('recaptcha-key'); ?>"></div>
                            <script type="text/javascript" src="https://www.google.com/recaptcha/api.js?hl=en"></script>
                        <?php endif ?>
                    <?php endif ?>
                </div>
                <div class="col-sm-4"></div>
                <div class="col-sm-8">
					<button id="contact-us" type="submit" name="reply" class="btn btn-info"><?php echo lang('contact::send') ?> </button>
				</div>
			</div>
		</div>
	</form>
</div>