<div class="box">
    <div class="title"><?php echo lang('payment-status') ?></div>
    <div class="box-content">
        <div class="alert alert-danger">
            <?php echo lang('ads::ads-payment-cancel') ?>
        </div>
        <a href="<?php echo url_to_pager('ads-manage') ?>" ajax="true" class="btn btn-info btn-block action-button"><?php echo lang('ads::manage-ads') ?></a>
    </div>
</div>