<div class="box">
    <div class="box-content">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#home" role="tab"><?php echo lang('store::description') ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#rating" role="tab"><?php echo ucwords(lang('store::ratings')); ?></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#messages" role="tab"><?php echo lang("store::reviews") ?></a>
            </li>

        </ul><br/>

        <!-- Tab panes -->
        <div class="tab-content">
            <div class="tab-pane active" id="home" role="tabpanel">

               <?php echo html_entity_decode($product['description']) ?>
            </div>
            <div class="tab-pane" id="rating" role="tabpanel">
              <?php echo view("store::products/rating",array('id'=>$product['id'])) ?>
            </div>
            <div class="tab-pane" id="messages" role="tabpanel">
               <?php echo view("store::products/comments",array('product'=>$product));?>
            </div>

        </div>
    </div>
</div>
