<div class="product-each-item clearfix" id="product-id-<?php echo $p['id']; ?>">
    <div class="left">
        <?php
        if (plugin_loaded('booster') && config('allow-members-to-boost-product', true) && is_store_owner($p)) {
            echo view('booster::marketplacebtn', array('type' => 'Product', 'product' => $p));
        }
        ?>
        <?php if ($p['featured']): ?>
            <span class="featured-tag"><?php _lang('featured') ?></span>
        <?php endif; ?>
        <a ajax="true" href="<?php echo url('store/product/' . $p['slug']) ?>"
           style="background-image:url(<?php echo getProductMainImage($p) ?>) "></a>
    </div>
    <div class="right">
                            <span class="product-item-title small"><a ajax="true"
                                                                      href="<?php echo url('store/product/' . $p['slug']) ?>"><?php echo ucwords(str_limit($p['name'], 35)); ?></a> </span>
        <span class="product-item-title full" style="display: none"><a ajax="true"
                                                                       href="<?php echo url('store/product/' . $p['slug']) ?>"><?php echo ucwords($p['name']); ?></a> </span>
        <span class="product-price"><?php echo config('currency-sign', '$') . number_format((float)getProductPrice($p), '2', '.', ','); ?>
            <small style="color: #aaa;text-decoration: line-through"><?php echo (getProductDiscountedPrice($p)) ? config('currency-sign', '$') . number_format((float)getProductDiscountedPrice($p), '2', '.', ',') : '' ?></small>
                    <span class="pull-right"><a title="<?php echo lang("store::compare"); ?>"
                                                data-id="<?php echo $p['id']; ?>"
                                                data-status="<?php echo (is_been_compared($p['id'])) ? '1' : '0' ?>"
                                                class="compare-add-me btn btn-sm btn-secondary <?php echo (is_been_compared($p['id'])) ? 'active' : '' ?>"><i
                                class="ion-arrow-swap"></i></a>
                       </span>
                    </span>
        <span class="sold-by">
                        <?php echo lang("store::sold-by") . ' '; ?><a ajax="true"
                                                                      href="<?php echo url_to_pager('store-profile', array('slug' => $productStoreOwner['slug'])); ?>"><?php echo $productStoreOwner['name']; ?></a>

                    </span>

        <div class="additional-info" style="display: none">

            <div class="product-rating-container" style="pointer-events:none; cursor: not-allowed">
                <?php $r = getItemRatings('product', $p['id']);
                if ($r) {
                    $rating = getAverageRating($r);
                    //print_r($rating);die();
                } else {
                    $rating = 0;
                }

                ?>
                <span>
                                <i data-id="1"
                                   class="ion-android-star <?php echo ($rating > 0) ? 'background-rating' : '' ?> star1 rating"></i>
                                <i data-id="2"
                                   class="ion-android-star <?php echo ($rating > 1) ? 'background-rating' : '' ?> star2 rating"></i>
                                <i data-id="3"
                                   class="ion-android-star <?php echo ($rating > 2) ? 'background-rating' : '' ?> star3 rating"></i>
                                <i data-id="4"
                                   class="ion-android-star <?php echo ($rating > 3) ? 'background-rating ' : '' ?> star4 rating"></i>
                                <i data-id="5"
                                   class="ion-android-star <?php echo ($rating > 4) ? 'background-rating' : '' ?> star5 rating"></i>
                            </span>

                <span class="number-sold"><?php echo countNumberOfSoldItems($p['id']) . lang("store::sold"); ?>
                    | <span><?php echo lang('store::reviews') ?><?php echo count_comments('product', $p['id']) ?></span></span>
            </div>

        </div>
        <!--<p class="item-desc"><?php /*echo html_entity_decode(str_limit($p['description'], 100))*/ ?></p>
                    <div class="item-info">
                        <span class="help-block" style="display: block">
                                    <?php /*_lang('store::posted-by')*/ ?> : <a href="<?php /*echo profile_url(null, $user)*/ ?>"><?php /*echo get_user_name($user)*/ ?></a>
                            <?php /*_lang('store::store')*/ ?> : <a href="<?php /*echo url('store/'.lpGetStoreById($p['store_id'],'slug'));*/ ?>"><?php /*echo lpGetStoreById($p['store_id'],'name')*/ ?></a>
                            <?php /*_lang('store::on')*/ ?> <?php /*echo date('M j , y  h:i A', $p['time'])*/ ?>
                                </span>
                    </div>-->
    </div>
</div>