<?php $link = isset($link) ? $link : sharer_self_url();
$bits = parse_url($link);
if(count(explode('.', $bits['host'])) < 3 && !in_array($bits['host'], array('::1', 'localhost')) && !ip2long($bits['host'])) {
    $link = $bits['scheme'].'://'.(substr($bits['host'], 0, 4) !== 'www.' ? 'www.'.$bits['host'] : $bits['host']).(isset($bits['port']) ? ':'.$bits['port'] : '').$bits['path'].(!empty($bits['query']) ? '?'.$bits['query'] : '');
}
$link = urlencode(urldecode($link));
$link0 = urlencode(preg_replace('/^.*?:\/\//i', '', $link));
$link1 = $link;
$name = get_setting("site_title", "crea8socialPRO");
$specs = 'width = 500, height = 500, scrollbars = yes' ?>

<?php if(config('facebook-button', true)): ?>
<a href="javascript:void(0)" class="ion-social-facebook" onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=<?php echo $link1 ?>', '<?php echo $name ?>', '<?php echo $specs ?>')"></a><?php endif ?>
<?php if(config('twitter-button', true)): ?>
<a href="javascript:void(0)" class="ion-social-twitter" onclick="window.open('https://twitter.com/home?status=<?php echo $link1 ?>', '<?php echo $name ?>', '<?php echo $specs ?>')"></a><?php endif ?>
<?php if(config('googleplus-button', true)): ?>
<a href="javascript:void(0)" class="ion-social-googleplus" onclick="window.open('https://plus.google.com/share?url=<?php echo $link1 ?>', '<?php echo $name ?>', '<?php echo $specs ?>')"></a><?php endif ?>
<?php if(config('linkedin-button', true)): ?>
<a href="javascript:void(0)" class="ion-social-linkedin" onclick="window.open('https://www.linkedin.com/cws/share?url=<?php echo $link1 ?>', '<?php echo $name ?>', '<?php echo $specs ?>')"></a><?php endif ?>
<!--<a href="javascript:void(0)" class="ion-social-pinterest" onclick="window.open('https://pinterest.com/pin/create/button/?url=<?php echo $link1 ?>&media=<?php echo $name ?>&description=', '<?php echo $name ?>', '<?php echo $specs ?>')"></a> -->
<?php if(config('email-button', true)): ?>
<a href="javascript:void(0)" class="ion-email" onclick="window.open('mailto:?subject=<?php echo $app->title ?>&body=<?php echo $link1 ?>', '_self', '<?php echo $specs ?>')"></a><?php endif ?>
<?php if(config('feed-button', true)): ?>
<a href="javascript:void(0)" class="ion-share" onclick="window.open('<?php echo url('sharer') ?>?url=<?php echo $link1 ?>', '<?php echo $name ?>', '<?php echo $specs ?>')"></a><?php endif ?>
